/* =========================================================================
   data.js — Course & lesson content
   Each meaning `m` is provided in the 3 UI languages (id / en / es).
   `reading` = romanization for non-Latin scripts. `speech` = BCP-47 TTS code.
   ES module: `import { COURSES, findCourse, findLesson } from "./data.js"`.
   ========================================================================= */
export const COURSES = [
  /* ---------------------------------------------------------------- ENGLISH */
  {
    id: "en", flag: "🇬🇧", native: "English", speech: "en-US", cjk: false,
    name: { id: "Bahasa Inggris", en: "English", es: "Inglés" },
    tagline: { id: "Bahasa internasional nomor satu di dunia.", en: "The world's number one international language.", es: "El idioma internacional número uno." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Hello", m: { id: "Halo", en: "Hello", es: "Hola" }, ex: { t: "Hello, nice to meet you.", m: { id: "Halo, senang bertemu denganmu.", en: "Hello, nice to meet you.", es: "Hola, encantado de conocerte." } } },
          { term: "Good morning", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Thank you", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Please", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Excuse me", m: { id: "Permisi", en: "Excuse me", es: "Disculpe" } },
          { term: "My name is…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "How are you?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "One", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Two", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Three", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Four", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Five", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Six", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Seven", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Ten", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Yes / No", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "I don't understand", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Where is…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "How much is it?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Help!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Goodbye", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "work", icon: "💼", level: "intermediate",
        title: { id: "Percakapan di Kantor", en: "Workplace Conversation", es: "Conversación en el trabajo" },
        items: [
          { term: "Meeting", m: { id: "Rapat", en: "Meeting", es: "Reunión" }, ex: { t: "We have a meeting at 10 AM.", m: { id: "Kita ada rapat jam 10 pagi.", en: "We have a meeting at 10 AM.", es: "Tenemos una reunión a las 10." } } },
          { term: "Deadline", m: { id: "Tenggat waktu", en: "Deadline", es: "Fecha límite" }, ex: { t: "The deadline is this Friday.", m: { id: "Tenggatnya hari Jumat ini.", en: "The deadline is this Friday.", es: "La fecha límite es este viernes." } } },
          { term: "Report", m: { id: "Laporan", en: "Report", es: "Informe" }, ex: { t: "Please send me the report by tomorrow.", m: { id: "Tolong kirim laporannya paling lambat besok.", en: "Please send me the report by tomorrow.", es: "Envíeme el informe para mañana." } } },
          { term: "Colleague", m: { id: "Rekan kerja", en: "Colleague", es: "Colega" }, ex: { t: "She is my colleague from the finance team.", m: { id: "Dia rekan kerja saya dari tim keuangan.", en: "She is my colleague from the finance team.", es: "Ella es mi colega del equipo de finanzas." } } },
          { term: "Manager", m: { id: "Manajer / atasan", en: "Manager", es: "Gerente" }, ex: { t: "I'll ask my manager about it.", m: { id: "Saya akan tanya atasan saya soal itu.", en: "I'll ask my manager about it.", es: "Le preguntaré a mi gerente." } } },
          { term: "Schedule", m: { id: "Jadwal", en: "Schedule", es: "Horario" }, ex: { t: "Let's schedule a call for next week.", m: { id: "Ayo jadwalkan panggilan minggu depan.", en: "Let's schedule a call for next week.", es: "Agendemos una llamada para la próxima semana." } } },
          { term: "Overtime", m: { id: "Lembur", en: "Overtime", es: "Horas extra" }, ex: { t: "I worked overtime last night.", m: { id: "Semalam saya lembur.", en: "I worked overtime last night.", es: "Anoche hice horas extra." } } },
          { term: "Day off", m: { id: "Cuti / hari libur", en: "Day off", es: "Día libre" }, ex: { t: "I'd like to take a day off on Monday.", m: { id: "Saya ingin ambil libur hari Senin.", en: "I'd like to take a day off on Monday.", es: "Quisiera tomar el lunes libre." } } },
          { term: "Salary", m: { id: "Gaji", en: "Salary", es: "Salario" }, ex: { t: "The salary is paid at the end of the month.", m: { id: "Gaji dibayar di akhir bulan.", en: "The salary is paid at the end of the month.", es: "El salario se paga a fin de mes." } } },
          { term: "Feedback", m: { id: "Masukan / umpan balik", en: "Feedback", es: "Comentarios" }, ex: { t: "Thank you for your feedback.", m: { id: "Terima kasih atas masukannya.", en: "Thank you for your feedback.", es: "Gracias por sus comentarios." } } },
          { term: "Project", m: { id: "Proyek", en: "Project", es: "Proyecto" }, ex: { t: "We're working on a new project.", m: { id: "Kami sedang mengerjakan proyek baru.", en: "We're working on a new project.", es: "Estamos trabajando en un proyecto nuevo." } } },
          { term: "Presentation", m: { id: "Presentasi", en: "Presentation", es: "Presentación" }, ex: { t: "I have a presentation this afternoon.", m: { id: "Saya ada presentasi sore ini.", en: "I have a presentation this afternoon.", es: "Tengo una presentación esta tarde." } } },
          { term: "Client", m: { id: "Klien", en: "Client", es: "Cliente" }, ex: { t: "The client approved our proposal.", m: { id: "Klien menyetujui proposal kami.", en: "The client approved our proposal.", es: "El cliente aprobó nuestra propuesta." } } },
          { term: "Email", m: { id: "Surel / email", en: "Email", es: "Correo electrónico" }, ex: { t: "I'll send you an email with the details.", m: { id: "Saya akan kirim email berisi detailnya.", en: "I'll send you an email with the details.", es: "Le enviaré un correo con los detalles." } } },
          { term: "Break", m: { id: "Istirahat", en: "Break", es: "Descanso" }, ex: { t: "Let's take a short break.", m: { id: "Ayo istirahat sebentar.", en: "Let's take a short break.", es: "Tomemos un breve descanso." } } },
        ] },
      { id: "ticket", icon: "✈️", level: "intermediate",
        title: { id: "Tiket Pesawat & Bandara", en: "Flight Tickets & Airport", es: "Billetes de avión y aeropuerto" },
        items: [
          { term: "Flight", m: { id: "Penerbangan", en: "Flight", es: "Vuelo" }, ex: { t: "My flight leaves at 8 PM.", m: { id: "Penerbangan saya berangkat jam 8 malam.", en: "My flight leaves at 8 PM.", es: "Mi vuelo sale a las 8." } } },
          { term: "Ticket", m: { id: "Tiket", en: "Ticket", es: "Billete" }, ex: { t: "I need to book a ticket to Seoul.", m: { id: "Saya perlu memesan tiket ke Seoul.", en: "I need to book a ticket to Seoul.", es: "Necesito reservar un billete a Seúl." } } },
          { term: "One-way", m: { id: "Sekali jalan", en: "One-way", es: "Solo ida" }, ex: { t: "I'd like a one-way ticket, please.", m: { id: "Tolong tiket sekali jalan.", en: "I'd like a one-way ticket, please.", es: "Un billete de ida, por favor." } } },
          { term: "Round trip", m: { id: "Pulang-pergi", en: "Round trip", es: "Ida y vuelta" }, ex: { t: "How much is a round-trip ticket?", m: { id: "Berapa harga tiket pulang-pergi?", en: "How much is a round-trip ticket?", es: "¿Cuánto cuesta un billete de ida y vuelta?" } } },
          { term: "Departure", m: { id: "Keberangkatan", en: "Departure", es: "Salida" }, ex: { t: "The departure time is 9:30.", m: { id: "Waktu keberangkatan jam 9.30.", en: "The departure time is 9:30.", es: "La hora de salida es a las 9:30." } } },
          { term: "Arrival", m: { id: "Kedatangan", en: "Arrival", es: "Llegada" }, ex: { t: "The arrival gate is B12.", m: { id: "Gerbang kedatangan B12.", en: "The arrival gate is B12.", es: "La puerta de llegada es B12." } } },
          { term: "Boarding pass", m: { id: "Pas naik", en: "Boarding pass", es: "Tarjeta de embarque" }, ex: { t: "Please show your boarding pass.", m: { id: "Tolong tunjukkan boarding pass Anda.", en: "Please show your boarding pass.", es: "Muestre su tarjeta de embarque." } } },
          { term: "Gate", m: { id: "Gerbang", en: "Gate", es: "Puerta" }, ex: { t: "Boarding is at gate 22.", m: { id: "Naik pesawat di gerbang 22.", en: "Boarding is at gate 22.", es: "El embarque es en la puerta 22." } } },
          { term: "Baggage", m: { id: "Bagasi", en: "Baggage", es: "Equipaje" }, ex: { t: "How much baggage can I bring?", m: { id: "Berapa banyak bagasi yang boleh dibawa?", en: "How much baggage can I bring?", es: "¿Cuánto equipaje puedo llevar?" } } },
          { term: "Window seat", m: { id: "Kursi jendela", en: "Window seat", es: "Asiento de ventanilla" }, ex: { t: "Can I have a window seat?", m: { id: "Boleh minta kursi dekat jendela?", en: "Can I have a window seat?", es: "¿Puedo tener un asiento de ventanilla?" } } },
          { term: "Aisle seat", m: { id: "Kursi lorong", en: "Aisle seat", es: "Asiento de pasillo" }, ex: { t: "I prefer an aisle seat.", m: { id: "Saya lebih suka kursi lorong.", en: "I prefer an aisle seat.", es: "Prefiero un asiento de pasillo." } } },
          { term: "Passport", m: { id: "Paspor", en: "Passport", es: "Pasaporte" }, ex: { t: "Please have your passport ready.", m: { id: "Tolong siapkan paspor Anda.", en: "Please have your passport ready.", es: "Tenga su pasaporte listo." } } },
          { term: "Delay", m: { id: "Penundaan", en: "Delay", es: "Retraso" }, ex: { t: "The flight is delayed by two hours.", m: { id: "Penerbangan tertunda dua jam.", en: "The flight is delayed by two hours.", es: "El vuelo tiene dos horas de retraso." } } },
          { term: "Layover", m: { id: "Transit", en: "Layover", es: "Escala" }, ex: { t: "I have a layover in Tokyo.", m: { id: "Saya transit di Tokyo.", en: "I have a layover in Tokyo.", es: "Tengo una escala en Tokio." } } },
          { term: "Check-in", m: { id: "Lapor diri (check-in)", en: "Check-in", es: "Facturación" }, ex: { t: "Online check-in opens 24 hours before departure.", m: { id: "Check-in online dibuka 24 jam sebelum berangkat.", en: "Online check-in opens 24 hours before departure.", es: "La facturación en línea abre 24 horas antes de la salida." } } },
        ] },
      { id: "refund", icon: "💸", level: "advanced",
        title: { id: "Refund & Pembatalan", en: "Refunds & Cancellations", es: "Reembolsos y cancelaciones" },
        items: [
          { term: "Refund", m: { id: "Pengembalian dana / refund", en: "Refund", es: "Reembolso" }, ex: { t: "I'd like to request a refund.", m: { id: "Saya ingin mengajukan refund.", en: "I'd like to request a refund.", es: "Quisiera solicitar un reembolso." } } },
          { term: "Cancel", m: { id: "Membatalkan", en: "Cancel", es: "Cancelar" }, ex: { t: "I need to cancel my booking.", m: { id: "Saya perlu membatalkan pesanan saya.", en: "I need to cancel my booking.", es: "Necesito cancelar mi reserva." } } },
          { term: "Cancellation fee", m: { id: "Biaya pembatalan", en: "Cancellation fee", es: "Cargo por cancelación" }, ex: { t: "Is there a cancellation fee?", m: { id: "Apakah ada biaya pembatalan?", en: "Is there a cancellation fee?", es: "¿Hay un cargo por cancelación?" } } },
          { term: "Full refund", m: { id: "Refund penuh", en: "Full refund", es: "Reembolso total" }, ex: { t: "Am I eligible for a full refund?", m: { id: "Apakah saya berhak atas refund penuh?", en: "Am I eligible for a full refund?", es: "¿Tengo derecho a un reembolso total?" } } },
          { term: "Partial refund", m: { id: "Refund sebagian", en: "Partial refund", es: "Reembolso parcial" }, ex: { t: "You'll receive a partial refund.", m: { id: "Anda akan menerima refund sebagian.", en: "You'll receive a partial refund.", es: "Recibirá un reembolso parcial." } } },
          { term: "Non-refundable", m: { id: "Tidak bisa dikembalikan", en: "Non-refundable", es: "No reembolsable" }, ex: { t: "This ticket is non-refundable.", m: { id: "Tiket ini tidak bisa dikembalikan.", en: "This ticket is non-refundable.", es: "Este billete no es reembolsable." } } },
          { term: "Refund policy", m: { id: "Kebijakan refund", en: "Refund policy", es: "Política de reembolso" }, ex: { t: "Please read the refund policy first.", m: { id: "Tolong baca dulu kebijakan refundnya.", en: "Please read the refund policy first.", es: "Lea primero la política de reembolso." } } },
          { term: "Receipt", m: { id: "Struk / kwitansi", en: "Receipt", es: "Recibo" }, ex: { t: "Please keep your receipt.", m: { id: "Tolong simpan struk Anda.", en: "Please keep your receipt.", es: "Guarde su recibo." } } },
          { term: "Processing time", m: { id: "Waktu pemrosesan", en: "Processing time", es: "Tiempo de procesamiento" }, ex: { t: "The refund processing time is 7 business days.", m: { id: "Waktu proses refund 7 hari kerja.", en: "The refund processing time is 7 business days.", es: "El tiempo de procesamiento es de 7 días hábiles." } } },
          { term: "Voucher", m: { id: "Voucher", en: "Voucher", es: "Vale / bono" }, ex: { t: "We can offer you a travel voucher instead.", m: { id: "Kami bisa menawarkan voucher perjalanan sebagai gantinya.", en: "We can offer you a travel voucher instead.", es: "Podemos ofrecerle un bono de viaje en su lugar." } } },
          { term: "Customer service", m: { id: "Layanan pelanggan", en: "Customer service", es: "Atención al cliente" }, ex: { t: "Please contact customer service.", m: { id: "Silakan hubungi layanan pelanggan.", en: "Please contact customer service.", es: "Contacte con atención al cliente." } } },
          { term: "Approve", m: { id: "Menyetujui", en: "To approve", es: "Aprobar" }, ex: { t: "Your refund has been approved.", m: { id: "Refund Anda telah disetujui.", en: "Your refund has been approved.", es: "Su reembolso ha sido aprobado." } } },
          { term: "Decline", m: { id: "Menolak", en: "To decline / reject", es: "Rechazar" }, ex: { t: "The refund request was declined.", m: { id: "Permintaan refund ditolak.", en: "The refund request was declined.", es: "La solicitud de reembolso fue rechazada." } } },
          { term: "Compensation", m: { id: "Kompensasi / ganti rugi", en: "Compensation", es: "Compensación" }, ex: { t: "You may be entitled to compensation.", m: { id: "Anda mungkin berhak atas kompensasi.", en: "You may be entitled to compensation.", es: "Puede tener derecho a una compensación." } } },
          { term: "Rebook", m: { id: "Pesan ulang / ubah jadwal", en: "To rebook", es: "Reprogramar" }, ex: { t: "Can I rebook my flight for another day?", m: { id: "Bisakah saya pesan ulang penerbangan di hari lain?", en: "Can I rebook my flight for another day?", es: "¿Puedo reprogramar mi vuelo para otro día?" } } },
        ] },
    ],
  },

  /* ---------------------------------------------------------------- SPANISH */
  {
    id: "es", flag: "🇪🇸", native: "Español", speech: "es-ES", cjk: false,
    name: { id: "Bahasa Spanyol", en: "Spanish", es: "Español" },
    tagline: { id: "Dituturkan di lebih dari 20 negara.", en: "Spoken in over 20 countries.", es: "Hablado en más de 20 países." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Hola", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "Buenos días", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Gracias", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Por favor", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Me llamo…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "¿Cómo estás?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Mucho gusto", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Mucho gusto" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Uno", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Dos", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Tres", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Cuatro", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Cinco", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Seis", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Siete", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Diez", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Sí / No", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "No entiendo", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "¿Dónde está…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "¿Cuánto cuesta?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "¡Ayuda!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Adiós", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- FRENCH */
  {
    id: "fr", flag: "🇫🇷", native: "Français", speech: "fr-FR", cjk: false,
    name: { id: "Bahasa Prancis", en: "French", es: "Francés" },
    tagline: { id: "Bahasa diplomasi dan seni.", en: "The language of diplomacy and art.", es: "El idioma de la diplomacia y el arte." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Bonjour", m: { id: "Halo / selamat pagi", en: "Hello / good day", es: "Hola / buenos días" } },
          { term: "Merci", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "S'il vous plaît", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Je m'appelle…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "Comment ça va?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Enchanté", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Encantado" } },
          { term: "Au revoir", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Un", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Deux", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Trois", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Quatre", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Cinq", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Six", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Sept", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Dix", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Oui / Non", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "Je ne comprends pas", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Où est…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "Combien ça coûte?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Au secours!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Excusez-moi", m: { id: "Permisi", en: "Excuse me", es: "Disculpe" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- GERMAN */
  {
    id: "de", flag: "🇩🇪", native: "Deutsch", speech: "de-DE", cjk: false,
    name: { id: "Bahasa Jerman", en: "German", es: "Alemán" },
    tagline: { id: "Bahasa sains, teknik, dan filsafat.", en: "The language of science and engineering.", es: "El idioma de la ciencia y la ingeniería." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Hallo", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "Guten Morgen", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Danke", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Bitte", m: { id: "Tolong / sama-sama", en: "Please / you're welcome", es: "Por favor / de nada" } },
          { term: "Ich heiße…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "Wie geht's?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Auf Wiedersehen", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Eins", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Zwei", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Drei", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Vier", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Fünf", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Sechs", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Sieben", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Zehn", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Ja / Nein", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "Ich verstehe nicht", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Wo ist…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "Wie viel kostet das?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Hilfe!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Entschuldigung", m: { id: "Permisi / maaf", en: "Excuse me / sorry", es: "Disculpe" } },
        ] },
    ],
  },

  /* --------------------------------------------------------------- JAPANESE */
  {
    id: "ja", flag: "🇯🇵", native: "日本語", speech: "ja-JP", cjk: true,
    name: { id: "Bahasa Jepang", en: "Japanese", es: "Japonés" },
    tagline: { id: "Pintu menuju budaya pop dan teknologi.", en: "A gateway to pop culture and technology.", es: "Puerta a la cultura pop y la tecnología." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "こんにちは", reading: "Konnichiwa", m: { id: "Halo / selamat siang", en: "Hello / good afternoon", es: "Hola / buenas tardes" } },
          { term: "おはよう", reading: "Ohayō", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "ありがとう", reading: "Arigatō", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "すみません", reading: "Sumimasen", m: { id: "Permisi / maaf", en: "Excuse me / sorry", es: "Disculpe" } },
          { term: "はい / いいえ", reading: "Hai / Iie", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "さようなら", reading: "Sayōnara", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "一", reading: "Ichi", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "二", reading: "Ni", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "三", reading: "San", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "四", reading: "Yon / Shi", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "五", reading: "Go", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "六", reading: "Roku", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "七", reading: "Nana / Shichi", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "十", reading: "Jū", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "はじめまして", reading: "Hajimemashite", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Mucho gusto" } },
          { term: "わかりません", reading: "Wakarimasen", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "いくらですか", reading: "Ikura desu ka", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "どこですか", reading: "Doko desu ka", m: { id: "Di mana?", en: "Where is it?", es: "¿Dónde está?" } },
          { term: "おいしい", reading: "Oishii", m: { id: "Enak / lezat", en: "Delicious", es: "Delicioso" } },
          { term: "たすけて", reading: "Tasukete", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- KOREAN */
  {
    id: "ko", flag: "🇰🇷", native: "한국어", speech: "ko-KR", cjk: true,
    name: { id: "Bahasa Korea", en: "Korean", es: "Coreano" },
    tagline: { id: "Bahasa di balik K-pop dan K-drama.", en: "The language behind K-pop and K-drama.", es: "El idioma del K-pop y el K-drama." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "안녕하세요", reading: "Annyeonghaseyo", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "감사합니다", reading: "Gamsahamnida", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "죄송합니다", reading: "Joesonghamnida", m: { id: "Maaf", en: "Sorry", es: "Lo siento" } },
          { term: "네 / 아니요", reading: "Ne / Aniyo", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "안녕히 가세요", reading: "Annyeonghi gaseyo", m: { id: "Selamat jalan", en: "Goodbye (to one leaving)", es: "Adiós" } },
          { term: "반갑습니다", reading: "Bangapseumnida", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Mucho gusto" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "하나", reading: "Hana", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "둘", reading: "Dul", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "셋", reading: "Set", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "넷", reading: "Net", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "다섯", reading: "Daseot", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "여섯", reading: "Yeoseot", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "일곱", reading: "Ilgop", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "열", reading: "Yeol", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "몰라요", reading: "Mollayo", m: { id: "Saya tidak tahu", en: "I don't know", es: "No sé" } },
          { term: "얼마예요?", reading: "Eolmayeyo?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "어디예요?", reading: "Eodiyeyo?", m: { id: "Di mana?", en: "Where is it?", es: "¿Dónde está?" } },
          { term: "맛있어요", reading: "Masisseoyo", m: { id: "Enak / lezat", en: "Delicious", es: "Delicioso" } },
          { term: "도와주세요", reading: "Dowajuseyo", m: { id: "Tolong saya", en: "Please help me", es: "Ayúdeme" } },
          { term: "사랑해요", reading: "Saranghaeyo", m: { id: "Aku cinta kamu", en: "I love you", es: "Te quiero" } },
        ] },
      { id: "work", icon: "💼", level: "intermediate",
        title: { id: "Percakapan di Kantor", en: "Workplace Conversation", es: "Conversación en el trabajo" },
        items: [
          { term: "회사", reading: "Hoesa", m: { id: "Perusahaan / kantor", en: "Company", es: "Empresa" }, ex: { t: "저는 이 회사에서 일해요.", m: { id: "Saya bekerja di perusahaan ini.", en: "I work at this company.", es: "Trabajo en esta empresa." } } },
          { term: "사장님", reading: "Sajangnim", m: { id: "Bos / direktur", en: "Boss / CEO", es: "Jefe" }, ex: { t: "사장님, 잠시 시간 괜찮으세요?", m: { id: "Pak/Bu, ada waktu sebentar?", en: "Boss, do you have a moment?", es: "Jefe, ¿tiene un momento?" } } },
          { term: "팀장님", reading: "Timjangnim", m: { id: "Pemimpin tim", en: "Team leader", es: "Jefe de equipo" }, ex: { t: "팀장님께 보고했어요.", m: { id: "Saya sudah lapor ke pemimpin tim.", en: "I reported to the team leader.", es: "Informé al jefe de equipo." } } },
          { term: "동료", reading: "Dongnyo", m: { id: "Rekan kerja", en: "Colleague", es: "Colega" }, ex: { t: "제 동료가 도와줬어요.", m: { id: "Rekan kerja saya membantu.", en: "My colleague helped me.", es: "Mi colega me ayudó." } } },
          { term: "회의", reading: "Hoeui", m: { id: "Rapat", en: "Meeting", es: "Reunión" }, ex: { t: "오후 2시에 회의가 있어요.", m: { id: "Ada rapat jam dua siang.", en: "There's a meeting at 2 PM.", es: "Hay una reunión a las 2." } } },
          { term: "보고서", reading: "Bogoseo", m: { id: "Laporan", en: "Report", es: "Informe" }, ex: { t: "보고서를 작성하고 있어요.", m: { id: "Saya sedang membuat laporan.", en: "I'm writing the report.", es: "Estoy redactando el informe." } } },
          { term: "마감", reading: "Magam", m: { id: "Tenggat waktu", en: "Deadline", es: "Fecha límite" }, ex: { t: "마감이 내일까지예요.", m: { id: "Tenggatnya sampai besok.", en: "The deadline is tomorrow.", es: "La fecha límite es mañana." } } },
          { term: "출근하다", reading: "Chulgeunhada", m: { id: "Masuk / berangkat kerja", en: "To go to work", es: "Ir a trabajar" }, ex: { t: "저는 아침 9시에 출근해요.", m: { id: "Saya masuk kerja jam sembilan pagi.", en: "I go to work at 9 AM.", es: "Entro a trabajar a las nueve." } } },
          { term: "퇴근하다", reading: "Toegeunhada", m: { id: "Pulang kerja", en: "To leave work", es: "Salir del trabajo" }, ex: { t: "보통 6시에 퇴근해요.", m: { id: "Biasanya pulang kerja jam enam.", en: "I usually leave work at 6.", es: "Suelo salir a las seis." } } },
          { term: "야근", reading: "Yageun", m: { id: "Lembur", en: "Overtime", es: "Horas extra" }, ex: { t: "오늘 야근해야 해요.", m: { id: "Hari ini harus lembur.", en: "I have to work overtime today.", es: "Hoy tengo que hacer horas extra." } } },
          { term: "휴가", reading: "Hyuga", m: { id: "Cuti / libur", en: "Leave / vacation", es: "Vacaciones / permiso" }, ex: { t: "다음 주에 휴가를 낼 거예요.", m: { id: "Minggu depan saya akan ambil cuti.", en: "I'll take leave next week.", es: "Tomaré vacaciones la próxima semana." } } },
          { term: "명함", reading: "Myeongham", m: { id: "Kartu nama", en: "Business card", es: "Tarjeta de visita" }, ex: { t: "제 명함입니다.", m: { id: "Ini kartu nama saya.", en: "Here's my business card.", es: "Aquí tiene mi tarjeta." } } },
          { term: "회식", reading: "Hoesik", m: { id: "Makan bersama kantor", en: "Company dinner", es: "Cena de empresa" }, ex: { t: "오늘 저녁에 회식이 있어요.", m: { id: "Malam ini ada acara makan kantor.", en: "There's a company dinner tonight.", es: "Esta noche hay cena de empresa." } } },
          { term: "수고하셨습니다", reading: "Sugohasyeotseumnida", m: { id: "Terima kasih atas kerja kerasnya", en: "Good work / thanks for your effort", es: "Buen trabajo / gracias por su esfuerzo" }, ex: { t: "오늘도 수고하셨습니다.", m: { id: "Terima kasih atas kerja keras hari ini.", en: "Good work again today.", es: "Buen trabajo otra vez hoy." } } },
          { term: "잘 부탁드립니다", reading: "Jal butakdeurimnida", m: { id: "Mohon kerja samanya", en: "I look forward to working with you", es: "Cuento con su ayuda" }, ex: { t: "앞으로 잘 부탁드립니다.", m: { id: "Mohon kerja samanya ke depan.", en: "I look forward to working with you.", es: "Espero trabajar bien con usted." } } },
        ] },
      { id: "ticket", icon: "✈️", level: "intermediate",
        title: { id: "Tiket Pesawat & Bandara", en: "Flight Tickets & Airport", es: "Billetes de avión y aeropuerto" },
        items: [
          { term: "항공권", reading: "Hanggonggwon", m: { id: "Tiket pesawat", en: "Airline ticket", es: "Billete de avión" }, ex: { t: "항공권을 예약하고 싶어요.", m: { id: "Saya ingin memesan tiket pesawat.", en: "I'd like to book a plane ticket.", es: "Quiero reservar un billete de avión." } } },
          { term: "예약", reading: "Yeyak", m: { id: "Reservasi / pemesanan", en: "Reservation / booking", es: "Reserva" }, ex: { t: "예약을 확인하고 싶어요.", m: { id: "Saya ingin konfirmasi reservasi.", en: "I'd like to confirm my reservation.", es: "Quiero confirmar mi reserva." } } },
          { term: "편도", reading: "Pyeondo", m: { id: "Sekali jalan", en: "One-way", es: "Solo ida" }, ex: { t: "편도 티켓 한 장 주세요.", m: { id: "Tolong satu tiket sekali jalan.", en: "One one-way ticket, please.", es: "Un billete de ida, por favor." } } },
          { term: "왕복", reading: "Wangbok", m: { id: "Pulang-pergi", en: "Round trip", es: "Ida y vuelta" }, ex: { t: "왕복 항공권은 얼마예요?", m: { id: "Berapa harga tiket pulang-pergi?", en: "How much is a round-trip ticket?", es: "¿Cuánto cuesta un billete de ida y vuelta?" } } },
          { term: "출발", reading: "Chulbal", m: { id: "Keberangkatan", en: "Departure", es: "Salida" }, ex: { t: "출발 시간이 몇 시예요?", m: { id: "Jam berapa keberangkatannya?", en: "What time is departure?", es: "¿A qué hora es la salida?" } } },
          { term: "도착", reading: "Dochak", m: { id: "Kedatangan", en: "Arrival", es: "Llegada" }, ex: { t: "도착 시간은 오후 3시예요.", m: { id: "Waktu tiba jam tiga sore.", en: "Arrival time is 3 PM.", es: "La llegada es a las tres." } } },
          { term: "공항", reading: "Gonghang", m: { id: "Bandara", en: "Airport", es: "Aeropuerto" }, ex: { t: "공항까지 어떻게 가요?", m: { id: "Bagaimana cara ke bandara?", en: "How do I get to the airport?", es: "¿Cómo llego al aeropuerto?" } } },
          { term: "탑승권", reading: "Tapseunggwon", m: { id: "Pas naik (boarding pass)", en: "Boarding pass", es: "Tarjeta de embarque" }, ex: { t: "탑승권을 보여 주세요.", m: { id: "Tolong tunjukkan boarding pass Anda.", en: "Please show your boarding pass.", es: "Muestre su tarjeta de embarque." } } },
          { term: "탑승구", reading: "Tapseunggu", m: { id: "Gerbang (gate)", en: "Boarding gate", es: "Puerta de embarque" }, ex: { t: "탑승구는 15번이에요.", m: { id: "Gerbangnya nomor 15.", en: "The gate is number 15.", es: "La puerta es la 15." } } },
          { term: "수하물", reading: "Suhamul", m: { id: "Bagasi", en: "Baggage", es: "Equipaje" }, ex: { t: "수하물은 몇 개까지 돼요?", m: { id: "Bagasi boleh berapa buah?", en: "How many bags are allowed?", es: "¿Cuántas maletas se permiten?" } } },
          { term: "좌석", reading: "Jwaseok", m: { id: "Kursi / tempat duduk", en: "Seat", es: "Asiento" }, ex: { t: "창가 좌석으로 주세요.", m: { id: "Tolong kursi dekat jendela.", en: "A window seat, please.", es: "Un asiento de ventanilla, por favor." } } },
          { term: "통로 자리", reading: "Tongno jari", m: { id: "Kursi lorong", en: "Aisle seat", es: "Asiento de pasillo" }, ex: { t: "통로 자리로 바꿀 수 있어요?", m: { id: "Bisa pindah ke kursi lorong?", en: "Can I change to an aisle seat?", es: "¿Puedo cambiar a un asiento de pasillo?" } } },
          { term: "여권", reading: "Yeogwon", m: { id: "Paspor", en: "Passport", es: "Pasaporte" }, ex: { t: "여권을 준비해 주세요.", m: { id: "Tolong siapkan paspor Anda.", en: "Please have your passport ready.", es: "Tenga su pasaporte listo." } } },
          { term: "지연", reading: "Jiyeon", m: { id: "Penundaan / delay", en: "Delay", es: "Retraso" }, ex: { t: "비행기가 지연됐어요.", m: { id: "Pesawatnya tertunda.", en: "The flight is delayed.", es: "El vuelo está retrasado." } } },
          { term: "결항", reading: "Gyeolhang", m: { id: "Penerbangan dibatalkan", en: "Flight cancellation", es: "Cancelación del vuelo" }, ex: { t: "태풍으로 항공편이 결항됐어요.", m: { id: "Penerbangan dibatalkan karena topan.", en: "The flight was canceled due to a typhoon.", es: "El vuelo se canceló por un tifón." } } },
          { term: "체크인", reading: "Chekeuin", m: { id: "Lapor diri (check-in)", en: "Check-in", es: "Facturación" }, ex: { t: "온라인으로 체크인했어요.", m: { id: "Saya check-in lewat online.", en: "I checked in online.", es: "Hice el check-in por internet." } } },
        ] },
      { id: "refund", icon: "💸", level: "advanced",
        title: { id: "Refund & Pembatalan", en: "Refunds & Cancellations", es: "Reembolsos y cancelaciones" },
        items: [
          { term: "환불", reading: "Hwanbul", m: { id: "Refund / pengembalian dana", en: "Refund", es: "Reembolso" }, ex: { t: "환불을 받고 싶어요.", m: { id: "Saya ingin minta refund.", en: "I'd like a refund.", es: "Quiero un reembolso." } } },
          { term: "취소", reading: "Chwiso", m: { id: "Pembatalan", en: "Cancellation", es: "Cancelación" }, ex: { t: "예약을 취소하고 싶어요.", m: { id: "Saya ingin membatalkan reservasi.", en: "I want to cancel my reservation.", es: "Quiero cancelar mi reserva." } } },
          { term: "수수료", reading: "Susuryo", m: { id: "Biaya administrasi", en: "Fee / charge", es: "Comisión" }, ex: { t: "취소 수수료가 있어요?", m: { id: "Apakah ada biaya pembatalan?", en: "Is there a cancellation fee?", es: "¿Hay comisión por cancelar?" } } },
          { term: "위약금", reading: "Wiyakgeum", m: { id: "Denda pembatalan", en: "Penalty fee", es: "Penalización" }, ex: { t: "위약금이 얼마예요?", m: { id: "Berapa dendanya?", en: "How much is the penalty?", es: "¿Cuánto es la penalización?" } } },
          { term: "전액 환불", reading: "Jeonaek hwanbul", m: { id: "Refund penuh", en: "Full refund", es: "Reembolso total" }, ex: { t: "전액 환불이 가능해요?", m: { id: "Apakah bisa refund penuh?", en: "Is a full refund possible?", es: "¿Es posible un reembolso total?" } } },
          { term: "부분 환불", reading: "Bubun hwanbul", m: { id: "Refund sebagian", en: "Partial refund", es: "Reembolso parcial" }, ex: { t: "부분 환불만 가능해요.", m: { id: "Hanya bisa refund sebagian.", en: "Only a partial refund is available.", es: "Solo es posible un reembolso parcial." } } },
          { term: "환불 규정", reading: "Hwanbul gyujeong", m: { id: "Kebijakan refund", en: "Refund policy", es: "Política de reembolso" }, ex: { t: "환불 규정을 알려 주세요.", m: { id: "Tolong beri tahu kebijakan refundnya.", en: "Please tell me the refund policy.", es: "Dígame la política de reembolso." } } },
          { term: "환불 불가", reading: "Hwanbul bulga", m: { id: "Tidak bisa direfund", en: "Non-refundable", es: "No reembolsable" }, ex: { t: "이 티켓은 환불 불가예요.", m: { id: "Tiket ini tidak bisa direfund.", en: "This ticket is non-refundable.", es: "Este billete no es reembolsable." } } },
          { term: "영수증", reading: "Yeongsujeung", m: { id: "Struk / kwitansi", en: "Receipt", es: "Recibo" }, ex: { t: "영수증을 첨부해 주세요.", m: { id: "Tolong lampirkan struknya.", en: "Please attach the receipt.", es: "Adjunte el recibo, por favor." } } },
          { term: "처리 기간", reading: "Cheori gigan", m: { id: "Waktu pemrosesan", en: "Processing time", es: "Tiempo de procesamiento" }, ex: { t: "처리 기간은 영업일 기준 5일이에요.", m: { id: "Prosesnya lima hari kerja.", en: "Processing takes five business days.", es: "El procesamiento tarda cinco días hábiles." } } },
          { term: "계좌", reading: "Gyejwa", m: { id: "Rekening bank", en: "Bank account", es: "Cuenta bancaria" }, ex: { t: "환불은 어느 계좌로 받으시겠어요?", m: { id: "Refund mau dikirim ke rekening mana?", en: "Which account should the refund go to?", es: "¿A qué cuenta enviamos el reembolso?" } } },
          { term: "요청하다", reading: "Yocheonghada", m: { id: "Meminta / mengajukan", en: "To request", es: "Solicitar" }, ex: { t: "환불을 요청했어요.", m: { id: "Saya sudah mengajukan refund.", en: "I requested a refund.", es: "Solicité un reembolso." } } },
          { term: "승인", reading: "Seungin", m: { id: "Persetujuan", en: "Approval", es: "Aprobación" }, ex: { t: "환불이 승인됐어요.", m: { id: "Refundnya disetujui.", en: "The refund was approved.", es: "El reembolso fue aprobado." } } },
          { term: "거절", reading: "Geojeol", m: { id: "Penolakan", en: "Rejection", es: "Rechazo" }, ex: { t: "환불 요청이 거절됐어요.", m: { id: "Permintaan refund ditolak.", en: "The refund request was rejected.", es: "La solicitud de reembolso fue rechazada." } } },
          { term: "고객센터", reading: "Gogaeksenteo", m: { id: "Layanan pelanggan", en: "Customer center", es: "Atención al cliente" }, ex: { t: "고객센터에 문의하세요.", m: { id: "Silakan hubungi layanan pelanggan.", en: "Please contact the customer center.", es: "Contacte con atención al cliente." } } },
          { term: "변경", reading: "Byeongyeong", m: { id: "Perubahan jadwal", en: "Change / rebooking", es: "Cambio" }, ex: { t: "날짜를 변경하고 싶어요.", m: { id: "Saya ingin mengubah tanggal.", en: "I want to change the date.", es: "Quiero cambiar la fecha." } } },
        ] },
    ],
  },

  /* ------------------------------------------------------ MANDARIN CHINESE */
  {
    id: "zh", flag: "🇨🇳", native: "中文", speech: "zh-CN", cjk: true,
    name: { id: "Bahasa Mandarin", en: "Mandarin Chinese", es: "Chino mandarín" },
    tagline: { id: "Bahasa dengan penutur terbanyak di dunia.", en: "The most spoken language in the world.", es: "El idioma más hablado del mundo." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "你好", reading: "Nǐ hǎo", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "谢谢", reading: "Xièxie", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "对不起", reading: "Duìbuqǐ", m: { id: "Maaf", en: "Sorry", es: "Lo siento" } },
          { term: "是 / 不是", reading: "Shì / Bù shì", m: { id: "Ya / Bukan", en: "Yes / No", es: "Sí / No" } },
          { term: "再见", reading: "Zàijiàn", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
          { term: "请", reading: "Qǐng", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "一", reading: "Yī", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "二", reading: "Èr", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "三", reading: "Sān", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "四", reading: "Sì", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "五", reading: "Wǔ", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "六", reading: "Liù", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "七", reading: "Qī", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "十", reading: "Shí", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "我不懂", reading: "Wǒ bù dǒng", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "多少钱?", reading: "Duōshao qián?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "在哪里?", reading: "Zài nǎlǐ?", m: { id: "Di mana?", en: "Where is it?", es: "¿Dónde está?" } },
          { term: "很好吃", reading: "Hěn hǎochī", m: { id: "Sangat enak", en: "Very delicious", es: "Muy rico" } },
          { term: "救命!", reading: "Jiùmìng!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "我爱你", reading: "Wǒ ài nǐ", m: { id: "Aku cinta kamu", en: "I love you", es: "Te quiero" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- ARABIC */
  {
    id: "ar", flag: "🇸🇦", native: "العربية", speech: "ar-SA", cjk: false, rtl: true,
    name: { id: "Bahasa Arab", en: "Arabic", es: "Árabe" },
    tagline: { id: "Bahasa Al-Qur'an dan dunia Arab.", en: "The language of the Qur'an and the Arab world.", es: "El idioma del Corán y el mundo árabe." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "مرحبا", reading: "Marhaban", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "السلام عليكم", reading: "As-salāmu ʿalaykum", m: { id: "Salam sejahtera", en: "Peace be upon you", es: "La paz sea contigo" } },
          { term: "شكرا", reading: "Shukran", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "من فضلك", reading: "Min faḍlik", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "نعم / لا", reading: "Naʿam / Lā", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "مع السلامة", reading: "Maʿa as-salāma", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "واحد", reading: "Wāḥid", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "اثنان", reading: "Ithnān", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "ثلاثة", reading: "Thalātha", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "أربعة", reading: "Arbaʿa", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "خمسة", reading: "Khamsa", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "ستة", reading: "Sitta", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "سبعة", reading: "Sabʿa", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "عشرة", reading: "ʿAshara", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "لا أفهم", reading: "Lā afham", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "كم الثمن؟", reading: "Kam ath-thaman?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "أين…؟", reading: "Ayna…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "لذيذ", reading: "Ladhīdh", m: { id: "Lezat", en: "Delicious", es: "Delicioso" } },
          { term: "النجدة!", reading: "An-najda!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "كيف حالك؟", reading: "Kayfa ḥāluk?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
        ] },
    ],
  },

  /* ---------------------------------------------------------------- ITALIAN */
  {
    id: "it", flag: "🇮🇹", native: "Italiano", speech: "it-IT", cjk: false,
    name: { id: "Bahasa Italia", en: "Italian", es: "Italiano" },
    tagline: { id: "Bahasa seni, musik, dan kuliner.", en: "The language of art, music, and cuisine.", es: "El idioma del arte, la música y la cocina." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Ciao", m: { id: "Halo / dah", en: "Hello / bye", es: "Hola / chao" } },
          { term: "Buongiorno", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Grazie", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Per favore", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Mi chiamo…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "Come stai?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Arrivederci", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Uno", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Due", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Tre", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Quattro", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Cinque", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Sei", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Sette", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Dieci", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Sì / No", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "Non capisco", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Dov'è…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "Quanto costa?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Aiuto!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Scusi", m: { id: "Permisi / maaf", en: "Excuse me", es: "Disculpe" } },
        ] },
    ],
  },

  /* ------------------------------------------------------------- PORTUGUESE */
  {
    id: "pt", flag: "🇧🇷", native: "Português", speech: "pt-BR", cjk: false,
    name: { id: "Bahasa Portugis", en: "Portuguese", es: "Portugués" },
    tagline: { id: "Dituturkan di empat benua.", en: "Spoken across four continents.", es: "Hablado en cuatro continentes." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Olá", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "Bom dia", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Obrigado", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Por favor", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Meu nome é…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "Como vai?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Tchau", m: { id: "Sampai jumpa", en: "Bye", es: "Chao" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Um", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Dois", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Três", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Quatro", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Cinco", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Seis", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Sete", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Dez", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Sim / Não", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "Não entendo", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Onde fica…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "Quanto custa?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Socorro!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Com licença", m: { id: "Permisi", en: "Excuse me", es: "Disculpe" } },
        ] },
    ],
  },

  /* ---------------------------------------------------------------- RUSSIAN */
  {
    id: "ru", flag: "🇷🇺", native: "Русский", speech: "ru-RU", cjk: false,
    name: { id: "Bahasa Rusia", en: "Russian", es: "Ruso" },
    tagline: { id: "Bahasa Slavia dengan penutur terbanyak.", en: "The most spoken Slavic language.", es: "La lengua eslava más hablada." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "Здравствуйте", reading: "Zdravstvuyte", m: { id: "Halo (formal)", en: "Hello (formal)", es: "Hola (formal)" } },
          { term: "Привет", reading: "Privet", m: { id: "Hai (santai)", en: "Hi (casual)", es: "Hola (informal)" } },
          { term: "Спасибо", reading: "Spasibo", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Пожалуйста", reading: "Pozhaluysta", m: { id: "Tolong / sama-sama", en: "Please / you're welcome", es: "Por favor / de nada" } },
          { term: "Меня зовут…", reading: "Menya zovut…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "До свидания", reading: "Do svidaniya", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Один", reading: "Odin", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Два", reading: "Dva", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Три", reading: "Tri", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Четыре", reading: "Chetyre", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Пять", reading: "Pyat'", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Шесть", reading: "Shest'", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Семь", reading: "Sem'", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Десять", reading: "Desyat'", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Да / Нет", reading: "Da / Net", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "Я не понимаю", reading: "Ya ne ponimayu", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Где…?", reading: "Gde…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "Сколько стоит?", reading: "Skol'ko stoit?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Помогите!", reading: "Pomogite!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Извините", reading: "Izvinite", m: { id: "Permisi / maaf", en: "Excuse me", es: "Disculpe" } },
        ] },
    ],
  },

  /* ------------------------------------------------------------------ HINDI */
  {
    id: "hi", flag: "🇮🇳", native: "हिन्दी", speech: "hi-IN", cjk: false,
    name: { id: "Bahasa Hindi", en: "Hindi", es: "Hindi" },
    tagline: { id: "Salah satu bahasa terbesar di Asia Selatan.", en: "One of South Asia's largest languages.", es: "Una de las mayores lenguas del sur de Asia." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "नमस्ते", reading: "Namaste", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "सुप्रभात", reading: "Suprabhāt", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "धन्यवाद", reading: "Dhanyavād", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "कृपया", reading: "Kṛpayā", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "मेरा नाम… है", reading: "Merā nām… hai", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "अलविदा", reading: "Alvidā", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "एक", reading: "Ek", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "दो", reading: "Do", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "तीन", reading: "Tīn", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "चार", reading: "Chār", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "पाँच", reading: "Pā̃ch", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "छह", reading: "Chhah", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "सात", reading: "Sāt", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "दस", reading: "Das", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "हाँ / नहीं", reading: "Hā̃ / Nahī̃", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "मैं नहीं समझा", reading: "Maĩ nahī̃ samjhā", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "कहाँ है…?", reading: "Kahā̃ hai…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "कितने का है?", reading: "Kitne kā hai?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "मदद!", reading: "Madad!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "माफ़ कीजिए", reading: "Māf kījie", m: { id: "Permisi / maaf", en: "Excuse me", es: "Disculpe" } },
        ] },
    ],
  },
];

export const findCourse = (id) => COURSES.find((c) => c.id === id);
export const findLesson = (course, lid) => course && course.lessons.find((l) => l.id === lid);
