/* =========================================================================
   data.js — Course & lesson content
   Each meaning `m` is provided in the 3 UI languages (id / en / es).
   `reading` = romanization for non-Latin scripts. `speech` = BCP-47 TTS code.
   ========================================================================= */
window.COURSES = [
  /* ---------------------------------------------------------------- ENGLISH */
  {
    id: "en", flag: "🇬🇧", native: "English", speech: "en-US", cjk: false,
    name: { id: "Bahasa Inggris", en: "English", es: "Inglés" },
    tagline: { id: "Bahasa internasional nomor satu di dunia.", en: "The world's number one international language.", es: "El idioma internacional número uno." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Hello", m: { id: "Halo", en: "Hello", es: "Hola" }, ex: { t: "Hello, nice to meet you.", m: { id: "Halo, senang bertemu denganmu.", en: "Hello, nice to meet you.", es: "Hola, encantado de conocerte." } } },
          { term: "Good morning", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Thank you", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Please", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Excuse me", m: { id: "Permisi", en: "Excuse me", es: "Disculpe" } },
          { term: "My name is…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "How are you?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "One", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Two", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Three", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Four", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Five", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Six", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Seven", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Ten", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Yes / No", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "I don't understand", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Where is…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "How much is it?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Help!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Goodbye", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
    ],
  },

  /* ---------------------------------------------------------------- SPANISH */
  {
    id: "es", flag: "🇪🇸", native: "Español", speech: "es-ES", cjk: false,
    name: { id: "Bahasa Spanyol", en: "Spanish", es: "Español" },
    tagline: { id: "Dituturkan di lebih dari 20 negara.", en: "Spoken in over 20 countries.", es: "Hablado en más de 20 países." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Hola", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "Buenos días", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Gracias", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Por favor", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Me llamo…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "¿Cómo estás?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Mucho gusto", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Mucho gusto" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Uno", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Dos", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Tres", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Cuatro", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Cinco", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Seis", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Siete", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Diez", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Sí / No", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "No entiendo", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "¿Dónde está…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "¿Cuánto cuesta?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "¡Ayuda!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Adiós", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- FRENCH */
  {
    id: "fr", flag: "🇫🇷", native: "Français", speech: "fr-FR", cjk: false,
    name: { id: "Bahasa Prancis", en: "French", es: "Francés" },
    tagline: { id: "Bahasa diplomasi dan seni.", en: "The language of diplomacy and art.", es: "El idioma de la diplomacia y el arte." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Bonjour", m: { id: "Halo / selamat pagi", en: "Hello / good day", es: "Hola / buenos días" } },
          { term: "Merci", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "S'il vous plaît", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "Je m'appelle…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "Comment ça va?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Enchanté", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Encantado" } },
          { term: "Au revoir", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Un", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Deux", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Trois", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Quatre", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Cinq", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Six", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Sept", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Dix", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Oui / Non", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "Je ne comprends pas", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Où est…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "Combien ça coûte?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Au secours!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Excusez-moi", m: { id: "Permisi", en: "Excuse me", es: "Disculpe" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- GERMAN */
  {
    id: "de", flag: "🇩🇪", native: "Deutsch", speech: "de-DE", cjk: false,
    name: { id: "Bahasa Jerman", en: "German", es: "Alemán" },
    tagline: { id: "Bahasa sains, teknik, dan filsafat.", en: "The language of science and engineering.", es: "El idioma de la ciencia y la ingeniería." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan & Perkenalan", en: "Greetings & Introductions", es: "Saludos y presentaciones" },
        items: [
          { term: "Hallo", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "Guten Morgen", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "Danke", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "Bitte", m: { id: "Tolong / sama-sama", en: "Please / you're welcome", es: "Por favor / de nada" } },
          { term: "Ich heiße…", m: { id: "Nama saya…", en: "My name is…", es: "Me llamo…" } },
          { term: "Wie geht's?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
          { term: "Auf Wiedersehen", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "Eins", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "Zwei", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "Drei", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "Vier", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "Fünf", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "Sechs", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "Sieben", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "Zehn", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "Ja / Nein", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "Ich verstehe nicht", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "Wo ist…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "Wie viel kostet das?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "Hilfe!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "Entschuldigung", m: { id: "Permisi / maaf", en: "Excuse me / sorry", es: "Disculpe" } },
        ] },
    ],
  },

  /* --------------------------------------------------------------- JAPANESE */
  {
    id: "ja", flag: "🇯🇵", native: "日本語", speech: "ja-JP", cjk: true,
    name: { id: "Bahasa Jepang", en: "Japanese", es: "Japonés" },
    tagline: { id: "Pintu menuju budaya pop dan teknologi.", en: "A gateway to pop culture and technology.", es: "Puerta a la cultura pop y la tecnología." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "こんにちは", reading: "Konnichiwa", m: { id: "Halo / selamat siang", en: "Hello / good afternoon", es: "Hola / buenas tardes" } },
          { term: "おはよう", reading: "Ohayō", m: { id: "Selamat pagi", en: "Good morning", es: "Buenos días" } },
          { term: "ありがとう", reading: "Arigatō", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "すみません", reading: "Sumimasen", m: { id: "Permisi / maaf", en: "Excuse me / sorry", es: "Disculpe" } },
          { term: "はい / いいえ", reading: "Hai / Iie", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "さようなら", reading: "Sayōnara", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "一", reading: "Ichi", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "二", reading: "Ni", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "三", reading: "San", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "四", reading: "Yon / Shi", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "五", reading: "Go", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "六", reading: "Roku", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "七", reading: "Nana / Shichi", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "十", reading: "Jū", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "はじめまして", reading: "Hajimemashite", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Mucho gusto" } },
          { term: "わかりません", reading: "Wakarimasen", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "いくらですか", reading: "Ikura desu ka", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "どこですか", reading: "Doko desu ka", m: { id: "Di mana?", en: "Where is it?", es: "¿Dónde está?" } },
          { term: "おいしい", reading: "Oishii", m: { id: "Enak / lezat", en: "Delicious", es: "Delicioso" } },
          { term: "たすけて", reading: "Tasukete", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- KOREAN */
  {
    id: "ko", flag: "🇰🇷", native: "한국어", speech: "ko-KR", cjk: true,
    name: { id: "Bahasa Korea", en: "Korean", es: "Coreano" },
    tagline: { id: "Bahasa di balik K-pop dan K-drama.", en: "The language behind K-pop and K-drama.", es: "El idioma del K-pop y el K-drama." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "안녕하세요", reading: "Annyeonghaseyo", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "감사합니다", reading: "Gamsahamnida", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "죄송합니다", reading: "Joesonghamnida", m: { id: "Maaf", en: "Sorry", es: "Lo siento" } },
          { term: "네 / 아니요", reading: "Ne / Aniyo", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "안녕히 가세요", reading: "Annyeonghi gaseyo", m: { id: "Selamat jalan", en: "Goodbye (to one leaving)", es: "Adiós" } },
          { term: "반갑습니다", reading: "Bangapseumnida", m: { id: "Senang berkenalan", en: "Nice to meet you", es: "Mucho gusto" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "하나", reading: "Hana", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "둘", reading: "Dul", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "셋", reading: "Set", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "넷", reading: "Net", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "다섯", reading: "Daseot", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "여섯", reading: "Yeoseot", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "일곱", reading: "Ilgop", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "열", reading: "Yeol", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "몰라요", reading: "Mollayo", m: { id: "Saya tidak tahu", en: "I don't know", es: "No sé" } },
          { term: "얼마예요?", reading: "Eolmayeyo?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "어디예요?", reading: "Eodiyeyo?", m: { id: "Di mana?", en: "Where is it?", es: "¿Dónde está?" } },
          { term: "맛있어요", reading: "Masisseoyo", m: { id: "Enak / lezat", en: "Delicious", es: "Delicioso" } },
          { term: "도와주세요", reading: "Dowajuseyo", m: { id: "Tolong saya", en: "Please help me", es: "Ayúdeme" } },
          { term: "사랑해요", reading: "Saranghaeyo", m: { id: "Aku cinta kamu", en: "I love you", es: "Te quiero" } },
        ] },
    ],
  },

  /* ------------------------------------------------------ MANDARIN CHINESE */
  {
    id: "zh", flag: "🇨🇳", native: "中文", speech: "zh-CN", cjk: true,
    name: { id: "Bahasa Mandarin", en: "Mandarin Chinese", es: "Chino mandarín" },
    tagline: { id: "Bahasa dengan penutur terbanyak di dunia.", en: "The most spoken language in the world.", es: "El idioma más hablado del mundo." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "你好", reading: "Nǐ hǎo", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "谢谢", reading: "Xièxie", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "对不起", reading: "Duìbuqǐ", m: { id: "Maaf", en: "Sorry", es: "Lo siento" } },
          { term: "是 / 不是", reading: "Shì / Bù shì", m: { id: "Ya / Bukan", en: "Yes / No", es: "Sí / No" } },
          { term: "再见", reading: "Zàijiàn", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
          { term: "请", reading: "Qǐng", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "一", reading: "Yī", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "二", reading: "Èr", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "三", reading: "Sān", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "四", reading: "Sì", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "五", reading: "Wǔ", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "六", reading: "Liù", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "七", reading: "Qī", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "十", reading: "Shí", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "我不懂", reading: "Wǒ bù dǒng", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "多少钱?", reading: "Duōshao qián?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "在哪里?", reading: "Zài nǎlǐ?", m: { id: "Di mana?", en: "Where is it?", es: "¿Dónde está?" } },
          { term: "很好吃", reading: "Hěn hǎochī", m: { id: "Sangat enak", en: "Very delicious", es: "Muy rico" } },
          { term: "救命!", reading: "Jiùmìng!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "我爱你", reading: "Wǒ ài nǐ", m: { id: "Aku cinta kamu", en: "I love you", es: "Te quiero" } },
        ] },
    ],
  },

  /* ----------------------------------------------------------------- ARABIC */
  {
    id: "ar", flag: "🇸🇦", native: "العربية", speech: "ar-SA", cjk: false, rtl: true,
    name: { id: "Bahasa Arab", en: "Arabic", es: "Árabe" },
    tagline: { id: "Bahasa Al-Qur'an dan dunia Arab.", en: "The language of the Qur'an and the Arab world.", es: "El idioma del Corán y el mundo árabe." },
    lessons: [
      { id: "greet", icon: "👋", level: "beginner",
        title: { id: "Sapaan Dasar", en: "Basic Greetings", es: "Saludos básicos" },
        items: [
          { term: "مرحبا", reading: "Marhaban", m: { id: "Halo", en: "Hello", es: "Hola" } },
          { term: "السلام عليكم", reading: "As-salāmu ʿalaykum", m: { id: "Salam sejahtera", en: "Peace be upon you", es: "La paz sea contigo" } },
          { term: "شكرا", reading: "Shukran", m: { id: "Terima kasih", en: "Thank you", es: "Gracias" } },
          { term: "من فضلك", reading: "Min faḍlik", m: { id: "Tolong / silakan", en: "Please", es: "Por favor" } },
          { term: "نعم / لا", reading: "Naʿam / Lā", m: { id: "Ya / Tidak", en: "Yes / No", es: "Sí / No" } },
          { term: "مع السلامة", reading: "Maʿa as-salāma", m: { id: "Selamat tinggal", en: "Goodbye", es: "Adiós" } },
        ] },
      { id: "num", icon: "🔢", level: "beginner",
        title: { id: "Angka 1–10", en: "Numbers 1–10", es: "Números 1–10" },
        items: [
          { term: "واحد", reading: "Wāḥid", m: { id: "Satu", en: "One", es: "Uno" } },
          { term: "اثنان", reading: "Ithnān", m: { id: "Dua", en: "Two", es: "Dos" } },
          { term: "ثلاثة", reading: "Thalātha", m: { id: "Tiga", en: "Three", es: "Tres" } },
          { term: "أربعة", reading: "Arbaʿa", m: { id: "Empat", en: "Four", es: "Cuatro" } },
          { term: "خمسة", reading: "Khamsa", m: { id: "Lima", en: "Five", es: "Cinco" } },
          { term: "ستة", reading: "Sitta", m: { id: "Enam", en: "Six", es: "Seis" } },
          { term: "سبعة", reading: "Sabʿa", m: { id: "Tujuh", en: "Seven", es: "Siete" } },
          { term: "عشرة", reading: "ʿAshara", m: { id: "Sepuluh", en: "Ten", es: "Diez" } },
        ] },
      { id: "ess", icon: "💬", level: "elementary",
        title: { id: "Frasa Penting", en: "Essential Phrases", es: "Frases esenciales" },
        items: [
          { term: "لا أفهم", reading: "Lā afham", m: { id: "Saya tidak mengerti", en: "I don't understand", es: "No entiendo" } },
          { term: "كم الثمن؟", reading: "Kam ath-thaman?", m: { id: "Berapa harganya?", en: "How much is it?", es: "¿Cuánto cuesta?" } },
          { term: "أين…؟", reading: "Ayna…?", m: { id: "Di mana…?", en: "Where is…?", es: "¿Dónde está…?" } },
          { term: "لذيذ", reading: "Ladhīdh", m: { id: "Lezat", en: "Delicious", es: "Delicioso" } },
          { term: "النجدة!", reading: "An-najda!", m: { id: "Tolong!", en: "Help!", es: "¡Ayuda!" } },
          { term: "كيف حالك؟", reading: "Kayfa ḥāluk?", m: { id: "Apa kabar?", en: "How are you?", es: "¿Cómo estás?" } },
        ] },
    ],
  },
];

window.findCourse = (id) => window.COURSES.find((c) => c.id === id);
window.findLesson = (course, lid) => course && course.lessons.find((l) => l.id === lid);
