/* =========================================================================
   lexicon/ar.js — قاموس: العربية (Modern Standard Arabic).
   Front matter + 72 headwords, A1→C2. Entri difilekan menurut huruf dasarnya
   (أ/إ/آ dikembalikan ke ا), seperti kamus Arab cetak.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Arab dibangun di atas akar tiga huruf. Dari satu akar seperti ك-ت-ب lahir كَتَبَ (menulis), كِتاب (buku), مَكْتَب (kantor), كاتِب (penulis) — memahami pola akarnya berarti membuka ratusan kata sekaligus.",
    "Arabic is built on three-letter roots. From one root like ك-ت-ب come كَتَبَ (to write), كِتاب (book), مَكْتَب (office), كاتِب (writer) — grasp the pattern and hundreds of words open at once.",
    "El árabe se construye sobre raíces de tres letras: de ك-ت-ب salen كَتَبَ (escribir), كِتاب (libro), مَكْتَب (oficina), كاتِب (escritor).",
  ],
  script: [
    "Ditulis dari kanan ke kiri; 28 huruf yang bentuknya berubah menurut posisi (awal, tengah, akhir, berdiri sendiri). Vokal pendek biasanya tidak ditulis — pembaca menebaknya dari pola kata.",
    "Written right to left; 28 letters whose shape changes with position (initial, medial, final, isolated). Short vowels are usually left out — readers infer them from the word pattern.",
    "Se escribe de derecha a izquierda; 28 letras que cambian de forma según su posición. Las vocales breves no se escriben.",
  ],
  pron: [
    ["ع", "Bunyi dari pangkal tenggorokan, tidak ada padanannya di bahasa Latin: عَين.", "A sound from deep in the throat with no Latin equivalent: عَين.", "Sonido faríngeo sin equivalente latino: عَين."],
    ["ح vs ه", "ح serak dari tenggorokan, ه ringan seperti 'h' biasa.", "ح is a sharp throat sound; ه is a light ordinary 'h'.", "ح es faríngea; ه es una 'h' suave."],
    ["ق", "Dibunyikan jauh di belakang, di anak tekak: قَلْب.", "Produced far back at the uvula: قَلْب.", "Se articula en la úvula: قَلْب."],
    ["huruf tebal", "ص ض ط ظ diucapkan dengan lidah melebar — mengubah warna vokal di sekitarnya.", "ص ض ط ظ are 'emphatic': the tongue flattens and colours the nearby vowels.", "ص ض ط ظ son enfáticas: la lengua se aplana y tiñe las vocales."],
    ["ال (al-)", "Kata sandang tentu; huruf 'l'-nya lebur pada huruf syamsiyah: الشمس → 'asy-syams'.", "The definite article; its 'l' assimilates to sun letters: الشمس → 'ash-shams'.", "El artículo definido; su 'l' se asimila: الشمس → 'ash-shams'."],
    ["vokal panjang", "ا و ي memanjangkan vokal dan membedakan arti: كَتَبَ ≠ كاتَبَ.", "ا و ي lengthen vowels and change meaning: كَتَبَ ≠ كاتَبَ.", "ا و ي alargan la vocal y cambian el sentido."],
  ],
  grammar: [
    {
      t: ["Akar tiga huruf", "The three-letter root", "La raíz trilítera"],
      d: ["Arti dasar tersimpan di akar; pola vokal dan imbuhan menentukan bentuk kata.", "The core meaning lives in the root; vowel patterns and affixes shape the word.", "El sentido vive en la raíz; los patrones vocálicos dan la forma."],
      ex: "د-ر-س → دَرَسَ (belajar) · مَدْرَسَة (sekolah) · مُدَرِّس (guru)",
    },
    {
      t: ["Kalimat tanpa kata kerja", "Verbless sentences", "Oraciones sin verbo"],
      d: ["Kalimat masa kini tidak memakai 'adalah': البيتُ كبيرٌ = 'Rumah itu besar'.", "The present needs no 'to be': البيتُ كبيرٌ = 'The house is big'.", "El presente no necesita 'ser': البيتُ كبيرٌ."],
      ex: "الطالبُ مجتهدٌ.",
    },
    {
      t: ["Bentuk ganda", "The dual number", "El número dual"],
      d: ["Selain tunggal dan jamak, ada bentuk khusus untuk tepat dua: كتابان (dua buku).", "Beyond singular and plural there is a form for exactly two: كتابان (two books).", "Además de singular y plural hay dual: كتابان (dos libros)."],
      ex: "كتاب · كتابان · كتب",
    },
    {
      t: ["Kata sifat mengikuti benda", "Adjectives follow and agree", "El adjetivo sigue y concuerda"],
      d: ["Kata sifat berdiri sesudah kata benda dan menyesuaikan gender, jumlah, serta kepastian.", "Adjectives come after the noun and agree in gender, number and definiteness.", "El adjetivo va detrás y concuerda en género, número y determinación."],
      ex: "البيت الكبير (rumah yang besar itu)",
    },
    {
      t: ["Sepuluh pola kata kerja", "The ten verb forms", "Las diez formas verbales"],
      d: ["Satu akar bisa masuk sepuluh pola dengan makna yang berbeda-beda (menyebabkan, saling, mencari…).", "One root can enter ten patterns with distinct meanings (causative, reciprocal, seeking…).", "Una raíz entra en diez formas con matices distintos."],
      ex: "عَلِمَ (tahu) → عَلَّمَ (mengajar) → تَعَلَّمَ (belajar)",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "امرأة", r: "imra'a", pos: "n", cefr: "A1", gen: "f", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["هذه المرأة طبيبة.", "Perempuan ini seorang dokter.", "This woman is a doctor.", "Esta mujer es médica."], ant: ["رجل"], note: ["Bentuk jamaknya tak beraturan: نساء.", "The plural is irregular: نساء.", "El plural es irregular: نساء."] },
  { w: "أراد", r: "arada", pos: "v", cefr: "A1", g: ["mau, ingin", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["أريد أن أتعلم العربية.", "Saya mau belajar bahasa Arab.", "I want to learn Arabic.", "Quiero aprender árabe."] },
  { w: "بيت", r: "bayt", pos: "n", cefr: "A1", gen: "m", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["بيتي قريب من الحديقة.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "جيد", r: "jayyid", pos: "adj", cefr: "A1", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["هذه فكرة جيدة.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["سيئ"] },
  { w: "ذهب", r: "dhahaba", pos: "v", cefr: "A1", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["أذهب إلى السوق.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "رجل", r: "rajul", pos: "n", cefr: "A1", gen: "m", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["هذا الرجل جاري.", "Laki-laki ini tetangga saya.", "This man is my neighbour.", "Este hombre es mi vecino."], ant: ["امرأة"] },
  { w: "صديق", r: "sadiq", pos: "n", cefr: "A1", gen: "m", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["هو أفضل صديق لي.", "Dia sahabat terbaik saya.", "He is my best friend.", "Es mi mejor amigo."] },
  { w: "صغير", r: "saghir", pos: "adj", cefr: "A1", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["لدي شقة صغيرة.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["كبير"] },
  { w: "كان", r: "kana", pos: "v", cefr: "A1", g: ["adalah (lampau)", "to be (past)", "ser/estar (pasado)"], d: ["Menyatakan keadaan pada masa lampau; masa kini tanpa kata kerja.", "Expresses a past state; the present needs no verb at all.", "Expresa un estado pasado; el presente no lleva verbo."], ex: ["كان الطقس جميلاً.", "Cuacanya indah waktu itu.", "The weather was lovely.", "Hacía buen tiempo."] },
  { w: "كبير", r: "kabir", pos: "adj", cefr: "A1", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["يعيشون في مدينة كبيرة.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["صغير"] },
  { w: "ليل", r: "layl", pos: "n", cefr: "A1", gen: "m", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["تصبح على خير!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["يوم"] },
  { w: "يوم", r: "yawm", pos: "n", cefr: "A1", gen: "m", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["أعمل كل يوم.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["ليل"] },

  /* ------------------------------------------------------------------ A2 */
  { w: "احتاج", r: "ihtaja", pos: "v", cefr: "A2", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["أحتاج إلى الراحة.", "Saya butuh istirahat.", "I need rest.", "Necesito descansar."] },
  { w: "بدأ", r: "bada'a", pos: "v", cefr: "A2", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["يبدأ الفيلم في الثامنة.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "دائما", r: "da'iman", pos: "adv", cefr: "A2", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["أتناول الفطور في البيت دائما.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },
  { w: "سريع", r: "sari'", pos: "adj", cefr: "A2", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["القطار أسرع.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["بطيء"] },
  { w: "سهل", r: "sahl", pos: "adj", cefr: "A2", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["كان الامتحان سهلاً.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["صعب"] },
  { w: "ساعد", r: "sa'ada", pos: "v", cefr: "A2", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["هل يمكنك أن تساعدني؟", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "صعب", r: "sa'b", pos: "adj", cefr: "A2", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["من الصعب أن تركن السيارة هنا.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["سهل"] },
  { w: "عمل", r: "'amal", pos: "n", cefr: "A2", gen: "m", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["يبدأ عملي في التاسعة.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "لأن", r: "li'anna", pos: "conj", cefr: "A2", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["أنا في البيت لأن المطر ينزل.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },
  { w: "مال", r: "mal", pos: "n", cefr: "A2", gen: "m", g: ["uang, harta", "money, wealth", "dinero"], d: ["Alat tukar dan harta yang dimiliki.", "Money and possessions.", "Dinero y bienes."], ex: ["ليس معي مال كافٍ.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "مدينة", r: "madina", pos: "n", cefr: "A2", gen: "f", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["القاهرة مدينة كبيرة.", "Kairo kota yang besar.", "Cairo is a big city.", "El Cairo es una ciudad grande."] },
  { w: "وقت", r: "waqt", pos: "n", cefr: "A2", gen: "m", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["ليس لدي وقت اليوم.", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "اشتاق", r: "ishtaqa", pos: "v", cefr: "B1", g: ["merindukan", "to miss, to long for", "añorar"], d: ["Merasa sedih karena seseorang tidak ada.", "To feel the absence of someone.", "Sentir la ausencia de alguien."], ex: ["اشتقت إلى عائلتي.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },
  { w: "اعتاد", r: "i'tada", pos: "v", cefr: "B1", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["اعتدت على الجو هنا.", "Saya sudah terbiasa dengan cuaca di sini.", "I've got used to the weather here.", "Ya me acostumbré al clima."] },
  { w: "بدا", r: "bada", pos: "v", cefr: "B1", g: ["tampak", "to seem, to appear", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["يبدو متعباً.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "حسّن", r: "hassana", pos: "v", cefr: "B1", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["أريد أن أحسّن نطقي.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "خبرة", r: "khibra", pos: "n", cefr: "B1", gen: "f", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["لديها خبرة كبيرة.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "ربما", r: "rubbama", pos: "adv", cefr: "B1", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["ربما يأتي غداً.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "رغم أن", r: "raghma anna", pos: "conj", cefr: "B1", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["رغم أن المطر ينزل، سنخرج.", "Meskipun hujan, kami akan keluar.", "Although it's raining, we'll go out.", "Aunque llueve, saldremos."] },
  { w: "فرصة", r: "fursa", pos: "n", cefr: "B1", gen: "f", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["هذه فرصة ممتازة.", "Ini kesempatan yang bagus.", "This is an excellent opportunity.", "Es una gran oportunidad."] },
  { w: "قرار", r: "qarar", pos: "n", cefr: "B1", gen: "m", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["كان قراراً صعباً.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."] },
  { w: "لكن", r: "lakin", pos: "conj", cefr: "B1", g: ["tetapi", "but", "pero"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["غالٍ لكنه يستحق.", "Mahal tetapi sepadan.", "It's expensive but worth it.", "Es caro pero vale la pena."] },
  { w: "نجح", r: "najaha", pos: "v", cefr: "B1", g: ["berhasil, lulus", "to succeed, to pass", "tener éxito, aprobar"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["نجح في الامتحان.", "Dia lulus ujian.", "He passed the exam.", "Aprobó el examen."] },
  { w: "نصيحة", r: "nasiha", pos: "n", cefr: "B1", gen: "f", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["هل تعطيني نصيحة؟", "Boleh minta nasihat?", "Would you give me some advice?", "¿Me das un consejo?"] },

  /* ------------------------------------------------------------------ B2 */
  { w: "اتفاق", r: "ittifaq", pos: "n", cefr: "B2", gen: "m", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["وقّع الطرفان الاتفاق.", "Kedua pihak menandatangani kesepakatan.", "Both sides signed the agreement.", "Ambas partes firmaron el acuerdo."] },
  { w: "أكد", r: "akkada", pos: "v", cefr: "B2", g: ["menegaskan", "to confirm, to emphasise", "confirmar, subrayar"], d: ["Menyatakan sesuatu dengan tegas dan pasti.", "To state something firmly and certainly.", "Afirmar algo con firmeza."], ex: ["أكد على أهمية السلامة.", "Dia menegaskan pentingnya keselamatan.", "He emphasised the importance of safety.", "Subrayó la importancia de la seguridad."] },
  { w: "بيئة", r: "bi'a", pos: "n", cefr: "B2", gen: "f", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["يجب أن نحمي البيئة.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "تحدي", r: "tahaddi", pos: "n", cefr: "B2", gen: "m", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["هذا تحدٍّ كبير.", "Ini tantangan besar.", "This is a big challenge.", "Es un gran desafío."] },
  { w: "تطوير", r: "tatwir", pos: "n", cefr: "B2", gen: "m", g: ["pengembangan", "development", "desarrollo"], d: ["Proses menjadikan sesuatu lebih maju.", "The process of making something more advanced.", "Proceso de hacer avanzar algo."], ex: ["تطوير المشروع يسير جيداً.", "Pengembangan proyeknya berjalan baik.", "The project's development is going well.", "El desarrollo del proyecto va bien."] },
  { w: "ضروري", r: "daruri", pos: "adj", cefr: "B2", g: ["mutlak perlu", "necessary, essential", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["جواز السفر ضروري.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "قضية", r: "qadiyya", pos: "n", cefr: "B2", gen: "f", g: ["perkara, isu", "issue, case", "asunto, caso"], d: ["Hal yang sedang dibahas; juga perkara hukum.", "The matter under discussion; also a legal case.", "El asunto tratado; también una causa judicial."], ex: ["هذه قضية حساسة.", "Ini perkara yang sensitif.", "It's a sensitive issue.", "Es un asunto delicado."] },
  { w: "لذلك", r: "lidhalika", pos: "conj", cefr: "B2", g: ["oleh karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["نزل المطر؛ لذلك ألغينا الرحلة.", "Hujan turun; oleh karena itu kami batalkan.", "It rained; therefore we cancelled the trip.", "Llovió; por eso cancelamos."] },
  { w: "موثوق", r: "mawthuq", pos: "adj", cefr: "B2", g: ["dapat dipercaya", "reliable, trusted", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["هذا مصدر موثوق.", "Ini sumber yang tepercaya.", "This is a reliable source.", "Es una fuente fiable."] },
  { w: "نفّذ", r: "naffadha", pos: "v", cefr: "B2", g: ["melaksanakan", "to carry out, to implement", "ejecutar"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["سننفّذ الخطة الشهر المقبل.", "Kami akan melaksanakan rencananya bulan depan.", "We'll carry out the plan next month.", "Ejecutaremos el plan el mes próximo."] },
  { w: "حقق", r: "haqqaqa", pos: "v", cefr: "B2", g: ["mewujudkan, mencapai", "to achieve, to realise", "lograr"], d: ["Berhasil mencapai atau mewujudkan sesuatu.", "To achieve or bring something about.", "Lograr o hacer realidad algo."], ex: ["حققنا الهدف.", "Kami mencapai targetnya.", "We achieved the goal.", "Alcanzamos el objetivo."] },
  { w: "رغم", r: "raghma", pos: "prep", cefr: "B2", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["رغم البرد، خرجنا.", "Meski dingin, kami keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "أبرز", r: "abraza", pos: "v", cefr: "C1", g: ["menonjolkan", "to highlight, to bring out", "destacar"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["أبرز التقرير المخاطر.", "Laporan itu menonjolkan risikonya.", "The report highlighted the risks.", "El informe destacó los riesgos."] },
  { w: "بهدف", r: "bihadaf", pos: "prep", cefr: "C1", g: ["demi, agar", "with the aim of", "con el fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["بسّطنا الإجراءات بهدف توفير الوقت.", "Kami sederhanakan prosedurnya demi menghemat waktu.", "We simplified the process with the aim of saving time.", "Simplificamos el proceso con el fin de ahorrar tiempo."] },
  { w: "دقيق", r: "daqiq", pos: "adj", cefr: "C1", g: ["cermat, tepat", "precise, meticulous", "preciso"], d: ["Tepat sampai ke bagian terkecil.", "Exact down to the smallest detail.", "Exacto hasta el último detalle."], ex: ["نحتاج إلى تحليل دقيق.", "Kita butuh analisis yang cermat.", "We need a precise analysis.", "Necesitamos un análisis preciso."] },
  { w: "دلالة", r: "dalala", pos: "n", cefr: "C1", gen: "f", g: ["makna tersirat, nuansa", "connotation, significance", "connotación"], d: ["Arti tambahan yang terkandung di balik kata.", "The extra meaning a word carries.", "El sentido añadido que lleva una palabra."], ex: ["للكلمة دلالة سياسية.", "Kata itu punya makna politis.", "The word carries a political connotation.", "La palabra tiene connotación política."] },
  { w: "رسّخ", r: "rassakha", pos: "v", cefr: "C1", g: ["memperkukuh", "to consolidate, to entrench", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["رسّخت الشركة مكانتها.", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "عالج", r: "'alaja", pos: "v", cefr: "C1", g: ["menangani; mengobati", "to address; to treat", "abordar; tratar"], d: ["Menangani persoalan; juga merawat penyakit.", "To deal with an issue; also to treat an illness.", "Abordar un asunto; también tratar una enfermedad."], ex: ["يجب أن نعالج هذه المسألة.", "Kita harus menangani persoalan ini.", "We must address this matter.", "Debemos abordar este asunto."] },
  { w: "عزّز", r: "'azzaza", pos: "v", cefr: "C1", g: ["memperkuat, mendorong", "to strengthen, to promote", "reforzar"], d: ["Membantu sesuatu tumbuh atau makin kuat.", "To help something grow or grow stronger.", "Ayudar a que algo crezca o se fortalezca."], ex: ["يعزّز القانون إعادة التدوير.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "عكس", r: "'akasa", pos: "v", cefr: "C1", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["تعكس الأرقام تحسناً.", "Angkanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "مجال", r: "majal", pos: "n", cefr: "C1", gen: "m", g: ["bidang, ranah", "field, domain", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["في المجال القانوني الأمر مختلف.", "Dalam ranah hukum hal itu berbeda.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "مع ذلك", r: "ma'a dhalika", pos: "conj", cefr: "C1", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["مع ذلك، يبقى الاقتراح قائماً.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "منهج", r: "manhaj", pos: "n", cefr: "C1", gen: "m", g: ["metode, pendekatan", "method, approach", "método"], d: ["Cara tersusun untuk mengerjakan sesuatu.", "An organised way of doing something.", "Manera organizada de hacer algo."], ex: ["نحتاج إلى منهج مختلف.", "Kita butuh pendekatan yang berbeda.", "We need a different approach.", "Necesitamos otro método."] },
  { w: "نطاق", r: "nitaq", pos: "n", cefr: "C1", gen: "m", g: ["cakupan, lingkup", "scope, range", "alcance"], d: ["Seberapa luas sesuatu berlaku.", "How far something extends.", "Hasta dónde llega algo."], ex: ["نطاق القرار واسع جداً.", "Cakupan keputusannya sangat luas.", "The decision's scope is very wide.", "El alcance de la decisión es amplio."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "أوضح", r: "awdaha", pos: "v", cefr: "C2", g: ["menjernihkan, menjelaskan", "to clarify, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["يجب أن نوضح التفاصيل.", "Rinciannya perlu dijernihkan.", "The details must be clarified.", "Hay que esclarecer los detalles."] },
  { w: "بصيص", r: "basis", pos: "n", cefr: "C2", gen: "m", g: ["secercah", "glimmer, faint gleam", "destello"], d: ["Cahaya sangat lemah; kiasan untuk harapan kecil.", "A very faint light; figuratively a small hope.", "Luz muy tenue; indicio de esperanza."], ex: ["ما زال هناك بصيص أمل.", "Masih ada secercah harapan.", "There's still a glimmer of hope.", "Aún hay un destello de esperanza."] },
  { w: "تجنّب", r: "tajannaba", pos: "v", cefr: "C2", g: ["menghindari, mengelak", "to avoid, to evade", "eludir"], d: ["Sengaja menjauhi sesuatu.", "To deliberately keep away from something.", "Apartarse de algo a propósito."], ex: ["تجنّب الإجابة عن السؤال.", "Dia mengelak menjawab pertanyaan itu.", "He avoided answering the question.", "Eludió responder la pregunta."] },
  { w: "تحيّز", r: "tahayyuz", pos: "n", cefr: "C2", gen: "m", g: ["keberpihakan, bias", "bias, partiality", "sesgo"], d: ["Kecenderungan menilai secara tidak berimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["في الدراسة تحيّز واضح.", "Kajian itu punya bias yang jelas.", "The study shows a clear bias.", "El estudio muestra un sesgo claro."] },
  { w: "حتمي", r: "hatmi", pos: "adj", cefr: "C2", g: ["tak terhindarkan", "inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["ارتفاع الأسعار أمر حتمي.", "Kenaikan harga tak terhindarkan.", "The price rise is inevitable.", "La subida es inevitable."] },
  { w: "عاجل", r: "'ajil", pos: "adj", cefr: "C2", g: ["mendesak", "urgent", "urgente"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["هذه مسألة عاجلة.", "Ini perkara mendesak.", "This is an urgent matter.", "Es un asunto urgente."] },
  { w: "قلّل", r: "qallala", pos: "v", cefr: "C2", g: ["mengurangi, meremehkan", "to reduce; to belittle", "reducir; minimizar"], d: ["Mengurangi jumlah; قلّل من = meremehkan.", "To reduce an amount; قلّل من means to belittle.", "Reducir; قلّل من significa minimizar."], ex: ["لا تقلّل من جهوده.", "Jangan remehkan usahanya.", "Don't belittle his efforts.", "No minimices su esfuerzo."] },
  { w: "لا يوصف", r: "la yusaf", pos: "phr", cefr: "C2", g: ["tak terlukiskan", "indescribable", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["شعرت بفرح لا يوصف.", "Dia merasakan sukacita tak terlukiskan.", "She felt an indescribable joy.", "Sintió una alegría indescriptible."] },
  { w: "معلم", r: "ma'lam", pos: "n", cefr: "C2", gen: "m", g: ["tonggak, penanda", "landmark, milestone", "hito"], d: ["Penanda penting yang menjadi rujukan.", "A prominent marker others navigate by.", "Marca destacada que sirve de referencia."], ex: ["كان الاتفاق معلماً تاريخياً.", "Kesepakatan itu tonggak sejarah.", "The agreement was a historic landmark.", "El acuerdo fue un hito histórico."] },
  { w: "نموذج", r: "namudhaj", pos: "n", cefr: "C2", gen: "m", g: ["model, paradigma", "model, paradigm", "modelo"], d: ["Kerangka atau contoh yang menjadi acuan.", "A framework or example others follow.", "Marco o ejemplo de referencia."], ex: ["كان ذلك تحوّلاً في النموذج.", "Itu pergeseran paradigma.", "That was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "وهم", r: "wahm", pos: "n", cefr: "C2", gen: "m", g: ["ilusi, angan kosong", "illusion, delusion", "ilusión"], d: ["Keyakinan indah yang ternyata semu.", "A pleasing belief that turns out false.", "Creencia agradable que resulta falsa."], ex: ["ذلك الوعد مجرد وهم.", "Janji itu hanyalah ilusi.", "That promise is a mere illusion.", "Esa promesa es solo una ilusión."] },
  { w: "في ضوء", r: "fi daw'", pos: "phr", cefr: "C2", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["في ضوء النتائج، هذا نجاح.", "Berdasarkan hasilnya, ini keberhasilan.", "In the light of the results, it's a success.", "A la luz de los resultados, es un éxito."] },
];
