/* =========================================================================
   lexicon/el.js — Λεξικό: Ελληνικά (Greek). Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Yunani sudah ditulis tanpa putus selama lebih dari 3.000 tahun. Abjadnya menurunkan huruf Latin dan Kiril, dan akar katanya hidup di dalam istilah ilmiah seluruh dunia.",
    "Greek has been written continuously for over 3,000 years. Its alphabet is the ancestor of both Latin and Cyrillic, and its roots live inside scientific terms worldwide.",
    "El griego se escribe sin interrupción desde hace más de 3.000 años. Su alfabeto es el antecesor del latino y el cirílico.",
  ],
  script: [
    "24 huruf. Setiap kata (lebih dari satu suku kata) menandai tekanannya dengan aksen — ini bukan hiasan, melainkan penentu arti: πότε (kapan) vs ποτέ (tak pernah).",
    "24 letters. Every multi-syllable word marks its stress with an accent — not decoration but meaning: πότε (when) vs ποτέ (never).",
    "24 letras. Toda palabra polisílaba marca el acento con tilde, y eso cambia el significado: πότε (cuándo) y ποτέ (nunca).",
  ],
  pron: [
    ["γ", "Bunyi /ɣ/ lembut seperti 'g' yang tidak menutup: γάλα.", "A soft /ɣ/, like a g that never closes: γάλα.", "Una /ɣ/ suave, como una g que no cierra: γάλα."],
    ["δ", "Selalu /ð/ seperti 'th' pada this: δέκα.", "Always /ð/ as in 'this': δέκα.", "Siempre /ð/ como en inglés 'this': δέκα."],
    ["θ", "Selalu /θ/ seperti 'th' pada think: θάλασσα.", "Always /θ/ as in 'think': θάλασσα.", "Siempre /θ/ como en inglés 'think': θάλασσα."],
    ["ου", "Dibaca /u/: μου, τουρίστας.", "Pronounced /u/: μου, τουρίστας.", "Se pronuncia /u/: μου, τουρίστας."],
    ["αι / ει / οι", "αι = /e/; ει dan οι sama-sama /i/ — ejaan berbeda, bunyi sama.", "αι = /e/; ει and οι are both /i/ — different spellings, one sound.", "αι = /e/; ει y οι suenan ambas /i/."],
    ["ντ / μπ / γκ", "Dipakai untuk bunyi d, b, g: ντομάτα, μπύρα, γκολ.", "These digraphs carry d, b, g: ντομάτα, μπύρα, γκολ.", "Estos dígrafos dan d, b, g: ντομάτα, μπύρα, γκολ."],
  ],
  grammar: [
    {
      t: ["Tiga gender + kasus", "Three genders and cases", "Tres géneros y casos"],
      d: ["Kata benda maskulin (ο), feminin (η), atau netral (το), dan berubah menurut kasus.", "Nouns are masculine (ο), feminine (η) or neuter (το), and change by case.", "Los sustantivos son masculinos (ο), femeninos (η) o neutros (το) y cambian por caso."],
      ex: "ο φίλος → τον φίλο · η πόλη → την πόλη",
    },
    {
      t: ["Tanpa infinitif", "No infinitive", "Sin infinitivo"],
      d: ["Bahasa Yunani modern kehilangan infinitif; dipakai να + kata kerja terkonjugasi.", "Modern Greek lost the infinitive; it uses να plus a conjugated verb instead.", "El griego moderno perdió el infinitivo; usa να más verbo conjugado."],
      ex: "Θέλω να πάω. (Saya mau pergi)",
    },
    {
      t: ["Subjek boleh hilang", "The subject can vanish", "El sujeto puede omitirse"],
      d: ["Akhiran kata kerja sudah menandai pelakunya.", "The verb ending already names the person.", "La terminación ya indica la persona."],
      ex: "(Εγώ) μιλάω ελληνικά.",
    },
    {
      t: ["Aksen menentukan arti", "The accent carries meaning", "La tilde da significado"],
      d: ["Tanda tekanan wajib ditulis dan membedakan kata: πότε ≠ ποτέ.", "The stress mark is obligatory and distinguishes words: πότε ≠ ποτέ.", "La tilde es obligatoria y distingue palabras: πότε ≠ ποτέ."],
      ex: "πότε (kapan) · ποτέ (tak pernah)",
    },
    {
      t: ["Kata kerja masa depan", "Making the future", "El futuro"],
      d: ["Cukup tambahkan θα di depan kata kerja.", "Just put θα in front of the verb.", "Basta anteponer θα al verbo."],
      ex: "θα πάω = saya akan pergi",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "άνθρωπος", r: "anthropos", pos: "n", cefr: "A1", gen: "m", ipa: "ˈanθropos", g: ["manusia, orang", "human being, person", "persona"], d: ["Satu manusia, laki-laki atau perempuan.", "A human being of either sex.", "Un ser humano de cualquier sexo."], ex: ["Είναι καλός άνθρωπος.", "Dia orang yang baik.", "He's a good person.", "Es una buena persona."] },
  { w: "γυναίκα", r: "gynaika", pos: "n", cefr: "A1", gen: "f", ipa: "ʝiˈneka", g: ["perempuan; istri", "woman; wife", "mujer; esposa"], d: ["Manusia dewasa perempuan; juga istri.", "An adult female; also a wife.", "Mujer adulta; también esposa."], ex: ["Η γυναίκα με το καπέλο είναι η θεία μου.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["άντρας"] },
  { w: "άντρας", r: "antras", pos: "n", cefr: "A1", gen: "m", ipa: "ˈandras", g: ["laki-laki; suami", "man; husband", "hombre; marido"], d: ["Manusia dewasa laki-laki; juga suami.", "An adult male; also a husband.", "Hombre adulto; también marido."], ex: ["Αυτός ο άντρας είναι γείτονάς μου.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["γυναίκα"] },
  { w: "θέλω", r: "thelo", pos: "v", cefr: "A1", ipa: "ˈθelo", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Θέλω να μάθω ελληνικά.", "Saya mau belajar bahasa Yunani.", "I want to learn Greek.", "Quiero aprender griego."] },
  { w: "καλός", r: "kalos", pos: "adj", cefr: "A1", ipa: "kaˈlos", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["Είναι καλή ιδέα.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["κακός"] },
  { w: "μέρα", r: "mera", pos: "n", cefr: "A1", gen: "f", ipa: "ˈmera", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Δουλεύω κάθε μέρα.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["νύχτα"] },
  { w: "μεγάλος", r: "megalos", pos: "adj", cefr: "A1", ipa: "meˈɣalos", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Μένουν σε μεγάλη πόλη.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["μικρός"] },
  { w: "μικρός", r: "mikros", pos: "adj", cefr: "A1", ipa: "miˈkros", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Έχω ένα μικρό διαμέρισμα.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["μεγάλος"] },
  { w: "νύχτα", r: "nychta", pos: "n", cefr: "A1", gen: "f", ipa: "ˈnixta", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Καληνύχτα!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["μέρα"] },
  { w: "πηγαίνω", r: "pigaino", pos: "v", cefr: "A1", ipa: "piˈʝeno", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Πηγαίνω στην αγορά.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "σπίτι", r: "spiti", pos: "n", cefr: "A1", gen: "nt", ipa: "ˈspiti", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Το σπίτι μου είναι κοντά στο πάρκο.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "φίλος", r: "filos", pos: "n", cefr: "A1", gen: "m", ipa: "ˈfilos", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Βγαίνω με έναν φίλο.", "Saya keluar dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "αρχίζω", r: "archizo", pos: "v", cefr: "A2", ipa: "arˈçizo", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Η ταινία αρχίζει στις οκτώ.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["τελειώνω"] },
  { w: "βοηθάω", r: "voithao", pos: "v", cefr: "A2", ipa: "voiˈθao", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Μπορείς να με βοηθήσεις;", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "γρήγορος", r: "grigoros", pos: "adj", cefr: "A2", ipa: "ˈɣriɣoros", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Το τρένο είναι πιο γρήγορο.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["αργός"] },
  { w: "δουλειά", r: "douleia", pos: "n", cefr: "A2", gen: "f", ipa: "ðuˈʎa", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Η δουλειά μου αρχίζει στις εννιά.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "δύσκολος", r: "dyskolos", pos: "adj", cefr: "A2", ipa: "ˈðiskolos", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Είναι δύσκολο να παρκάρεις εδώ.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["εύκολος"] },
  { w: "εύκολος", r: "efkolos", pos: "adj", cefr: "A2", ipa: "ˈefkolos", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["Οι εξετάσεις ήταν εύκολες.", "Ujiannya mudah.", "The exams were easy.", "Los exámenes fueron fáciles."], ant: ["δύσκολος"] },
  { w: "επειδή", r: "epeidi", pos: "conj", cefr: "A2", ipa: "epiˈði", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Μένω σπίτι επειδή βρέχει.", "Saya di rumah karena hujan.", "I'm staying home because it's raining.", "Me quedo en casa porque llueve."] },
  { w: "καιρός", r: "kairos", pos: "n", cefr: "A2", gen: "m", ipa: "keˈros", g: ["cuaca; waktu", "weather; time", "tiempo (clima y horas)"], d: ["Keadaan cuaca; juga waktu yang tersedia.", "The weather; also available time.", "El clima; también el tiempo disponible."], ex: ["Ο καιρός είναι ωραίος σήμερα.", "Cuacanya bagus hari ini.", "The weather is nice today.", "Hoy hace buen tiempo."] },
  { w: "λεφτά", r: "lefta", pos: "n", cefr: "A2", ipa: "lefˈta", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Δεν έχω αρκετά λεφτά.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."], syn: ["χρήματα"] },
  { w: "πάντα", r: "panta", pos: "adv", cefr: "A2", ipa: "ˈpanda", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Πάντα τρώω πρωινό στο σπίτι.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["ποτέ"] },
  { w: "πόλη", r: "poli", pos: "n", cefr: "A2", gen: "f", ipa: "ˈpoli", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Η Θεσσαλονίκη είναι όμορφη πόλη.", "Thessaloniki kota yang indah.", "Thessaloniki is a beautiful city.", "Salónica es una ciudad bonita."] },
  { w: "χρειάζομαι", r: "chreiazomai", pos: "v", cefr: "A2", ipa: "xriˈazome", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Χρειάζομαι ξεκούραση.", "Saya butuh istirahat.", "I need rest.", "Necesito descansar."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "άποψη", r: "apopsi", pos: "n", cefr: "B1", gen: "f", ipa: "ˈapopsi", g: ["pendapat, sudut pandang", "opinion, view", "opinión, punto de vista"], d: ["Cara seseorang memandang sesuatu.", "The way someone sees something.", "Manera en que alguien ve algo."], ex: ["Ποια είναι η άποψή σου;", "Bagaimana pendapatmu?", "What's your view?", "¿Cuál es tu opinión?"] },
  { w: "βελτιώνω", r: "veltiono", pos: "v", cefr: "B1", ipa: "veltiˈono", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Θέλω να βελτιώσω την προφορά μου.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "εμπειρία", r: "empeiria", pos: "n", cefr: "B1", gen: "f", ipa: "embiˈria", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Έχει μεγάλη εμπειρία.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "ευκαιρία", r: "efkairia", pos: "n", cefr: "B1", gen: "f", ipa: "efkeˈria", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["Είναι μεγάλη ευκαιρία.", "Ini kesempatan besar.", "It's a great opportunity.", "Es una gran oportunidad."] },
  { w: "ίσως", r: "isos", pos: "adv", cefr: "B1", ipa: "ˈisos", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Ίσως έρθει αύριο.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "λύση", r: "lysi", pos: "n", cefr: "B1", gen: "f", ipa: "ˈlisi", g: ["solusi", "solution", "solución"], d: ["Jalan keluar dari suatu masalah.", "A way out of a problem.", "Salida a un problema."], ex: ["Βρήκαμε μια λύση.", "Kami menemukan solusi.", "We found a solution.", "Encontramos una solución."] },
  { w: "μοιάζω", r: "moiazo", pos: "v", cefr: "B1", ipa: "ˈmʝazo", g: ["tampak; mirip", "to seem; to resemble", "parecer; asemejarse"], d: ["Memberi kesan tertentu; juga menyerupai.", "To give an impression; also to resemble.", "Dar una impresión; también asemejarse."], ex: ["Μοιάζει κουρασμένος.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "όμως", r: "omos", pos: "conj", cefr: "B1", ipa: "ˈomos", g: ["namun begitu", "however, but", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Είναι ακριβό· αξίζει όμως.", "Mahal; namun begitu sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "παρόλο που", r: "parolo pou", pos: "conj", cefr: "B1", ipa: "paˈrolo pu", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Παρόλο που βρέχει, θα βγούμε.", "Meskipun hujan, kami akan keluar.", "Although it's raining, we'll go out.", "Aunque llueve, saldremos."] },
  { w: "συμβουλή", r: "symvouli", pos: "n", cefr: "B1", gen: "f", ipa: "simvuˈli", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Μου δίνεις μια συμβουλή;", "Boleh minta saran?", "Can you give me some advice?", "¿Me das un consejo?"] },
  { w: "συνηθίζω", r: "synithizo", pos: "v", cefr: "B1", ipa: "siniˈθizo", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Συνήθισα το κλίμα.", "Saya terbiasa dengan iklimnya.", "I got used to the climate.", "Me acostumbré al clima."] },
  { w: "απόφαση", r: "apofasi", pos: "n", cefr: "B1", gen: "f", ipa: "aˈpofasi", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Ήταν δύσκολη απόφαση.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya παίρνω απόφαση.", "The collocation is παίρνω απόφαση (to take a decision).", "La colocación es παίρνω απόφαση."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "ανάπτυξη", r: "anaptyxi", pos: "n", cefr: "B2", gen: "f", ipa: "aˈnaptiksi", g: ["pengembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Η ανάπτυξη του έργου προχωρά.", "Pengembangan proyeknya berjalan.", "The project's development is advancing.", "El desarrollo del proyecto avanza."] },
  { w: "αξιόπιστος", r: "axiopistos", pos: "adj", cefr: "B2", ipa: "aksiˈopistos", g: ["dapat diandalkan", "reliable, credible", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Είναι αξιόπιστη πηγή.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "απαραίτητος", r: "aparaititos", pos: "adj", cefr: "B2", ipa: "apaˈretitos", g: ["mutlak perlu", "essential, indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Το διαβατήριο είναι απαραίτητο.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "επιτυγχάνω", r: "epitynchano", pos: "v", cefr: "B2", ipa: "epitiŋˈxano", g: ["mencapai, berhasil", "to achieve, to succeed", "lograr"], d: ["Meraih tujuan setelah berusaha.", "To reach a goal after effort.", "Alcanzar una meta tras esfuerzo."], ex: ["Επιτύχαμε τον στόχο.", "Kami mencapai targetnya.", "We achieved the target.", "Logramos el objetivo."] },
  { w: "ζήτημα", r: "zitima", pos: "n", cefr: "B2", gen: "nt", ipa: "ˈzitima", g: ["persoalan", "matter, issue", "cuestión"], d: ["Hal yang sedang dibicarakan atau ditangani.", "The matter under discussion.", "Tema del que se trata."], ex: ["Είναι ευαίσθητο ζήτημα.", "Itu perkara yang sensitif.", "It's a delicate matter.", "Es una cuestión delicada."] },
  { w: "παρά", r: "para", pos: "prep", cefr: "B2", ipa: "paˈra", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Παρά το κρύο, βγήκαμε.", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."] },
  { w: "περιβάλλον", r: "perivallon", pos: "n", cefr: "B2", gen: "nt", ipa: "periˈvalon", g: ["lingkungan", "environment", "medio ambiente"], d: ["Alam sekitar; juga suasana tempat kerja.", "The natural surroundings; also a work setting.", "Entorno natural; también ambiente laboral."], ex: ["Πρέπει να προστατεύσουμε το περιβάλλον.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "πρόκληση", r: "proklisi", pos: "n", cefr: "B2", gen: "f", ipa: "ˈproklisi", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Είναι πραγματική πρόκληση.", "Ini benar-benar tantangan.", "That's a real challenge.", "Es todo un desafío."] },
  { w: "συμφωνία", r: "symfonia", pos: "n", cefr: "B2", gen: "f", ipa: "simfoˈnia", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Καταλήξαμε σε συμφωνία.", "Kami mencapai kesepakatan.", "We reached an agreement.", "Llegamos a un acuerdo."] },
  { w: "τονίζω", r: "tonizo", pos: "v", cefr: "B2", ipa: "toˈnizo", g: ["menekankan", "to emphasise, to stress", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Θέλω να τονίσω αυτό το σημείο.", "Saya ingin menekankan poin ini.", "I want to stress this point.", "Quiero subrayar este punto."] },
  { w: "υλοποιώ", r: "ylopoio", pos: "v", cefr: "B2", ipa: "ilopiˈo", g: ["mewujudkan, menerapkan", "to implement, to realise", "implementar"], d: ["Mengubah rencana menjadi kenyataan.", "To turn a plan into reality.", "Convertir un plan en realidad."], ex: ["Θα υλοποιήσουμε το σχέδιο.", "Kami akan mewujudkan rencananya.", "We'll implement the plan.", "Implementaremos el plan."] },
  { w: "επομένως", r: "epomenos", pos: "conj", cefr: "B2", ipa: "epoˈmenos", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat logis.", "Marks a logical consequence.", "Marca la consecuencia lógica."], ex: ["Έβρεχε· επομένως ακυρώσαμε.", "Hujan; oleh karena itu kami batalkan.", "It rained; therefore we cancelled.", "Llovía; por lo tanto cancelamos."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "αντικατοπτρίζω", r: "antikatoptrizo", pos: "v", cefr: "C1", ipa: "andikatoˈptrizo", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Τα στοιχεία αντικατοπτρίζουν βελτίωση.", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "διεξοδικός", r: "diexodikos", pos: "adj", cefr: "C1", ipa: "ðieksoðiˈkos", g: ["menyeluruh, tuntas", "thorough, exhaustive", "exhaustivo"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest detail.", "Hecho hasta el último detalle."], ex: ["Χρειάζεται διεξοδική ανάλυση.", "Analisis tuntas diperlukan.", "A thorough analysis is needed.", "Hace falta un análisis exhaustivo."] },
  { w: "εδραιώνω", r: "edraiono", pos: "v", cefr: "C1", ipa: "eðreˈono", g: ["memperkukuh", "to consolidate, to entrench", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Η εταιρεία εδραίωσε τη θέση της.", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "εμβέλεια", r: "emveleia", pos: "n", cefr: "C1", gen: "f", ipa: "emˈvelia", g: ["jangkauan", "range, reach", "alcance"], d: ["Seberapa jauh pengaruh sesuatu terasa.", "How far something's effect reaches.", "Hasta dónde llega el efecto."], ex: ["Μια απόφαση μεγάλης εμβέλειας.", "Keputusan berjangkauan luas.", "A decision of wide reach.", "Una decisión de gran alcance."] },
  { w: "εντούτοις", r: "entoutois", pos: "conj", cefr: "C1", ipa: "enˈdutis", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Εντούτοις, η πρόταση ισχύει.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "προσέγγιση", r: "prosengisi", pos: "n", cefr: "C1", gen: "f", ipa: "proˈseŋɟisi", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Χρειαζόμαστε διαφορετική προσέγγιση.", "Kita butuh pendekatan lain.", "We need a different approach.", "Necesitamos otro enfoque."] },
  { w: "προωθώ", r: "proötho", pos: "v", cefr: "C1", ipa: "prooˈθo", g: ["mendorong, mempromosikan", "to promote, to push forward", "impulsar"], d: ["Membantu sesuatu maju atau tumbuh.", "To help something advance or grow.", "Ayudar a que algo avance."], ex: ["Ο νόμος προωθεί την ανακύκλωση.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley impulsa el reciclaje."] },
  { w: "τομέας", r: "tomeas", pos: "n", cefr: "C1", gen: "m", ipa: "toˈmeas", g: ["bidang, sektor", "field, sector", "ámbito, sector"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["Στον νομικό τομέα ισχύουν άλλα.", "Dalam bidang hukum berlaku hal lain.", "Different rules apply in the legal sector.", "En el ámbito jurídico rige otra cosa."] },
  { w: "υπογραμμίζω", r: "ypogrammizo", pos: "v", cefr: "C1", ipa: "ipoɣraˈmizo", g: ["menggarisbawahi", "to underline, to highlight", "resaltar"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["Η έκθεση υπογραμμίζει τους κινδύνους.", "Laporan itu menggarisbawahi risikonya.", "The report underlines the risks.", "El informe resalta los riesgos."] },
  { w: "χειρίζομαι", r: "cheirizomai", pos: "v", cefr: "C1", ipa: "çiˈrizome", g: ["menangani", "to handle, to manage", "manejar"], d: ["Mengurus sesuatu dengan cermat.", "To deal with something carefully.", "Ocuparse de algo con cuidado."], ex: ["Χειρίστηκε καλά την κατάσταση.", "Dia menangani situasinya dengan baik.", "He handled the situation well.", "Manejó bien la situación."] },
  { w: "με σκοπό", r: "me skopo", pos: "prep", cefr: "C1", ipa: "me skoˈpo", g: ["demi, agar", "in order to", "con el fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["Με σκοπό την εξοικονόμηση χρόνου, απλοποιήσαμε.", "Demi menghemat waktu, kami sederhanakan.", "In order to save time, we simplified.", "Con el fin de ahorrar tiempo, simplificamos."] },
  { w: "απόχρωση", r: "apochrosi", pos: "n", cefr: "C1", gen: "f", ipa: "aˈpoxrosi", g: ["nuansa, gradasi", "shade, nuance", "matiz"], d: ["Perbedaan halus dalam warna atau makna.", "A subtle difference in colour or meaning.", "Diferencia sutil de color o sentido."], ex: ["Υπάρχει μια σημαντική απόχρωση.", "Ada nuansa yang penting.", "There's an important nuance.", "Hay un matiz importante."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "αναπόφευκτος", r: "anapofefktos", pos: "adj", cefr: "C2", ipa: "anaˈpofefktos", g: ["tak terhindarkan", "inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Η αύξηση τιμών είναι αναπόφευκτη.", "Kenaikan harga tak terhindarkan.", "A price rise is inevitable.", "La subida de precios es inevitable."] },
  { w: "ανείπωτος", r: "aneipotos", pos: "adj", cefr: "C2", ipa: "aˈnipotos", g: ["tak terkatakan", "unspeakable, ineffable", "inefable"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Ένιωσε ανείπωτη χαρά.", "Dia merasakan sukacita tak terkatakan.", "She felt an ineffable joy.", "Sintió una alegría inefable."] },
  { w: "αποφεύγω", r: "apofevgo", pos: "v", cefr: "C2", ipa: "apoˈfevɣo", g: ["menghindari, mengelak", "to avoid, to evade", "eludir"], d: ["Menjauhi persoalan alih-alih menghadapinya.", "To keep away from an issue instead of facing it.", "Evitar un asunto en vez de afrontarlo."], ex: ["Απέφυγε την ερώτηση.", "Dia mengelak dari pertanyaan itu.", "He evaded the question.", "Eludió la pregunta."] },
  { w: "διασαφηνίζω", r: "diasafinizo", pos: "v", cefr: "C2", ipa: "ðiasafiˈnizo", g: ["menjernihkan", "to clarify, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Πρέπει να διασαφηνιστούν οι όροι.", "Ketentuannya perlu dijernihkan.", "The terms must be clarified.", "Hay que esclarecer los términos."] },
  { w: "μεροληψία", r: "merolipsia", pos: "n", cefr: "C2", gen: "f", ipa: "meroliˈpsia", g: ["keberpihakan, bias", "bias, partiality", "parcialidad"], d: ["Kecenderungan berpihak sehingga tidak adil.", "A leaning that makes judgement unfair.", "Inclinación que hace injusto el juicio."], ex: ["Η μελέτη δείχνει μεροληψία.", "Kajian itu menunjukkan keberpihakan.", "The study shows bias.", "El estudio muestra parcialidad."] },
  { w: "ορόσημο", r: "orosimo", pos: "n", cefr: "C2", gen: "nt", ipa: "oˈrosimo", g: ["tonggak", "milestone, landmark", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Η συμφωνία ήταν ορόσημο.", "Kesepakatan itu menjadi tonggak.", "The agreement was a milestone.", "El acuerdo fue un hito."] },
  { w: "παράδειγμα", r: "paradeigma", pos: "n", cefr: "C2", gen: "nt", ipa: "paˈraðiɣma", g: ["contoh; paradigma", "example; paradigm", "ejemplo; paradigma"], d: ["Contoh yang mewakili; juga kerangka berpikir suatu zaman.", "A representative case; also an era's framework of thought.", "Caso representativo; también modelo de pensamiento."], ex: ["Ήταν αλλαγή παραδείγματος.", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "υποβαθμίζω", r: "ypovathmizo", pos: "v", cefr: "C2", ipa: "ipovaθˈmizo", g: ["merendahkan, menurunkan", "to downgrade, to belittle", "menoscabar"], d: ["Membuat nilai sesuatu tampak lebih kecil.", "To make something seem less valuable.", "Hacer que algo parezca menor."], ex: ["Δεν θέλω να υποβαθμίσω τη δουλειά του.", "Saya tak ingin merendahkan kerjanya.", "I don't want to belittle his work.", "No quiero menoscabar su trabajo."] },
  { w: "υπό το πρίσμα", r: "ypo to prisma", pos: "phr", cefr: "C2", ipa: "iˈpo to ˈprizma", g: ["dari kacamata, berdasarkan", "in the light of, through the prism of", "a la luz de"], d: ["Menilai sesuatu dari sudut pandang tertentu.", "Judging something from a given standpoint.", "Juzgar algo desde cierto prisma."], ex: ["Υπό το πρίσμα των αποτελεσμάτων, είναι επιτυχία.", "Berdasarkan hasilnya, ini sukses.", "In the light of the results, it's a success.", "A la luz de los resultados, es un éxito."] },
  { w: "χίμαιρα", r: "chimaira", pos: "n", cefr: "C2", gen: "f", ipa: "ˈçimera", g: ["angan kosong", "chimera, pipe dream", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Αυτή η υπόσχεση είναι χίμαιρα.", "Janji itu angan kosong.", "That promise is a chimera.", "Esa promesa es una quimera."] },
  { w: "επιτακτικός", r: "epitaktikos", pos: "adj", cefr: "C2", ipa: "epitaktiˈkos", g: ["mendesak, imperatif", "imperative, pressing", "imperioso"], d: ["Menuntut dipenuhi segera.", "Demanding immediate attention.", "Que exige atención inmediata."], ex: ["Είναι επιτακτική ανάγκη.", "Ini kebutuhan mendesak.", "It's a pressing need.", "Es una necesidad imperiosa."] },
  { w: "αναδεικνύω", r: "anadeiknyo", pos: "v", cefr: "C2", ipa: "anaðiˈknio", g: ["menonjolkan, mengangkat", "to bring out, to showcase", "poner de relieve"], d: ["Membuat nilai sesuatu terlihat jelas.", "To make something's worth visible.", "Hacer visible el valor de algo."], ex: ["Η έρευνα αναδεικνύει ένα πρόβλημα.", "Riset itu mengangkat sebuah masalah.", "The research brings a problem to light.", "La investigación pone de relieve un problema."] },
];
