/* =========================================================================
   lexicon/es.js — Diccionario: Español. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Spanyol memakai abjad Latin dengan ñ dan tanda tanya/seru terbalik (¿ ¡). Ejaannya nyaris fonetis: sekali kamu tahu bunyinya, kamu bisa membaca hampir semua kata.",
    "Spanish uses the Latin alphabet plus ñ and the inverted ¿ ¡ marks. Spelling is almost perfectly phonetic: learn the sounds once and you can read nearly any word.",
    "El español usa el alfabeto latino más la ñ y los signos ¿ ¡. La ortografía es casi fonética: aprende los sonidos y podrás leer casi cualquier palabra.",
  ],
  script: [
    "27 huruf. Tekanan kata: berakhiran vokal/-n/-s → suku kata kedua dari belakang; selain itu → suku terakhir; tanda aksen (´) menandai pengecualian.",
    "27 letters. Stress: words ending in a vowel, -n or -s stress the second-to-last syllable; otherwise the last one. An accent (´) marks every exception.",
    "27 letras. Acentuación: palabras terminadas en vocal, -n o -s llevan el acento en la penúltima sílaba; si no, en la última. La tilde (´) marca las excepciones.",
  ],
  pron: [
    ["j / ge, gi", "Bunyi /x/ seperti 'kh' serak: jamón, gente.", "A raspy /x/ sound, like Scottish 'loch': jamón, gente.", "Sonido /x/ áspero: jamón, gente."],
    ["ñ", "/ɲ/ seperti 'ny' pada 'nyanyi': año, mañana.", "/ɲ/ like the 'ny' in canyon: año, mañana.", "/ɲ/ como en año, mañana."],
    ["ll / y", "/ʝ/ mirip 'y' dalam 'ya': llave, ayer.", "/ʝ/ close to English 'y': llave, ayer.", "/ʝ/ parecido a la 'y': llave, ayer."],
    ["rr", "Getar lidah kuat, membedakan arti: pero ≠ perro.", "A strongly trilled r — it changes meaning: pero ≠ perro.", "Vibrante múltiple; cambia el significado: pero ≠ perro."],
    ["h", "Selalu bisu: hola dibaca 'ola'.", "Always silent: hola sounds like 'ola'.", "Siempre muda: hola suena 'ola'."],
    ["z / ce, ci", "/θ/ (Spanyol) atau /s/ (Amerika Latin): cinco, zapato.", "/θ/ in Spain, /s/ in Latin America: cinco, zapato.", "/θ/ en España, /s/ en Hispanoamérica: cinco, zapato."],
  ],
  grammar: [
    {
      t: ["Gender & artikel", "Gender & articles", "Género y artículos"],
      d: ["Setiap kata benda maskulin (el) atau feminin (la); kata sifat mengikutinya: el libro rojo, la casa roja.", "Every noun is masculine (el) or feminine (la), and adjectives agree: el libro rojo, la casa roja.", "Todo sustantivo es masculino (el) o femenino (la), y el adjetivo concuerda: el libro rojo, la casa roja."],
      ex: "la casa blanca · el coche blanco",
    },
    {
      t: ["Ser vs. estar", "Ser vs. estar", "Ser y estar"],
      d: ["Keduanya berarti 'adalah': ser untuk sifat tetap/identitas, estar untuk keadaan & lokasi.", "Both mean 'to be': ser for identity and permanent traits, estar for states and location.", "Ambos significan 'to be': ser para identidad, estar para estados y ubicación."],
      ex: "Soy médico. · Estoy cansado.",
    },
    {
      t: ["Konjugasi tiga kelompok", "Three verb families", "Tres conjugaciones"],
      d: ["Kata kerja berakhiran -ar, -er, -ir dan berubah menurut pelaku: hablo, hablas, habla…", "Verbs end in -ar, -er or -ir and change with the person: hablo, hablas, habla…", "Los verbos terminan en -ar, -er o -ir y cambian según la persona: hablo, hablas, habla…"],
      ex: "hablar → hablo · comer → como · vivir → vivo",
    },
    {
      t: ["Dua masa lampau", "Two past tenses", "Dos pasados"],
      d: ["Pretérito untuk kejadian selesai, imperfecto untuk kebiasaan/latar.", "The preterite tells what happened; the imperfect describes habits and background.", "El pretérito cuenta lo que pasó; el imperfecto describe costumbres y contexto."],
      ex: "Ayer comí paella. · De niño comía paella.",
    },
    {
      t: ["Subjuntivo", "The subjunctive", "El subjuntivo"],
      d: ["Dipakai setelah harapan, keraguan, atau emosi — pintu masuk ke tingkat mahir.", "Used after wishes, doubt or emotion — the gateway to advanced Spanish.", "Se usa tras deseos, dudas o emociones — la puerta al nivel avanzado."],
      ex: "Espero que vengas. · No creo que sea fácil.",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "casa", pos: "n", cefr: "A1", gen: "f", ipa: "ˈka.sa", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Mi casa está cerca del parque.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."], syn: ["hogar", "vivienda"] },
  { w: "día", pos: "n", cefr: "A1", gen: "m", ipa: "ˈdi.a", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also the light part of it.", "Periodo de 24 horas; también la parte con luz."], ex: ["Trabajo todos los días.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["noche"] },
  { w: "noche", pos: "n", cefr: "A1", gen: "f", ipa: "ˈno.tʃe", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Por la noche leo un poco.", "Pada malam hari saya membaca sedikit.", "At night I read a little.", "Por la noche leo un poco."], ant: ["día"] },
  { w: "hombre", pos: "n", cefr: "A1", gen: "m", ipa: "ˈom.bɾe", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa berjenis kelamin laki-laki.", "An adult male human being.", "Ser humano adulto de sexo masculino."], ex: ["Ese hombre es mi vecino.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["mujer"] },
  { w: "mujer", pos: "n", cefr: "A1", gen: "f", ipa: "muˈxeɾ", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa berjenis kelamin perempuan.", "An adult female human being.", "Ser humano adulto de sexo femenino."], ex: ["La mujer del sombrero es mi tía.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["hombre"] },
  { w: "amigo", pos: "n", cefr: "A1", gen: "m", ipa: "aˈmi.ɣo", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita sukai.", "Someone you like and spend time with.", "Persona con la que tienes confianza y afecto."], ex: ["Voy al cine con un amigo.", "Saya pergi ke bioskop dengan teman.", "I'm going to the cinema with a friend.", "Voy al cine con un amigo."], syn: ["compañero"] },
  { w: "grande", pos: "adj", cefr: "A1", ipa: "ˈɡɾan.de", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Of more than average size.", "De tamaño superior a lo normal."], ex: ["Vivimos en una ciudad grande.", "Kami tinggal di kota besar.", "We live in a big city.", "Vivimos en una ciudad grande."], ant: ["pequeño"] },
  { w: "pequeño", pos: "adj", cefr: "A1", ipa: "peˈke.ɲo", g: ["kecil", "small, little", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Of less than average size.", "De tamaño inferior a lo normal."], ex: ["Tengo un piso pequeño.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["grande"] },
  { w: "bueno", pos: "adj", cefr: "A1", ipa: "ˈbwe.no", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["Es un buen restaurante.", "Itu restoran yang bagus.", "It's a good restaurant.", "Es un buen restaurante."], ant: ["malo"] },
  { w: "tener", pos: "v", cefr: "A1", ipa: "teˈneɾ", g: ["punya, memiliki", "to have", "tener"], d: ["Memiliki sesuatu; juga menyatakan usia & rasa.", "To possess; also used for age and sensations.", "Poseer algo; también expresa edad y sensaciones."], ex: ["Tengo dos hermanas.", "Saya punya dua saudara perempuan.", "I have two sisters.", "Tengo dos hermanas."], note: ["Rasa dinyatakan dengan tener, bukan estar: tengo hambre, tengo frío, tengo 20 años.", "Sensations use tener, not estar: tengo hambre (I'm hungry), tengo frío, tengo 20 años.", "Las sensaciones usan tener: tengo hambre, tengo frío, tengo 20 años."] },
  { w: "querer", pos: "v", cefr: "A1", ipa: "keˈɾeɾ", g: ["mau, mencintai", "to want; to love", "querer"], d: ["Menginginkan sesuatu; menyayangi seseorang.", "To want something; to love someone.", "Desear algo; amar a alguien."], ex: ["Quiero aprender español.", "Saya mau belajar bahasa Spanyol.", "I want to learn Spanish.", "Quiero aprender español."] },
  { w: "ir", pos: "v", cefr: "A1", ipa: "iɾ", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse hacia un lugar."], ex: ["Voy al mercado ahora.", "Saya pergi ke pasar sekarang.", "I'm going to the market now.", "Voy al mercado ahora."], note: ["ir a + infinitif = masa depan dekat: voy a estudiar.", "ir a + infinitive is the near future: voy a estudiar (I'm going to study).", "ir a + infinitivo es el futuro próximo: voy a estudiar."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "trabajo", pos: "n", cefr: "A2", gen: "m", ipa: "tɾaˈβa.xo", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan yang dilakukan untuk mencari nafkah.", "The activity you do to earn a living.", "Actividad que se hace para ganarse la vida."], ex: ["Mi trabajo empieza a las nueve.", "Pekerjaan saya mulai pukul sembilan.", "My job starts at nine.", "Mi trabajo empieza a las nueve."], syn: ["empleo"] },
  { w: "dinero", pos: "n", cefr: "A2", gen: "m", ipa: "diˈne.ɾo", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio que se usa para comprar cosas."], ex: ["No llevo dinero encima.", "Saya tidak membawa uang.", "I don't have any money on me.", "No llevo dinero encima."], syn: ["plata (Am.)"] },
  { w: "tiempo", pos: "n", cefr: "A2", gen: "m", ipa: "ˈtjem.po", g: ["waktu; cuaca", "time; weather", "tiempo"], d: ["Rentang jam & hari; juga keadaan cuaca.", "Hours and days passing; also the weather.", "Duración de horas y días; también el clima."], ex: ["No tengo tiempo hoy.", "Hari ini saya tidak punya waktu.", "I don't have time today.", "No tengo tiempo hoy."], note: ["¿Qué tiempo hace? menanyakan cuaca, bukan jam.", "¿Qué tiempo hace? asks about the weather, not the clock.", "¿Qué tiempo hace? pregunta por el clima, no por la hora."] },
  { w: "ciudad", pos: "n", cefr: "A2", gen: "f", ipa: "θjuˈðað", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Barcelona es una ciudad preciosa.", "Barcelona kota yang indah.", "Barcelona is a beautiful city.", "Barcelona es una ciudad preciosa."], ant: ["pueblo"] },
  { w: "ayudar", pos: "v", cefr: "A2", ipa: "a.ʝuˈðaɾ", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih mudah.", "To make someone else's task easier.", "Hacer más fácil la tarea de otro."], ex: ["¿Me puedes ayudar, por favor?", "Bisakah kamu menolong saya?", "Can you help me, please?", "¿Me puedes ayudar, por favor?"] },
  { w: "necesitar", pos: "v", cefr: "A2", ipa: "ne.θe.siˈtaɾ", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something you cannot do without.", "Requerir algo imprescindible."], ex: ["Necesito descansar un poco.", "Saya perlu istirahat sebentar.", "I need to rest a little.", "Necesito descansar un poco."] },
  { w: "empezar", pos: "v", cefr: "A2", ipa: "em.peˈθaɾ", g: ["memulai", "to begin, to start", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["La película empieza a las ocho.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], syn: ["comenzar"], ant: ["terminar"] },
  { w: "fácil", pos: "adj", cefr: "A2", ipa: "ˈfa.θil", g: ["mudah", "easy", "fácil"], d: ["Tidak memerlukan banyak usaha.", "Not requiring much effort.", "Que no exige mucho esfuerzo."], ex: ["El examen fue muy fácil.", "Ujiannya sangat mudah.", "The exam was very easy.", "El examen fue muy fácil."], ant: ["difícil"] },
  { w: "difícil", pos: "adj", cefr: "A2", ipa: "diˈfi.θil", g: ["sulit", "difficult, hard", "difícil"], d: ["Memerlukan usaha atau keahlian besar.", "Requiring effort or skill.", "Que exige esfuerzo o habilidad."], ex: ["Es difícil aparcar aquí.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["fácil"] },
  { w: "rápido", pos: "adj", cefr: "A2", ipa: "ˈra.pi.ðo", g: ["cepat", "fast, quick", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in a short time.", "Que se mueve u ocurre en poco tiempo."], ex: ["El tren es más rápido que el bus.", "Kereta lebih cepat daripada bus.", "The train is faster than the bus.", "El tren es más rápido que el bus."], ant: ["lento"] },
  { w: "siempre", pos: "adv", cefr: "A2", ipa: "ˈsjem.pɾe", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan, tanpa kecuali.", "On every occasion, without exception.", "En todas las ocasiones, sin excepción."], ex: ["Siempre desayuno en casa.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["nunca"] },
  { w: "porque", pos: "conj", cefr: "A2", ipa: "ˈpoɾ.ke", g: ["karena", "because", "porque"], d: ["Menyatakan sebab dari suatu hal.", "Introduces the reason for something.", "Introduce la causa de algo."], ex: ["No salgo porque llueve.", "Saya tidak keluar karena hujan.", "I'm not going out because it's raining.", "No salgo porque llueve."], note: ["porque = karena; por qué = mengapa; porqué = alasan.", "porque = because; por qué = why; el porqué = the reason.", "porque = causa; por qué = pregunta; el porqué = la razón."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "experiencia", pos: "n", cefr: "B1", gen: "f", ipa: "eks.peˈɾjen.θja", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing something.", "Conocimiento adquirido al hacer algo."], ex: ["Tiene mucha experiencia en ventas.", "Dia sangat berpengalaman di bidang penjualan.", "They have a lot of experience in sales.", "Tiene mucha experiencia en ventas."] },
  { w: "decisión", pos: "n", cefr: "B1", gen: "f", ipa: "de.θiˈsjon", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice you have settled on.", "Elección que se ha tomado."], ex: ["Fue una decisión difícil.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Kata kerjanya: tomar una decisión (bukan 'hacer').", "The verb is tomar una decisión — never 'hacer'.", "Se dice tomar una decisión, no 'hacer'."] },
  { w: "oportunidad", pos: "n", cefr: "B1", gen: "f", ipa: "o.poɾ.tu.niˈðað", g: ["kesempatan", "opportunity, chance", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to do something.", "Momento favorable para hacer algo."], ex: ["Es una gran oportunidad para ti.", "Ini kesempatan besar untukmu.", "It's a great opportunity for you.", "Es una gran oportunidad para ti."] },
  { w: "consejo", pos: "n", cefr: "B1", gen: "m", ipa: "konˈse.xo", g: ["nasihat, saran", "advice, tip", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["¿Me das un consejo?", "Boleh minta saran?", "Can you give me some advice?", "¿Me das un consejo?"] },
  { w: "mejorar", pos: "v", cefr: "B1", ipa: "me.xoˈɾaɾ", g: ["memperbaiki, meningkat", "to improve", "mejorar"], d: ["Menjadikan atau menjadi lebih baik.", "To make or become better.", "Hacer o volverse mejor."], ex: ["Quiero mejorar mi pronunciación.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."], ant: ["empeorar"] },
  { w: "conseguir", pos: "v", cefr: "B1", ipa: "kon.seˈɣiɾ", g: ["mendapatkan, berhasil", "to get, to manage to", "conseguir"], d: ["Berhasil memperoleh atau melakukan sesuatu.", "To obtain something or succeed in doing it.", "Lograr obtener o hacer algo."], ex: ["Conseguí entradas para el concierto.", "Saya berhasil dapat tiket konser.", "I managed to get concert tickets.", "Conseguí entradas para el concierto."], syn: ["lograr", "obtener"] },
  { w: "parecer", pos: "v", cefr: "B1", ipa: "pa.ɾeˈθeɾ", g: ["tampak, terkesan", "to seem; to think of", "parecer"], d: ["Memberi kesan tertentu; menyatakan pendapat.", "To give an impression; to give an opinion.", "Dar cierta impresión; opinar."], ex: ["¿Qué te parece la idea?", "Bagaimana menurutmu ide ini?", "What do you think of the idea?", "¿Qué te parece la idea?"] },
  { w: "aunque", pos: "conj", cefr: "B1", ipa: "ˈaun.ke", g: ["meskipun", "although, even though", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca un contraste con el resto de la frase."], ex: ["Aunque llueve, saldremos.", "Meskipun hujan, kami akan keluar.", "Even though it's raining, we'll go out.", "Aunque llueve, saldremos."] },
  { w: "sin embargo", pos: "phr", cefr: "B1", ipa: "sin emˈbaɾ.ɣo", g: ["namun begitu", "however, nevertheless", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector that signals a contrast.", "Conector que señala contraste."], ex: ["Es caro; sin embargo, vale la pena.", "Mahal; namun begitu, sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."], syn: ["no obstante"] },
  { w: "tal vez", pos: "adv", cefr: "B1", ipa: "tal ˈβeθ", g: ["mungkin", "maybe, perhaps", "tal vez"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility rather than certainty.", "Expresa posibilidad, no certeza."], ex: ["Tal vez venga mañana.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Tal vez venga mañana."], syn: ["quizás"] },
  { w: "acostumbrarse", pos: "v", cefr: "B1", ipa: "a.kos.tumˈbɾaɾ.se", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan hal baru.", "To become familiar with something new.", "Habituarse a algo nuevo."], ex: ["Me acostumbré al horario español.", "Saya terbiasa dengan jadwal Spanyol.", "I got used to the Spanish schedule.", "Me acostumbré al horario español."] },
  { w: "echar de menos", pos: "phr", cefr: "B1", ipa: "eˈtʃaɾ de ˈme.nos", g: ["merindukan", "to miss (someone)", "echar de menos"], d: ["Merasa sedih karena sesuatu tidak ada.", "To feel sad that someone or something is absent.", "Sentir la ausencia de alguien o algo."], ex: ["Echo de menos a mi familia.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."], syn: ["extrañar (Am.)"] },

  /* ------------------------------------------------------------------ B2 */
  { w: "desarrollo", pos: "n", cefr: "B2", gen: "m", ipa: "de.saˈro.ʝo", g: ["pengembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["El desarrollo del proyecto va bien.", "Pengembangan proyeknya berjalan baik.", "The development of the project is going well.", "El desarrollo del proyecto va bien."] },
  { w: "medio ambiente", pos: "n", cefr: "B2", gen: "m", ipa: "ˈme.ðjo amˈbjen.te", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en el que vivimos."], ex: ["Debemos cuidar el medio ambiente.", "Kita harus menjaga lingkungan.", "We must look after the environment.", "Debemos cuidar el medio ambiente."] },
  { w: "desafío", pos: "n", cefr: "B2", gen: "m", ipa: "de.saˈfi.o", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha keras.", "Something difficult that demands effort.", "Cosa difícil que exige esfuerzo."], ex: ["Aprender chino es todo un desafío.", "Belajar bahasa Mandarin benar-benar tantangan.", "Learning Chinese is quite a challenge.", "Aprender chino es todo un desafío."], syn: ["reto"] },
  { w: "acuerdo", pos: "n", cefr: "B2", gen: "m", ipa: "aˈkweɾ.ðo", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision that two or more sides accept.", "Decisión aceptada por varias partes."], ex: ["Llegamos a un acuerdo justo.", "Kami mencapai kesepakatan yang adil.", "We reached a fair agreement.", "Llegamos a un acuerdo justo."], note: ["estar de acuerdo = setuju; de acuerdo = baiklah.", "estar de acuerdo = to agree; ¡de acuerdo! = OK, agreed.", "estar de acuerdo = coincidir; ¡de acuerdo! = vale."] },
  { w: "lograr", pos: "v", cefr: "B2", ipa: "loˈɣɾaɾ", g: ["mencapai", "to achieve, to manage", "lograr"], d: ["Berhasil meraih tujuan setelah berusaha.", "To reach a goal after effort.", "Alcanzar un objetivo tras esforzarse."], ex: ["Logró terminar la carrera.", "Dia berhasil menyelesaikan kuliahnya.", "She managed to finish her degree.", "Logró terminar la carrera."], syn: ["alcanzar"] },
  { w: "plantear", pos: "v", cefr: "B2", ipa: "plan.teˈaɾ", g: ["mengajukan, mengemukakan", "to raise, to put forward", "plantear"], d: ["Mengemukakan masalah atau usulan.", "To bring up a problem or a proposal.", "Exponer un problema o una propuesta."], ex: ["Planteó una pregunta interesante.", "Dia mengajukan pertanyaan menarik.", "He raised an interesting question.", "Planteó una pregunta interesante."] },
  { w: "destacar", pos: "v", cefr: "B2", ipa: "des.taˈkaɾ", g: ["menonjol; menyoroti", "to stand out; to highlight", "destacar"], d: ["Terlihat lebih menonjol; menekankan sesuatu.", "To be noticeably better; to emphasise something.", "Sobresalir; subrayar algo."], ex: ["Cabe destacar su esfuerzo.", "Perlu disoroti kerja kerasnya.", "Their effort is worth highlighting.", "Cabe destacar su esfuerzo."], syn: ["resaltar"] },
  { w: "fiable", pos: "adj", cefr: "B2", ipa: "ˈfja.βle", g: ["dapat diandalkan", "reliable, trustworthy", "fiable"], d: ["Bisa dipercaya karena hasilnya konsisten.", "Deserving trust because it works consistently.", "Digno de confianza por su constancia."], ex: ["Es una fuente fiable.", "Itu sumber yang tepercaya.", "It's a reliable source.", "Es una fuente fiable."], syn: ["confiable"] },
  { w: "imprescindible", pos: "adj", cefr: "B2", ipa: "im.pɾes.θinˈdi.βle", g: ["mutlak perlu", "essential, indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "So necessary it cannot be left out.", "Tan necesario que no se puede omitir."], ex: ["El pasaporte es imprescindible.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "a pesar de", pos: "prep", cefr: "B2", ipa: "a peˈsaɾ de", g: ["meskipun, kendati", "in spite of, despite", "a pesar de"], d: ["Menyatakan hambatan yang tidak menghalangi.", "Introduces an obstacle that does not stop things.", "Introduce un obstáculo que no impide algo."], ex: ["A pesar del frío, salimos.", "Meski dingin, kami tetap keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "por lo tanto", pos: "conj", cefr: "B2", ipa: "poɾ lo ˈtan.to", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat logis dari pernyataan sebelumnya.", "Marks the logical consequence of what precedes.", "Marca la consecuencia lógica de lo anterior."], ex: ["Llovía; por lo tanto, cancelamos.", "Hujan; oleh karena itu kami batalkan.", "It was raining; therefore we cancelled.", "Llovía; por lo tanto, cancelamos."], syn: ["por consiguiente"] },
  { w: "asunto", pos: "n", cefr: "B2", gen: "m", ipa: "aˈsun.to", g: ["urusan, perkara", "matter, issue", "asunto"], d: ["Hal yang sedang dibicarakan atau ditangani.", "The thing being discussed or dealt with.", "Tema del que se trata."], ex: ["Es un asunto delicado.", "Ini perkara yang sensitif.", "It's a delicate matter.", "Es un asunto delicado."], syn: ["cuestión", "tema"] },

  /* ------------------------------------------------------------------ C1 */
  { w: "ámbito", pos: "n", cefr: "C1", gen: "m", ipa: "ˈam.bi.to", g: ["ranah, lingkup", "sphere, field, scope", "ámbito"], d: ["Wilayah atau bidang tempat sesuatu berlaku.", "The area or field in which something applies.", "Espacio o campo en que algo se aplica."], ex: ["En el ámbito laboral es distinto.", "Dalam ranah pekerjaan hal itu berbeda.", "In the workplace sphere it's different.", "En el ámbito laboral es distinto."], syn: ["campo", "esfera"] },
  { w: "enfoque", pos: "n", cefr: "C1", gen: "m", ipa: "eɱˈfo.ke", g: ["pendekatan, sudut pandang", "approach, focus", "enfoque"], d: ["Cara memandang atau menangani suatu masalah.", "The way a problem is looked at or handled.", "Manera de ver o tratar un asunto."], ex: ["Necesitamos un enfoque distinto.", "Kita butuh pendekatan yang berbeda.", "We need a different approach.", "Necesitamos un enfoque distinto."] },
  { w: "matiz", pos: "n", cefr: "C1", gen: "m", ipa: "maˈtiθ", g: ["nuansa", "nuance, shade of meaning", "matiz"], d: ["Perbedaan halus dalam arti atau warna.", "A subtle difference in meaning or colour.", "Diferencia sutil de significado o color."], ex: ["Hay un matiz irónico en su tono.", "Ada nuansa ironi dalam nadanya.", "There's an ironic nuance in his tone.", "Hay un matiz irónico en su tono."] },
  { w: "abordar", pos: "v", cefr: "C1", ipa: "a.βoɾˈðaɾ", g: ["menangani, membahas", "to tackle, to address", "abordar"], d: ["Mulai menangani masalah secara langsung.", "To start dealing with a problem directly.", "Empezar a tratar un asunto de frente."], ex: ["Hay que abordar el tema con calma.", "Masalah itu harus ditangani dengan tenang.", "We must tackle the issue calmly.", "Hay que abordar el tema con calma."], syn: ["afrontar"] },
  { w: "fomentar", pos: "v", cefr: "C1", ipa: "fo.menˈtaɾ", g: ["mendorong, menggalakkan", "to promote, to foster", "fomentar"], d: ["Membantu sesuatu tumbuh atau berkembang.", "To help something grow or spread.", "Ayudar a que algo crezca o se extienda."], ex: ["La ley fomenta el reciclaje.", "Undang-undang itu menggalakkan daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."], syn: ["impulsar"] },
  { w: "reflejar", pos: "v", cefr: "C1", ipa: "re.fleˈxaɾ", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan atau menggambarkan keadaan lain.", "To show or express something else.", "Mostrar o expresar otra cosa."], ex: ["Los datos reflejan una mejora.", "Datanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "contundente", pos: "adj", cefr: "C1", ipa: "kon.tunˈden.te", g: ["tegas, telak", "forceful, conclusive", "contundente"], d: ["Begitu kuat sampai sulit dibantah.", "So strong it leaves no room for doubt.", "Tan firme que no admite réplica."], ex: ["Dio una respuesta contundente.", "Dia memberi jawaban telak.", "He gave a forceful answer.", "Dio una respuesta contundente."] },
  { w: "minucioso", pos: "adj", cefr: "C1", ipa: "mi.nuˈθjo.so", g: ["teliti, cermat", "meticulous, thorough", "minucioso"], d: ["Memperhatikan setiap detail kecil.", "Paying attention to every small detail.", "Que atiende a cada pequeño detalle."], ex: ["Hizo un análisis minucioso.", "Dia membuat analisis yang teliti.", "She did a meticulous analysis.", "Hizo un análisis minucioso."], syn: ["meticuloso"] },
  { w: "no obstante", pos: "conj", cefr: "C1", ipa: "no oβsˈtan.te", g: ["walaupun demikian", "nonetheless, nevertheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal connector marking contrast.", "Conector formal de contraste."], ex: ["No obstante, la propuesta sigue en pie.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal still stands.", "No obstante, la propuesta sigue en pie."] },
  { w: "en aras de", pos: "prep", cefr: "C1", ipa: "en ˈa.ɾas de", g: ["demi", "for the sake of", "en aras de"], d: ["Menyatakan tujuan mulia yang dikejar.", "States the worthy aim being pursued.", "Expresa el fin que se persigue."], ex: ["En aras de la transparencia, publicamos todo.", "Demi transparansi, kami terbitkan semuanya.", "For the sake of transparency, we published everything.", "En aras de la transparencia, publicamos todo."] },
  { w: "consolidar", pos: "v", cefr: "C1", ipa: "kon.so.liˈðaɾ", g: ["memperkukuh", "to consolidate, to strengthen", "consolidar"], d: ["Membuat sesuatu menjadi mantap dan kuat.", "To make something firm and lasting.", "Dar firmeza y solidez a algo."], ex: ["La empresa consolidó su posición.", "Perusahaan itu memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "índole", pos: "n", cefr: "C1", gen: "f", ipa: "ˈin.do.le", g: ["sifat, jenis", "nature, kind", "índole"], d: ["Watak atau jenis dasar sesuatu.", "The essential character or type of something.", "Carácter o tipo esencial de algo."], ex: ["Son problemas de otra índole.", "Itu masalah dengan sifat yang lain.", "Those are problems of a different nature.", "Son problemas de otra índole."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "idiosincrasia", pos: "n", cefr: "C2", gen: "f", ipa: "i.ðjo.sinˈkɾa.sja", g: ["kekhasan watak", "idiosyncrasy, distinctive character", "idiosincrasia"], d: ["Ciri khas yang membedakan orang atau bangsa.", "The distinctive character of a person or people.", "Rasgos propios de una persona o pueblo."], ex: ["Refleja la idiosincrasia del país.", "Itu mencerminkan kekhasan negeri itu.", "It reflects the country's distinctive character.", "Refleja la idiosincrasia del país."] },
  { w: "paradigma", pos: "n", cefr: "C2", gen: "m", ipa: "pa.ɾaˈðiɣ.ma", g: ["paradigma", "paradigm, model", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Supuso un cambio de paradigma.", "Itu menandai perubahan paradigma.", "It marked a paradigm shift.", "Supuso un cambio de paradigma."] },
  { w: "soslayar", pos: "v", cefr: "C2", ipa: "sos.laˈʝaɾ", g: ["mengelak, menghindari", "to sidestep, to evade", "soslayar"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto en vez de afrontarlo."], ex: ["Soslayó la pregunta con elegancia.", "Dia mengelak pertanyaan itu dengan elegan.", "He elegantly sidestepped the question.", "Soslayó la pregunta con elegancia."], syn: ["eludir"] },
  { w: "dilucidar", pos: "v", cefr: "C2", ipa: "di.lu.θiˈðaɾ", g: ["menjernihkan, mengurai", "to elucidate, to clarify", "dilucidar"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Falta dilucidar quién decidió.", "Masih harus diurai siapa yang memutuskan.", "It remains to be clarified who decided.", "Falta dilucidar quién decidió."], syn: ["esclarecer"] },
  { w: "inefable", pos: "adj", cefr: "C2", ipa: "i.neˈfa.βle", g: ["tak terlukiskan", "ineffable, indescribable", "inefable"], d: ["Terlalu indah atau besar untuk dikatakan.", "Too great or beautiful to put into words.", "Tan grande o bello que no se puede expresar."], ex: ["Sintió una alegría inefable.", "Dia merasakan sukacita yang tak terlukiskan.", "She felt an ineffable joy.", "Sintió una alegría inefable."] },
  { w: "perentorio", pos: "adj", cefr: "C2", ipa: "pe.ɾenˈto.ɾjo", g: ["mendesak, mutlak", "peremptory, urgent", "perentorio"], d: ["Harus dipenuhi segera, tanpa penundaan.", "Requiring immediate compliance.", "Que urge y no admite demora."], ex: ["El plazo es perentorio.", "Tenggatnya mendesak.", "The deadline is peremptory.", "El plazo es perentorio."] },
  { w: "atisbo", pos: "n", cefr: "C2", gen: "m", ipa: "aˈtiz.βo", g: ["secercah, kilasan", "glimmer, hint", "atisbo"], d: ["Tanda sangat kecil dari sesuatu.", "A very faint sign of something.", "Señal muy leve de algo."], ex: ["No hay ni un atisbo de duda.", "Tak ada secercah keraguan pun.", "There isn't a glimmer of doubt.", "No hay ni un atisbo de duda."] },
  { w: "sesgo", pos: "n", cefr: "C2", gen: "m", ipa: "ˈsez.ɣo", g: ["bias, kecondongan", "bias, slant", "sesgo"], d: ["Kecenderungan tidak netral dalam menilai.", "A tendency that distorts judgement.", "Tendencia que desvía el juicio."], ex: ["El estudio tiene un sesgo evidente.", "Kajian itu punya bias yang jelas.", "The study has an obvious bias.", "El estudio tiene un sesgo evidente."] },
  { w: "menoscabar", pos: "v", cefr: "C2", ipa: "me.nos.kaˈβaɾ", g: ["merongrong, mengurangi", "to undermine, to diminish", "menoscabar"], d: ["Mengurangi nilai atau kekuatan sesuatu.", "To reduce the value or strength of something.", "Disminuir el valor o la fuerza de algo."], ex: ["Eso menoscaba su credibilidad.", "Hal itu merongrong kredibilitasnya.", "That undermines his credibility.", "Eso menoscaba su credibilidad."] },
  { w: "hito", pos: "n", cefr: "C2", gen: "m", ipa: "ˈi.to", g: ["tonggak sejarah", "milestone, landmark", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event that marks a new stage.", "Suceso que marca una nueva etapa."], ex: ["El acuerdo fue un hito histórico.", "Kesepakatan itu tonggak sejarah.", "The agreement was a historic milestone.", "El acuerdo fue un hito histórico."] },
  { w: "ineludible", pos: "adj", cefr: "C2", ipa: "i.ne.luˈði.βle", g: ["tak terhindarkan", "inescapable, unavoidable", "ineludible"], d: ["Tidak mungkin dihindari atau ditolak.", "Impossible to avoid or escape.", "Que no se puede evitar."], ex: ["Es un deber ineludible.", "Itu kewajiban yang tak terhindarkan.", "It's an inescapable duty.", "Es un deber ineludible."] },
  { w: "quimera", pos: "n", cefr: "C2", gen: "f", ipa: "kiˈme.ɾa", g: ["angan kosong", "pipe dream, chimera", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A beautiful hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Esa promesa es una quimera.", "Janji itu hanyalah angan kosong.", "That promise is a pipe dream.", "Esa promesa es una quimera."] },
];
