/* =========================================================================
   lexicon/fr.js — Dictionnaire : Français. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Prancis ditulis dengan abjad Latin plus lima tanda aksen (é è ê ë ç). Banyak huruf di akhir kata tidak dibunyikan, jadi telinga harus dilatih terpisah dari mata.",
    "French uses the Latin alphabet plus five accents (é è ê ë ç). Many final letters are silent, so the ear must be trained separately from the eye.",
    "El francés usa el alfabeto latino más cinco acentos (é è ê ë ç). Muchas letras finales son mudas: el oído se entrena aparte de la vista.",
  ],
  script: [
    "Tekanan selalu jatuh di suku kata terakhir kelompok kata, bukan per kata. Konsonan akhir umumnya bisu, kecuali disambung ke vokal berikutnya (liaison).",
    "Stress falls on the last syllable of a word group, not of each word. Final consonants are usually silent unless they link onto a following vowel (liaison).",
    "El acento cae en la última sílaba del grupo, no de cada palabra. Las consonantes finales suelen ser mudas salvo en la liaison.",
  ],
  pron: [
    ["u vs ou", "u /y/ bibir bulat lidah depan; ou /u/ seperti 'u' Indonesia: rue ≠ roue.", "u /y/ rounded lips with a front tongue; ou /u/ as in 'soup': rue ≠ roue.", "u /y/ labios redondeados con lengua adelante; ou /u/ como en 'sopa': rue ≠ roue."],
    ["r", "Getar di anak tekak (uvular) /ʁ/, bukan ujung lidah: Paris, rouge.", "A uvular /ʁ/ made in the throat, not with the tongue tip: Paris, rouge.", "Una /ʁ/ uvular, no vibrante de lengua: Paris, rouge."],
    ["vokal sengau", "an /ɑ̃/, in /ɛ̃/, on /ɔ̃/, un /œ̃/ — udara lewat hidung: pain, bon, temps.", "an /ɑ̃/, in /ɛ̃/, on /ɔ̃/, un /œ̃/ — air passes through the nose: pain, bon, temps.", "Vocales nasales an /ɑ̃/, in /ɛ̃/, on /ɔ̃/: pain, bon, temps."],
    ["liaison", "Konsonan bisu berbunyi bila kata berikutnya diawali vokal: les amis → /le.z‿a.mi/.", "A silent consonant sounds before a vowel: les amis → /le.z‿a.mi/.", "La consonante muda suena ante vocal: les amis → /le.z‿a.mi/."],
    ["e muet", "e di akhir kata biasanya tidak dibunyikan: table → /tabl/.", "A final e is normally silent: table → /tabl/.", "La e final normalmente no se pronuncia: table → /tabl/."],
    ["ch / j", "ch = /ʃ/ (chat), j dan ge/gi = /ʒ/ (jour, gilet).", "ch = /ʃ/ (chat); j and ge/gi = /ʒ/ (jour, gilet).", "ch = /ʃ/ (chat); j y ge/gi = /ʒ/ (jour, gilet)."],
  ],
  grammar: [
    {
      t: ["Gender & artikel", "Gender & articles", "Género y artículos"],
      d: ["Setiap benda maskulin (le) atau feminin (la); artikelnya menyusut jadi l' di depan vokal.", "Every noun is masculine (le) or feminine (la); the article shrinks to l' before a vowel.", "Todo sustantivo es masculino (le) o femenino (la); el artículo se reduce a l' ante vocal."],
      ex: "le livre · la table · l'ami",
    },
    {
      t: ["Kata sifat mengikuti benda", "Adjectives follow the noun", "El adjetivo sigue al sustantivo"],
      d: ["Umumnya kata sifat diletakkan sesudah kata benda dan menyesuaikan gender & jumlah.", "Adjectives usually come after the noun and agree in gender and number.", "El adjetivo suele ir después del sustantivo y concuerda en género y número."],
      ex: "une voiture rouge · des voitures rouges",
    },
    {
      t: ["Negasi berpasangan", "Two-part negation", "Negación en dos partes"],
      d: ["Ne … pas mengapit kata kerja; dalam percakapan ne sering hilang.", "Ne … pas wraps the verb; in speech the ne is often dropped.", "Ne … pas rodea al verbo; al hablar suele omitirse ne."],
      ex: "Je ne sais pas. · (Je sais pas.)",
    },
    {
      t: ["Passé composé", "The passé composé", "El passé composé"],
      d: ["Masa lampau dibentuk dengan avoir/être + partisip; kata kerja gerak memakai être.", "The past uses avoir or être plus a participle; verbs of motion take être.", "El pasado usa avoir o être más participio; los verbos de movimiento llevan être."],
      ex: "J'ai mangé. · Je suis allé.",
    },
    {
      t: ["Subjonctif", "The subjunctive", "El subjuntivo"],
      d: ["Muncul setelah keinginan, keraguan, atau emosi — penanda tingkat mahir.", "Appears after wishes, doubt or emotion — a marker of advanced French.", "Aparece tras deseos, dudas o emociones: marca el nivel avanzado."],
      ex: "Il faut que tu viennes. · Bien qu'il soit tard…",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "maison", pos: "n", cefr: "A1", gen: "f", ipa: "mɛ.zɔ̃", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Ma maison est près du parc.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "jour", pos: "n", cefr: "A1", gen: "m", ipa: "ʒuʁ", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Je travaille tous les jours.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["nuit"] },
  { w: "nuit", pos: "n", cefr: "A1", gen: "f", ipa: "nɥi", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Bonne nuit !", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["jour"] },
  { w: "homme", pos: "n", cefr: "A1", gen: "m", ipa: "ɔm", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["Cet homme est mon voisin.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["femme"] },
  { w: "femme", pos: "n", cefr: "A1", gen: "f", ipa: "fam", g: ["perempuan; istri", "woman; wife", "mujer; esposa"], d: ["Manusia dewasa perempuan; juga istri.", "An adult female human being; also a wife.", "Ser humano adulto femenino; también esposa."], ex: ["Sa femme est médecin.", "Istrinya seorang dokter.", "His wife is a doctor.", "Su mujer es médica."], note: ["Dibaca /fam/, bukan /fɛm/ — pengecualian ejaan yang harus dihafal.", "Pronounced /fam/, not /fɛm/ — a spelling exception worth memorising.", "Se pronuncia /fam/, no /fɛm/: excepción que hay que memorizar."] },
  { w: "ami", pos: "n", cefr: "A1", gen: "m", ipa: "a.mi", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Je sors avec un ami.", "Saya keluar dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."] },
  { w: "grand", pos: "adj", cefr: "A1", ipa: "ɡʁɑ̃", g: ["besar, tinggi", "big, tall", "grande, alto"], d: ["Berukuran atau bertinggi lebih dari biasanya.", "Larger or taller than average.", "De tamaño o estatura mayor de lo normal."], ex: ["Ils habitent une grande ville.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["petit"] },
  { w: "petit", pos: "adj", cefr: "A1", ipa: "pə.ti", g: ["kecil", "small, little", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["J'ai un petit appartement.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["grand"] },
  { w: "bon", pos: "adj", cefr: "A1", ipa: "bɔ̃", g: ["baik, enak", "good, tasty", "bueno"], d: ["Bermutu baik atau terasa enak.", "Of good quality, or tasting good.", "De buena calidad o sabroso."], ex: ["C'est un bon restaurant.", "Itu restoran yang bagus.", "It's a good restaurant.", "Es un buen restaurante."], ant: ["mauvais"] },
  { w: "avoir", pos: "v", cefr: "A1", ipa: "a.vwaʁ", g: ["punya", "to have", "tener"], d: ["Memiliki sesuatu; juga menyatakan usia & rasa.", "To possess; also used for age and sensations.", "Poseer; también expresa edad y sensaciones."], ex: ["J'ai deux sœurs.", "Saya punya dua saudara perempuan.", "I have two sisters.", "Tengo dos hermanas."], note: ["Rasa dan usia memakai avoir: j'ai faim, j'ai 20 ans.", "Sensations and age use avoir: j'ai faim, j'ai 20 ans.", "Sensaciones y edad usan avoir: j'ai faim, j'ai 20 ans."] },
  { w: "vouloir", pos: "v", cefr: "A1", ipa: "vu.lwaʁ", g: ["mau, ingin", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Je veux apprendre le français.", "Saya ingin belajar bahasa Prancis.", "I want to learn French.", "Quiero aprender francés."] },
  { w: "aller", pos: "v", cefr: "A1", ipa: "a.le", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Je vais au marché.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."], note: ["aller + infinitif = masa depan dekat: je vais partir.", "aller + infinitive is the near future: je vais partir.", "aller + infinitivo es el futuro próximo: je vais partir."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "travail", pos: "n", cefr: "A2", gen: "m", ipa: "tʁa.vaj", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you do to earn a living.", "Actividad para ganarse la vida."], ex: ["Mon travail commence à neuf heures.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."], syn: ["emploi"] },
  { w: "argent", pos: "n", cefr: "A2", gen: "m", ipa: "aʁ.ʒɑ̃", g: ["uang; perak", "money; silver", "dinero; plata"], d: ["Alat tukar untuk membeli; juga logam perak.", "What you buy things with; also the metal silver.", "Medio para comprar; también el metal plata."], ex: ["Je n'ai pas assez d'argent.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "temps", pos: "n", cefr: "A2", gen: "m", ipa: "tɑ̃", g: ["waktu; cuaca", "time; weather", "tiempo"], d: ["Jam yang berjalan; juga keadaan cuaca.", "Passing hours; also the weather.", "El paso del tiempo; también el clima."], ex: ["Je n'ai pas le temps.", "Saya tidak punya waktu.", "I don't have time.", "No tengo tiempo."] },
  { w: "ville", pos: "n", cefr: "A2", gen: "f", ipa: "vil", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Lyon est une belle ville.", "Lyon kota yang indah.", "Lyon is a beautiful city.", "Lyon es una ciudad bonita."] },
  { w: "aider", pos: "v", cefr: "A2", ipa: "e.de", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Tu peux m'aider, s'il te plaît ?", "Bisakah kamu menolong saya?", "Can you help me, please?", "¿Puedes ayudarme, por favor?"] },
  { w: "commencer", pos: "v", cefr: "A2", ipa: "kɔ.mɑ̃.se", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Le film commence à huit heures.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["finir"] },
  { w: "besoin", pos: "n", cefr: "A2", gen: "m", ipa: "bə.zwɛ̃", g: ["kebutuhan (avoir besoin de)", "need (avoir besoin de = to need)", "necesidad"], d: ["Hal yang diperlukan; dipakai dalam avoir besoin de.", "Something required; used in avoir besoin de.", "Lo que hace falta; se usa en avoir besoin de."], ex: ["J'ai besoin de repos.", "Saya butuh istirahat.", "I need some rest.", "Necesito descansar."] },
  { w: "facile", pos: "adj", cefr: "A2", ipa: "fa.sil", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["L'examen était facile.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["difficile"] },
  { w: "difficile", pos: "adj", cefr: "A2", ipa: "di.fi.sil", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["C'est difficile de se garer ici.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["facile"] },
  { w: "rapide", pos: "adj", cefr: "A2", ipa: "ʁa.pid", g: ["cepat", "fast, quick", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Le train est plus rapide.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["lent"] },
  { w: "toujours", pos: "adv", cefr: "A2", ipa: "tu.ʒuʁ", g: ["selalu; masih", "always; still", "siempre; todavía"], d: ["Pada setiap kesempatan; juga 'masih'.", "On every occasion; also 'still'.", "En toda ocasión; también 'todavía'."], ex: ["Je prends toujours le bus.", "Saya selalu naik bus.", "I always take the bus.", "Siempre tomo el autobús."] },
  { w: "parce que", pos: "conj", cefr: "A2", ipa: "paʁs kə", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Je reste parce qu'il pleut.", "Saya tinggal karena hujan.", "I'm staying because it's raining.", "Me quedo porque llueve."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "expérience", pos: "n", cefr: "B1", gen: "f", ipa: "ɛks.pe.ʁjɑ̃s", g: ["pengalaman; percobaan", "experience; experiment", "experiencia"], d: ["Pengetahuan dari hal yang dijalani; juga eksperimen.", "Knowledge from doing; also a scientific experiment.", "Conocimiento por la práctica; también experimento."], ex: ["Elle a beaucoup d'expérience.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "décision", pos: "n", cefr: "B1", gen: "f", ipa: "de.si.zjɔ̃", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice you have settled on.", "Elección ya tomada."], ex: ["C'était une décision difficile.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya prendre une décision, bukan 'faire'.", "The collocation is prendre une décision, not 'faire'.", "Se dice prendre une décision, no 'faire'."] },
  { w: "occasion", pos: "n", cefr: "B1", gen: "f", ipa: "ɔ.ka.zjɔ̃", g: ["kesempatan; barang bekas", "opportunity; second-hand", "ocasión"], d: ["Saat yang tepat; d'occasion berarti bekas.", "A good moment; d'occasion means second-hand.", "Momento propicio; d'occasion es de segunda mano."], ex: ["C'est une belle occasion.", "Ini kesempatan bagus.", "It's a great opportunity.", "Es una buena ocasión."] },
  { w: "conseil", pos: "n", cefr: "B1", gen: "m", ipa: "kɔ̃.sɛj", g: ["nasihat", "advice, tip", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Donne-moi un conseil.", "Beri saya saran.", "Give me some advice.", "Dame un consejo."] },
  { w: "améliorer", pos: "v", cefr: "B1", ipa: "a.me.ljɔ.ʁe", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Je veux améliorer mon accent.", "Saya ingin memperbaiki aksen saya.", "I want to improve my accent.", "Quiero mejorar mi acento."] },
  { w: "réussir", pos: "v", cefr: "B1", ipa: "ʁe.y.siʁ", g: ["berhasil, lulus", "to succeed, to pass", "conseguir, aprobar"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["Il a réussi son examen.", "Dia lulus ujiannya.", "He passed his exam.", "Aprobó el examen."], ant: ["échouer"] },
  { w: "sembler", pos: "v", cefr: "B1", ipa: "sɑ̃.ble", g: ["tampak", "to seem", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Il semble fatigué.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "cependant", pos: "conj", cefr: "B1", ipa: "sə.pɑ̃.dɑ̃", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking contrast.", "Conector de contraste."], ex: ["C'est cher ; cependant, ça vaut le coup.", "Mahal; namun begitu, sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."], syn: ["pourtant"] },
  { w: "peut-être", pos: "adv", cefr: "B1", ipa: "pø.tɛtʁ", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility rather than certainty.", "Expresa posibilidad, no certeza."], ex: ["Il viendra peut-être demain.", "Mungkin dia datang besok.", "He may come tomorrow.", "Quizá venga mañana."] },
  { w: "s'habituer", pos: "v", cefr: "B1", ipa: "sa.bi.tɥe", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Je me suis habitué au climat.", "Saya sudah terbiasa dengan iklimnya.", "I got used to the climate.", "Me acostumbré al clima."] },
  { w: "manquer", pos: "v", cefr: "B1", ipa: "mɑ̃.ke", g: ["kurang; merindukan", "to lack; to miss", "faltar; echar de menos"], d: ["Tidak ada dalam jumlah cukup; juga dirindukan.", "To be missing; also to be missed by someone.", "Faltar; también ser echado de menos."], ex: ["Tu me manques.", "Aku merindukanmu.", "I miss you.", "Te echo de menos."], note: ["Susunannya terbalik: 'tu me manques' = aku merindukanmu.", "The syntax is reversed: 'tu me manques' means I miss you.", "La sintaxis se invierte: 'tu me manques' = te echo de menos."] },
  { w: "bien que", pos: "conj", cefr: "B1", ipa: "bjɛ̃ kə", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras; diikuti subjonctif.", "Marks a contrast; takes the subjunctive.", "Marca contraste; exige subjuntivo."], ex: ["Bien qu'il pleuve, on sort.", "Meskipun hujan, kami keluar.", "Although it's raining, we're going out.", "Aunque llueve, salimos."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "développement", pos: "n", cefr: "B2", gen: "m", ipa: "dev.lɔp.mɑ̃", g: ["pengembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Le développement du projet avance.", "Pengembangan proyeknya berjalan.", "The project's development is progressing.", "El desarrollo del proyecto avanza."] },
  { w: "environnement", pos: "n", cefr: "B2", gen: "m", ipa: "ɑ̃.vi.ʁɔn.mɑ̃", g: ["lingkungan", "environment", "medio ambiente"], d: ["Alam sekitar; juga suasana kerja.", "The natural surroundings; also a work setting.", "Entorno natural; también ambiente laboral."], ex: ["Il faut protéger l'environnement.", "Lingkungan harus dilindungi.", "The environment must be protected.", "Hay que proteger el medio ambiente."] },
  { w: "défi", pos: "n", cefr: "B2", gen: "m", ipa: "de.fi", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["C'est un vrai défi.", "Ini benar-benar tantangan.", "It's a real challenge.", "Es todo un desafío."] },
  { w: "accord", pos: "n", cefr: "B2", gen: "m", ipa: "a.kɔʁ", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui.", "A decision both sides accept.", "Decisión aceptada por ambas partes."], ex: ["Nous sommes d'accord.", "Kami sepakat.", "We agree.", "Estamos de acuerdo."] },
  { w: "atteindre", pos: "v", cefr: "B2", ipa: "a.tɛ̃dʁ", g: ["mencapai", "to reach, to achieve", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Nous avons atteint l'objectif.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "souligner", pos: "v", cefr: "B2", ipa: "su.li.ɲe", g: ["menggarisbawahi, menekankan", "to underline, to emphasise", "subrayar"], d: ["Menarik perhatian pada hal penting.", "To draw attention to something important.", "Destacar algo importante."], ex: ["Il faut souligner ce point.", "Poin ini perlu ditekankan.", "This point must be emphasised.", "Hay que subrayar este punto."] },
  { w: "fiable", pos: "adj", cefr: "B2", ipa: "fjabl", g: ["dapat diandalkan", "reliable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because it is consistent.", "De confianza por su constancia."], ex: ["C'est une source fiable.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "indispensable", pos: "adj", cefr: "B2", ipa: "ɛ̃.dis.pɑ̃.sabl", g: ["mutlak perlu", "essential", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "So necessary it cannot be left out.", "Tan necesario que no se puede omitir."], ex: ["Le passeport est indispensable.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "malgré", pos: "prep", cefr: "B2", ipa: "mal.ɡʁe", g: ["meskipun ada", "despite, in spite of", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Malgré le froid, nous sommes sortis.", "Meski dingin, kami keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "par conséquent", pos: "conj", cefr: "B2", ipa: "paʁ kɔ̃.se.kɑ̃", g: ["oleh karena itu", "consequently", "por consiguiente"], d: ["Menandai akibat logis.", "Marks a logical consequence.", "Marca la consecuencia lógica."], ex: ["Il pleuvait ; par conséquent, tout a été annulé.", "Hujan; oleh karena itu semua dibatalkan.", "It was raining; consequently everything was cancelled.", "Llovía; por consiguiente, se canceló todo."] },
  { w: "enjeu", pos: "n", cefr: "B2", gen: "m", ipa: "ɑ̃.ʒø", g: ["taruhan, hal yang dipertaruhkan", "what is at stake", "lo que está en juego"], d: ["Hal penting yang bisa hilang atau didapat.", "What can be won or lost in a situation.", "Lo que se puede ganar o perder."], ex: ["L'enjeu est considérable.", "Yang dipertaruhkan sangat besar.", "The stakes are considerable.", "Lo que está en juego es enorme."] },
  { w: "mettre en œuvre", pos: "phr", cefr: "B2", ipa: "mɛtʁ ɑ̃ nœvʁ", g: ["menerapkan", "to implement", "poner en práctica"], d: ["Menjalankan rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["Nous allons mettre en œuvre ce plan.", "Kami akan menerapkan rencana ini.", "We will implement this plan.", "Vamos a poner en práctica este plan."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "domaine", pos: "n", cefr: "C1", gen: "m", ipa: "dɔ.mɛn", g: ["bidang, ranah", "field, sphere", "ámbito"], d: ["Wilayah pengetahuan atau kegiatan tertentu.", "An area of knowledge or activity.", "Área de conocimiento o actividad."], ex: ["Dans le domaine juridique, c'est différent.", "Dalam ranah hukum, hal itu berbeda.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "démarche", pos: "n", cefr: "C1", gen: "f", ipa: "de.maʁʃ", g: ["pendekatan; langkah resmi", "approach; formal step", "enfoque; gestión"], d: ["Cara menangani sesuatu; juga urusan administrasi.", "A way of proceeding; also an official procedure.", "Manera de proceder; también trámite."], ex: ["Leur démarche est originale.", "Pendekatan mereka orisinal.", "Their approach is original.", "Su enfoque es original."] },
  { w: "nuance", pos: "n", cefr: "C1", gen: "f", ipa: "nɥɑ̃s", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau warna.", "A subtle difference in meaning or colour.", "Diferencia sutil de sentido o color."], ex: ["Il y a une nuance importante.", "Ada nuansa yang penting.", "There's an important nuance.", "Hay un matiz importante."] },
  { w: "aborder", pos: "v", cefr: "C1", ipa: "a.bɔʁ.de", g: ["menangani, membahas", "to tackle, to address", "abordar"], d: ["Mulai membahas atau menghadapi persoalan.", "To start dealing with an issue.", "Empezar a tratar un asunto."], ex: ["Abordons le sujet calmement.", "Mari bahas topik itu dengan tenang.", "Let's address the subject calmly.", "Abordemos el tema con calma."] },
  { w: "favoriser", pos: "v", cefr: "C1", ipa: "fa.vɔ.ʁi.ze", g: ["mendorong, memihak", "to promote, to favour", "favorecer"], d: ["Membuat sesuatu lebih mungkin terjadi.", "To make something more likely to happen.", "Hacer más probable algo."], ex: ["Cette loi favorise le recyclage.", "Undang-undang ini mendorong daur ulang.", "This law promotes recycling.", "Esta ley favorece el reciclaje."] },
  { w: "refléter", pos: "v", cefr: "C1", ipa: "ʁə.fle.te", g: ["mencerminkan", "to reflect", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Les chiffres reflètent une amélioration.", "Angkanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "rigoureux", pos: "adj", cefr: "C1", ipa: "ʁi.ɡu.ʁø", g: ["ketat, cermat", "rigorous, strict", "riguroso"], d: ["Dijalankan dengan disiplin dan teliti.", "Carried out with discipline and precision.", "Realizado con disciplina y precisión."], ex: ["Une analyse rigoureuse s'impose.", "Analisis yang cermat diperlukan.", "A rigorous analysis is called for.", "Se impone un análisis riguroso."] },
  { w: "néanmoins", pos: "conj", cefr: "C1", ipa: "ne.ɑ̃.mwɛ̃", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Néanmoins, la proposition tient.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue en pie."] },
  { w: "afin de", pos: "prep", cefr: "C1", ipa: "a.fɛ̃ də", g: ["demi, agar", "in order to", "a fin de"], d: ["Menyatakan tujuan secara formal.", "States a purpose in formal register.", "Expresa una finalidad en registro formal."], ex: ["Afin de gagner du temps, simplifions.", "Demi menghemat waktu, mari sederhanakan.", "In order to save time, let's simplify.", "A fin de ahorrar tiempo, simplifiquemos."] },
  { w: "consolider", pos: "v", cefr: "C1", ipa: "kɔ̃.sɔ.li.de", g: ["memperkukuh", "to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["L'entreprise a consolidé sa position.", "Perusahaan memperkukuh posisinya.", "The firm consolidated its position.", "La empresa consolidó su posición."] },
  { w: "portée", pos: "n", cefr: "C1", gen: "f", ipa: "pɔʁ.te", g: ["jangkauan, bobot", "scope, significance", "alcance"], d: ["Seberapa jauh pengaruh sesuatu terasa.", "How far something's effect reaches.", "Hasta dónde llega el efecto de algo."], ex: ["Une décision d'une grande portée.", "Keputusan berjangkauan luas.", "A decision of great significance.", "Una decisión de gran alcance."] },
  { w: "mettre l'accent sur", pos: "phr", cefr: "C1", ipa: "mɛtʁ lak.sɑ̃ syʁ", g: ["menitikberatkan pada", "to place the emphasis on", "poner el acento en"], d: ["Menjadikan sesuatu sebagai fokus utama.", "To make something the main focus.", "Convertir algo en el foco principal."], ex: ["Le rapport met l'accent sur la sécurité.", "Laporan itu menitikberatkan keselamatan.", "The report places the emphasis on safety.", "El informe pone el acento en la seguridad."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "porte", pos: "n", cefr: "A1", gen: "f", ipa: "pɔʁt", g: ["pintu", "door", "puerta"] },
  { w: "fenêtre", pos: "n", cefr: "A1", gen: "f", ipa: "fə.nɛtʁ", g: ["jendela", "window", "ventana"] },
  { w: "chambre", pos: "n", cefr: "A1", gen: "f", ipa: "ʃɑ̃bʁ", g: ["kamar", "room, bedroom", "habitación"] },
  { w: "table", pos: "n", cefr: "A1", gen: "f", ipa: "tabl", g: ["meja", "table", "mesa"] },
  { w: "chaise", pos: "n", cefr: "A1", gen: "f", ipa: "ʃɛz", g: ["kursi", "chair", "silla"] },
  { w: "lit", pos: "n", cefr: "A1", gen: "m", ipa: "li", g: ["tempat tidur", "bed", "cama"] },
  { w: "cuisine", pos: "n", cefr: "A1", gen: "f", ipa: "kɥi.zin", g: ["dapur; masakan", "kitchen; cooking", "cocina"] },
  { w: "salle de bains", pos: "n", cefr: "A1", gen: "f", ipa: "sal də bɛ̃", g: ["kamar mandi", "bathroom", "cuarto de baño"] },
  { w: "lampe", pos: "n", cefr: "A1", gen: "f", ipa: "lɑ̃p", g: ["lampu", "lamp", "lámpara"] },
  { w: "clé", pos: "n", cefr: "A1", gen: "f", ipa: "kle", g: ["kunci", "key", "llave"] },
  { w: "mur", pos: "n", cefr: "A1", gen: "m", ipa: "myʁ", g: ["dinding, tembok", "wall", "pared"] },
  { w: "toit", pos: "n", cefr: "A1", gen: "m", ipa: "twa", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "pain", pos: "n", cefr: "A1", gen: "m", ipa: "pɛ̃", g: ["roti", "bread", "pan"] },
  { w: "riz", pos: "n", cefr: "A1", gen: "m", ipa: "ʁi", g: ["nasi, beras", "rice", "arroz"] },
  { w: "viande", pos: "n", cefr: "A1", gen: "f", ipa: "vjɑ̃d", g: ["daging", "meat", "carne"] },
  { w: "poisson", pos: "n", cefr: "A1", gen: "m", ipa: "pwa.sɔ̃", g: ["ikan", "fish", "pescado"] },
  { w: "œuf", pos: "n", cefr: "A1", gen: "m", ipa: "œf", g: ["telur", "egg", "huevo"], note: ["Jamaknya dibaca tanpa f: des œufs /dez‿ø/.", "The plural drops the f: des œufs /dez‿ø/.", "El plural pierde la f: des œufs /dez‿ø/."] },
  { w: "lait", pos: "n", cefr: "A1", gen: "m", ipa: "lɛ", g: ["susu", "milk", "leche"] },
  { w: "thé", pos: "n", cefr: "A1", gen: "m", ipa: "te", g: ["teh", "tea", "té"] },
  { w: "café", pos: "n", cefr: "A1", gen: "m", ipa: "ka.fe", g: ["kopi; kedai kopi", "coffee; café", "café"] },
  { w: "sucre", pos: "n", cefr: "A1", gen: "m", ipa: "sykʁ", g: ["gula", "sugar", "azúcar"] },
  { w: "sel", pos: "n", cefr: "A1", gen: "m", ipa: "sɛl", g: ["garam", "salt", "sal"] },
  { w: "fruit", pos: "n", cefr: "A1", gen: "m", ipa: "fʁɥi", g: ["buah", "fruit", "fruta"] },
  { w: "légume", pos: "n", cefr: "A1", gen: "m", ipa: "le.ɡym", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "chemise", pos: "n", cefr: "A2", gen: "f", ipa: "ʃə.miz", g: ["kemeja", "shirt", "camisa"] },
  { w: "pantalon", pos: "n", cefr: "A2", gen: "m", ipa: "pɑ̃.ta.lɔ̃", g: ["celana", "trousers", "pantalón"] },
  { w: "chaussure", pos: "n", cefr: "A2", gen: "f", ipa: "ʃo.syʁ", g: ["sepatu", "shoe", "zapato"] },
  { w: "chapeau", pos: "n", cefr: "A2", gen: "m", ipa: "ʃa.po", g: ["topi", "hat", "sombrero"] },
  { w: "main", pos: "n", cefr: "A2", gen: "f", ipa: "mɛ̃", g: ["tangan", "hand", "mano"] },
  { w: "œil", pos: "n", cefr: "A2", gen: "m", ipa: "œj", g: ["mata", "eye", "ojo"], note: ["Jamaknya benar-benar berbeda: œil → yeux.", "The plural is a different word: œil → yeux.", "El plural es otra palabra: œil → yeux."] },
  { w: "tête", pos: "n", cefr: "A2", gen: "f", ipa: "tɛt", g: ["kepala", "head", "cabeza"] },
  { w: "cœur", pos: "n", cefr: "A2", gen: "m", ipa: "kœʁ", g: ["jantung, hati", "heart", "corazón"] },
  { w: "cheveu", pos: "n", cefr: "A2", gen: "m", ipa: "ʃə.vø", g: ["rambut (sehelai)", "hair (a single one)", "cabello"] },
  { w: "dent", pos: "n", cefr: "A2", gen: "f", ipa: "dɑ̃", g: ["gigi", "tooth", "diente"] },
  { w: "oreille", pos: "n", cefr: "A2", gen: "f", ipa: "ɔ.ʁɛj", g: ["telinga", "ear", "oreja"] },
  { w: "visage", pos: "n", cefr: "A2", gen: "m", ipa: "vi.zaʒ", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "arbre", pos: "n", cefr: "A2", gen: "m", ipa: "aʁbʁ", g: ["pohon", "tree", "árbol"] },
  { w: "fleur", pos: "n", cefr: "A2", gen: "f", ipa: "flœʁ", g: ["bunga", "flower", "flor"] },
  { w: "montagne", pos: "n", cefr: "A2", gen: "f", ipa: "mɔ̃.taɲ", g: ["gunung", "mountain", "montaña"] },
  { w: "rivière", pos: "n", cefr: "A2", gen: "f", ipa: "ʁi.vjɛʁ", g: ["sungai", "river", "río"] },
  { w: "mer", pos: "n", cefr: "A2", gen: "f", ipa: "mɛʁ", g: ["laut", "sea", "mar"] },
  { w: "ciel", pos: "n", cefr: "A2", gen: "m", ipa: "sjɛl", g: ["langit", "sky", "cielo"] },
  { w: "étoile", pos: "n", cefr: "A2", gen: "f", ipa: "e.twal", g: ["bintang", "star", "estrella"] },
  { w: "chien", pos: "n", cefr: "A2", gen: "m", ipa: "ʃjɛ̃", g: ["anjing", "dog", "perro"] },
  { w: "chat", pos: "n", cefr: "A2", gen: "m", ipa: "ʃa", g: ["kucing", "cat", "gato"] },
  { w: "oiseau", pos: "n", cefr: "A2", gen: "m", ipa: "wa.zo", g: ["burung", "bird", "pájaro"] },
  { w: "cheval", pos: "n", cefr: "A2", gen: "m", ipa: "ʃə.val", g: ["kuda", "horse", "caballo"] },
  { w: "pluie", pos: "n", cefr: "A2", gen: "f", ipa: "plɥi", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "rue", pos: "n", cefr: "B1", gen: "f", ipa: "ʁy", g: ["jalan", "street", "calle"] },
  { w: "pont", pos: "n", cefr: "B1", gen: "m", ipa: "pɔ̃", g: ["jembatan", "bridge", "puente"] },
  { w: "marché", pos: "n", cefr: "B1", gen: "m", ipa: "maʁ.ʃe", g: ["pasar", "market", "mercado"] },
  { w: "école", pos: "n", cefr: "B1", gen: "f", ipa: "e.kɔl", g: ["sekolah", "school", "escuela"] },
  { w: "hôpital", pos: "n", cefr: "B1", gen: "m", ipa: "ɔ.pi.tal", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "bureau", pos: "n", cefr: "B1", gen: "m", ipa: "by.ʁo", g: ["kantor; meja kerja", "office; desk", "oficina; escritorio"] },
  { w: "bus", pos: "n", cefr: "B1", gen: "m", ipa: "bys", g: ["bus", "bus", "autobús"] },
  { w: "train", pos: "n", cefr: "B1", gen: "m", ipa: "tʁɛ̃", g: ["kereta api", "train", "tren"] },
  { w: "voiture", pos: "n", cefr: "B1", gen: "f", ipa: "vwa.tyʁ", g: ["mobil", "car", "coche"] },
  { w: "vélo", pos: "n", cefr: "B1", gen: "m", ipa: "ve.lo", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "aéroport", pos: "n", cefr: "B1", gen: "m", ipa: "a.e.ʁɔ.pɔʁ", g: ["bandara", "airport", "aeropuerto"] },
  { w: "billet", pos: "n", cefr: "B1", gen: "m", ipa: "bi.jɛ", g: ["tiket; uang kertas", "ticket; banknote", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "entreprise", pos: "n", cefr: "B2", gen: "f", ipa: "ɑ̃.tʁə.pʁiz", g: ["perusahaan", "company", "empresa"] },
  { w: "réunion", pos: "n", cefr: "B2", gen: "f", ipa: "ʁe.y.njɔ̃", g: ["rapat", "meeting", "reunión"] },
  { w: "contrat", pos: "n", cefr: "B2", gen: "m", ipa: "kɔ̃.tʁa", g: ["kontrak", "contract", "contrato"] },
  { w: "salaire", pos: "n", cefr: "B2", gen: "m", ipa: "sa.lɛʁ", g: ["gaji", "salary", "sueldo"] },
  { w: "prix", pos: "n", cefr: "B2", gen: "m", ipa: "pʁi", g: ["harga; hadiah", "price; prize", "precio; premio"] },
  { w: "impôt", pos: "n", cefr: "B2", gen: "m", ipa: "ɛ̃.po", g: ["pajak", "tax", "impuesto"] },
  { w: "banque", pos: "n", cefr: "B2", gen: "f", ipa: "bɑ̃k", g: ["bank", "bank", "banco"] },
  { w: "ordinateur", pos: "n", cefr: "B2", gen: "m", ipa: "ɔʁ.di.na.tœʁ", g: ["komputer", "computer", "ordenador"] },
  { w: "téléphone", pos: "n", cefr: "B2", gen: "m", ipa: "te.le.fɔn", g: ["telepon", "telephone", "teléfono"] },
  { w: "courriel", pos: "n", cefr: "B2", gen: "m", ipa: "ku.ʁjɛl", g: ["surel, email", "email", "correo electrónico"], syn: ["mail"] },
  { w: "fichier", pos: "n", cefr: "B2", gen: "m", ipa: "fi.ʃje", g: ["berkas", "file", "archivo"] },
  { w: "mot de passe", pos: "n", cefr: "B2", gen: "m", ipa: "mo də pas", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "paradigme", pos: "n", cefr: "C2", gen: "m", ipa: "pa.ʁa.diɡm", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["C'est un changement de paradigme.", "Ini pergeseran paradigma.", "It's a paradigm shift.", "Es un cambio de paradigma."] },
  { w: "éluder", pos: "v", cefr: "C2", ipa: "e.ly.de", g: ["mengelak", "to evade, to sidestep", "eludir"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto sin afrontarlo."], ex: ["Il a éludé la question.", "Dia mengelak dari pertanyaan itu.", "He sidestepped the question.", "Eludió la pregunta."] },
  { w: "élucider", pos: "v", cefr: "C2", ipa: "e.ly.si.de", g: ["menjernihkan", "to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Reste à élucider les causes.", "Penyebabnya masih harus dijernihkan.", "The causes remain to be elucidated.", "Queda por esclarecer las causas."] },
  { w: "ineffable", pos: "adj", cefr: "C2", ipa: "i.ne.fabl", g: ["tak terlukiskan", "ineffable", "inefable"], d: ["Terlalu besar atau indah untuk dikatakan.", "Too great or beautiful for words.", "Demasiado grande o bello para expresarse."], ex: ["Une joie ineffable.", "Sukacita yang tak terlukiskan.", "An ineffable joy.", "Una alegría inefable."] },
  { w: "impérieux", pos: "adj", cefr: "C2", ipa: "ɛ̃.pe.ʁjø", g: ["mendesak; angkuh", "pressing; imperious", "imperioso"], d: ["Menuntut dipenuhi segera; juga bernada memerintah.", "Demanding immediate attention; also commanding in tone.", "Que exige atención inmediata; también autoritario."], ex: ["Un besoin impérieux de réforme.", "Kebutuhan mendesak akan reformasi.", "A pressing need for reform.", "Una necesidad imperiosa de reforma."] },
  { w: "lueur", pos: "n", cefr: "C2", gen: "f", ipa: "lɥœʁ", g: ["secercah cahaya", "glimmer, faint light", "destello"], d: ["Cahaya lemah; kiasan untuk tanda kecil harapan.", "A faint light; figuratively, a small sign of hope.", "Luz tenue; en sentido figurado, indicio de esperanza."], ex: ["Une lueur d'espoir subsiste.", "Secercah harapan masih ada.", "A glimmer of hope remains.", "Queda un destello de esperanza."] },
  { w: "biais", pos: "n", cefr: "C2", gen: "m", ipa: "bjɛ", g: ["bias; cara", "bias; means", "sesgo; medio"], d: ["Kecondongan menilai; par le biais de = melalui.", "A slant in judgement; par le biais de = by means of.", "Inclinación del juicio; par le biais de = por medio de."], ex: ["L'étude présente un biais évident.", "Kajian itu punya bias yang jelas.", "The study shows an obvious bias.", "El estudio presenta un sesgo evidente."] },
  { w: "amoindrir", pos: "v", cefr: "C2", ipa: "a.mwɛ̃.dʁiʁ", g: ["mengurangi, melemahkan", "to diminish, to weaken", "menoscabar"], d: ["Membuat nilai atau kekuatan sesuatu berkurang.", "To reduce the value or force of something.", "Reducir el valor o la fuerza de algo."], ex: ["Cela amoindrit sa crédibilité.", "Hal itu mengurangi kredibilitasnya.", "That diminishes his credibility.", "Eso menoscaba su credibilidad."] },
  { w: "jalon", pos: "n", cefr: "C2", gen: "m", ipa: "ʒa.lɔ̃", g: ["tonggak", "milestone, marker", "hito"], d: ["Titik penting yang menandai kemajuan.", "A point that marks progress.", "Punto que marca un avance."], ex: ["Cet accord pose un jalon.", "Kesepakatan itu menjadi tonggak.", "That agreement sets a milestone.", "Ese acuerdo marca un hito."] },
  { w: "incontournable", pos: "adj", cefr: "C2", ipa: "ɛ̃.kɔ̃.tuʁ.nabl", g: ["tak bisa dilewatkan", "unavoidable, essential", "ineludible"], d: ["Begitu penting sehingga tak bisa dilewati.", "So important it cannot be bypassed.", "Tan importante que no se puede evitar."], ex: ["Un ouvrage incontournable.", "Karya yang tak boleh dilewatkan.", "An essential work.", "Una obra ineludible."] },
  { w: "chimère", pos: "n", cefr: "C2", gen: "f", ipa: "ʃi.mɛʁ", g: ["angan kosong", "pipe dream, chimera", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Cette promesse est une chimère.", "Janji itu hanyalah angan kosong.", "That promise is a chimera.", "Esa promesa es una quimera."] },
  { w: "à l'aune de", pos: "phr", cefr: "C2", ipa: "a lon də", g: ["diukur dengan", "measured against", "a la luz de"], d: ["Menilai sesuatu memakai ukuran tertentu.", "Judging something by a given yardstick.", "Juzgar algo con cierta vara de medir."], ex: ["À l'aune des résultats, c'est un succès.", "Diukur dari hasilnya, ini sukses.", "Measured against the results, it's a success.", "A la luz de los resultados, es un éxito."] },
];
