/* =========================================================================
   lexicon/hi.js — शब्दकोश: हिन्दी (Hindi). Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Hindi ditulis dengan aksara Devanagari yang benar-benar teratur: satu huruf, satu bunyi. Kosakatanya berlapis — akar Sanskerta untuk ranah resmi, kata Persia-Arab untuk kehidupan sehari-hari.",
    "Hindi is written in Devanagari, a remarkably regular script: one letter, one sound. Its vocabulary is layered — Sanskrit roots for formal registers, Perso-Arabic words for daily life.",
    "El hindi se escribe en devanagari, una escritura muy regular: una letra, un sonido. Su léxico tiene capas: raíces sánscritas y palabras persoárabes.",
  ],
  script: [
    "Huruf digantung pada satu garis horizontal (शिरोरेखा). Setiap konsonan sudah mengandung bunyi 'a'; tanda ् menghapusnya, dan tanda vokal ditulis di sekelilingnya.",
    "Letters hang from a single horizontal line (शिरोरेखा). Every consonant carries an inherent 'a'; the mark ् removes it, and vowel signs are written around the letter.",
    "Las letras cuelgan de una línea horizontal. Cada consonante lleva una 'a' inherente; el signo ् la elimina.",
  ],
  pron: [
    ["aspirasi", "क/ख, प/फ, त/थ berbeda hanya oleh embusan napas — dan itu mengubah arti.", "क/ख, प/फ, त/थ differ only by a puff of air — and that changes the word.", "क/ख, प/फ, त/थ solo se distinguen por el soplo de aire."],
    ["retrofleks", "ट ठ ड ढ dilafalkan dengan lidah menekuk ke langit-langit.", "ट ठ ड ढ are said with the tongue curled back to the palate.", "ट ठ ड ढ se pronuncian con la lengua curvada."],
    ["vokal sengau", "Tanda ँ menyengaukan vokal: हाँ (ya), माँ (ibu).", "The sign ँ nasalises a vowel: हाँ (yes), माँ (mother).", "El signo ँ nasaliza la vocal: हाँ, माँ."],
    ["ड़ / ढ़", "Bunyi kepakan retrofleks: बड़ा (bada), पढ़ना (padhna).", "A retroflex flap: बड़ा (bada), पढ़ना (padhna).", "Vibrante retrofleja: बड़ा, पढ़ना."],
    ["'a' bawaan", "Konsonan terakhir kata biasanya kehilangan bunyi 'a': राम dibaca 'Ram'.", "A word-final consonant usually loses its inherent 'a': राम is 'Ram'.", "La consonante final suele perder la 'a': राम suena 'Ram'."],
    ["व", "Antara 'v' dan 'w': विवाह bisa terdengar 'vivah' atau 'wiwah'.", "Between 'v' and 'w': विवाह may sound like 'vivah' or 'wiwah'.", "Entre 'v' y 'w': विवाह puede sonar 'vivah' o 'wiwah'."],
  ],
  grammar: [
    {
      t: ["Kata kerja di akhir", "The verb comes last", "El verbo va al final"],
      d: ["Urutannya Subjek–Objek–Kata kerja, dan kata bantu berdiri paling belakang.", "The order is Subject–Object–Verb, with the auxiliary at the very end.", "El orden es sujeto–objeto–verbo, con el auxiliar al final."],
      ex: "मैं हिन्दी सीख रहा हूँ। (Saya · Hindi · sedang belajar)",
    },
    {
      t: ["Kata belakang, bukan kata depan", "Postpositions, not prepositions", "Posposiciones, no preposiciones"],
      d: ["Penanda seperti में (di), से (dari), को (kepada) berdiri sesudah kata bendanya.", "Markers like में (in), से (from), को (to) follow their noun.", "Marcadores como में, से, को van detrás del sustantivo."],
      ex: "घर में · दोस्त से · माँ को",
    },
    {
      t: ["Gender pada kata kerja", "Verbs agree in gender", "El verbo concuerda en género"],
      d: ["Bentuk kata kerja berubah menurut jenis kelamin pelakunya.", "Verb forms change with the speaker's gender.", "Las formas verbales cambian según el género."],
      ex: "मैं जाता हूँ (laki-laki) · मैं जाती हूँ (perempuan)",
    },
    {
      t: ["Tiga tingkat 'kamu'", "Three levels of 'you'", "Tres niveles de 'tú'"],
      d: ["तू (sangat akrab), तुम (biasa), आप (hormat) — memilih yang salah terasa kasar.", "तू (very intimate), तुम (familiar), आप (respectful) — the wrong choice sounds rude.", "तू (muy íntimo), तुम (familiar), आप (respetuoso)."],
      ex: "आप कैसे हैं? · तुम कैसे हो?",
    },
    {
      t: ["Penanda ने pada masa lampau", "The ergative ने", "La marca ने"],
      d: ["Pada kalimat lampau transitif, pelakunya diberi ने dan kata kerjanya menyesuaikan objek.", "In transitive past sentences the subject takes ने and the verb agrees with the object.", "En pasado transitivo el sujeto lleva ने y el verbo concuerda con el objeto."],
      ex: "मैंने किताब पढ़ी।",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "अच्छा", r: "achchha", pos: "adj", cefr: "A1", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["यह अच्छा विचार है।", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["बुरा"] },
  { w: "आदमी", r: "aadmi", pos: "n", cefr: "A1", gen: "m", g: ["laki-laki, orang", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["वह आदमी मेरा पड़ोसी है।", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["औरत"] },
  { w: "औरत", r: "aurat", pos: "n", cefr: "A1", gen: "f", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["वह औरत मेरी मौसी है।", "Perempuan itu bibi saya.", "That woman is my aunt.", "Esa mujer es mi tía."], ant: ["आदमी"] },
  { w: "घर", r: "ghar", pos: "n", cefr: "A1", gen: "m", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["मेरा घर पार्क के पास है।", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "चाहना", r: "chahna", pos: "v", cefr: "A1", g: ["mau, ingin", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["मैं हिन्दी सीखना चाहता हूँ।", "Saya mau belajar bahasa Hindi.", "I want to learn Hindi.", "Quiero aprender hindi."] },
  { w: "छोटा", r: "chhota", pos: "adj", cefr: "A1", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["मेरा कमरा छोटा है।", "Kamar saya kecil.", "My room is small.", "Mi habitación es pequeña."], ant: ["बड़ा"] },
  { w: "जाना", r: "jana", pos: "v", cefr: "A1", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["मैं बाज़ार जा रहा हूँ।", "Saya sedang pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "दिन", r: "din", pos: "n", cefr: "A1", gen: "m", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["मैं हर दिन काम करता हूँ।", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["रात"] },
  { w: "दोस्त", r: "dost", pos: "n", cefr: "A1", gen: "m", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["वह मेरा सबसे अच्छा दोस्त है।", "Dia sahabat terbaik saya.", "He is my best friend.", "Es mi mejor amigo."] },
  { w: "बड़ा", r: "bada", pos: "adj", cefr: "A1", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["वे बड़े शहर में रहते हैं।", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["छोटा"] },
  { w: "रात", r: "raat", pos: "n", cefr: "A1", gen: "f", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["शुभ रात्रि!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["दिन"] },
  { w: "होना", r: "hona", pos: "v", cefr: "A1", g: ["ada, menjadi", "to be, to become", "ser, estar"], d: ["Menyatakan keberadaan atau perubahan keadaan.", "Expresses existence or becoming.", "Expresa existencia o transformación."], ex: ["वह डॉक्टर है।", "Dia seorang dokter.", "She is a doctor.", "Ella es médica."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "आसान", r: "aasaan", pos: "adj", cefr: "A2", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["परीक्षा आसान थी।", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["मुश्किल"] },
  { w: "काम", r: "kaam", pos: "n", cefr: "A2", gen: "m", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["मेरा काम नौ बजे शुरू होता है।", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "क्योंकि", r: "kyunki", pos: "conj", cefr: "A2", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["मैं घर पर हूँ क्योंकि बारिश हो रही है।", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },
  { w: "जरूरत", r: "zaroorat", pos: "n", cefr: "A2", gen: "f", g: ["kebutuhan", "need", "necesidad"], d: ["Hal yang diperlukan; ज़रूरत है = perlu.", "Something required; ज़रूरत है means 'need'.", "Lo que hace falta; ज़रूरत है = necesitar."], ex: ["मुझे आराम की जरूरत है।", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "तेज", r: "tez", pos: "adj", cefr: "A2", g: ["cepat; tajam", "fast; sharp", "rápido; agudo"], d: ["Bergerak cepat; juga tajam atau pedas.", "Moving fast; also sharp or spicy.", "Rápido; también agudo o picante."], ex: ["ट्रेन ज्यादा तेज है।", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["धीमा"] },
  { w: "पैसा", r: "paisa", pos: "n", cefr: "A2", gen: "m", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["मेरे पास पर्याप्त पैसा नहीं है।", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "मदद", r: "madad", pos: "n", cefr: "A2", gen: "f", g: ["bantuan", "help", "ayuda"], d: ["Tindakan meringankan pekerjaan orang lain.", "The act of making someone's task easier.", "Acción de facilitar la tarea de otro."], ex: ["क्या आप मेरी मदद कर सकते हैं?", "Bisakah Anda menolong saya?", "Can you help me?", "¿Puede ayudarme?"] },
  { w: "मुश्किल", r: "mushkil", pos: "adj", cefr: "A2", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["यहाँ गाड़ी खड़ी करना मुश्किल है।", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["आसान"] },
  { w: "समय", r: "samay", pos: "n", cefr: "A2", gen: "m", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["आज मेरे पास समय नहीं है।", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "शहर", r: "shahar", pos: "n", cefr: "A2", gen: "m", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["जयपुर एक सुंदर शहर है।", "Jaipur kota yang indah.", "Jaipur is a beautiful city.", "Jaipur es una ciudad bonita."] },
  { w: "शुरू", r: "shuru", pos: "v", cefr: "A2", g: ["mulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["फ़िल्म आठ बजे शुरू होती है।", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "हमेशा", r: "hamesha", pos: "adv", cefr: "A2", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["मैं हमेशा घर पर नाश्ता करता हूँ।", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "अनुभव", r: "anubhav", pos: "n", cefr: "B1", gen: "m", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["उनके पास बहुत अनुभव है।", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "आदत", r: "aadat", pos: "n", cefr: "B1", gen: "f", g: ["kebiasaan", "habit", "costumbre"], d: ["Perbuatan yang dilakukan berulang tanpa dipikir.", "Something done repeatedly without thinking.", "Acción repetida sin pensarlo."], ex: ["मुझे यहाँ की गर्मी की आदत हो गई।", "Saya sudah terbiasa dengan panas di sini.", "I've got used to the heat here.", "Ya me acostumbré al calor de aquí."] },
  { w: "फैसला", r: "faisla", pos: "n", cefr: "B1", gen: "m", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["यह मुश्किल फैसला था।", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], syn: ["निर्णय"] },
  { w: "मौका", r: "mauka", pos: "n", cefr: "B1", gen: "m", g: ["kesempatan", "opportunity, chance", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["यह अच्छा मौका है।", "Ini kesempatan bagus.", "This is a good opportunity.", "Es una buena oportunidad."] },
  { w: "लगना", r: "lagna", pos: "v", cefr: "B1", g: ["tampak, terasa", "to seem, to feel", "parecer"], d: ["Memberi kesan atau menimbulkan rasa tertentu.", "To give an impression or a feeling.", "Dar cierta impresión o sensación."], ex: ["वह थका हुआ लगता है।", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "लेकिन", r: "lekin", pos: "conj", cefr: "B1", g: ["tetapi", "but", "pero"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["महँगा है, लेकिन उपयोगी है।", "Mahal, tetapi berguna.", "It's expensive, but useful.", "Es caro, pero útil."] },
  { w: "सफल", r: "safal", pos: "adj", cefr: "B1", g: ["berhasil, sukses", "successful", "exitoso"], d: ["Mencapai apa yang diusahakan.", "Having achieved what was intended.", "Que logró lo que pretendía."], ex: ["परियोजना सफल रही।", "Proyeknya berhasil.", "The project was successful.", "El proyecto tuvo éxito."] },
  { w: "सलाह", r: "salah", pos: "n", cefr: "B1", gen: "f", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["क्या आप मुझे सलाह देंगे?", "Bisakah Anda memberi saya nasihat?", "Would you give me some advice?", "¿Me daría un consejo?"] },
  { w: "सुधारना", r: "sudharna", pos: "v", cefr: "B1", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["मैं अपना उच्चारण सुधारना चाहता हूँ।", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "शायद", r: "shayad", pos: "adv", cefr: "B1", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["शायद वह कल आएगा।", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "हालाँकि", r: "halanki", pos: "conj", cefr: "B1", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["हालाँकि बारिश हो रही है, हम जाएँगे।", "Meskipun hujan, kami akan pergi.", "Although it's raining, we'll go.", "Aunque llueve, iremos."] },
  { w: "याद", r: "yaad", pos: "n", cefr: "B1", gen: "f", g: ["ingatan; rindu", "memory; missing someone", "recuerdo; añoranza"], d: ["Ingatan; याद आना berarti merindukan.", "A memory; याद आना means to miss someone.", "Recuerdo; याद आना significa añorar."], ex: ["मुझे अपने परिवार की याद आती है।", "Saya merindukan keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "इसलिए", r: "isliye", pos: "conj", cefr: "B2", g: ["oleh karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["बारिश हुई, इसलिए हमने रद्द कर दिया।", "Hujan, oleh karena itu kami batalkan.", "It rained, therefore we cancelled.", "Llovió, por eso cancelamos."] },
  { w: "चुनौती", r: "chunauti", pos: "n", cefr: "B2", gen: "f", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["यह बड़ी चुनौती है।", "Ini tantangan besar.", "This is a big challenge.", "Es un gran desafío."] },
  { w: "जरूरी", r: "zaroori", pos: "adj", cefr: "B2", g: ["penting, wajib", "necessary, essential", "necesario"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["पासपोर्ट बहुत जरूरी है।", "Paspor sangat diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "जोर देना", r: "zor dena", pos: "v", cefr: "B2", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["उन्होंने सुरक्षा पर जोर दिया।", "Dia menekankan keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "बावजूद", r: "bawajood", pos: "prep", cefr: "B2", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["ठंड के बावजूद हम बाहर गए।", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."] },
  { w: "भरोसेमंद", r: "bharosemand", pos: "adj", cefr: "B2", g: ["dapat dipercaya", "reliable, trustworthy", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["यह भरोसेमंद स्रोत है।", "Ini sumber yang bisa dipercaya.", "This is a reliable source.", "Es una fuente fiable."] },
  { w: "मुद्दा", r: "mudda", pos: "n", cefr: "B2", gen: "m", g: ["isu, persoalan", "issue", "asunto"], d: ["Hal yang sedang dibicarakan atau diperdebatkan.", "The matter under discussion.", "Tema del que se trata."], ex: ["यह संवेदनशील मुद्दा है।", "Ini isu yang sensitif.", "It's a sensitive issue.", "Es un asunto delicado."] },
  { w: "लागू करना", r: "lagu karna", pos: "v", cefr: "B2", g: ["menerapkan, memberlakukan", "to implement, to enforce", "implantar"], d: ["Mengubah rencana atau aturan menjadi kenyataan.", "To put a plan or rule into force.", "Poner en vigor un plan o norma."], ex: ["हम नई नीति लागू करेंगे।", "Kami akan memberlakukan kebijakan baru.", "We'll implement the new policy.", "Implantaremos la nueva política."] },
  { w: "विकास", r: "vikas", pos: "n", cefr: "B2", gen: "m", g: ["perkembangan, pembangunan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["परियोजना का विकास अच्छा चल रहा है।", "Perkembangan proyeknya baik.", "The project's development is going well.", "El desarrollo del proyecto va bien."] },
  { w: "समझौता", r: "samjhauta", pos: "n", cefr: "B2", gen: "m", g: ["kesepakatan; kompromi", "agreement; compromise", "acuerdo"], d: ["Kesepakatan bersama, sering lewat saling mengalah.", "A mutual agreement, often through compromise.", "Acuerdo mutuo, a menudo por transacción."], ex: ["दोनों पक्षों ने समझौता किया।", "Kedua pihak membuat kesepakatan.", "Both sides reached an agreement.", "Ambas partes llegaron a un acuerdo."] },
  { w: "हासिल", r: "hasil", pos: "v", cefr: "B2", g: ["mencapai, memperoleh", "to attain, to obtain", "alcanzar"], d: ["Berhasil memperoleh sesuatu.", "To succeed in obtaining something.", "Lograr obtener algo."], ex: ["हमने लक्ष्य हासिल कर लिया।", "Kami sudah mencapai targetnya.", "We attained the target.", "Alcanzamos el objetivo."] },
  { w: "पर्यावरण", r: "paryavaran", pos: "n", cefr: "B2", gen: "m", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["हमें पर्यावरण बचाना चाहिए।", "Kita harus menjaga lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "उजागर करना", r: "ujagar karna", pos: "v", cefr: "C1", g: ["mengungkap, menyoroti", "to bring to light, to highlight", "sacar a la luz"], d: ["Membuat sesuatu terlihat dan diperhatikan.", "To make something visible and noticed.", "Hacer visible algo."], ex: ["रिपोर्ट ने जोखिम उजागर किए।", "Laporan itu mengungkap risikonya.", "The report brought the risks to light.", "El informe sacó a la luz los riesgos."] },
  { w: "क्षेत्र", r: "kshetra", pos: "n", cefr: "C1", gen: "m", g: ["bidang; wilayah", "field; region", "ámbito; región"], d: ["Wilayah kegiatan atau pengetahuan; juga daerah.", "An area of activity or knowledge; also a region.", "Área de actividad o conocimiento; también región."], ex: ["कानूनी क्षेत्र में स्थिति अलग है।", "Dalam bidang hukum keadaannya berbeda.", "In the legal field the situation differs.", "En el ámbito jurídico es distinto."] },
  { w: "गहन", r: "gahan", pos: "adj", cefr: "C1", g: ["mendalam, saksama", "deep, thorough", "profundo"], d: ["Dikerjakan sampai ke akar persoalan.", "Carried down to the root of the matter.", "Llevado hasta la raíz del asunto."], ex: ["गहन विश्लेषण की जरूरत है।", "Diperlukan analisis yang mendalam.", "A thorough analysis is needed.", "Hace falta un análisis profundo."] },
  { w: "ताकि", r: "taki", pos: "conj", cefr: "C1", g: ["agar, supaya", "so that, in order to", "para que"], d: ["Menyatakan tujuan dari suatu tindakan.", "States the purpose of an action.", "Expresa la finalidad de una acción."], ex: ["हमने प्रक्रिया सरल की ताकि समय बचे।", "Kami sederhanakan prosesnya agar hemat waktu.", "We simplified the process so as to save time.", "Simplificamos el proceso para ahorrar tiempo."] },
  { w: "दायरा", r: "dayra", pos: "n", cefr: "C1", gen: "m", g: ["cakupan, lingkup", "scope, ambit", "alcance"], d: ["Seberapa luas sesuatu berlaku.", "How far something extends.", "Hasta dónde llega algo."], ex: ["इस फैसले का दायरा बहुत बड़ा है।", "Cakupan keputusan ini sangat luas.", "The decision's scope is very wide.", "El alcance de la decisión es amplio."] },
  { w: "दृष्टिकोण", r: "drishtikon", pos: "n", cefr: "C1", gen: "m", g: ["sudut pandang, pendekatan", "viewpoint, approach", "punto de vista"], d: ["Cara seseorang memandang persoalan.", "The angle from which someone sees an issue.", "Ángulo desde el que se ve un asunto."], ex: ["हमें नया दृष्टिकोण चाहिए।", "Kita butuh sudut pandang baru.", "We need a new approach.", "Necesitamos otro enfoque."] },
  { w: "दर्शाना", r: "darshana", pos: "v", cefr: "C1", g: ["menunjukkan, mencerminkan", "to indicate, to reflect", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["आँकड़े सुधार दर्शाते हैं।", "Angkanya menunjukkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "निपटना", r: "nipatna", pos: "v", cefr: "C1", g: ["menangani", "to deal with, to tackle", "afrontar"], d: ["Mengurus persoalan sampai selesai.", "To deal with a matter until it is settled.", "Ocuparse de un asunto hasta resolverlo."], ex: ["हमें इस समस्या से निपटना होगा।", "Kita harus menangani masalah ini.", "We must tackle this problem.", "Debemos afrontar este problema."] },
  { w: "फिर भी", r: "phir bhi", pos: "conj", cefr: "C1", g: ["walaupun demikian", "nonetheless, even so", "aun así"], d: ["Menyatakan bahwa hasilnya tetap sama.", "Says the result holds anyway.", "Indica que el resultado se mantiene."], ex: ["फिर भी प्रस्ताव मान्य है।", "Walaupun demikian, usulan itu tetap berlaku.", "Even so, the proposal stands.", "Aun así, la propuesta sigue vigente."] },
  { w: "बारीकी", r: "bariki", pos: "n", cefr: "C1", gen: "f", g: ["kehalusan, nuansa", "fine detail, nuance", "matiz"], d: ["Perbedaan halus yang mudah terlewat.", "A fine difference that is easily missed.", "Diferencia fina que se pasa por alto."], ex: ["इसमें एक अहम बारीकी है।", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "बढ़ावा", r: "badhava", pos: "n", cefr: "C1", gen: "m", g: ["dorongan, promosi", "encouragement, boost", "impulso"], d: ["Dukungan yang membuat sesuatu tumbuh.", "Support that makes something grow.", "Apoyo que hace crecer algo."], ex: ["कानून पुनर्चक्रण को बढ़ावा देता है।", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "मजबूत करना", r: "mazboot karna", pos: "v", cefr: "C1", g: ["memperkukuh", "to strengthen", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["कंपनी ने अपनी स्थिति मजबूत की।", "Perusahaan memperkukuh posisinya.", "The company strengthened its position.", "La empresa consolidó su posición."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "अत्यावश्यक", r: "atyavashyak", pos: "adj", cefr: "C2", g: ["sangat mendesak", "urgent, imperative", "urgentísimo"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["यह अत्यावश्यक मामला है।", "Ini perkara yang sangat mendesak.", "This is an urgent matter.", "Es un asunto urgentísimo."] },
  { w: "अपरिहार्य", r: "aparihary", pos: "adj", cefr: "C2", g: ["tak terhindarkan", "inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["कीमत बढ़ना अपरिहार्य है।", "Kenaikan harga tak terhindarkan.", "A price rise is inevitable.", "La subida es inevitable."] },
  { w: "अवर्णनीय", r: "avarnaniya", pos: "adj", cefr: "C2", g: ["tak terlukiskan", "indescribable", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["उसे अवर्णनीय खुशी हुई।", "Dia merasakan kebahagiaan tak terlukiskan.", "She felt an indescribable joy.", "Sintió una alegría indescriptible."] },
  { w: "कमतर आँकना", r: "kamtar aankna", pos: "v", cefr: "C2", g: ["meremehkan", "to underestimate, to belittle", "subestimar"], d: ["Menganggap sesuatu lebih kecil nilainya.", "To judge something as worth less than it is.", "Juzgar algo por debajo de su valor."], ex: ["उनकी मेहनत को कमतर मत आँकिए।", "Jangan remehkan kerja kerasnya.", "Don't underestimate their effort.", "No subestimes su esfuerzo."] },
  { w: "किरण", r: "kiran", pos: "n", cefr: "C2", gen: "f", g: ["secercah sinar", "ray, glimmer", "rayo"], d: ["Berkas cahaya kecil; kiasan untuk harapan.", "A small beam of light; figuratively hope.", "Rayo pequeño; en sentido figurado, esperanza."], ex: ["उम्मीद की किरण अब भी है।", "Secercah harapan masih ada.", "A ray of hope remains.", "Aún queda un rayo de esperanza."] },
  { w: "के आलोक में", r: "ke aalok mein", pos: "phr", cefr: "C2", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["परिणामों के आलोक में यह सफलता है।", "Berdasarkan hasilnya, ini keberhasilan.", "In the light of the results it's a success.", "A la luz de los resultados, es un éxito."] },
  { w: "टालना", r: "talna", pos: "v", cefr: "C2", g: ["menunda, mengelak", "to put off, to dodge", "eludir, aplazar"], d: ["Menghindari atau menunda menghadapi sesuatu.", "To avoid or postpone facing something.", "Evitar o aplazar afrontar algo."], ex: ["उन्होंने सवाल टाल दिया।", "Dia mengelak dari pertanyaan itu.", "He dodged the question.", "Eludió la pregunta."] },
  { w: "पूर्वाग्रह", r: "purvagrah", pos: "n", cefr: "C2", gen: "m", g: ["prasangka, bias", "prejudice, bias", "prejuicio"], d: ["Penilaian yang dibuat sebelum mengetahui fakta.", "A judgement made before knowing the facts.", "Juicio previo al conocimiento de los hechos."], ex: ["अध्ययन में स्पष्ट पूर्वाग्रह है।", "Kajian itu punya bias yang jelas.", "The study has a clear bias.", "El estudio tiene un sesgo claro."] },
  { w: "प्रतिमान", r: "pratiman", pos: "n", cefr: "C2", gen: "m", g: ["paradigma, model", "paradigm, model", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["यह प्रतिमान बदलाव था।", "Itu pergeseran paradigma.", "That was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "मील का पत्थर", r: "meel ka patthar", pos: "n", cefr: "C2", gen: "m", g: ["tonggak sejarah", "milestone", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["यह समझौता मील का पत्थर है।", "Kesepakatan ini tonggak sejarah.", "This agreement is a milestone.", "Este acuerdo es un hito."] },
  { w: "मृगतृष्णा", r: "mrigtrishna", pos: "n", cefr: "C2", gen: "f", g: ["fatamorgana, angan kosong", "mirage, illusion", "espejismo"], d: ["Harapan indah yang ternyata semu.", "A lovely hope that turns out to be illusory.", "Ilusión hermosa que resulta ser falsa."], ex: ["वह वादा मृगतृष्णा निकला।", "Janji itu ternyata fatamorgana.", "That promise proved to be a mirage.", "Esa promesa resultó un espejismo."] },
  { w: "स्पष्ट करना", r: "spasht karna", pos: "v", cefr: "C2", g: ["menjernihkan", "to clarify, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["विवरण स्पष्ट करना होगा।", "Rinciannya perlu dijernihkan.", "The details must be clarified.", "Hay que esclarecer los detalles."] },
];
