/* =========================================================================
   lexicon/it.js — Dizionario: Italiano. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Italia adalah bahasa Latin yang paling mudah dibaca: hampir setiap huruf dibunyikan persis seperti tertulis, dan vokalnya hanya lima dan selalu jernih.",
    "Italian is the most readable of the Romance languages: nearly every letter is pronounced exactly as written, and the five vowels stay pure.",
    "El italiano es la lengua románica más transparente: casi todas las letras se pronuncian como se escriben y las cinco vocales son puras.",
  ],
  script: [
    "21 huruf (j k w x y hanya untuk kata serapan). Tekanan biasanya di suku kedua dari belakang; bila jatuh di suku terakhir, ditandai aksen: città, perché.",
    "21 letters (j k w x y appear only in loanwords). Stress usually falls on the second-to-last syllable; when it falls on the last, it is written: città, perché.",
    "21 letras (j k w x y solo en préstamos). El acento suele ir en la penúltima sílaba; si va en la última, se escribe: città, perché.",
  ],
  pron: [
    ["c / ci", "c = /k/ sebelum a o u (casa), tapi /tʃ/ sebelum e i (cena).", "c is /k/ before a o u (casa) but /tʃ/ before e i (cena).", "c es /k/ ante a o u (casa) y /tʃ/ ante e i (cena)."],
    ["g / gi", "g = /ɡ/ sebelum a o u (gatto), /dʒ/ sebelum e i (gelato).", "g is /ɡ/ before a o u (gatto), /dʒ/ before e i (gelato).", "g es /ɡ/ ante a o u (gatto), /dʒ/ ante e i (gelato)."],
    ["gn / gl", "gn = /ɲ/ (gnocchi), gli = /ʎ/ (famiglia).", "gn = /ɲ/ (gnocchi), gli = /ʎ/ (famiglia).", "gn = /ɲ/ (gnocchi), gli = /ʎ/ (famiglia)."],
    ["konsonan ganda", "Dibunyikan lebih panjang dan mengubah arti: nono ≠ nonno, casa ≠ cassa.", "Double consonants are held longer and change meaning: nono ≠ nonno, casa ≠ cassa.", "Las dobles se alargan y cambian el sentido: nono ≠ nonno, casa ≠ cassa."],
    ["h", "Selalu bisu; hanya dipakai untuk membedakan tulisan: ho, hai, hanno.", "Always silent; it only distinguishes spellings: ho, hai, hanno.", "Siempre muda; solo distingue grafías: ho, hai, hanno."],
    ["z", "Bisa /ts/ (grazie) atau /dz/ (zero) — pelajari per kata.", "Either /ts/ (grazie) or /dz/ (zero) — learned word by word.", "Puede ser /ts/ (grazie) o /dz/ (zero), según la palabra."],
  ],
  grammar: [
    {
      t: ["Gender & jumlah", "Gender & number", "Género y número"],
      d: ["Kata benda maskulin biasanya berakhir -o (jamak -i), feminin -a (jamak -e); kata sifat ikut berubah.", "Masculine nouns usually end in -o (plural -i), feminine in -a (plural -e); adjectives follow.", "Los masculinos suelen acabar en -o (plural -i) y los femeninos en -a (plural -e)."],
      ex: "il libro rosso → i libri rossi · la casa rossa → le case rosse",
    },
    {
      t: ["Subjek boleh dihilangkan", "The subject can vanish", "El sujeto puede omitirse"],
      d: ["Akhiran kata kerja sudah menyatakan pelakunya, jadi io/tu/lui jarang ditulis.", "The verb ending already names the person, so io/tu/lui are usually dropped.", "La terminación ya indica la persona: io/tu/lui suelen omitirse."],
      ex: "(Io) parlo italiano. · (Loro) arrivano domani.",
    },
    {
      t: ["Essere vs. avere", "Essere vs. avere", "Essere y avere"],
      d: ["Masa lampau memakai avere untuk sebagian besar kata kerja, tetapi essere untuk kata kerja gerak & refleksif — dan partisipnya ikut menyesuaikan.", "The past uses avere for most verbs but essere for motion and reflexive verbs — and then the participle agrees.", "El pasado usa avere en general y essere con verbos de movimiento y reflexivos; el participio concuerda."],
      ex: "Ho mangiato. · Sono andata.",
    },
    {
      t: ["Kata ganti melekat", "Pronouns attach to the verb", "Pronombres pegados al verbo"],
      d: ["Kata ganti objek berdiri sebelum kata kerja terkonjugasi, tetapi menempel di ujung infinitif.", "Object pronouns stand before a conjugated verb but attach to the end of an infinitive.", "Los pronombres van antes del verbo conjugado, pero se pegan al infinitivo."],
      ex: "Lo vedo. · Voglio vederlo.",
    },
    {
      t: ["Congiuntivo", "The subjunctive", "El subjuntivo"],
      d: ["Muncul setelah harapan, keraguan, dan emosi — penanda bahasa Italia yang terpelajar.", "Appears after wishes, doubt and emotion — the mark of educated Italian.", "Aparece tras deseos, dudas y emociones: marca del italiano culto."],
      ex: "Spero che tu venga. · Benché sia tardi…",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "casa", pos: "n", cefr: "A1", gen: "f", ipa: "ˈka.za", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["La mia casa è vicino al parco.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "giorno", pos: "n", cefr: "A1", gen: "m", ipa: "ˈdʒor.no", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Lavoro tutti i giorni.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["notte"] },
  { w: "notte", pos: "n", cefr: "A1", gen: "f", ipa: "ˈnɔt.te", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Buona notte!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["giorno"] },
  { w: "uomo", pos: "n", cefr: "A1", gen: "m", ipa: "ˈwɔ.mo", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["Quell'uomo è mio vicino.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], note: ["Jamaknya tak beraturan: uomo → uomini.", "Irregular plural: uomo → uomini.", "Plural irregular: uomo → uomini."] },
  { w: "donna", pos: "n", cefr: "A1", gen: "f", ipa: "ˈdɔn.na", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["La donna con il cappello è mia zia.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["uomo"] },
  { w: "amico", pos: "n", cefr: "A1", gen: "m", ipa: "aˈmi.ko", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Esco con un amico.", "Saya keluar dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."] },
  { w: "grande", pos: "adj", cefr: "A1", ipa: "ˈɡran.de", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Vivono in una grande città.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["piccolo"] },
  { w: "piccolo", pos: "adj", cefr: "A1", ipa: "ˈpik.ko.lo", g: ["kecil", "small, little", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Ho un appartamento piccolo.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["grande"] },
  { w: "buono", pos: "adj", cefr: "A1", ipa: "ˈbwɔ.no", g: ["baik, enak", "good, tasty", "bueno"], d: ["Bermutu baik atau terasa enak.", "Of good quality, or tasting good.", "De buena calidad o sabroso."], ex: ["È un buon ristorante.", "Itu restoran yang bagus.", "It's a good restaurant.", "Es un buen restaurante."], ant: ["cattivo"] },
  { w: "avere", pos: "v", cefr: "A1", ipa: "aˈve.re", g: ["punya", "to have", "tener"], d: ["Memiliki sesuatu; juga menyatakan usia & rasa.", "To possess; also used for age and sensations.", "Poseer; también expresa edad y sensaciones."], ex: ["Ho due sorelle.", "Saya punya dua saudara perempuan.", "I have two sisters.", "Tengo dos hermanas."], note: ["Rasa dan usia memakai avere: ho fame, ho vent'anni.", "Sensations and age use avere: ho fame, ho vent'anni.", "Sensaciones y edad usan avere: ho fame, ho vent'anni."] },
  { w: "volere", pos: "v", cefr: "A1", ipa: "voˈle.re", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Voglio imparare l'italiano.", "Saya mau belajar bahasa Italia.", "I want to learn Italian.", "Quiero aprender italiano."] },
  { w: "andare", pos: "v", cefr: "A1", ipa: "anˈda.re", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Vado al mercato.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "lavoro", pos: "n", cefr: "A2", gen: "m", ipa: "laˈvo.ro", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Il mio lavoro inizia alle nove.", "Pekerjaan saya mulai pukul sembilan.", "My job starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "denaro", pos: "n", cefr: "A2", gen: "m", ipa: "deˈna.ro", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Non ho abbastanza denaro.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."], syn: ["soldi"] },
  { w: "tempo", pos: "n", cefr: "A2", gen: "m", ipa: "ˈtɛm.po", g: ["waktu; cuaca", "time; weather", "tiempo"], d: ["Jam yang berjalan; juga keadaan cuaca.", "Passing hours; also the weather.", "El paso del tiempo; también el clima."], ex: ["Non ho tempo oggi.", "Hari ini saya tak punya waktu.", "I don't have time today.", "Hoy no tengo tiempo."] },
  { w: "città", pos: "n", cefr: "A2", gen: "f", ipa: "tʃitˈta", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Firenze è una città bellissima.", "Firenze kota yang sangat indah.", "Florence is a beautiful city.", "Florencia es una ciudad preciosa."], note: ["Kata berakhiran aksen tidak berubah di jamak: la città → le città.", "Words ending in a stressed vowel do not change in the plural: la città → le città.", "Las palabras con vocal tónica final no cambian en plural: la città → le città."] },
  { w: "aiutare", pos: "v", cefr: "A2", ipa: "a.juˈta.re", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Puoi aiutarmi, per favore?", "Bisakah kamu menolong saya?", "Can you help me, please?", "¿Puedes ayudarme, por favor?"] },
  { w: "cominciare", pos: "v", cefr: "A2", ipa: "ko.minˈtʃa.re", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Il film comincia alle otto.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], syn: ["iniziare"], ant: ["finire"] },
  { w: "bisogno", pos: "n", cefr: "A2", gen: "m", ipa: "biˈzoɲ.ɲo", g: ["kebutuhan (avere bisogno di)", "need (avere bisogno di = to need)", "necesidad"], d: ["Hal yang diperlukan; dipakai dalam avere bisogno di.", "Something required; used in avere bisogno di.", "Lo que hace falta; se usa en avere bisogno di."], ex: ["Ho bisogno di riposare.", "Saya butuh istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "facile", pos: "adj", cefr: "A2", ipa: "ˈfa.tʃi.le", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["L'esame era facile.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["difficile"] },
  { w: "difficile", pos: "adj", cefr: "A2", ipa: "difˈfi.tʃi.le", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["È difficile parcheggiare qui.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["facile"] },
  { w: "veloce", pos: "adj", cefr: "A2", ipa: "veˈlo.tʃe", g: ["cepat", "fast, quick", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Il treno è più veloce.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["lento"] },
  { w: "sempre", pos: "adv", cefr: "A2", ipa: "ˈsɛm.pre", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Faccio sempre colazione a casa.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["mai"] },
  { w: "perché", pos: "conj", cefr: "A2", ipa: "perˈke", g: ["karena; mengapa", "because; why", "porque; por qué"], d: ["Menyatakan sebab; juga kata tanya 'mengapa'.", "Introduces a reason; also the question word 'why'.", "Introduce la causa; también significa '¿por qué?'."], ex: ["Resto a casa perché piove.", "Saya di rumah karena hujan.", "I'm staying home because it's raining.", "Me quedo en casa porque llueve."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "esperienza", pos: "n", cefr: "B1", gen: "f", ipa: "es.peˈrjɛn.tsa", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Ha molta esperienza nel settore.", "Dia sangat berpengalaman di bidang itu.", "She has a lot of experience in the field.", "Tiene mucha experiencia en el sector."] },
  { w: "decisione", pos: "n", cefr: "B1", gen: "f", ipa: "de.tʃiˈzjo.ne", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["È stata una decisione difficile.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya prendere una decisione.", "The collocation is prendere una decisione.", "La colocación es prendere una decisione."] },
  { w: "occasione", pos: "n", cefr: "B1", gen: "f", ipa: "ok.kaˈzjo.ne", g: ["kesempatan", "opportunity, occasion", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["È una bella occasione per te.", "Ini kesempatan bagus untukmu.", "It's a great opportunity for you.", "Es una buena oportunidad para ti."] },
  { w: "consiglio", pos: "n", cefr: "B1", gen: "m", ipa: "konˈsiʎ.ʎo", g: ["nasihat", "advice, tip", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Mi dai un consiglio?", "Boleh minta saran?", "Can you give me some advice?", "¿Me das un consejo?"] },
  { w: "migliorare", pos: "v", cefr: "B1", ipa: "miʎ.ʎoˈra.re", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan atau menjadi lebih baik.", "To make or get better.", "Hacer o volverse mejor."], ex: ["Voglio migliorare la pronuncia.", "Saya ingin memperbaiki pelafalan.", "I want to improve my pronunciation.", "Quiero mejorar la pronunciación."], ant: ["peggiorare"] },
  { w: "riuscire", pos: "v", cefr: "B1", ipa: "riuʃˈʃi.re", g: ["berhasil", "to manage to, to succeed", "conseguir"], d: ["Berhasil melakukan sesuatu yang diusahakan.", "To succeed in doing something.", "Lograr hacer algo."], ex: ["Sono riuscito a finire in tempo.", "Saya berhasil selesai tepat waktu.", "I managed to finish on time.", "Conseguí terminar a tiempo."] },
  { w: "sembrare", pos: "v", cefr: "B1", ipa: "semˈbra.re", g: ["tampak", "to seem", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Sembra stanco.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "tuttavia", pos: "conj", cefr: "B1", ipa: "tut.taˈvi.a", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["È caro; tuttavia ne vale la pena.", "Mahal; namun begitu sepadan.", "It's expensive; however it's worth it.", "Es caro; sin embargo vale la pena."] },
  { w: "forse", pos: "adv", cefr: "B1", ipa: "ˈfor.se", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Forse arriva domani.", "Mungkin dia datang besok.", "Maybe he'll arrive tomorrow.", "Quizá llegue mañana."] },
  { w: "abituarsi", pos: "v", cefr: "B1", ipa: "a.bi.tuˈar.si", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Mi sono abituato agli orari italiani.", "Saya terbiasa dengan jadwal Italia.", "I got used to Italian hours.", "Me acostumbré a los horarios italianos."] },
  { w: "mancare", pos: "v", cefr: "B1", ipa: "manˈka.re", g: ["kurang; merindukan", "to be missing; to be missed", "faltar; echar de menos"], d: ["Tidak ada; juga dirindukan oleh seseorang.", "To be absent; also to be missed by someone.", "Faltar; también ser echado de menos."], ex: ["Mi manchi.", "Aku merindukanmu.", "I miss you.", "Te echo de menos."], note: ["Susunannya terbalik: 'mi manchi' = aku merindukanmu.", "The syntax is reversed: 'mi manchi' means I miss you.", "La sintaxis se invierte: 'mi manchi' = te echo de menos."] },
  { w: "benché", pos: "conj", cefr: "B1", ipa: "benˈke", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras; diikuti congiuntivo.", "Marks a contrast; takes the subjunctive.", "Marca contraste; exige subjuntivo."], ex: ["Benché piova, usciamo.", "Meskipun hujan, kami keluar.", "Although it's raining, we're going out.", "Aunque llueve, salimos."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "sviluppo", pos: "n", cefr: "B2", gen: "m", ipa: "zviˈlup.po", g: ["pengembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Lo sviluppo del progetto procede bene.", "Pengembangan proyeknya berjalan baik.", "The project's development is going well.", "El desarrollo del proyecto va bien."] },
  { w: "ambiente", pos: "n", cefr: "B2", gen: "m", ipa: "amˈbjɛn.te", g: ["lingkungan", "environment", "medio ambiente"], d: ["Alam sekitar; juga suasana suatu tempat.", "The natural surroundings; also an atmosphere.", "Entorno natural; también el ambiente."], ex: ["Dobbiamo proteggere l'ambiente.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "sfida", pos: "n", cefr: "B2", gen: "f", ipa: "ˈsfi.da", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["È una vera sfida.", "Ini benar-benar tantangan.", "It's a real challenge.", "Es todo un desafío."] },
  { w: "accordo", pos: "n", cefr: "B2", gen: "m", ipa: "akˈkɔr.do", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Siamo d'accordo.", "Kami sepakat.", "We agree.", "Estamos de acuerdo."] },
  { w: "raggiungere", pos: "v", cefr: "B2", ipa: "radˈdʒun.dʒe.re", g: ["mencapai", "to reach, to achieve", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Abbiamo raggiunto l'obiettivo.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "sottolineare", pos: "v", cefr: "B2", ipa: "sot.to.liˈne.a.re", g: ["menggarisbawahi", "to underline, to stress", "subrayar"], d: ["Menarik perhatian pada hal penting.", "To draw attention to something important.", "Destacar algo importante."], ex: ["Vorrei sottolineare un punto.", "Saya ingin menggarisbawahi satu poin.", "I'd like to stress one point.", "Quisiera subrayar un punto."] },
  { w: "affidabile", pos: "adj", cefr: "B2", ipa: "af.fiˈda.bi.le", g: ["dapat diandalkan", "reliable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["È una fonte affidabile.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "imprescindibile", pos: "adj", cefr: "B2", ipa: "im.pre.ʃinˈdi.bi.le", g: ["mutlak perlu", "essential", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Il passaporto è imprescindibile.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "nonostante", pos: "prep", cefr: "B2", ipa: "no.nosˈtan.te", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Nonostante il freddo, siamo usciti.", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."] },
  { w: "pertanto", pos: "conj", cefr: "B2", ipa: "perˈtan.to", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat logis.", "Marks a logical consequence.", "Marca la consecuencia lógica."], ex: ["Pioveva; pertanto abbiamo annullato.", "Hujan; oleh karena itu kami batalkan.", "It was raining; therefore we cancelled.", "Llovía; por lo tanto cancelamos."] },
  { w: "questione", pos: "n", cefr: "B2", gen: "f", ipa: "kwesˈtjo.ne", g: ["persoalan", "matter, issue", "cuestión"], d: ["Hal yang sedang dibicarakan atau ditangani.", "The matter under discussion.", "Tema del que se trata."], ex: ["È una questione delicata.", "Ini persoalan yang sensitif.", "It's a delicate matter.", "Es una cuestión delicada."] },
  { w: "attuare", pos: "v", cefr: "B2", ipa: "at.tuˈa.re", g: ["menerapkan", "to implement", "poner en práctica"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["Attueremo il piano a settembre.", "Kami terapkan rencananya September.", "We'll implement the plan in September.", "Aplicaremos el plan en septiembre."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "ambito", pos: "n", cefr: "C1", gen: "m", ipa: "ˈam.bi.to", g: ["ranah, lingkup", "sphere, field", "ámbito"], d: ["Wilayah tempat sesuatu berlaku.", "The area in which something applies.", "Espacio en que algo se aplica."], ex: ["In ambito giuridico è diverso.", "Dalam ranah hukum hal itu berbeda.", "In the legal sphere it's different.", "En el ámbito jurídico es distinto."] },
  { w: "approccio", pos: "n", cefr: "C1", gen: "m", ipa: "apˈprɔt.tʃo", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Serve un approccio diverso.", "Kita butuh pendekatan berbeda.", "A different approach is needed.", "Hace falta un enfoque distinto."] },
  { w: "sfumatura", pos: "n", cefr: "C1", gen: "f", ipa: "sfu.maˈtu.ra", g: ["nuansa", "nuance, shade", "matiz"], d: ["Perbedaan halus dalam makna atau warna.", "A subtle difference in meaning or colour.", "Diferencia sutil de sentido o color."], ex: ["C'è una sfumatura ironica.", "Ada nuansa ironi di situ.", "There's an ironic nuance.", "Hay un matiz irónico."] },
  { w: "affrontare", pos: "v", cefr: "C1", ipa: "af.fronˈta.re", g: ["menghadapi, menangani", "to face, to tackle", "afrontar"], d: ["Menghadapi persoalan secara langsung.", "To deal with a problem head-on.", "Enfrentar un problema de frente."], ex: ["Bisogna affrontare il tema con calma.", "Topik itu harus dihadapi dengan tenang.", "The issue must be tackled calmly.", "Hay que afrontar el tema con calma."] },
  { w: "favorire", pos: "v", cefr: "C1", ipa: "fa.voˈri.re", g: ["mendorong, memihak", "to promote, to favour", "favorecer"], d: ["Membuat sesuatu lebih mungkin terjadi.", "To make something more likely.", "Hacer más probable algo."], ex: ["La legge favorisce il riciclo.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley favorece el reciclaje."] },
  { w: "riflettere", pos: "v", cefr: "C1", ipa: "riˈflɛt.te.re", g: ["mencerminkan; merenung", "to reflect; to ponder", "reflejar; reflexionar"], d: ["Menunjukkan keadaan lain; juga berpikir dalam-dalam.", "To show another state; also to think deeply.", "Mostrar otra realidad; también meditar."], ex: ["I dati riflettono un miglioramento.", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "minuzioso", pos: "adj", cefr: "C1", ipa: "mi.nutˈtsjo.zo", g: ["teliti, cermat", "meticulous", "minucioso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["Ha fatto un'analisi minuziosa.", "Dia membuat analisis yang teliti.", "He did a meticulous analysis.", "Hizo un análisis minucioso."] },
  { w: "ciononostante", pos: "conj", cefr: "C1", ipa: "tʃo.no.nosˈtan.te", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Ciononostante, la proposta resta valida.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "al fine di", pos: "prep", cefr: "C1", ipa: "al ˈfi.ne di", g: ["demi, agar", "in order to", "a fin de"], d: ["Menyatakan tujuan secara formal.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["Al fine di risparmiare tempo, semplifichiamo.", "Demi menghemat waktu, mari sederhanakan.", "In order to save time, let's simplify.", "A fin de ahorrar tiempo, simplifiquemos."] },
  { w: "consolidare", pos: "v", cefr: "C1", ipa: "kon.so.liˈda.re", g: ["memperkukuh", "to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["L'azienda ha consolidato la sua posizione.", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "portata", pos: "n", cefr: "C1", gen: "f", ipa: "porˈta.ta", g: ["jangkauan; hidangan", "scope; course (of a meal)", "alcance; plato"], d: ["Seberapa jauh dampak sesuatu; juga sajian dalam menu.", "How far something reaches; also a course at table.", "Hasta dónde llega algo; también un plato."], ex: ["Una decisione di ampia portata.", "Keputusan berjangkauan luas.", "A decision of wide scope.", "Una decisión de gran alcance."] },
  { w: "mettere in luce", pos: "phr", cefr: "C1", ipa: "ˈmet.te.re in ˈlu.tʃe", g: ["menyoroti", "to bring to light, to highlight", "poner de relieve"], d: ["Membuat sesuatu terlihat dan diperhatikan.", "To make something visible and noticed.", "Hacer visible algo."], ex: ["Lo studio mette in luce un rischio.", "Kajian itu menyoroti sebuah risiko.", "The study brings a risk to light.", "El estudio pone de relieve un riesgo."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "paradigma", pos: "n", cefr: "C2", gen: "m", ipa: "pa.raˈdiɡ.ma", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Fu un cambio di paradigma.", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "eludere", pos: "v", cefr: "C2", ipa: "eˈlu.de.re", g: ["mengelak", "to evade, to sidestep", "eludir"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto sin afrontarlo."], ex: ["Ha eluso la domanda.", "Dia mengelak dari pertanyaan itu.", "He sidestepped the question.", "Eludió la pregunta."] },
  { w: "delucidare", pos: "v", cefr: "C2", ipa: "de.lu.tʃiˈda.re", g: ["menjernihkan", "to elucidate", "dilucidar"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Resta da delucidare chi ha deciso.", "Masih harus dijernihkan siapa yang memutuskan.", "It remains to be elucidated who decided.", "Queda por dilucidar quién decidió."] },
  { w: "ineffabile", pos: "adj", cefr: "C2", ipa: "i.nefˈfa.bi.le", g: ["tak terlukiskan", "ineffable", "inefable"], d: ["Terlalu besar atau indah untuk dikatakan.", "Too great or beautiful for words.", "Demasiado grande o bello para expresarse."], ex: ["Provò una gioia ineffabile.", "Dia merasakan sukacita tak terlukiskan.", "She felt an ineffable joy.", "Sintió una alegría inefable."] },
  { w: "perentorio", pos: "adj", cefr: "C2", ipa: "pe.renˈtɔ.rjo", g: ["mendesak, mutlak", "peremptory", "perentorio"], d: ["Harus dipenuhi segera tanpa penundaan.", "Requiring immediate compliance.", "Que no admite demora."], ex: ["Il termine è perentorio.", "Tenggatnya mutlak.", "The deadline is peremptory.", "El plazo es perentorio."] },
  { w: "barlume", pos: "n", cefr: "C2", gen: "m", ipa: "barˈlu.me", g: ["secercah", "glimmer", "destello"], d: ["Cahaya lemah; kiasan untuk tanda kecil harapan.", "A faint light; figuratively a small sign of hope.", "Luz tenue; indicio de esperanza."], ex: ["Non c'è un barlume di dubbio.", "Tak ada secercah keraguan.", "There isn't a glimmer of doubt.", "No hay un destello de duda."] },
  { w: "pregiudizio", pos: "n", cefr: "C2", gen: "m", ipa: "pre.dʒuˈdit.tsjo", g: ["prasangka, bias", "prejudice, bias", "prejuicio"], d: ["Penilaian yang dibuat sebelum mengetahui fakta.", "A judgement made before knowing the facts.", "Juicio previo al conocimiento de los hechos."], ex: ["Lo studio mostra un pregiudizio evidente.", "Kajian itu menunjukkan bias yang jelas.", "The study shows an obvious bias.", "El estudio muestra un sesgo evidente."] },
  { w: "sminuire", pos: "v", cefr: "C2", ipa: "zmi.nuˈi.re", g: ["merendahkan, mengurangi", "to belittle, to diminish", "menoscabar"], d: ["Membuat nilai sesuatu tampak lebih kecil.", "To make something seem less valuable.", "Hacer que algo parezca menos valioso."], ex: ["Non voglio sminuire il suo lavoro.", "Saya tak ingin merendahkan kerjanya.", "I don't want to belittle his work.", "No quiero menoscabar su trabajo."] },
  { w: "pietra miliare", pos: "n", cefr: "C2", gen: "f", ipa: "ˈpjɛ.tra miˈlja.re", g: ["tonggak sejarah", "milestone", "hito"], d: ["Peristiwa yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["L'accordo è una pietra miliare.", "Kesepakatan itu tonggak sejarah.", "The agreement is a milestone.", "El acuerdo es un hito."] },
  { w: "ineludibile", pos: "adj", cefr: "C2", ipa: "i.ne.luˈdi.bi.le", g: ["tak terhindarkan", "inescapable", "ineludible"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["È un dovere ineludibile.", "Itu kewajiban tak terhindarkan.", "It's an inescapable duty.", "Es un deber ineludible."] },
  { w: "chimera", pos: "n", cefr: "C2", gen: "f", ipa: "kiˈmɛ.ra", g: ["angan kosong", "chimera, pipe dream", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Quella promessa è una chimera.", "Janji itu angan kosong.", "That promise is a pipe dream.", "Esa promesa es una quimera."] },
  { w: "alla luce di", pos: "phr", cefr: "C2", ipa: "ˈal.la ˈlu.tʃe di", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["Alla luce dei risultati, è un successo.", "Berdasarkan hasilnya, ini sukses.", "In the light of the results, it's a success.", "A la luz de los resultados, es un éxito."] },
];
