/* =========================================================================
   lexicon/ja.js — 辞書: 日本語 (Japanese). Front matter + 72 headwords, A1→C2.
   Entri diurutkan menurut romaji (seperti indeks rōmaji di kamus cetak).
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Jepang memakai tiga sistem tulisan sekaligus: hiragana untuk tata bahasa, katakana untuk kata serapan, dan kanji untuk akar makna. Ketiganya bercampur dalam satu kalimat yang sama.",
    "Japanese uses three writing systems at once: hiragana for grammar, katakana for loanwords, kanji for meaning-roots. All three mix inside a single sentence.",
    "El japonés usa tres sistemas a la vez: hiragana para la gramática, katakana para préstamos y kanji para las raíces de significado.",
  ],
  script: [
    "Hiragana dan katakana masing-masing 46 tanda dasar dan bisa dikuasai dalam hitungan hari; kanji dipelajari seumur hidup — 2.136 karakter dipakai dalam tulisan umum.",
    "Hiragana and katakana have 46 basic signs each and can be learned in days; kanji is a lifelong project — 2,136 characters are used in general writing.",
    "El hiragana y el katakana tienen 46 signos cada uno; el kanji es tarea de por vida: 2.136 caracteres de uso general.",
  ],
  pron: [
    ["vokal panjang", "おばさん (bibi) ≠ おばあさん (nenek) — panjang vokal membedakan arti.", "おばさん (aunt) ≠ おばあさん (grandmother) — vowel length changes the word.", "おばさん (tía) ≠ おばあさん (abuela): la duración cambia la palabra."],
    ["っ (sokuon)", "Menggandakan konsonan berikutnya dengan jeda: きって (kitte).", "It doubles the next consonant with a short pause: きって (kitte).", "Duplica la consonante siguiente con una pausa: きって."],
    ["ん", "Suku kata tersendiri; bunyinya menyesuaikan huruf sesudahnya.", "A syllable of its own; its sound adapts to the letter after it.", "Es una sílaba propia; su sonido se adapta a la letra siguiente."],
    ["r", "Antara r, l, dan d — lidah menyentuh langit-langit sekilas: ら行.", "Between r, l and d — the tongue taps the palate once: ら行.", "Entre r, l y d: la lengua toca el paladar una vez."],
    ["nada tinggi-rendah", "はし bisa berarti jembatan, sumpit, atau tepi tergantung nadanya.", "はし can mean bridge, chopsticks or edge depending on pitch.", "はし puede ser puente, palillos o borde según el tono."],
    ["u yang luruh", "u dan i sering nyaris hilang: です → 'des', 好き → 'ski'.", "u and i often nearly vanish: です → 'des', 好き → 'ski'.", "u e i casi desaparecen: です → 'des', 好き → 'ski'."],
  ],
  grammar: [
    {
      t: ["Kata kerja di akhir", "The verb comes last", "El verbo va al final"],
      d: ["Urutannya Subjek–Objek–Kata kerja; seluruh isi kalimat menunggu kata kerjanya.", "The order is Subject–Object–Verb; the whole sentence waits for the verb.", "El orden es sujeto–objeto–verbo."],
      ex: "私はご飯を食べます。",
    },
    {
      t: ["Partikel penanda", "Particles mark the role", "Las partículas marcan la función"],
      d: ["は menandai topik, が subjek, を objek, に arah/waktu, で tempat kegiatan.", "は marks the topic, が the subject, を the object, に direction/time, で the place of an action.", "は marca el tema, が el sujeto, を el objeto, に dirección, で lugar."],
      ex: "私は駅で友達に会います。",
    },
    {
      t: ["Tingkat kesopanan", "Politeness levels", "Niveles de cortesía"],
      d: ["Bentuk biasa (食べる), sopan (食べます), dan hormat (召し上がる) dipilih menurut lawan bicara.", "Plain (食べる), polite (食べます) and honorific (召し上がる) are chosen by who you speak to.", "Llano (食べる), cortés (食べます) y honorífico (召し上がる)."],
      ex: "食べる · 食べます · 召し上がる",
    },
    {
      t: ["Kata penggolong", "Counters", "Contadores"],
      d: ["Angka memerlukan penggolong yang cocok dengan bentuk benda: 一本, 二枚, 三人.", "Numbers need a counter matched to the object's shape: 一本, 二枚, 三人.", "Los números requieren contador según la forma: 一本, 二枚, 三人."],
      ex: "鉛筆二本 · 紙三枚 · 学生五人",
    },
    {
      t: ["Subjek sering dihilangkan", "The subject is often dropped", "El sujeto suele omitirse"],
      d: ["Bila sudah jelas dari konteks, pelaku tidak disebutkan sama sekali.", "When context makes it clear, the actor is simply left out.", "Si el contexto lo aclara, el actor se omite."],
      ex: "（私は）行きます。",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "ある", r: "aru", pos: "v", cefr: "A1", g: ["ada (benda mati)", "there is (inanimate)", "haber (inanimado)"], d: ["Menyatakan keberadaan benda tak bernyawa.", "States that an inanimate thing exists.", "Indica la existencia de algo inanimado."], ex: ["机の上に本があります。", "Di atas meja ada buku.", "There's a book on the desk.", "Hay un libro sobre la mesa."], note: ["Untuk makhluk hidup dipakai いる, bukan ある.", "For living things use いる, not ある.", "Para seres vivos se usa いる, no ある."] },
  { w: "大きい", r: "ookii", pos: "adj", cefr: "A1", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["大きい町に住んでいます。", "Saya tinggal di kota besar.", "I live in a big town.", "Vivo en una ciudad grande."], ant: ["小さい"] },
  { w: "家", r: "ie", pos: "n", cefr: "A1", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["家は公園の近くです。", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "行く", r: "iku", pos: "v", cefr: "A1", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["市場へ行きます。", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."], ant: ["来る"] },
  { w: "いい", r: "ii", pos: "adj", cefr: "A1", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["それはいい考えです。", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], note: ["Bentuk lampaunya tak beraturan: よかった, bukan 'いかった'.", "The past is irregular: よかった, never 'いかった'.", "El pasado es irregular: よかった."] },
  { w: "小さい", r: "chiisai", pos: "adj", cefr: "A1", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["小さいアパートです。", "Ini apartemen kecil.", "It's a small flat.", "Es un piso pequeño."], ant: ["大きい"] },
  { w: "来る", r: "kuru", pos: "v", cefr: "A1", g: ["datang", "to come", "venir"], d: ["Bergerak mendekat ke tempat pembicara.", "To move towards the speaker.", "Moverse hacia el hablante."], ex: ["友達が家に来ました。", "Teman saya datang ke rumah.", "A friend came to my house.", "Un amigo vino a casa."], ant: ["行く"] },
  { w: "見る", r: "miru", pos: "v", cefr: "A1", g: ["melihat, menonton", "to see, to watch", "ver, mirar"], d: ["Menangkap sesuatu dengan mata.", "To perceive something with the eyes.", "Percibir algo con los ojos."], ex: ["昨日映画を見ました。", "Kemarin saya menonton film.", "I watched a film yesterday.", "Ayer vi una película."] },
  { w: "水", r: "mizu", pos: "n", cefr: "A1", g: ["air (dingin)", "water (cold)", "agua"], d: ["Cairan bening yang diminum; air panas disebut お湯.", "The clear liquid we drink; hot water is お湯.", "Líquido transparente que se bebe; el agua caliente es お湯."], ex: ["お水をください。", "Tolong air minumnya.", "Water, please.", "Agua, por favor."] },
  { w: "人", r: "hito", pos: "n", cefr: "A1", g: ["orang", "person", "persona"], d: ["Satu manusia.", "A single human being.", "Un ser humano."], ex: ["あの人は先生です。", "Orang itu seorang guru.", "That person is a teacher.", "Esa persona es profesora."] },
  { w: "食べる", r: "taberu", pos: "v", cefr: "A1", g: ["makan", "to eat", "comer"], d: ["Memasukkan makanan ke mulut.", "To take food into the mouth.", "Tomar alimento."], ex: ["朝ご飯を食べました。", "Saya sudah sarapan.", "I ate breakfast.", "Desayuné."] },
  { w: "友達", r: "tomodachi", pos: "n", cefr: "A1", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["友達と出かけます。", "Saya keluar dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "始める", r: "hajimeru", pos: "v", cefr: "A2", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["映画は八時に始まります。", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "速い", r: "hayai", pos: "adj", cefr: "A2", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["電車のほうが速いです。", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["遅い"] },
  { w: "必要", r: "hitsuyou", pos: "adj", cefr: "A2", g: ["perlu, dibutuhkan", "necessary", "necesario"], d: ["Yang diperlukan agar sesuatu berjalan.", "What is required for something to work.", "Lo que hace falta para algo."], ex: ["休みが必要です。", "Saya perlu istirahat.", "I need a rest.", "Necesito descansar."] },
  { w: "いつも", r: "itsumo", pos: "adv", cefr: "A2", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["いつも家で朝ご飯を食べます。", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },
  { w: "時間", r: "jikan", pos: "n", cefr: "A2", g: ["waktu; jam", "time; hour", "tiempo; hora"], d: ["Waktu yang berjalan; juga satuan jam.", "Passing time; also the unit 'hour'.", "El tiempo; también la hora."], ex: ["今日は時間がありません。", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "簡単", r: "kantan", pos: "adj", cefr: "A2", g: ["mudah, sederhana", "easy, simple", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["試験は簡単でした。", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["難しい"] },
  { w: "から", r: "kara", pos: "conj", cefr: "A2", g: ["karena; dari", "because; from", "porque; desde"], d: ["Menyatakan sebab; juga menandai titik awal.", "Introduces a reason; also marks a starting point.", "Introduce la causa; también el punto de partida."], ex: ["雨だから家にいます。", "Karena hujan, saya di rumah.", "I'm home because it's raining.", "Como llueve, me quedo en casa."] },
  { w: "町", r: "machi", pos: "n", cefr: "A2", g: ["kota kecil", "town", "pueblo, ciudad"], d: ["Permukiman; lebih kecil daripada 市 (kota besar).", "A settlement, smaller than a 市 (city).", "Población, menor que una 市."], ex: ["静かな町ですね。", "Kota yang tenang, ya.", "It's a quiet town.", "Es un pueblo tranquilo."] },
  { w: "難しい", r: "muzukashii", pos: "adj", cefr: "A2", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["ここに駐車するのは難しいです。", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["簡単"] },
  { w: "お金", r: "okane", pos: "n", cefr: "A2", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["お金が足りません。", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "仕事", r: "shigoto", pos: "n", cefr: "A2", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["仕事は九時に始まります。", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "手伝う", r: "tetsudau", pos: "v", cefr: "A2", g: ["membantu", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["手伝ってくれますか。", "Bisakah kamu membantu saya?", "Could you help me?", "¿Podrías ayudarme?"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "アドバイス", r: "adobaisu", pos: "n", cefr: "B1", g: ["nasihat, saran", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["アドバイスをいただけますか。", "Boleh minta saran?", "Could I have some advice?", "¿Me daría un consejo?"], note: ["Serapan Inggris; padanan aslinya 助言 (jogen), lebih formal.", "An English loan; the native 助言 (jogen) is more formal.", "Préstamo del inglés; 助言 es más formal."] },
  { w: "改善する", r: "kaizen suru", pos: "v", cefr: "B1", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik sedikit demi sedikit.", "To make something better, step by step.", "Mejorar algo paso a paso."], ex: ["発音を改善したいです。", "Saya ingin memperbaiki pelafalan.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "けれども", r: "keredomo", pos: "conj", cefr: "B1", g: ["meskipun, tetapi", "although, but", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["高いけれども、買います。", "Mahal, tetapi saya beli.", "It's expensive, but I'll buy it.", "Es caro, pero lo compro."] },
  { w: "機会", r: "kikai", pos: "n", cefr: "B1", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["いい機会ですね。", "Ini kesempatan yang bagus.", "It's a good opportunity.", "Es una buena oportunidad."] },
  { w: "決める", r: "kimeru", pos: "v", cefr: "B1", g: ["memutuskan", "to decide", "decidir"], d: ["Menetapkan pilihan setelah berpikir.", "To settle on a choice after thinking.", "Tomar una decisión tras pensar."], ex: ["まだ決めていません。", "Saya belum memutuskan.", "I haven't decided yet.", "Todavía no lo he decidido."] },
  { w: "気がする", r: "ki ga suru", pos: "v", cefr: "B1", g: ["merasa, tampaknya", "to have a feeling that", "tener la impresión"], d: ["Merasa bahwa sesuatu tampaknya begitu.", "To feel that something seems to be so.", "Tener la sensación de que algo es así."], ex: ["彼は疲れている気がします。", "Sepertinya dia lelah.", "I get the feeling he's tired.", "Tengo la impresión de que está cansado."] },
  { w: "経験", r: "keiken", pos: "n", cefr: "B1", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["彼女は経験が豊富です。", "Dia sangat berpengalaman.", "She has rich experience.", "Tiene mucha experiencia."] },
  { w: "慣れる", r: "nareru", pos: "v", cefr: "B1", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["こちらの生活に慣れました。", "Saya sudah terbiasa dengan kehidupan di sini.", "I've got used to life here.", "Ya me acostumbré a la vida aquí."] },
  { w: "懐かしい", r: "natsukashii", pos: "adj", cefr: "B1", g: ["mengharukan karena kenangan", "nostalgic, dearly missed", "nostálgico"], d: ["Menimbulkan rindu manis pada masa lalu.", "Stirring a warm longing for the past.", "Que despierta añoranza del pasado."], ex: ["この歌は懐かしいです。", "Lagu ini membangkitkan kenangan.", "This song brings back memories.", "Esta canción me trae recuerdos."], note: ["Rasa 'rindu masa lalu' ini tidak punya padanan satu kata dalam banyak bahasa.", "This feeling of fond nostalgia has no one-word equivalent in many languages.", "Este sentimiento nostálgico no tiene equivalente de una palabra."] },
  { w: "しかし", r: "shikashi", pos: "conj", cefr: "B1", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["しかし、結論は違いました。", "Namun, kesimpulannya berbeda.", "However, the conclusion was different.", "Sin embargo, la conclusión fue distinta."] },
  { w: "成功する", r: "seikou suru", pos: "v", cefr: "B1", g: ["berhasil", "to succeed", "tener éxito"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["計画は成功しました。", "Rencananya berhasil.", "The plan succeeded.", "El plan tuvo éxito."], ant: ["失敗する"] },
  { w: "たぶん", r: "tabun", pos: "adv", cefr: "B1", g: ["mungkin", "maybe, probably", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["たぶん明日来ます。", "Mungkin dia datang besok.", "He'll probably come tomorrow.", "Probablemente venga mañana."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "合意", r: "goui", pos: "n", cefr: "B2", g: ["kesepakatan", "agreement, consensus", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["両者は合意に達しました。", "Kedua pihak mencapai kesepakatan.", "The two sides reached an agreement.", "Ambas partes llegaron a un acuerdo."] },
  { w: "発展", r: "hatten", pos: "n", cefr: "B2", g: ["perkembangan", "development, growth", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["経済の発展が続いています。", "Perkembangan ekonominya berlanjut.", "Economic development continues.", "El desarrollo económico continúa."] },
  { w: "必要不可欠", r: "hitsuyou fukaketsu", pos: "adj", cefr: "B2", g: ["mutlak perlu", "indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["パスポートは必要不可欠です。", "Paspor mutlak diperlukan.", "A passport is indispensable.", "El pasaporte es imprescindible."] },
  { w: "実施する", r: "jisshi suru", pos: "v", cefr: "B2", g: ["melaksanakan", "to carry out, to implement", "llevar a cabo"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["来月、新制度を実施します。", "Bulan depan sistem baru dilaksanakan.", "We'll implement the new system next month.", "Aplicaremos el nuevo sistema el mes próximo."] },
  { w: "課題", r: "kadai", pos: "n", cefr: "B2", g: ["tantangan, tugas", "challenge, task", "reto, tarea"], d: ["Persoalan yang harus diselesaikan.", "A problem that has to be worked on.", "Problema que hay que resolver."], ex: ["これは大きな課題です。", "Ini tantangan yang besar.", "This is a big challenge.", "Es un gran reto."] },
  { w: "環境", r: "kankyou", pos: "n", cefr: "B2", g: ["lingkungan", "environment", "medio ambiente"], d: ["Alam sekitar; juga lingkungan kerja.", "The natural surroundings; also a work setting.", "Entorno natural; también ambiente laboral."], ex: ["環境を守らなければなりません。", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "強調する", r: "kyouchou suru", pos: "v", cefr: "B2", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["安全を強調しました。", "Dia menekankan keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "問題", r: "mondai", pos: "n", cefr: "B2", g: ["masalah; soal", "problem; question", "problema"], d: ["Hal yang menyulitkan; juga soal ujian.", "Something difficult; also an exam question.", "Algo difícil; también una pregunta."], ex: ["これは微妙な問題です。", "Ini persoalan yang peka.", "This is a delicate problem.", "Es un asunto delicado."] },
  { w: "にもかかわらず", r: "nimo kakawarazu", pos: "conj", cefr: "B2", g: ["meskipun begitu", "despite, in spite of", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["寒さにもかかわらず出かけました。", "Meski dingin, kami keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "したがって", r: "shitagatte", pos: "conj", cefr: "B2", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai kesimpulan logis dalam gaya tulis.", "Marks a logical conclusion in written register.", "Marca una conclusión lógica en registro escrito."], ex: ["雨でした。したがって中止しました。", "Hujan. Oleh karena itu dibatalkan.", "It rained; therefore it was cancelled.", "Llovió; por lo tanto se canceló."] },
  { w: "信頼できる", r: "shinrai dekiru", pos: "adj", cefr: "B2", g: ["dapat dipercaya", "reliable, trustworthy", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["信頼できる情報源です。", "Ini sumber yang bisa dipercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "達成する", r: "tassei suru", pos: "v", cefr: "B2", g: ["mencapai", "to achieve, to attain", "alcanzar"], d: ["Sampai pada tujuan setelah berusaha.", "To reach a goal after effort.", "Alcanzar una meta tras esfuerzo."], ex: ["目標を達成しました。", "Kami mencapai targetnya.", "We achieved the target.", "Alcanzamos el objetivo."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "アプローチ", r: "apuroochi", pos: "n", cefr: "C1", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["別のアプローチが必要です。", "Kita butuh pendekatan lain.", "A different approach is needed.", "Hace falta otro enfoque."] },
  { w: "分野", r: "bunya", pos: "n", cefr: "C1", g: ["bidang", "field, domain", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["法律の分野では事情が違います。", "Dalam bidang hukum keadaannya berbeda.", "In the legal field things differ.", "En el ámbito jurídico es distinto."] },
  { w: "範囲", r: "han'i", pos: "n", cefr: "C1", g: ["cakupan, lingkup", "scope, range", "alcance"], d: ["Seberapa luas sesuatu berlaku.", "How far something extends.", "Hasta dónde llega algo."], ex: ["この決定の範囲は広いです。", "Cakupan keputusan ini luas.", "The scope of this decision is wide.", "El alcance de esta decisión es amplio."] },
  { w: "反映する", r: "han'ei suru", pos: "v", cefr: "C1", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["数字は改善を反映しています。", "Angkanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "際立たせる", r: "kiwadataseru", pos: "v", cefr: "C1", g: ["menonjolkan", "to make stand out, to highlight", "hacer destacar"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["報告書はリスクを際立たせています。", "Laporan itu menonjolkan risikonya.", "The report makes the risks stand out.", "El informe hace destacar los riesgos."] },
  { w: "強化する", r: "kyouka suru", pos: "v", cefr: "C1", g: ["memperkukuh", "to strengthen, to reinforce", "reforzar"], d: ["Membuat sesuatu makin kuat dan mantap.", "To make something stronger and firmer.", "Hacer algo más fuerte y firme."], ex: ["会社は立場を強化しました。", "Perusahaan memperkukuh posisinya.", "The company strengthened its position.", "La empresa reforzó su posición."] },
  { w: "綿密", r: "menmitsu", pos: "adj", cefr: "C1", g: ["teliti, saksama", "meticulous, detailed", "minucioso"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest detail.", "Hecho hasta el último detalle."], ex: ["綿密な分析が必要です。", "Diperlukan analisis yang saksama.", "A meticulous analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "ニュアンス", r: "nyuansu", pos: "n", cefr: "C1", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["訳すとニュアンスが失われます。", "Kalau diterjemahkan, nuansanya hilang.", "Translation loses the nuance.", "Al traducir se pierde el matiz."] },
  { w: "促進する", r: "sokushin suru", pos: "v", cefr: "C1", g: ["mendorong, memacu", "to promote, to accelerate", "fomentar"], d: ["Membuat sesuatu berjalan lebih cepat atau tumbuh.", "To make something move faster or grow.", "Hacer que algo avance o crezca."], ex: ["法律はリサイクルを促進します。", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "ために", r: "tame ni", pos: "conj", cefr: "C1", g: ["agar, demi", "in order to, for the sake of", "para"], d: ["Menyatakan tujuan dari suatu tindakan.", "States the purpose of an action.", "Expresa la finalidad de una acción."], ex: ["時間を節約するために簡略化しました。", "Demi menghemat waktu, kami sederhanakan.", "We simplified it in order to save time.", "Lo simplificamos para ahorrar tiempo."] },
  { w: "取り組む", r: "torikumu", pos: "v", cefr: "C1", g: ["menggarap, menangani", "to tackle, to work on", "abordar"], d: ["Menghadapi persoalan dengan sungguh-sungguh.", "To take a problem on in earnest.", "Afrontar un problema con seriedad."], ex: ["この課題に取り組んでいます。", "Kami sedang menggarap persoalan ini.", "We're tackling this challenge.", "Estamos abordando este reto."] },
  { w: "とはいえ", r: "to wa ie", pos: "conj", cefr: "C1", g: ["walaupun demikian", "that said, nonetheless", "dicho esto"], d: ["Membatasi pernyataan sebelumnya secara halus.", "Softly qualifies what was just said.", "Matiza con suavidad lo dicho."], ex: ["とはいえ、提案は有効です。", "Walaupun demikian, usulan itu tetap berlaku.", "That said, the proposal stands.", "Dicho esto, la propuesta sigue vigente."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "ドア", r: "doa", pos: "n", cefr: "A1", g: ["pintu", "door", "puerta"] },
  { w: "窓", r: "mado", pos: "n", cefr: "A1", g: ["jendela", "window", "ventana"] },
  { w: "部屋", r: "heya", pos: "n", cefr: "A1", g: ["kamar, ruangan", "room", "habitación"] },
  { w: "机", r: "tsukue", pos: "n", cefr: "A1", g: ["meja tulis", "desk", "escritorio"] },
  { w: "椅子", r: "isu", pos: "n", cefr: "A1", g: ["kursi", "chair", "silla"] },
  { w: "ベッド", r: "beddo", pos: "n", cefr: "A1", g: ["tempat tidur", "bed", "cama"] },
  { w: "台所", r: "daidokoro", pos: "n", cefr: "A1", g: ["dapur", "kitchen", "cocina"] },
  { w: "風呂", r: "furo", pos: "n", cefr: "A1", g: ["kamar mandi, bak mandi", "bath, bathroom", "baño"] },
  { w: "電気", r: "denki", pos: "n", cefr: "A1", g: ["lampu; listrik", "light; electricity", "luz; electricidad"] },
  { w: "鍵", r: "kagi", pos: "n", cefr: "A1", g: ["kunci", "key", "llave"] },
  { w: "壁", r: "kabe", pos: "n", cefr: "A1", g: ["dinding", "wall", "pared"] },
  { w: "屋根", r: "yane", pos: "n", cefr: "A1", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "パン", r: "pan", pos: "n", cefr: "A1", g: ["roti", "bread", "pan"], note: ["Dari bahasa Portugis pão, bukan dari bahasa Inggris.", "From Portuguese pão, not from English.", "Del portugués pão, no del inglés."] },
  { w: "ご飯", r: "gohan", pos: "n", cefr: "A1", g: ["nasi; makanan", "cooked rice; a meal", "arroz; comida"] },
  { w: "肉", r: "niku", pos: "n", cefr: "A1", g: ["daging", "meat", "carne"] },
  { w: "魚", r: "sakana", pos: "n", cefr: "A1", g: ["ikan", "fish", "pescado"] },
  { w: "卵", r: "tamago", pos: "n", cefr: "A1", g: ["telur", "egg", "huevo"] },
  { w: "牛乳", r: "gyuunyuu", pos: "n", cefr: "A1", g: ["susu sapi", "milk", "leche"] },
  { w: "お茶", r: "ocha", pos: "n", cefr: "A1", g: ["teh", "tea", "té"] },
  { w: "コーヒー", r: "koohii", pos: "n", cefr: "A1", g: ["kopi", "coffee", "café"] },
  { w: "砂糖", r: "satou", pos: "n", cefr: "A1", g: ["gula", "sugar", "azúcar"] },
  { w: "塩", r: "shio", pos: "n", cefr: "A1", g: ["garam", "salt", "sal"] },
  { w: "果物", r: "kudamono", pos: "n", cefr: "A1", g: ["buah", "fruit", "fruta"] },
  { w: "野菜", r: "yasai", pos: "n", cefr: "A1", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "シャツ", r: "shatsu", pos: "n", cefr: "A2", g: ["kemeja", "shirt", "camisa"] },
  { w: "ズボン", r: "zubon", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalón"] },
  { w: "靴", r: "kutsu", pos: "n", cefr: "A2", g: ["sepatu", "shoe", "zapato"] },
  { w: "帽子", r: "boushi", pos: "n", cefr: "A2", g: ["topi", "hat", "sombrero"] },
  { w: "手", r: "te", pos: "n", cefr: "A2", g: ["tangan", "hand", "mano"] },
  { w: "目", r: "me", pos: "n", cefr: "A2", g: ["mata", "eye", "ojo"] },
  { w: "頭", r: "atama", pos: "n", cefr: "A2", g: ["kepala", "head", "cabeza"] },
  { w: "心臓", r: "shinzou", pos: "n", cefr: "A2", g: ["jantung", "heart (organ)", "corazón"] },
  { w: "髪", r: "kami", pos: "n", cefr: "A2", g: ["rambut", "hair", "cabello"] },
  { w: "歯", r: "ha", pos: "n", cefr: "A2", g: ["gigi", "tooth", "diente"] },
  { w: "耳", r: "mimi", pos: "n", cefr: "A2", g: ["telinga", "ear", "oreja"] },
  { w: "顔", r: "kao", pos: "n", cefr: "A2", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "木", r: "ki", pos: "n", cefr: "A2", g: ["pohon; kayu", "tree; wood", "árbol; madera"] },
  { w: "花", r: "hana", pos: "n", cefr: "A2", g: ["bunga", "flower", "flor"] },
  { w: "山", r: "yama", pos: "n", cefr: "A2", g: ["gunung", "mountain", "montaña"] },
  { w: "川", r: "kawa", pos: "n", cefr: "A2", g: ["sungai", "river", "río"] },
  { w: "海", r: "umi", pos: "n", cefr: "A2", g: ["laut", "sea", "mar"] },
  { w: "空", r: "sora", pos: "n", cefr: "A2", g: ["langit", "sky", "cielo"] },
  { w: "星", r: "hoshi", pos: "n", cefr: "A2", g: ["bintang", "star", "estrella"] },
  { w: "犬", r: "inu", pos: "n", cefr: "A2", g: ["anjing", "dog", "perro"] },
  { w: "猫", r: "neko", pos: "n", cefr: "A2", g: ["kucing", "cat", "gato"] },
  { w: "鳥", r: "tori", pos: "n", cefr: "A2", g: ["burung", "bird", "pájaro"] },
  { w: "馬", r: "uma", pos: "n", cefr: "A2", g: ["kuda", "horse", "caballo"] },
  { w: "雨", r: "ame", pos: "n", cefr: "A2", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "道", r: "michi", pos: "n", cefr: "B1", g: ["jalan", "road, way", "camino"] },
  { w: "橋", r: "hashi", pos: "n", cefr: "B1", g: ["jembatan", "bridge", "puente"] },
  { w: "市場", r: "ichiba", pos: "n", cefr: "B1", g: ["pasar", "market", "mercado"] },
  { w: "学校", r: "gakkou", pos: "n", cefr: "B1", g: ["sekolah", "school", "escuela"] },
  { w: "病院", r: "byouin", pos: "n", cefr: "B1", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "事務所", r: "jimusho", pos: "n", cefr: "B1", g: ["kantor", "office", "oficina"] },
  { w: "バス", r: "basu", pos: "n", cefr: "B1", g: ["bus", "bus", "autobús"] },
  { w: "電車", r: "densha", pos: "n", cefr: "B1", g: ["kereta listrik", "train", "tren"] },
  { w: "車", r: "kuruma", pos: "n", cefr: "B1", g: ["mobil", "car", "coche"] },
  { w: "自転車", r: "jitensha", pos: "n", cefr: "B1", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "空港", r: "kuukou", pos: "n", cefr: "B1", g: ["bandara", "airport", "aeropuerto"] },
  { w: "切符", r: "kippu", pos: "n", cefr: "B1", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "会社", r: "kaisha", pos: "n", cefr: "B2", g: ["perusahaan", "company", "empresa"] },
  { w: "会議", r: "kaigi", pos: "n", cefr: "B2", g: ["rapat", "meeting", "reunión"] },
  { w: "契約", r: "keiyaku", pos: "n", cefr: "B2", g: ["kontrak", "contract", "contrato"] },
  { w: "給料", r: "kyuuryou", pos: "n", cefr: "B2", g: ["gaji", "salary", "sueldo"] },
  { w: "値段", r: "nedan", pos: "n", cefr: "B2", g: ["harga", "price", "precio"] },
  { w: "税金", r: "zeikin", pos: "n", cefr: "B2", g: ["pajak", "tax", "impuesto"] },
  { w: "銀行", r: "ginkou", pos: "n", cefr: "B2", g: ["bank", "bank", "banco"] },
  { w: "パソコン", r: "pasokon", pos: "n", cefr: "B2", g: ["komputer (pribadi)", "personal computer", "ordenador"], note: ["Singkatan dari 'personal computer'.", "A clipping of 'personal computer'.", "Abreviatura de 'personal computer'."] },
  { w: "電話", r: "denwa", pos: "n", cefr: "B2", g: ["telepon", "telephone", "teléfono"] },
  { w: "メール", r: "meeru", pos: "n", cefr: "B2", g: ["surel, email", "email", "correo electrónico"] },
  { w: "ファイル", r: "fairu", pos: "n", cefr: "B2", g: ["berkas", "file", "archivo"] },
  { w: "パスワード", r: "pasuwaado", pos: "n", cefr: "B2", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "節目", r: "fushime", pos: "n", cefr: "C2", g: ["tonggak, titik balik", "milestone, turning point", "hito"], d: ["Titik penting yang menandai babak baru.", "A point that marks a new stage.", "Punto que marca una nueva etapa."], ex: ["創業十年の節目を迎えました。", "Kami mencapai tonggak sepuluh tahun.", "We reached the ten-year milestone.", "Alcanzamos el hito de los diez años."] },
  { w: "幻想", r: "gensou", pos: "n", cefr: "C2", g: ["ilusi, angan kosong", "illusion, fantasy", "ilusión"], d: ["Keyakinan indah yang ternyata semu.", "A pleasing belief that turns out false.", "Creencia agradable que resulta falsa."], ex: ["その約束は幻想にすぎません。", "Janji itu hanyalah ilusi.", "That promise is a mere illusion.", "Esa promesa es solo una ilusión."] },
  { w: "一縷の望み", r: "ichiru no nozomi", pos: "n", cefr: "C2", g: ["secercah harapan", "a sliver of hope", "un hilo de esperanza"], d: ["Harapan yang sangat tipis tetapi masih ada.", "A very thin hope that nonetheless remains.", "Esperanza muy tenue que aún persiste."], ex: ["まだ一縷の望みがあります。", "Masih ada secercah harapan.", "There's still a sliver of hope.", "Aún queda un hilo de esperanza."] },
  { w: "回避する", r: "kaihi suru", pos: "v", cefr: "C2", g: ["menghindari, mengelak", "to avoid, to evade", "eludir"], d: ["Menjauhi persoalan alih-alih menghadapinya.", "To keep away from an issue instead of facing it.", "Evitar un asunto en vez de afrontarlo."], ex: ["彼は質問を回避しました。", "Dia mengelak dari pertanyaan itu.", "He evaded the question.", "Eludió la pregunta."] },
  { w: "解明する", r: "kaimei suru", pos: "v", cefr: "C2", g: ["mengurai, menjernihkan", "to elucidate, to unravel", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["原因を解明する必要があります。", "Penyebabnya perlu diurai.", "The cause must be elucidated.", "Hay que esclarecer la causa."] },
  { w: "過小評価する", r: "kashou hyouka suru", pos: "v", cefr: "C2", g: ["meremehkan", "to underestimate", "subestimar"], d: ["Menilai sesuatu lebih rendah dari semestinya.", "To judge something as worth less than it is.", "Juzgar algo por debajo de su valor."], ex: ["彼の努力を過小評価してはいけません。", "Jangan remehkan usahanya.", "Don't underestimate his effort.", "No subestimes su esfuerzo."] },
  { w: "偏り", r: "katayori", pos: "n", cefr: "C2", g: ["kecondongan, bias", "bias, imbalance", "sesgo"], d: ["Kecenderungan menilai secara tidak berimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["調査に偏りがあります。", "Kajian itu mengandung bias.", "The survey carries a bias.", "La encuesta tiene un sesgo."] },
  { w: "喫緊", r: "kikkin", pos: "adj", cefr: "C2", g: ["sangat mendesak", "pressing, of utmost urgency", "acuciante"], d: ["Harus ditangani sekarang juga.", "Requiring attention right now.", "Que exige atención inmediata."], ex: ["これは喫緊の課題です。", "Ini persoalan yang sangat mendesak.", "This is a pressing issue.", "Es un asunto acuciante."] },
  { w: "パラダイム", r: "paradaimu", pos: "n", cefr: "C2", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["パラダイムの転換でした。", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "避けられない", r: "sakerarenai", pos: "adj", cefr: "C2", g: ["tak terhindarkan", "unavoidable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["値上げは避けられません。", "Kenaikan harga tak terhindarkan.", "The price rise is unavoidable.", "La subida es inevitable."] },
  { w: "筆舌に尽くしがたい", r: "hitsuzetsu ni tsukushigatai", pos: "phr", cefr: "C2", g: ["tak terlukiskan", "beyond words", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["筆舌に尽くしがたい喜びでした。", "Sukacita yang tak terlukiskan.", "It was a joy beyond words.", "Fue una alegría indescriptible."] },
  { w: "を踏まえて", r: "o fumaete", pos: "phr", cefr: "C2", g: ["berdasarkan, mengingat", "in the light of, based on", "a la luz de"], d: ["Menilai sesuatu dengan memperhatikan fakta tertentu.", "Judging something while taking given facts into account.", "Juzgar algo teniendo en cuenta ciertos datos."], ex: ["結果を踏まえて、成功と言えます。", "Berdasarkan hasilnya, ini bisa disebut sukses.", "In the light of the results, it's a success.", "A la luz de los resultados, es un éxito."] },
];
