/* =========================================================================
   lexicon/ko.js — 사전: 한국어 (Korean). Front matter + 96 headwords, A1→C2.
   Romanisation follows Revised Romanization (RR); entries are indexed by the
   leading jamo, i.e. 가나다순.
   ========================================================================= */
export const guide = {
  intro: [
    "Hangul (한글) diciptakan tahun 1443 dan dirancang secara ilmiah: bentuk hurufnya meniru posisi lidah dan bibir. Kamu bisa membacanya dalam satu jam — inilah pintu tercepat menuju bahasa Korea.",
    "Hangul (한글) was created in 1443 and designed scientifically: the letter shapes copy the position of tongue and lips. You can learn to read it in an hour — the fastest door into Korean.",
    "El hangul (한글) se creó en 1443 con criterio científico: las letras imitan la posición de la lengua y los labios. Se aprende a leer en una hora.",
  ],
  script: [
    "14 konsonan + 10 vokal disusun menjadi blok suku kata (한 → ㅎ+ㅏ+ㄴ). Konsonan penutup disebut batchim dan mengubah bunyi kata berikutnya.",
    "14 consonants and 10 vowels stack into syllable blocks (한 = ㅎ+ㅏ+ㄴ). The closing consonant is called batchim and reshapes the sound that follows.",
    "14 consonantes y 10 vocales se agrupan en bloques silábicos (한 = ㅎ+ㅏ+ㄴ). La consonante final (batchim) altera el sonido siguiente.",
  ],
  pron: [
    ["ㅓ vs ㅗ", "ㅓ (eo) mulut lebih terbuka, ㅗ (o) bibir bulat: 거 ≠ 고.", "ㅓ (eo) is open-mouthed, ㅗ (o) is rounded: 거 ≠ 고.", "ㅓ (eo) con boca abierta, ㅗ (o) con labios redondeados: 거 ≠ 고."],
    ["ㄲ ㄸ ㅃ ㅆ ㅉ", "Konsonan tegang: tenggorokan menegang, tanpa embusan napas — 싸다 ≠ 사다.", "Tense consonants: tight throat, no puff of air — 싸다 ≠ 사다.", "Consonantes tensas: garganta tensa, sin soplo — 싸다 ≠ 사다."],
    ["ㅋ ㅌ ㅍ ㅊ", "Konsonan beraspirasi: keluarkan embusan napas kuat — 카 vs 가.", "Aspirated consonants: release a strong puff of air — 카 vs 가.", "Consonantes aspiradas: con soplo fuerte — 카 frente a 가."],
    ["batchim", "Penutup suku kata hanya berbunyi 7 macam; ㅅ ㅈ ㅊ ㅌ semuanya jadi /t/: 옷 → ot.", "Only seven closing sounds exist; ㅅ ㅈ ㅊ ㅌ all become /t/: 옷 → ot.", "Solo hay siete finales; ㅅ ㅈ ㅊ ㅌ suenan /t/: 옷 → ot."],
    ["연음 (liaison)", "Batchim pindah ke suku berikutnya bila diawali vokal: 한국어 → 한구거.", "The batchim moves onto a following vowel: 한국어 sounds like 한구거.", "El batchim pasa a la vocal siguiente: 한국어 suena 한구거."],
    ["ㄹ", "Antara r dan l: di tengah kata seperti r, di akhir seperti l — 사랑 (sarang), 발 (bal).", "Between r and l: r inside a word, l at the end — 사랑 (sarang), 발 (bal).", "Entre r y l: r en medio, l al final — 사랑 (sarang), 발 (bal)."],
  ],
  grammar: [
    {
      t: ["Kata kerja selalu di akhir", "The verb always comes last", "El verbo va siempre al final"],
      d: ["Urutannya Subjek–Objek–Kata kerja. Kalimat baru selesai setelah kata kerjanya diucapkan.", "The order is Subject–Object–Verb; a Korean sentence is not finished until the verb arrives.", "El orden es sujeto–objeto–verbo: la frase no termina hasta el verbo."],
      ex: "저는 밥을 먹어요. (Saya · nasi · makan)",
    },
    {
      t: ["Partikel penanda peran", "Particles mark the role", "Las partículas marcan la función"],
      d: ["은/는 menandai topik, 이/가 menandai subjek, 을/를 menandai objek — karena itu urutan kata bisa lentur.", "은/는 marks the topic, 이/가 the subject, 을/를 the object — which is why word order can flex.", "은/는 marca el tema, 이/가 el sujeto, 을/를 el objeto; por eso el orden es flexible."],
      ex: "저는 학생이에요. · 커피가 좋아요. · 책을 읽어요.",
    },
    {
      t: ["Tingkat tutur", "Speech levels", "Niveles de habla"],
      d: ["Akhiran kata kerja menyatakan kesopanan: -아/어요 (santun sehari-hari), -습니다 (formal), tanpa akhiran (반말, akrab).", "The verb ending carries politeness: -아/어요 (everyday polite), -습니다 (formal), bare form (반말, intimate).", "La terminación marca la cortesía: -아/어요 (cortés), -습니다 (formal), forma llana (반말)."],
      ex: "가요 · 갑니다 · 가",
    },
    {
      t: ["Honorifik -(으)시-", "The honorific -(으)시-", "El honorífico -(으)시-"],
      d: ["Disisipkan pada kata kerja untuk menghormati pelakunya, terpisah dari kesopanan pada lawan bicara.", "Slipped into the verb to honour the *subject*, independently of politeness toward the listener.", "Se inserta en el verbo para honrar al sujeto, aparte de la cortesía hacia el oyente."],
      ex: "선생님이 오세요. (bukan 와요)",
    },
    {
      t: ["Dua cara menyangkal", "Two ways to say no", "Dos negaciones"],
      d: ["안 (tidak mau/tidak begitu) vs 못 (tidak bisa). Bentuk panjangnya -지 않다 dan -지 못하다.", "안 (do not) vs 못 (cannot). Their long forms are -지 않다 and -지 못하다.", "안 (no quiero/no es) frente a 못 (no puedo). Formas largas: -지 않다 y -지 못하다."],
      ex: "안 가요 (tidak pergi) · 못 가요 (tidak bisa pergi)",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "가다", r: "gada", pos: "v", cefr: "A1", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse hacia un lugar."], ex: ["학교에 가요.", "Saya pergi ke sekolah.", "I go to school.", "Voy a la escuela."], ant: ["오다"] },
  { w: "고맙다", r: "gomapda", pos: "adj", cefr: "A1", g: ["berterima kasih", "to be thankful", "agradecido"], d: ["Merasa berterima kasih atas kebaikan.", "Feeling grateful for a kindness.", "Sentir gratitud por un favor."], ex: ["정말 고맙습니다.", "Terima kasih banyak.", "Thank you very much.", "Muchas gracias."], syn: ["감사하다"] },
  { w: "그리고", r: "geurigo", pos: "conj", cefr: "A1", g: ["dan", "and", "y"], d: ["Menghubungkan dua hal atau dua kalimat.", "Joins two things or two sentences.", "Une dos cosas o dos frases."], ex: ["빵 그리고 우유를 샀어요.", "Saya membeli roti dan susu.", "I bought bread and milk.", "Compré pan y leche."] },
  { w: "먹다", r: "meokda", pos: "v", cefr: "A1", g: ["makan", "to eat", "comer"], d: ["Memasukkan makanan ke mulut dan menelannya.", "To take food into the mouth and swallow it.", "Tomar alimento y tragarlo."], ex: ["아침을 먹었어요.", "Saya sudah sarapan.", "I ate breakfast.", "Desayuné."] },
  { w: "물", r: "mul", pos: "n", cefr: "A1", g: ["air", "water", "agua"], d: ["Cairan bening yang diminum.", "The clear liquid people drink.", "Líquido transparente que se bebe."], ex: ["물 한 잔 주세요.", "Tolong segelas air.", "A glass of water, please.", "Un vaso de agua, por favor."] },
  { w: "밥", r: "bap", pos: "n", cefr: "A1", g: ["nasi; makanan", "cooked rice; a meal", "arroz; comida"], d: ["Nasi; secara luas berarti 'makan' itu sendiri.", "Cooked rice; by extension, a meal.", "Arroz cocido; por extensión, la comida."], ex: ["밥 먹었어요?", "Sudah makan?", "Have you eaten?", "¿Ya comiste?"], note: ["밥 먹었어요? adalah sapaan akrab, bukan sekadar pertanyaan.", "밥 먹었어요? works as a friendly greeting, not just a question.", "밥 먹었어요? funciona como saludo, no solo como pregunta."] },
  { w: "보다", r: "boda", pos: "v", cefr: "A1", g: ["melihat, menonton", "to see, to watch", "ver, mirar"], d: ["Menangkap sesuatu dengan mata.", "To perceive something with the eyes.", "Percibir algo con los ojos."], ex: ["영화를 봤어요.", "Saya menonton film.", "I watched a film.", "Vi una película."] },
  { w: "사람", r: "saram", pos: "n", cefr: "A1", g: ["orang", "person", "persona"], d: ["Satu manusia.", "A single human being.", "Un ser humano."], ex: ["좋은 사람이에요.", "Dia orang yang baik.", "He's a good person.", "Es una buena persona."] },
  { w: "작다", r: "jakda", pos: "adj", cefr: "A1", g: ["kecil", "to be small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["방이 조금 작아요.", "Kamarnya agak kecil.", "The room is a little small.", "La habitación es algo pequeña."], ant: ["크다"] },
  { w: "오늘", r: "oneul", pos: "n", cefr: "A1", g: ["hari ini", "today", "hoy"], d: ["Hari yang sedang berlangsung.", "The day that is happening now.", "El día en curso."], ex: ["오늘 날씨가 좋아요.", "Cuaca hari ini bagus.", "The weather is nice today.", "Hoy hace buen tiempo."] },
  { w: "오다", r: "oda", pos: "v", cefr: "A1", g: ["datang", "to come", "venir"], d: ["Bergerak mendekat ke tempat pembicara.", "To move towards the speaker.", "Moverse hacia el hablante."], ex: ["친구가 집에 왔어요.", "Teman saya datang ke rumah.", "A friend came to my house.", "Un amigo vino a casa."], ant: ["가다"] },
  { w: "있다", r: "itda", pos: "v", cefr: "A1", g: ["ada, punya", "to exist, to have", "haber, tener"], d: ["Menyatakan keberadaan atau kepemilikan.", "States that something exists or is owned.", "Indica existencia o posesión."], ex: ["시간 있어요?", "Apakah kamu punya waktu?", "Do you have time?", "¿Tienes tiempo?"], ant: ["없다"] },
  { w: "좋다", r: "jota", pos: "adj", cefr: "A1", g: ["bagus, suka", "to be good, to be nice", "bueno, gustar"], d: ["Bermutu baik atau menyenangkan hati.", "Of good quality, or pleasing.", "De buena calidad o agradable."], ex: ["이 책이 정말 좋아요.", "Buku ini benar-benar bagus.", "This book is really good.", "Este libro es muy bueno."], ant: ["나쁘다"] },
  { w: "집", r: "jip", pos: "n", cefr: "A1", g: ["rumah", "house, home", "casa"], d: ["Tempat tinggal seseorang.", "The place where someone lives.", "Lugar donde se vive."], ex: ["집에 가고 싶어요.", "Saya ingin pulang.", "I want to go home.", "Quiero ir a casa."] },
  { w: "친구", r: "chingu", pos: "n", cefr: "A1", g: ["teman", "friend", "amigo"], d: ["Orang seusia yang dekat denganmu.", "Someone close to you, usually of the same age.", "Persona cercana, normalmente de la misma edad."], ex: ["친구를 만났어요.", "Saya bertemu teman.", "I met a friend.", "Me encontré con un amigo."], note: ["Dalam bahasa Korea 친구 mengandaikan usia sebaya; untuk yang lebih tua pakai 선배/형/언니.", "친구 implies the same age; for someone older use 선배/형/언니.", "친구 supone la misma edad; para alguien mayor se usa 선배/형/언니."] },
  { w: "크다", r: "keuda", pos: "adj", cefr: "A1", g: ["besar", "to be big", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["가방이 커요.", "Tasnya besar.", "The bag is big.", "El bolso es grande."], ant: ["작다"] },

  /* ------------------------------------------------------------------ A2 */
  { w: "기다리다", r: "gidarida", pos: "v", cefr: "A2", g: ["menunggu", "to wait", "esperar"], d: ["Tinggal di tempat sampai sesuatu terjadi.", "To stay until something happens.", "Permanecer hasta que algo ocurra."], ex: ["여기서 기다려 주세요.", "Tolong tunggu di sini.", "Please wait here.", "Espere aquí, por favor."] },
  { w: "날씨", r: "nalssi", pos: "n", cefr: "A2", g: ["cuaca", "weather", "tiempo, clima"], d: ["Keadaan udara pada suatu hari.", "The state of the air on a given day.", "Estado del aire en un día."], ex: ["날씨가 흐려요.", "Cuacanya mendung.", "The weather is cloudy.", "Está nublado."] },
  { w: "돈", r: "don", pos: "n", cefr: "A2", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["돈이 조금 부족해요.", "Uangnya kurang sedikit.", "I'm a little short of money.", "Me falta algo de dinero."] },
  { w: "바쁘다", r: "bappeuda", pos: "adj", cefr: "A2", g: ["sibuk", "to be busy", "estar ocupado"], d: ["Punya banyak hal yang harus dikerjakan.", "Having a lot to do.", "Con muchas cosas que hacer."], ex: ["요즘 정말 바빠요.", "Belakangan ini saya sangat sibuk.", "I'm really busy these days.", "Últimamente estoy muy ocupado."] },
  { w: "배우다", r: "baeuda", pos: "v", cefr: "A2", g: ["belajar", "to learn", "aprender"], d: ["Memperoleh pengetahuan atau keterampilan baru.", "To gain new knowledge or a new skill.", "Adquirir conocimientos o destrezas."], ex: ["한국어를 배우고 있어요.", "Saya sedang belajar bahasa Korea.", "I'm learning Korean.", "Estoy aprendiendo coreano."], syn: ["공부하다"] },
  { w: "병원", r: "byeongwon", pos: "n", cefr: "A2", g: ["rumah sakit", "hospital, clinic", "hospital"], d: ["Tempat orang sakit dirawat dokter.", "Where doctors treat the sick.", "Lugar donde los médicos atienden enfermos."], ex: ["병원에 가 봤어요?", "Sudah ke rumah sakit?", "Have you been to the hospital?", "¿Has ido al hospital?"] },
  { w: "비싸다", r: "bissada", pos: "adj", cefr: "A2", g: ["mahal", "to be expensive", "ser caro"], d: ["Harganya tinggi.", "Costing a lot of money.", "Que cuesta mucho."], ex: ["이 옷은 너무 비싸요.", "Baju ini terlalu mahal.", "These clothes are too expensive.", "Esta ropa es demasiado cara."], ant: ["싸다"] },
  { w: "시간", r: "sigan", pos: "n", cefr: "A2", g: ["waktu; jam", "time; hour", "tiempo; hora"], d: ["Rentang waktu; juga satuan jam.", "A stretch of time; also the unit 'hour'.", "Lapso de tiempo; también la hora."], ex: ["시간이 없어요.", "Saya tidak punya waktu.", "I don't have time.", "No tengo tiempo."] },
  { w: "시작하다", r: "sijakhada", pos: "v", cefr: "A2", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["수업이 아홉 시에 시작해요.", "Kelas mulai pukul sembilan.", "Class starts at nine.", "La clase empieza a las nueve."], ant: ["끝나다"] },
  { w: "일", r: "il", pos: "n", cefr: "A2", g: ["pekerjaan; hal", "work; a matter", "trabajo; asunto"], d: ["Kegiatan mencari nafkah; juga urusan.", "The activity you earn a living by; also an affair.", "Actividad laboral; también un asunto."], ex: ["오늘 일이 많아요.", "Hari ini banyak pekerjaan.", "I have a lot of work today.", "Hoy tengo mucho trabajo."] },
  { w: "자주", r: "jaju", pos: "adv", cefr: "A2", g: ["sering", "often", "a menudo"], d: ["Berulang kali dalam rentang waktu tertentu.", "Many times within a period.", "Muchas veces en un periodo."], ex: ["자주 연락해요.", "Kami sering berhubungan.", "We keep in touch often.", "Nos escribimos a menudo."] },
  { w: "조용하다", r: "joyonghada", pos: "adj", cefr: "A2", g: ["tenang, sunyi", "to be quiet", "estar tranquilo"], d: ["Tanpa banyak suara.", "With little noise.", "Con poco ruido."], ex: ["도서관은 조용해요.", "Perpustakaannya tenang.", "The library is quiet.", "La biblioteca está tranquila."] },
  { w: "지하철", r: "jihacheol", pos: "n", cefr: "A2", g: ["kereta bawah tanah", "subway, metro", "metro"], d: ["Kereta yang berjalan di bawah kota.", "A train that runs under the city.", "Tren que circula bajo la ciudad."], ex: ["지하철로 가는 게 빨라요.", "Naik kereta bawah tanah lebih cepat.", "Going by subway is faster.", "Ir en metro es más rápido."] },
  { w: "찾다", r: "chatda", pos: "v", cefr: "A2", g: ["mencari, menemukan", "to look for, to find", "buscar, encontrar"], d: ["Berusaha menemukan sesuatu.", "To try to find something.", "Intentar encontrar algo."], ex: ["열쇠를 찾고 있어요.", "Saya sedang mencari kunci.", "I'm looking for my key.", "Estoy buscando la llave."] },
  { w: "타다", r: "tada", pos: "v", cefr: "A2", g: ["naik (kendaraan)", "to ride, to board", "montar, subir a"], d: ["Masuk ke kendaraan untuk bepergian.", "To get onto a vehicle in order to travel.", "Subir a un vehículo para viajar."], ex: ["버스를 타고 왔어요.", "Saya datang naik bus.", "I came by bus.", "Vine en autobús."], note: ["Memakai partikel 을/를: 버스를 타다 (bukan 에).", "Takes 을/를: 버스를 타다, not 버스에 타다.", "Lleva 을/를: 버스를 타다, no 버스에."] },
  { w: "만나다", r: "mannada", pos: "v", cefr: "A2", g: ["bertemu", "to meet", "encontrarse con"], d: ["Berjumpa dengan seseorang.", "To come together with someone.", "Reunirse con alguien."], ex: ["내일 만나요.", "Sampai jumpa besok.", "See you tomorrow.", "Nos vemos mañana."] },
  { w: "여행", r: "yeohaeng", pos: "n", cefr: "A2", g: ["perjalanan wisata", "travel, a trip", "viaje"], d: ["Bepergian ke tempat lain untuk bersenang-senang.", "Going somewhere else, usually for pleasure.", "Ir a otro lugar, normalmente por placer."], ex: ["제주도로 여행을 갔어요.", "Saya berwisata ke Pulau Jeju.", "I took a trip to Jeju Island.", "Hice un viaje a la isla de Jeju."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "계획", r: "gyehoek", pos: "n", cefr: "B1", g: ["rencana", "a plan", "plan"], d: ["Rangkaian langkah yang disusun lebih dulu.", "Steps decided on beforehand.", "Pasos decididos de antemano."], ex: ["주말 계획이 있어요?", "Ada rencana akhir pekan?", "Do you have weekend plans?", "¿Tienes planes para el fin de semana?"] },
  { w: "경험", r: "gyeongheom", pos: "n", cefr: "B1", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan yang lahir dari menjalani sesuatu.", "Knowledge gained by living through something.", "Conocimiento nacido de la práctica."], ex: ["좋은 경험이었어요.", "Itu pengalaman yang baik.", "It was a good experience.", "Fue una buena experiencia."] },
  { w: "결정하다", r: "gyeoljeonghada", pos: "v", cefr: "B1", g: ["memutuskan", "to decide", "decidir"], d: ["Menetapkan pilihan setelah berpikir.", "To settle on a choice after thinking.", "Tomar una decisión tras pensar."], ex: ["아직 결정하지 못했어요.", "Saya belum bisa memutuskan.", "I haven't been able to decide yet.", "Todavía no he podido decidir."] },
  { w: "기회", r: "gihoe", pos: "n", cefr: "B1", g: ["kesempatan", "opportunity, chance", "oportunidad"], d: ["Saat yang memungkinkan sesuatu dilakukan.", "A moment that makes something possible.", "Momento que hace posible algo."], ex: ["좋은 기회를 놓쳤어요.", "Saya melewatkan kesempatan bagus.", "I missed a good opportunity.", "Perdí una buena oportunidad."] },
  { w: "미리", r: "miri", pos: "adv", cefr: "B1", g: ["sebelumnya, di muka", "in advance, beforehand", "de antemano"], d: ["Sebelum waktunya tiba.", "Before the time comes.", "Antes de que llegue el momento."], ex: ["미리 예약하세요.", "Silakan pesan sebelumnya.", "Please book in advance.", "Reserve con antelación."] },
  { w: "문제", r: "munje", pos: "n", cefr: "B1", g: ["masalah; soal", "problem; question", "problema; pregunta"], d: ["Hal yang menyulitkan; juga soal ujian.", "Something difficult; also an exam question.", "Algo difícil; también una pregunta de examen."], ex: ["문제가 생겼어요.", "Timbul masalah.", "A problem has come up.", "Ha surgido un problema."] },
  { w: "복잡하다", r: "bokjaphada", pos: "adj", cefr: "B1", g: ["rumit; ramai", "to be complicated; crowded", "complicado; concurrido"], d: ["Banyak bagian sehingga sulit; juga penuh sesak.", "Having many parts, hence difficult; also crowded.", "Con muchas partes, difícil; también abarrotado."], ex: ["절차가 좀 복잡해요.", "Prosedurnya agak rumit.", "The procedure is a bit complicated.", "El trámite es algo complicado."], ant: ["간단하다"] },
  { w: "설명하다", r: "seolmyeonghada", pos: "v", cefr: "B1", g: ["menjelaskan", "to explain", "explicar"], d: ["Membuat sesuatu menjadi mudah dipahami.", "To make something easy to understand.", "Hacer algo comprensible."], ex: ["다시 설명해 주시겠어요?", "Bisakah dijelaskan sekali lagi?", "Could you explain it again?", "¿Podría explicarlo otra vez?"] },
  { w: "아마", r: "ama", pos: "adv", cefr: "B1", g: ["mungkin", "probably, perhaps", "quizá"], d: ["Menyatakan dugaan, bukan kepastian.", "Expresses a guess rather than certainty.", "Expresa suposición, no certeza."], ex: ["아마 내일 올 거예요.", "Mungkin dia datang besok.", "He'll probably come tomorrow.", "Probablemente venga mañana."] },
  { w: "약속", r: "yaksok", pos: "n", cefr: "B1", g: ["janji; janji temu", "a promise; an appointment", "promesa; cita"], d: ["Kesepakatan untuk melakukan atau bertemu.", "An agreement to do something or to meet.", "Compromiso de hacer algo o de verse."], ex: ["오후에 약속이 있어요.", "Sore ini saya ada janji.", "I have an appointment this afternoon.", "Tengo una cita esta tarde."] },
  { w: "일부러", r: "ilbureo", pos: "adv", cefr: "B1", g: ["dengan sengaja", "on purpose, deliberately", "a propósito"], d: ["Dilakukan dengan maksud tertentu.", "Done deliberately, not by chance.", "Hecho con intención."], ex: ["일부러 그런 게 아니에요.", "Saya tidak sengaja melakukannya.", "I didn't do it on purpose.", "No lo hice a propósito."] },
  { w: "준비하다", r: "junbihada", pos: "v", cefr: "B1", g: ["mempersiapkan", "to prepare", "preparar"], d: ["Menyiapkan segala sesuatu lebih dulu.", "To get things ready beforehand.", "Dejar algo listo de antemano."], ex: ["시험을 준비하고 있어요.", "Saya sedang mempersiapkan ujian.", "I'm preparing for an exam.", "Me estoy preparando para un examen."] },
  { w: "편리하다", r: "pyeollihada", pos: "adj", cefr: "B1", g: ["praktis, memudahkan", "to be convenient", "ser práctico"], d: ["Mudah dipakai dan menghemat tenaga.", "Easy to use and saving effort.", "Fácil de usar y que ahorra esfuerzo."], ex: ["이 앱이 아주 편리해요.", "Aplikasi ini sangat praktis.", "This app is very convenient.", "Esta aplicación es muy práctica."], ant: ["불편하다"] },
  { w: "필요하다", r: "piryohada", pos: "adj", cefr: "B1", g: ["perlu", "to be necessary, to need", "ser necesario"], d: ["Diperlukan agar sesuatu berjalan.", "Needed for something to work.", "Que hace falta para algo."], ex: ["도움이 필요해요.", "Saya butuh bantuan.", "I need help.", "Necesito ayuda."] },
  { w: "하지만", r: "hajiman", pos: "conj", cefr: "B1", g: ["tetapi", "but, however", "pero"], d: ["Menandai pertentangan dengan kalimat sebelumnya.", "Marks a contrast with the previous sentence.", "Marca contraste con lo anterior."], ex: ["비쌌어요. 하지만 만족해요.", "Mahal. Tetapi saya puas.", "It was expensive. But I'm satisfied.", "Fue caro. Pero estoy satisfecho."], syn: ["그렇지만"] },
  { w: "그래서", r: "geuraeseo", pos: "conj", cefr: "B1", g: ["jadi, karena itu", "so, therefore", "así que"], d: ["Menandai akibat dari kalimat sebelumnya.", "Marks the consequence of what was just said.", "Marca la consecuencia de lo anterior."], ex: ["비가 왔어요. 그래서 집에 있었어요.", "Hujan. Jadi saya di rumah.", "It rained, so I stayed home.", "Llovió, así que me quedé en casa."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "가능하다", r: "ganeunghada", pos: "adj", cefr: "B2", g: ["mungkin dilakukan", "to be possible", "ser posible"], d: ["Bisa terjadi atau bisa dikerjakan.", "Able to happen or to be done.", "Que puede ocurrir o hacerse."], ex: ["환불이 가능한가요?", "Apakah refund memungkinkan?", "Is a refund possible?", "¿Es posible el reembolso?"], ant: ["불가능하다"] },
  { w: "감소하다", r: "gamsohada", pos: "v", cefr: "B2", g: ["berkurang", "to decrease", "disminuir"], d: ["Jumlahnya menjadi lebih sedikit.", "To become smaller in number or amount.", "Hacerse menor en cantidad."], ex: ["매출이 감소했습니다.", "Penjualan menurun.", "Sales decreased.", "Las ventas disminuyeron."], ant: ["증가하다"] },
  { w: "강조하다", r: "gangjohada", pos: "v", cefr: "B2", g: ["menekankan", "to emphasise", "enfatizar"], d: ["Menonjolkan bagian yang dianggap penting.", "To give special weight to something.", "Destacar lo que se considera importante."], ex: ["안전을 특히 강조했어요.", "Dia sangat menekankan keselamatan.", "He especially emphasised safety.", "Enfatizó especialmente la seguridad."] },
  { w: "결과", r: "gyeolgwa", pos: "n", cefr: "B2", g: ["hasil", "result, outcome", "resultado"], d: ["Yang muncul setelah suatu proses selesai.", "What comes out of a process.", "Lo que produce un proceso."], ex: ["결과를 기다리고 있어요.", "Saya sedang menunggu hasilnya.", "I'm waiting for the results.", "Estoy esperando los resultados."] },
  { w: "고려하다", r: "goryeohada", pos: "v", cefr: "B2", g: ["mempertimbangkan", "to take into consideration", "considerar"], d: ["Memasukkan sesuatu ke dalam pertimbangan.", "To weigh something when deciding.", "Tener algo en cuenta al decidir."], ex: ["비용도 고려해야 해요.", "Biayanya juga harus dipertimbangkan.", "We must also consider the cost.", "También hay que considerar el coste."] },
  { w: "그러나", r: "geureona", pos: "conj", cefr: "B2", g: ["namun", "however (formal)", "sin embargo"], d: ["Penghubung pertentangan bergaya tulis.", "A written-register contrast connector.", "Conector adversativo de registro escrito."], ex: ["그러나 결론은 달랐습니다.", "Namun kesimpulannya berbeda.", "However, the conclusion was different.", "Sin embargo, la conclusión fue distinta."] },
  { w: "따라서", r: "ttaraseo", pos: "conj", cefr: "B2", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai kesimpulan logis.", "Marks a logical conclusion.", "Marca una conclusión lógica."], ex: ["따라서 계획을 수정했습니다.", "Oleh karena itu rencananya direvisi.", "Therefore the plan was revised.", "Por lo tanto se revisó el plan."] },
  { w: "반면에", r: "banmyeone", pos: "conj", cefr: "B2", g: ["sebaliknya, di sisi lain", "on the other hand", "en cambio"], d: ["Menyandingkan dua hal yang berlawanan.", "Sets two opposite things side by side.", "Contrapone dos cosas."], ex: ["가격은 싸요. 반면에 품질은 낮아요.", "Harganya murah. Sebaliknya mutunya rendah.", "It's cheap; on the other hand, the quality is low.", "Es barato; en cambio, la calidad es baja."] },
  { w: "영향", r: "yeonghyang", pos: "n", cefr: "B2", g: ["pengaruh", "influence, effect", "influencia"], d: ["Perubahan yang ditimbulkan pada hal lain.", "The change one thing causes in another.", "Cambio que algo provoca en otra cosa."], ex: ["날씨가 큰 영향을 미쳤어요.", "Cuaca sangat berpengaruh.", "The weather had a big effect.", "El tiempo influyó mucho."], note: ["Kolokasi tetap: 영향을 미치다 / 영향을 받다.", "Fixed collocations: 영향을 미치다 (to affect), 영향을 받다 (to be affected).", "Colocaciones fijas: 영향을 미치다 y 영향을 받다."] },
  { w: "중요하다", r: "jungyohada", pos: "adj", cefr: "B2", g: ["penting", "to be important", "ser importante"], d: ["Punya bobot besar bagi hasil akhir.", "Carrying great weight for the outcome.", "Que pesa mucho en el resultado."], ex: ["무엇보다 건강이 중요해요.", "Yang terpenting adalah kesehatan.", "Health matters above all.", "Lo más importante es la salud."] },
  { w: "증가하다", r: "jeunggahada", pos: "v", cefr: "B2", g: ["meningkat", "to increase", "aumentar"], d: ["Jumlahnya menjadi lebih banyak.", "To become greater in number or amount.", "Hacerse mayor en cantidad."], ex: ["이용자가 크게 증가했어요.", "Penggunanya meningkat tajam.", "Users increased sharply.", "Los usuarios aumentaron mucho."], ant: ["감소하다"] },
  { w: "태도", r: "taedo", pos: "n", cefr: "B2", g: ["sikap", "attitude", "actitud"], d: ["Cara seseorang bersikap terhadap sesuatu.", "The way someone behaves towards something.", "Manera de comportarse ante algo."], ex: ["태도가 아주 좋아요.", "Sikapnya sangat baik.", "His attitude is excellent.", "Su actitud es excelente."] },
  { w: "해결하다", r: "haegyeolhada", pos: "v", cefr: "B2", g: ["menyelesaikan (masalah)", "to solve", "resolver"], d: ["Menemukan jalan keluar dari masalah.", "To find a way out of a problem.", "Encontrar salida a un problema."], ex: ["문제를 빨리 해결했어요.", "Masalahnya cepat diselesaikan.", "The problem was solved quickly.", "El problema se resolvió rápido."] },
  { w: "확실하다", r: "hwaksilhada", pos: "adj", cefr: "B2", g: ["pasti", "to be certain", "ser seguro"], d: ["Tidak ada keraguan sedikit pun.", "Leaving no room for doubt.", "Sin lugar a dudas."], ex: ["아직 확실하지 않아요.", "Belum pasti.", "It isn't certain yet.", "Todavía no es seguro."] },
  { w: "환경", r: "hwangyeong", pos: "n", cefr: "B2", g: ["lingkungan", "environment, surroundings", "entorno, medio ambiente"], d: ["Keadaan sekeliling; juga alam.", "The surroundings; also the natural world.", "El entorno; también la naturaleza."], ex: ["근무 환경이 좋아요.", "Lingkungan kerjanya bagus.", "The working environment is good.", "El ambiente de trabajo es bueno."] },
  { w: "비하다", r: "bihada", pos: "v", cefr: "B2", g: ["membandingkan (~에 비해)", "to compare (as ~에 비해)", "comparar (~에 비해)"], d: ["Dipakai dalam pola ~에 비해: 'dibandingkan dengan'.", "Used in the pattern ~에 비해: 'compared with'.", "Se usa en ~에 비해: 'en comparación con'."], ex: ["작년에 비해 두 배예요.", "Dua kali lipat dibandingkan tahun lalu.", "It's double compared with last year.", "Es el doble en comparación con el año pasado."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "간과하다", r: "gangwahada", pos: "v", cefr: "C1", g: ["mengabaikan, melewatkan", "to overlook", "pasar por alto"], d: ["Tidak memperhatikan hal yang sebenarnya penting.", "To fail to notice something important.", "No advertir algo importante."], ex: ["이 점을 간과해서는 안 됩니다.", "Hal ini tidak boleh diabaikan.", "This point must not be overlooked.", "No debe pasarse por alto este punto."] },
  { w: "관점", r: "gwanjeom", pos: "n", cefr: "C1", g: ["sudut pandang", "point of view, perspective", "punto de vista"], d: ["Cara seseorang memandang suatu persoalan.", "The angle from which someone sees an issue.", "Ángulo desde el que se ve un asunto."], ex: ["다른 관점에서 봅시다.", "Mari lihat dari sudut pandang lain.", "Let's look at it from another perspective.", "Veámoslo desde otra perspectiva."] },
  { w: "근거", r: "geungeo", pos: "n", cefr: "C1", g: ["dasar, landasan", "grounds, evidence", "fundamento"], d: ["Bukti atau alasan yang menopang pendapat.", "The evidence a claim rests on.", "Prueba en que se apoya una afirmación."], ex: ["근거가 부족합니다.", "Landasannya kurang kuat.", "The evidence is insufficient.", "Los fundamentos son insuficientes."] },
  { w: "다만", r: "daman", pos: "conj", cefr: "C1", g: ["hanya saja", "except that, only", "solo que"], d: ["Menambahkan satu pembatasan pada pernyataan.", "Adds a single qualification to a statement.", "Añade una salvedad a lo dicho."], ex: ["좋습니다. 다만 시간이 촉박해요.", "Bagus. Hanya saja waktunya mepet.", "Fine — only, time is short.", "Bien; solo que hay poco tiempo."] },
  { w: "대안", r: "daean", pos: "n", cefr: "C1", g: ["alternatif", "an alternative", "alternativa"], d: ["Pilihan lain bila yang pertama gagal.", "Another option if the first fails.", "Otra opción si la primera falla."], ex: ["현실적인 대안이 필요해요.", "Kita butuh alternatif yang realistis.", "We need a realistic alternative.", "Necesitamos una alternativa realista."] },
  { w: "도출하다", r: "dochulhada", pos: "v", cefr: "C1", g: ["menarik (kesimpulan)", "to derive, to draw (a conclusion)", "extraer"], d: ["Menghasilkan kesimpulan dari data atau diskusi.", "To arrive at a conclusion from data or discussion.", "Obtener una conclusión a partir de datos."], ex: ["합의를 도출했습니다.", "Kesepakatan berhasil dicapai.", "An agreement was reached.", "Se alcanzó un acuerdo."] },
  { w: "모호하다", r: "mohohada", pos: "adj", cefr: "C1", g: ["kabur, bermakna ganda", "to be ambiguous", "ser ambiguo"], d: ["Bisa ditafsirkan lebih dari satu cara.", "Open to more than one reading.", "Que admite más de una lectura."], ex: ["표현이 모호합니다.", "Ungkapannya kabur.", "The wording is ambiguous.", "La expresión es ambigua."], ant: ["명확하다"] },
  { w: "반영하다", r: "banyeonghada", pos: "v", cefr: "C1", g: ["mencerminkan; memasukkan", "to reflect; to incorporate", "reflejar"], d: ["Menunjukkan keadaan lain; memasukkan masukan.", "To show another state; to build feedback in.", "Mostrar otra realidad; incorporar aportes."], ex: ["의견을 정책에 반영했어요.", "Masukan itu dimasukkan ke kebijakan.", "The feedback was reflected in the policy.", "Las opiniones se reflejaron en la política."] },
  { w: "불구하고", r: "bulguhago", pos: "prep", cefr: "C1", g: ["meskipun (~에도 불구하고)", "despite (as ~에도 불구하고)", "a pesar de"], d: ["Menandai hambatan yang tidak menghalangi.", "Marks an obstacle that changes nothing.", "Marca un obstáculo que no impide nada."], ex: ["악천후에도 불구하고 출발했어요.", "Meskipun cuaca buruk, kami berangkat.", "We set off despite the bad weather.", "Salimos a pesar del mal tiempo."] },
  { w: "아울러", r: "aulleo", pos: "adv", cefr: "C1", g: ["sekaligus, di samping itu", "furthermore, together with", "asimismo"], d: ["Menambahkan poin kedua dalam gaya formal.", "Adds a second point in formal register.", "Añade un segundo punto en registro formal."], ex: ["아울러 예산도 검토했습니다.", "Di samping itu, anggarannya juga ditinjau.", "Furthermore, the budget was reviewed.", "Asimismo se revisó el presupuesto."] },
  { w: "오히려", r: "ohiryeo", pos: "adv", cefr: "C1", g: ["justru, malah", "rather, on the contrary", "más bien"], d: ["Menyatakan kebalikan dari yang diduga.", "States the opposite of what was expected.", "Expresa lo contrario de lo esperado."], ex: ["값이 오히려 내렸어요.", "Harganya justru turun.", "The price actually went down.", "El precio más bien bajó."] },
  { w: "철저하다", r: "cheoljeohada", pos: "adj", cefr: "C1", g: ["menyeluruh, teliti", "to be thorough", "ser minucioso"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest part.", "Hecho hasta el último detalle."], ex: ["철저한 준비가 필요합니다.", "Persiapan menyeluruh diperlukan.", "Thorough preparation is needed.", "Hace falta una preparación minuciosa."] },
  { w: "추진하다", r: "chujinhada", pos: "v", cefr: "C1", g: ["mendorong, menjalankan", "to push forward, to drive", "impulsar"], d: ["Menjalankan rencana besar dengan tekad.", "To drive a large plan forward.", "Llevar adelante un plan importante."], ex: ["새 사업을 추진하고 있습니다.", "Kami sedang menjalankan usaha baru.", "We're driving a new project forward.", "Estamos impulsando un nuevo proyecto."] },
  { w: "타당하다", r: "tadanghada", pos: "adj", cefr: "C1", g: ["masuk akal, sahih", "to be valid, reasonable", "ser válido"], d: ["Sesuai nalar dan bisa dipertanggungjawabkan.", "Reasonable and defensible.", "Razonable y defendible."], ex: ["타당한 지적입니다.", "Itu kritik yang masuk akal.", "That's a valid point.", "Es una observación válida."] },
  { w: "여건", r: "yeogeon", pos: "n", cefr: "C1", g: ["kondisi, keadaan yang tersedia", "conditions, circumstances", "condiciones"], d: ["Keadaan sekitar yang memungkinkan atau menghambat sesuatu.", "The surrounding conditions that enable or hinder something.", "Condiciones que facilitan o dificultan algo."], ex: ["여건이 허락하면 진행하겠습니다.", "Kalau kondisinya memungkinkan, kami lanjutkan.", "We'll proceed if conditions allow.", "Procederemos si las condiciones lo permiten."] },
  { w: "궁극적", r: "gunggeukjeok", pos: "adj", cefr: "C1", g: ["pada akhirnya, hakiki", "ultimate, final", "último, definitivo"], d: ["Berkaitan dengan tujuan paling akhir.", "Relating to the final aim.", "Relativo al fin último."], ex: ["궁극적인 목표는 자립입니다.", "Tujuan akhirnya adalah kemandirian.", "The ultimate goal is independence.", "El objetivo último es la autonomía."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "문", r: "mun", pos: "n", cefr: "A1", g: ["pintu", "door", "puerta"] },
  { w: "창문", r: "changmun", pos: "n", cefr: "A1", g: ["jendela", "window", "ventana"] },
  { w: "방", r: "bang", pos: "n", cefr: "A1", g: ["kamar", "room", "habitación"] },
  { w: "책상", r: "chaeksang", pos: "n", cefr: "A1", g: ["meja tulis", "desk", "escritorio"] },
  { w: "의자", r: "uija", pos: "n", cefr: "A1", g: ["kursi", "chair", "silla"] },
  { w: "침대", r: "chimdae", pos: "n", cefr: "A1", g: ["tempat tidur", "bed", "cama"] },
  { w: "부엌", r: "bueok", pos: "n", cefr: "A1", g: ["dapur", "kitchen", "cocina"] },
  { w: "화장실", r: "hwajangsil", pos: "n", cefr: "A1", g: ["kamar kecil, toilet", "bathroom, toilet", "baño"] },
  { w: "전등", r: "jeondeung", pos: "n", cefr: "A1", g: ["lampu", "lamp, light", "lámpara"] },
  { w: "열쇠", r: "yeolsoe", pos: "n", cefr: "A1", g: ["kunci", "key", "llave"] },
  { w: "벽", r: "byeok", pos: "n", cefr: "A1", g: ["dinding", "wall", "pared"] },
  { w: "지붕", r: "jibung", pos: "n", cefr: "A1", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "빵", r: "ppang", pos: "n", cefr: "A1", g: ["roti", "bread", "pan"] },
  { w: "쌀", r: "ssal", pos: "n", cefr: "A1", g: ["beras", "uncooked rice", "arroz crudo"], note: ["쌀 = beras mentah, 밥 = nasi yang sudah matang.", "쌀 is uncooked rice; 밥 is cooked rice.", "쌀 es arroz crudo; 밥, arroz cocido."] },
  { w: "고기", r: "gogi", pos: "n", cefr: "A1", g: ["daging", "meat", "carne"] },
  { w: "생선", r: "saengseon", pos: "n", cefr: "A1", g: ["ikan (makanan)", "fish (as food)", "pescado"] },
  { w: "달걀", r: "dalgyal", pos: "n", cefr: "A1", g: ["telur", "egg", "huevo"], syn: ["계란"] },
  { w: "우유", r: "uyu", pos: "n", cefr: "A1", g: ["susu", "milk", "leche"] },
  { w: "차", r: "cha", pos: "n", cefr: "A1", g: ["teh; mobil", "tea; car", "té; coche"], note: ["Dua kata berbeda yang kebetulan sama bunyinya (茶 dan 車).", "Two different words that happen to sound alike (茶 and 車).", "Dos palabras distintas que suenan igual (茶 y 車)."] },
  { w: "커피", r: "keopi", pos: "n", cefr: "A1", g: ["kopi", "coffee", "café"] },
  { w: "설탕", r: "seoltang", pos: "n", cefr: "A1", g: ["gula", "sugar", "azúcar"] },
  { w: "소금", r: "sogeum", pos: "n", cefr: "A1", g: ["garam", "salt", "sal"] },
  { w: "과일", r: "gwail", pos: "n", cefr: "A1", g: ["buah", "fruit", "fruta"] },
  { w: "채소", r: "chaeso", pos: "n", cefr: "A1", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "셔츠", r: "syeocheu", pos: "n", cefr: "A2", g: ["kemeja", "shirt", "camisa"] },
  { w: "바지", r: "baji", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalón"] },
  { w: "신발", r: "sinbal", pos: "n", cefr: "A2", g: ["sepatu, alas kaki", "shoes", "zapatos"] },
  { w: "모자", r: "moja", pos: "n", cefr: "A2", g: ["topi", "hat", "sombrero"] },
  { w: "손", r: "son", pos: "n", cefr: "A2", g: ["tangan", "hand", "mano"] },
  { w: "눈", r: "nun", pos: "n", cefr: "A2", g: ["mata; salju", "eye; snow", "ojo; nieve"], note: ["Panjang vokalnya berbeda: mata pendek, salju panjang.", "Vowel length differs: 'eye' is short, 'snow' is long.", "La duración vocálica difiere: ojo breve, nieve larga."] },
  { w: "머리", r: "meori", pos: "n", cefr: "A2", g: ["kepala; rambut", "head; hair", "cabeza; pelo"] },
  { w: "심장", r: "simjang", pos: "n", cefr: "A2", g: ["jantung", "heart (organ)", "corazón"] },
  { w: "치아", r: "chia", pos: "n", cefr: "A2", g: ["gigi", "tooth", "diente"], syn: ["이"] },
  { w: "귀", r: "gwi", pos: "n", cefr: "A2", g: ["telinga", "ear", "oreja"] },
  { w: "얼굴", r: "eolgul", pos: "n", cefr: "A2", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "나무", r: "namu", pos: "n", cefr: "A2", g: ["pohon; kayu", "tree; wood", "árbol; madera"] },
  { w: "꽃", r: "kkot", pos: "n", cefr: "A2", g: ["bunga", "flower", "flor"] },
  { w: "산", r: "san", pos: "n", cefr: "A2", g: ["gunung", "mountain", "montaña"] },
  { w: "강", r: "gang", pos: "n", cefr: "A2", g: ["sungai", "river", "río"] },
  { w: "바다", r: "bada", pos: "n", cefr: "A2", g: ["laut", "sea", "mar"] },
  { w: "하늘", r: "haneul", pos: "n", cefr: "A2", g: ["langit", "sky", "cielo"] },
  { w: "별", r: "byeol", pos: "n", cefr: "A2", g: ["bintang", "star", "estrella"] },
  { w: "개", r: "gae", pos: "n", cefr: "A2", g: ["anjing", "dog", "perro"] },
  { w: "고양이", r: "goyangi", pos: "n", cefr: "A2", g: ["kucing", "cat", "gato"] },
  { w: "새", r: "sae", pos: "n", cefr: "A2", g: ["burung", "bird", "pájaro"] },
  { w: "말", r: "mal", pos: "n", cefr: "A2", g: ["kuda; perkataan", "horse; speech", "caballo; habla"] },
  { w: "비", r: "bi", pos: "n", cefr: "A2", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "거리", r: "geori", pos: "n", cefr: "B1", g: ["jalan; jarak", "street; distance", "calle; distancia"] },
  { w: "다리", r: "dari", pos: "n", cefr: "B1", g: ["jembatan; kaki", "bridge; leg", "puente; pierna"] },
  { w: "시장", r: "sijang", pos: "n", cefr: "B1", g: ["pasar; wali kota", "market; mayor", "mercado; alcalde"] },
  { w: "학교", r: "hakgyo", pos: "n", cefr: "B1", g: ["sekolah", "school", "escuela"] },
  { w: "도서관", r: "doseogwan", pos: "n", cefr: "B1", g: ["perpustakaan", "library", "biblioteca"] },
  { w: "사무실", r: "samusil", pos: "n", cefr: "B1", g: ["kantor, ruang kerja", "office", "oficina"] },
  { w: "버스", r: "beoseu", pos: "n", cefr: "B1", g: ["bus", "bus", "autobús"] },
  { w: "기차", r: "gicha", pos: "n", cefr: "B1", g: ["kereta api", "train", "tren"] },
  { w: "자동차", r: "jadongcha", pos: "n", cefr: "B1", g: ["mobil", "car", "coche"] },
  { w: "자전거", r: "jajeongeo", pos: "n", cefr: "B1", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "공항", r: "gonghang", pos: "n", cefr: "B1", g: ["bandara", "airport", "aeropuerto"] },
  { w: "표", r: "pyo", pos: "n", cefr: "B1", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "회사", r: "hoesa", pos: "n", cefr: "B2", g: ["perusahaan", "company", "empresa"] },
  { w: "회의", r: "hoeui", pos: "n", cefr: "B2", g: ["rapat", "meeting", "reunión"] },
  { w: "계약", r: "gyeyak", pos: "n", cefr: "B2", g: ["kontrak", "contract", "contrato"] },
  { w: "월급", r: "wolgeup", pos: "n", cefr: "B2", g: ["gaji bulanan", "monthly salary", "sueldo"] },
  { w: "가격", r: "gagyeok", pos: "n", cefr: "B2", g: ["harga", "price", "precio"] },
  { w: "세금", r: "segeum", pos: "n", cefr: "B2", g: ["pajak", "tax", "impuesto"] },
  { w: "은행", r: "eunhaeng", pos: "n", cefr: "B2", g: ["bank", "bank", "banco"] },
  { w: "컴퓨터", r: "keompyuteo", pos: "n", cefr: "B2", g: ["komputer", "computer", "ordenador"] },
  { w: "전화", r: "jeonhwa", pos: "n", cefr: "B2", g: ["telepon", "telephone", "teléfono"] },
  { w: "이메일", r: "imeil", pos: "n", cefr: "B2", g: ["surel, email", "email", "correo electrónico"] },
  { w: "파일", r: "pail", pos: "n", cefr: "B2", g: ["berkas", "file", "archivo"] },
  { w: "비밀번호", r: "bimilbeonho", pos: "n", cefr: "B2", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "급기야", r: "geupgiya", pos: "adv", cefr: "C2", g: ["akhirnya (sampai begitu)", "in the end, finally (dramatic)", "al final (dramático)"], d: ["Menandai puncak rangkaian peristiwa yang memburuk.", "Marks the climax of a worsening chain of events.", "Marca el clímax de una cadena que empeora."], ex: ["급기야 사업을 접었습니다.", "Akhirnya usahanya ditutup.", "In the end, the business closed.", "Al final cerró el negocio."] },
  { w: "나아가", r: "naaga", pos: "adv", cefr: "C2", g: ["lebih jauh lagi", "furthermore, going further", "más aún"], d: ["Melangkah ke pernyataan yang lebih luas.", "Steps up to a broader claim.", "Da un paso hacia una afirmación mayor."], ex: ["나아가 제도 개선도 필요합니다.", "Lebih jauh lagi, sistemnya perlu dibenahi.", "Furthermore, the system needs reform.", "Más aún, el sistema necesita reforma."] },
  { w: "명백하다", r: "myeongbaekhada", pos: "adj", cefr: "C2", g: ["nyata, gamblang", "to be obvious, evident", "ser evidente"], d: ["Jelas sehingga tak perlu dibuktikan lagi.", "So clear it needs no proof.", "Tan claro que no requiere prueba."], ex: ["명백한 위반입니다.", "Itu pelanggaran yang nyata.", "It's an obvious violation.", "Es una infracción evidente."] },
  { w: "미묘하다", r: "mimyohada", pos: "adj", cefr: "C2", g: ["halus, pelik", "to be subtle, delicate", "ser sutil"], d: ["Perbedaannya kecil dan sulit dijelaskan.", "Differing in ways that are small and hard to name.", "Con diferencias pequeñas y difíciles de nombrar."], ex: ["뉘앙스가 미묘하게 달라요.", "Nuansanya berbeda secara halus.", "The nuance differs subtly.", "El matiz difiere sutilmente."] },
  { w: "부합하다", r: "buhaphada", pos: "v", cefr: "C2", g: ["sesuai, selaras", "to conform to, to match", "ajustarse a"], d: ["Cocok dengan syarat atau prinsip yang ada.", "To match a requirement or principle.", "Coincidir con un requisito o principio."], ex: ["규정에 부합하지 않습니다.", "Itu tidak sesuai dengan aturan.", "It does not conform to the rules.", "No se ajusta a la normativa."] },
  { w: "불가피하다", r: "bulgapihada", pos: "adj", cefr: "C2", g: ["tak terhindarkan", "to be unavoidable", "ser inevitable"], d: ["Tidak mungkin dihindari lagi.", "Impossible to avoid.", "Imposible de evitar."], ex: ["가격 인상이 불가피합니다.", "Kenaikan harga tak terhindarkan.", "A price rise is unavoidable.", "La subida de precios es inevitable."] },
  { w: "비로소", r: "biroso", pos: "adv", cefr: "C2", g: ["barulah (setelah itu)", "only then, not until then", "solo entonces"], d: ["Menandai bahwa sesuatu baru terjadi setelah syarat terpenuhi.", "Marks that something happens only once a condition is met.", "Indica que algo ocurre solo tras cumplirse una condición."], ex: ["설명을 듣고 비로소 이해했어요.", "Setelah mendengar penjelasan, barulah saya paham.", "Only after the explanation did I understand.", "Solo tras la explicación lo entendí."] },
  { w: "역설적", r: "yeokseoljeok", pos: "adj", cefr: "C2", g: ["paradoksal", "paradoxical", "paradójico"], d: ["Tampak bertentangan tetapi sebenarnya benar.", "Seemingly contradictory yet true.", "En apariencia contradictorio pero cierto."], ex: ["역설적으로 규제가 시장을 키웠어요.", "Secara paradoksal, regulasi justru menumbuhkan pasar.", "Paradoxically, regulation grew the market.", "Paradójicamente, la regulación hizo crecer el mercado."] },
  { w: "이른바", r: "ireunba", pos: "adv", cefr: "C2", g: ["yang disebut", "so-called", "el llamado"], d: ["Memperkenalkan istilah yang lazim dipakai orang.", "Introduces a term people commonly use.", "Introduce un término de uso común."], ex: ["이른바 '워라밸' 문제입니다.", "Inilah yang disebut masalah 'work-life balance'.", "This is the so-called work-life balance issue.", "Es el llamado problema del equilibrio vida-trabajo."] },
  { w: "자칫", r: "jachit", pos: "adv", cefr: "C2", g: ["sedikit saja lengah", "if one is not careful", "por poco, si uno se descuida"], d: ["Menandai risiko yang muncul bila lengah sedikit.", "Marks a risk that appears with the slightest slip.", "Marca un riesgo ante el menor descuido."], ex: ["자칫 오해를 살 수 있어요.", "Sedikit lengah bisa menimbulkan salah paham.", "It could easily be misunderstood.", "Podría malinterpretarse fácilmente."] },
  { w: "지양하다", r: "jiyanghada", pos: "v", cefr: "C2", g: ["menghindari (secara prinsip)", "to refrain from, to avoid on principle", "evitar por principio"], d: ["Sengaja tidak melakukan sesuatu karena dinilai kurang baik.", "To deliberately not do something judged undesirable.", "Abstenerse de algo por considerarlo indeseable."], ex: ["과도한 표현은 지양합시다.", "Mari hindari ungkapan yang berlebihan.", "Let's refrain from excessive wording.", "Evitemos expresiones excesivas."], ant: ["지향하다"] },
  { w: "촉진하다", r: "chokjinhada", pos: "v", cefr: "C2", g: ["mempercepat, mendorong", "to promote, to accelerate", "fomentar"], d: ["Membuat suatu proses berjalan lebih cepat.", "To make a process move faster.", "Hacer que un proceso avance más rápido."], ex: ["투자가 성장을 촉진했습니다.", "Investasi mendorong pertumbuhan.", "Investment accelerated growth.", "La inversión impulsó el crecimiento."] },
  { w: "편향", r: "pyeonhyang", pos: "n", cefr: "C2", g: ["bias, kecondongan", "bias, slant", "sesgo"], d: ["Kecenderungan menilai secara tidak seimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["표본에 편향이 있습니다.", "Sampelnya mengandung bias.", "The sample carries a bias.", "La muestra tiene un sesgo."] },
  { w: "함의", r: "hami", pos: "n", cefr: "C2", g: ["makna tersirat", "implication, implied meaning", "implicación"], d: ["Arti yang terkandung tanpa dinyatakan langsung.", "A meaning carried without being stated.", "Sentido que se transmite sin decirse."], ex: ["정책적 함의가 큽니다.", "Implikasi kebijakannya besar.", "The policy implications are large.", "Las implicaciones políticas son grandes."] },
  { w: "획기적", r: "hoekgijeok", pos: "adj", cefr: "C2", g: ["terobosan, mengubah zaman", "groundbreaking, epoch-making", "revolucionario"], d: ["Begitu baru sehingga menandai babak baru.", "So new that it marks a new era.", "Tan nuevo que abre una era."], ex: ["획기적인 성과였습니다.", "Itu pencapaian yang menjadi terobosan.", "It was a groundbreaking achievement.", "Fue un logro revolucionario."] },
];
