/* =========================================================================
   lexicon/ms.js — Kamus: Bahasa Melayu. Front matter + 72 headwords, A1→C2.
   Catatan khusus penutur Indonesia: entri yang menjadi "teman palsu" diberi
   catatan pemakaian.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Melayu dan bahasa Indonesia serumpun, sehingga penutur Indonesia bisa langsung memahami sekitar 80% isinya. Sisanya justru yang berbahaya: kata yang sama bentuknya tetapi berbeda artinya.",
    "Malay and Indonesian are sister languages: an Indonesian speaker understands perhaps 80% at once. It is the other 20% that bites — identical words with different meanings.",
    "El malayo y el indonesio son lenguas hermanas: un hablante de indonesio entiende cerca del 80%. El otro 20% engaña: palabras iguales con significados distintos.",
  ],
  script: [
    "Ditulis dengan abjad Latin (Rumi); aksara Jawi berbasis Arab masih dipakai untuk keperluan keagamaan dan budaya. Ejaannya konsisten dan hampir tanpa kekecualian.",
    "Written in the Latin alphabet (Rumi); the Arabic-based Jawi script survives in religious and cultural use. Spelling is consistent with almost no exceptions.",
    "Se escribe en alfabeto latino (Rumi); la escritura jawi, de base árabe, pervive en usos religiosos y culturales.",
  ],
  pron: [
    ["a di akhir", "Di Malaysia sering dibaca /ə/: apa → 'ape', saya → 'saye'.", "In Malaysia a final a is often /ə/: apa → 'ape', saya → 'saye'.", "En Malasia la a final suele ser /ə/: apa → 'ape'."],
    ["e pepet vs e taling", "e /ə/ (emas) berbeda dari e /e/ (enak) — ejaannya sama.", "The two e's differ: /ə/ (emas) vs /e/ (enak), though spelled alike.", "Dos es distintas: /ə/ (emas) y /e/ (enak), con la misma grafía."],
    ["r", "Digetarkan jelas di semua posisi: besar, kereta.", "Clearly trilled in every position: besar, kereta.", "Vibrante clara en toda posición: besar, kereta."],
    ["ng / ngg", "ng = /ŋ/ (bunga); ngg = /ŋɡ/ (tangga).", "ng = /ŋ/ (bunga); ngg = /ŋɡ/ (tangga).", "ng = /ŋ/ (bunga); ngg = /ŋɡ/ (tangga)."],
    ["k di akhir", "Menjadi hentakan glotal: tidak → 'tida'.", "Becomes a glottal stop: tidak → 'tida'.", "Se convierte en oclusión glotal: tidak → 'tida'."],
    ["tekanan", "Ringan dan merata; tidak ada suku kata yang ditekan kuat seperti bahasa Inggris.", "Light and even; no syllable is hammered as in English.", "Ligero y uniforme; ninguna sílaba se marca como en inglés."],
  ],
  grammar: [
    {
      t: ["Tanpa perubahan bentuk kata kerja", "Verbs never conjugate", "Los verbos no se conjugan"],
      d: ["Kata kerja tidak berubah menurut pelaku atau waktu; waktu dinyatakan dengan kata bantu.", "Verbs do not change for person or tense; time is carried by helper words.", "El verbo no cambia; el tiempo lo marcan partículas."],
      ex: "saya makan · sudah makan · akan makan",
    },
    {
      t: ["Awalan me- dan ber-", "The me- and ber- prefixes", "Los prefijos me- y ber-"],
      d: ["me- membentuk kata kerja aktif bertujuan, ber- membentuk kata kerja keadaan atau kepemilikan.", "me- forms a transitive active verb; ber- forms a stative or possessive verb.", "me- forma verbo activo; ber-, verbo estativo o posesivo."],
      ex: "membaca buku · berbaju putih",
    },
    {
      t: ["Kata penjodoh bilangan", "Numeral classifiers", "Clasificadores numerales"],
      d: ["Bilangan memerlukan penjodoh: seorang guru, sebuah rumah, seekor kucing.", "Numbers need a classifier: seorang guru, sebuah rumah, seekor kucing.", "Los números requieren clasificador: seorang guru, sebuah rumah."],
      ex: "dua orang · tiga buah · empat ekor",
    },
    {
      t: ["Pengulangan kata", "Reduplication", "Reduplicación"],
      d: ["Mengulang kata menandai jamak atau makna baru: budak-budak, mata-mata.", "Repeating a word marks a plural or a new meaning: budak-budak, mata-mata.", "Repetir la palabra marca plural o nuevo sentido."],
      ex: "buku-buku (buku-buku) · orang-orang",
    },
    {
      t: ["Kesantunan kata ganti", "Polite pronouns", "Pronombres corteses"],
      d: ["saya (sopan) vs aku (akrab); anda/awak/kamu dipilih menurut jarak sosial.", "saya (polite) vs aku (intimate); anda/awak/kamu depend on social distance.", "saya (cortés) frente a aku (íntimo); anda/awak/kamu según la distancia."],
      ex: "Saya rasa… · Awak nak pergi?",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "ada", pos: "v", cefr: "A1", ipa: "ˈada", g: ["ada, punya", "there is; to have", "haber; tener"], d: ["Menyatakan keberadaan atau kepemilikan.", "States that something exists or is owned.", "Indica existencia o posesión."], ex: ["Ada kedai di hujung jalan.", "Ada kedai di ujung jalan.", "There's a shop at the end of the street.", "Hay una tienda al final de la calle."] },
  { w: "baik", pos: "adj", cefr: "A1", ipa: "baik", g: ["baik, bagus", "good, kind", "bueno"], d: ["Bermutu baik; juga berhati baik.", "Of good quality; also kind-hearted.", "De buena calidad; también bondadoso."], ex: ["Itu satu idea yang baik.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["buruk"] },
  { w: "besar", pos: "adj", cefr: "A1", ipa: "bəˈsar", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Mereka tinggal di bandar besar.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["kecil"] },
  { w: "hari", pos: "n", cefr: "A1", ipa: "ˈhari", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Saya bekerja setiap hari.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["malam"] },
  { w: "kawan", pos: "n", cefr: "A1", ipa: "ˈkawan", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Saya keluar dengan kawan.", "Saya keluar dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."], syn: ["sahabat"] },
  { w: "kecil", pos: "adj", cefr: "A1", ipa: "kəˈtʃil", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Saya ada rumah kecil.", "Saya punya rumah kecil.", "I have a small house.", "Tengo una casa pequeña."], ant: ["besar"] },
  { w: "lelaki", pos: "n", cefr: "A1", ipa: "ləˈlaki", g: ["laki-laki", "man, male", "hombre"], d: ["Manusia berjenis kelamin laki-laki.", "A male human being.", "Ser humano de sexo masculino."], ex: ["Lelaki itu jiran saya.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["perempuan"] },
  { w: "mahu", pos: "v", cefr: "A1", ipa: "ˈmahu", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Saya mahu belajar bahasa Melayu.", "Saya mau belajar bahasa Melayu.", "I want to learn Malay.", "Quiero aprender malayo."], note: ["Di Malaysia lazim ditulis mahu/nak; di Indonesia 'mau'.", "Malaysia writes mahu or the casual nak; Indonesian uses mau.", "En Malasia se escribe mahu o el coloquial nak."] },
  { w: "malam", pos: "n", cefr: "A1", ipa: "ˈmalam", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Selamat malam!", "Selamat malam!", "Good evening!", "¡Buenas noches!"], ant: ["hari"] },
  { w: "pergi", pos: "v", cefr: "A1", ipa: "pərˈɡi", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Saya pergi ke pasar.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "perempuan", pos: "n", cefr: "A1", ipa: "pərəmˈpuan", g: ["perempuan", "woman, female", "mujer"], d: ["Manusia berjenis kelamin perempuan.", "A female human being.", "Ser humano de sexo femenino."], ex: ["Perempuan bertopi itu mak cik saya.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["lelaki"] },
  { w: "rumah", pos: "n", cefr: "A1", ipa: "ˈrumah", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Rumah saya dekat taman.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "bandar", pos: "n", cefr: "A2", ipa: "ˈbandar", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Kuala Lumpur bandar yang sibuk.", "Kuala Lumpur kota yang sibuk.", "Kuala Lumpur is a busy city.", "Kuala Lumpur es una ciudad concurrida."], note: ["TEMAN PALSU: di Indonesia 'bandar' berarti pelabuhan atau cukong; kota dalam bahasa Melayu = bandar.", "FALSE FRIEND: Indonesian 'bandar' means a port or a kingpin; in Malay it means town.", "FALSO AMIGO: en indonesio 'bandar' es puerto; en malayo, ciudad."] },
  { w: "cepat", pos: "adj", cefr: "A2", ipa: "tʃəˈpat", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Keretapi lebih cepat.", "Kereta api lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["lambat"] },
  { w: "kerana", pos: "conj", cefr: "A2", ipa: "kəˈrana", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Saya di rumah kerana hujan.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."], note: ["Ejaan Melayu 'kerana'; ejaan Indonesia 'karena'.", "Malay spells it kerana; Indonesian karena.", "El malayo escribe kerana; el indonesio, karena."] },
  { w: "kerja", pos: "n", cefr: "A2", ipa: "ˈkərdʒa", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Kerja saya bermula pukul sembilan.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "masa", pos: "n", cefr: "A2", ipa: "ˈmasa", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["Saya tiada masa hari ini.", "Saya tidak punya waktu hari ini.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "mudah", pos: "adj", cefr: "A2", ipa: "ˈmudah", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["Peperiksaan itu mudah.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["susah"] },
  { w: "mula", pos: "v", cefr: "A2", ipa: "ˈmula", g: ["mulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Wayang bermula pukul lapan.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "pejabat", pos: "n", cefr: "A2", ipa: "pəˈdʒabat", g: ["kantor", "office", "oficina"], d: ["Tempat bekerja para pegawai.", "The place where office staff work.", "Lugar donde trabajan los empleados."], ex: ["Saya di pejabat sekarang.", "Saya sedang di kantor.", "I'm at the office now.", "Ahora estoy en la oficina."], note: ["TEMAN PALSU: dalam bahasa Indonesia 'pejabat' berarti orang yang menjabat; kantor dalam bahasa Melayu = pejabat.", "FALSE FRIEND: Indonesian 'pejabat' means an official (a person); Malay 'pejabat' is an office (a place).", "FALSO AMIGO: en indonesio 'pejabat' es un funcionario; en malayo, una oficina."] },
  { w: "percuma", pos: "adj", cefr: "A2", ipa: "pərˈtʃuma", g: ["gratis", "free of charge", "gratis"], d: ["Tidak dipungut bayaran.", "Costing nothing.", "Que no cuesta nada."], ex: ["Kemasukan adalah percuma.", "Masuknya gratis.", "Entry is free.", "La entrada es gratuita."], note: ["TEMAN PALSU: di Indonesia 'percuma' berarti sia-sia; gratis dalam bahasa Melayu = percuma.", "FALSE FRIEND: Indonesian 'percuma' means pointless; Malay 'percuma' means free of charge.", "FALSO AMIGO: en indonesio 'percuma' es inútil; en malayo, gratis."] },
  { w: "perlu", pos: "v", cefr: "A2", ipa: "pərˈlu", g: ["perlu", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Saya perlu berehat.", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "selalu", pos: "adv", cefr: "A2", ipa: "səˈlalu", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Saya selalu sarapan di rumah.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },
  { w: "susah", pos: "adj", cefr: "A2", ipa: "ˈsusah", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Susah nak parking di sini.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["mudah"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "berjaya", pos: "v", cefr: "B1", ipa: "bərˈdʒaja", g: ["berhasil", "to succeed", "tener éxito"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["Dia berjaya menamatkan pengajian.", "Dia berhasil menyelesaikan studinya.", "She succeeded in finishing her studies.", "Logró terminar sus estudios."], note: ["Bandingkan: Indonesia memakai 'berhasil'; 'berjaya' di Indonesia berkonotasi kejayaan/kemasyhuran.", "Compare Indonesian 'berhasil'; Indonesian 'berjaya' suggests glory instead.", "Compárese con el indonesio 'berhasil'."] },
  { w: "budak", pos: "n", cefr: "B1", ipa: "ˈbudak", g: ["anak (kecil)", "child, kid", "niño"], d: ["Anak yang masih kecil.", "A young child.", "Un niño pequeño."], ex: ["Budak-budak itu bermain di taman.", "Anak-anak itu bermain di taman.", "The children are playing in the park.", "Los niños juegan en el parque."], note: ["TEMAN PALSU: di Indonesia 'budak' berarti hamba sahaya — dalam bahasa Melayu artinya anak.", "FALSE FRIEND: Indonesian 'budak' means a slave; Malay 'budak' simply means a child.", "FALSO AMIGO: en indonesio 'budak' es esclavo; en malayo, niño."] },
  { w: "keputusan", pos: "n", cefr: "B1", ipa: "kəpuˈtusan", g: ["keputusan; hasil", "decision; result", "decisión; resultado"], d: ["Pilihan yang ditetapkan; juga hasil ujian.", "A settled choice; also an exam result.", "Elección tomada; también resultado."], ex: ["Itu keputusan yang sukar.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Dalam bahasa Melayu 'keputusan' juga berarti hasil/nilai ujian.", "In Malay 'keputusan' also means results or scores.", "En malayo 'keputusan' también significa resultados."] },
  { w: "mungkin", pos: "adv", cefr: "B1", ipa: "ˈmuŋkin", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Mungkin dia datang esok.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "nampak", pos: "v", cefr: "B1", ipa: "ˈnampak", g: ["tampak, terlihat", "to seem, to be visible", "parecer, verse"], d: ["Memberi kesan tertentu; juga bisa dilihat.", "To give an impression; also to be visible.", "Dar una impresión; también ser visible."], ex: ["Dia nampak penat.", "Dia tampak lelah.", "He looks tired.", "Parece cansado."] },
  { w: "nasihat", pos: "n", cefr: "B1", ipa: "naˈsihat", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Boleh beri saya nasihat?", "Boleh beri saya nasihat?", "Can you give me some advice?", "¿Me das un consejo?"] },
  { w: "pengalaman", pos: "n", cefr: "B1", ipa: "pəŋaˈlaman", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Dia banyak pengalaman.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "peluang", pos: "n", cefr: "B1", ipa: "pəˈluaŋ", g: ["peluang, kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["Ini peluang yang baik.", "Ini kesempatan yang baik.", "This is a good opportunity.", "Es una buena oportunidad."] },
  { w: "memperbaiki", pos: "v", cefr: "B1", ipa: "məmpərbaˈiki", g: ["memperbaiki", "to improve, to repair", "mejorar, reparar"], d: ["Menjadikan sesuatu lebih baik atau berfungsi lagi.", "To make something better or working again.", "Hacer algo mejor o repararlo."], ex: ["Saya mahu memperbaiki sebutan saya.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "rindu", pos: "v", cefr: "B1", ipa: "ˈrindu", g: ["rindu", "to miss, to long for", "echar de menos"], d: ["Merasa sedih karena sesuatu tidak ada.", "To feel the absence of someone.", "Sentir la ausencia de alguien."], ex: ["Saya rindu keluarga saya.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },
  { w: "terbiasa", pos: "adj", cefr: "B1", ipa: "tərbiˈasa", g: ["terbiasa", "used to, accustomed", "acostumbrado"], d: ["Sudah menjadi kebiasaan sehingga tidak asing lagi.", "So habitual that it no longer feels strange.", "Tan habitual que ya no extraña."], ex: ["Saya sudah terbiasa dengan cuaca panas.", "Saya sudah terbiasa dengan cuaca panas.", "I'm used to the hot weather.", "Ya estoy acostumbrado al calor."] },
  { w: "walaupun", pos: "conj", cefr: "B1", ipa: "walauˈpun", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Walaupun hujan, kami tetap keluar.", "Meskipun hujan, kami tetap keluar.", "Although it's raining, we're going out.", "Aunque llueve, salimos."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "alam sekitar", pos: "n", cefr: "B2", ipa: "ˈalam səˈkitar", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["Kita mesti menjaga alam sekitar.", "Kita harus menjaga lingkungan hidup.", "We must protect the environment.", "Debemos cuidar el medio ambiente."], note: ["Istilah Indonesia: 'lingkungan hidup'.", "The Indonesian term is 'lingkungan hidup'.", "El término indonesio es 'lingkungan hidup'."] },
  { w: "berkesan", pos: "adj", cefr: "B2", ipa: "bərkəˈsan", g: ["mujarab, berdaya guna", "effective", "eficaz"], d: ["Memberi hasil yang nyata.", "Producing a real result.", "Que produce un resultado real."], ex: ["Kaedah ini sangat berkesan.", "Metode ini sangat efektif.", "This method is very effective.", "Este método es muy eficaz."] },
  { w: "cabaran", pos: "n", cefr: "B2", ipa: "tʃaˈbaran", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Ini cabaran yang besar.", "Ini tantangan yang besar.", "That's a big challenge.", "Es un gran desafío."], note: ["Indonesia memakai 'tantangan'.", "Indonesian uses 'tantangan'.", "El indonesio usa 'tantangan'."] },
  { w: "isu", pos: "n", cefr: "B2", ipa: "ˈisu", g: ["isu, persoalan", "issue", "asunto"], d: ["Hal yang sedang dibicarakan atau diperdebatkan.", "The matter under discussion.", "Tema del que se trata."], ex: ["Ini isu yang sensitif.", "Ini isu yang sensitif.", "It's a sensitive issue.", "Es un asunto delicado."] },
  { w: "melaksanakan", pos: "v", cefr: "B2", ipa: "məlaksaˈnakan", g: ["melaksanakan", "to carry out, to implement", "llevar a cabo"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["Kami akan melaksanakan rancangan itu.", "Kami akan melaksanakan rencana itu.", "We'll carry out that plan.", "Llevaremos a cabo ese plan."] },
  { w: "mencapai", pos: "v", cefr: "B2", ipa: "məntʃaˈpai", g: ["mencapai", "to reach, to achieve", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Kami mencapai sasaran.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "menekankan", pos: "v", cefr: "B2", ipa: "mənəkanˈkan", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Beliau menekankan aspek keselamatan.", "Beliau menekankan aspek keselamatan.", "He emphasised the safety aspect.", "Subrayó el aspecto de la seguridad."] },
  { w: "mustahak", pos: "adj", cefr: "B2", ipa: "musˈtahak", g: ["sangat penting", "essential, vital", "esencial"], d: ["Tidak bisa diabaikan sama sekali.", "Impossible to leave out.", "Imposible de omitir."], ex: ["Pasport itu mustahak.", "Paspor itu sangat penting.", "The passport is essential.", "El pasaporte es esencial."] },
  { w: "oleh itu", pos: "conj", cefr: "B2", ipa: "ˈoleh ˈitu", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Hujan turun; oleh itu kami membatalkannya.", "Hujan turun; oleh karena itu kami batalkan.", "It rained; therefore we cancelled.", "Llovió; por lo tanto cancelamos."] },
  { w: "pembangunan", pos: "n", cefr: "B2", ipa: "pəmbaŋuˈnan", g: ["pembangunan", "development", "desarrollo"], d: ["Proses membangun dan memajukan.", "The process of building and advancing.", "Proceso de construir y avanzar."], ex: ["Pembangunan projek itu berjalan lancar.", "Pembangunan proyek itu berjalan lancar.", "The project's development is going smoothly.", "El desarrollo del proyecto va bien."] },
  { w: "perjanjian", pos: "n", cefr: "B2", ipa: "pərdʒanˈdʒian", g: ["perjanjian", "agreement, treaty", "acuerdo"], d: ["Kesepakatan resmi antara dua pihak.", "A formal agreement between two sides.", "Acuerdo formal entre dos partes."], ex: ["Kedua-dua pihak menandatangani perjanjian.", "Kedua pihak menandatangani perjanjian.", "Both sides signed the agreement.", "Ambas partes firmaron el acuerdo."] },
  { w: "walau bagaimanapun", pos: "conj", cefr: "B2", ipa: "ˈwalau baɡaimaˈnapun", g: ["bagaimanapun juga", "however, nevertheless", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Mahal; walau bagaimanapun, ia berbaloi.", "Mahal; bagaimanapun juga, sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "bertujuan", pos: "v", cefr: "C1", ipa: "bərtuˈdʒuan", g: ["bertujuan, demi", "to aim at, for the purpose of", "tener por objeto"], d: ["Menyatakan maksud yang hendak dicapai.", "States the aim being pursued.", "Expresa el objetivo perseguido."], ex: ["Dasar ini bertujuan mengurangkan kos.", "Kebijakan ini bertujuan menurunkan biaya.", "This policy aims to cut costs.", "Esta política busca reducir costes."] },
  { w: "bidang", pos: "n", cefr: "C1", ipa: "ˈbidaŋ", g: ["bidang", "field, domain", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["Dalam bidang undang-undang, keadaannya lain.", "Dalam bidang hukum, keadaannya lain.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "liputan", pos: "n", cefr: "C1", ipa: "liˈputan", g: ["liputan, cakupan", "coverage", "cobertura"], d: ["Seberapa luas sesuatu meliputi atau diberitakan.", "How widely something covers or is reported.", "Hasta dónde abarca o se informa algo."], ex: ["Liputan program itu sangat luas.", "Cakupan program itu sangat luas.", "The programme's coverage is very wide.", "La cobertura del programa es amplia."] },
  { w: "menangani", pos: "v", cefr: "C1", ipa: "mənaˈŋani", g: ["menangani", "to handle, to tackle", "abordar"], d: ["Mengurus dan menyelesaikan suatu masalah.", "To take a problem on and deal with it.", "Ocuparse de un problema."], ex: ["Kita perlu menangani isu ini segera.", "Kita perlu menangani isu ini segera.", "We must tackle this issue at once.", "Debemos abordar este asunto ya."] },
  { w: "mencerminkan", pos: "v", cefr: "C1", ipa: "məntʃərminˈkan", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Data itu mencerminkan peningkatan.", "Data itu mencerminkan peningkatan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "menggalakkan", pos: "v", cefr: "C1", ipa: "məŋɡalakˈkan", g: ["menggalakkan", "to encourage, to promote", "fomentar"], d: ["Membantu sesuatu tumbuh atau lebih sering dilakukan.", "To help something grow or happen more.", "Ayudar a que algo crezca."], ex: ["Undang-undang itu menggalakkan kitar semula.", "Undang-undang itu menggalakkan daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "mengukuhkan", pos: "v", cefr: "C1", ipa: "məŋukuhˈkan", g: ["mengukuhkan", "to consolidate, to strengthen", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Syarikat itu mengukuhkan kedudukannya.", "Perusahaan itu mengukuhkan posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "menonjolkan", pos: "v", cefr: "C1", ipa: "mənondʒolˈkan", g: ["menonjolkan", "to highlight, to foreground", "poner de relieve"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["Laporan itu menonjolkan risiko utama.", "Laporan itu menonjolkan risiko utama.", "The report highlights the main risks.", "El informe destaca los riesgos."] },
  { w: "namun begitu", pos: "conj", cefr: "C1", ipa: "ˈnamun bəˈɡitu", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Namun begitu, cadangan itu masih sah.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "nuansa", pos: "n", cefr: "C1", ipa: "nuˈansa", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau warna.", "A subtle difference in meaning or colour.", "Diferencia sutil de sentido o color."], ex: ["Ada nuansa penting di sini.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "pendekatan", pos: "n", cefr: "C1", ipa: "pəndəˈkatan", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Kita perlukan pendekatan yang berbeza.", "Kita perlu pendekatan yang berbeda.", "We need a different approach.", "Necesitamos otro enfoque."] },
  { w: "teliti", pos: "adj", cefr: "C1", ipa: "təˈliti", g: ["teliti, cermat", "thorough, meticulous", "minucioso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["Analisis yang teliti amat perlu.", "Analisis yang teliti sangat perlu.", "A thorough analysis is needed.", "Hace falta un análisis minucioso."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "angan-angan", pos: "n", cefr: "C2", ipa: "ˈaŋan ˈaŋan", g: ["angan-angan", "wishful thinking, daydream", "ilusión"], d: ["Harapan indah yang belum tentu bisa terwujud.", "A lovely hope that may never come true.", "Ilusión hermosa quizá irrealizable."], ex: ["Janji itu tinggal angan-angan.", "Janji itu tinggal angan-angan.", "That promise remains wishful thinking.", "Esa promesa quedó en ilusión."] },
  { w: "berat sebelah", pos: "phr", cefr: "C2", ipa: "bəˈrat səˈbəlah", g: ["berat sebelah, bias", "one-sided, biased", "parcial"], d: ["Menilai dengan memihak sehingga tidak adil.", "Judging in a way that favours one side.", "Juzgar favoreciendo a una parte."], ex: ["Kajian itu berat sebelah.", "Kajian itu berat sebelah.", "The study is one-sided.", "El estudio es parcial."] },
  { w: "menghuraikan", pos: "v", cefr: "C2", ipa: "məŋhuraiˈkan", g: ["menguraikan", "to expound, to elucidate", "exponer"], d: ["Menjelaskan hal rumit bagian demi bagian.", "To explain something complex part by part.", "Explicar algo complejo por partes."], ex: ["Beliau menghuraikan kaedah itu dengan terperinci.", "Beliau menguraikan metode itu secara rinci.", "He expounded the method in detail.", "Expuso el método en detalle."] },
  { w: "mengelak", pos: "v", cefr: "C2", ipa: "məŋəˈlak", g: ["mengelak", "to dodge, to evade", "eludir"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto sin afrontarlo."], ex: ["Dia mengelak daripada menjawab.", "Dia mengelak menjawab.", "He dodged answering.", "Eludió responder."] },
  { w: "memperlekehkan", pos: "v", cefr: "C2", ipa: "məmpərləkehˈkan", g: ["meremehkan", "to belittle, to disparage", "menospreciar"], d: ["Menganggap sesuatu lebih rendah nilainya.", "To treat something as worth less than it is.", "Tratar algo como de menor valor."], ex: ["Jangan memperlekehkan usahanya.", "Jangan meremehkan usahanya.", "Don't belittle her effort.", "No menosprecies su esfuerzo."] },
  { w: "mercu tanda", pos: "n", cefr: "C2", ipa: "ˈmərtʃu ˈtanda", g: ["mercusuar, tonggak", "landmark, milestone", "hito"], d: ["Penanda penting yang menjadi rujukan.", "A prominent marker others navigate by.", "Marca destacada que sirve de referencia."], ex: ["Perjanjian itu menjadi mercu tanda sejarah.", "Perjanjian itu menjadi tonggak sejarah.", "The treaty became a historic landmark.", "El tratado fue un hito histórico."] },
  { w: "mendesak", pos: "adj", cefr: "C2", ipa: "məndəˈsak", g: ["mendesak", "urgent, pressing", "urgente"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["Ini perkara yang mendesak.", "Ini perkara yang mendesak.", "This is a pressing matter.", "Es un asunto urgente."] },
  { w: "paradigma", pos: "n", cefr: "C2", ipa: "paraˈdiɡma", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Itu satu anjakan paradigma.", "Itu sebuah pergeseran paradigma.", "That was a paradigm shift.", "Fue un cambio de paradigma."], note: ["Istilah Melayu 'anjakan paradigma' = pergeseran paradigma.", "Malay says 'anjakan paradigma' for a paradigm shift.", "En malayo 'anjakan paradigma' es cambio de paradigma."] },
  { w: "secebis", pos: "det", cefr: "C2", ipa: "səˈtʃəbis", g: ["secuil, secercah", "a shred of, a scrap of", "un ápice de"], d: ["Bagian yang sangat kecil dari sesuatu.", "A very small piece of something.", "Una parte mínima de algo."], ex: ["Masih ada secebis harapan.", "Masih ada secercah harapan.", "There's still a shred of hope.", "Aún queda un ápice de esperanza."] },
  { w: "tak terperi", pos: "adj", cefr: "C2", ipa: "tak tərˈpəri", g: ["tak terkatakan", "beyond words, indescribable", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Dia gembira tak terperi.", "Dia gembira tak terkira.", "She was happy beyond words.", "Estaba feliz más allá de las palabras."] },
  { w: "tidak dapat dielakkan", pos: "phr", cefr: "C2", ipa: "ˈtidak ˈdapat diəlakˈkan", g: ["tak terhindarkan", "unavoidable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Kenaikan harga tidak dapat dielakkan.", "Kenaikan harga tak terhindarkan.", "A price rise is unavoidable.", "La subida es inevitable."] },
  { w: "dari sudut", pos: "phr", cefr: "C2", ipa: "ˈdari ˈsudut", g: ["dari segi", "from the standpoint of", "desde el punto de vista de"], d: ["Membatasi penilaian pada satu sudut pandang.", "Limits a judgement to one standpoint.", "Limita el juicio a un punto de vista."], ex: ["Dari sudut kos, ia pilihan terbaik.", "Dari segi biaya, itu pilihan terbaik.", "From the standpoint of cost, it's the best option.", "Desde el punto de vista del coste, es lo mejor."] },
];
