/* =========================================================================
   lexicon/nl.js — Woordenboek: Nederlands. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Belanda berdiri di antara Inggris dan Jerman: kosakatanya sering terasa akrab bagi penutur Inggris, tetapi tata kalimatnya bekerja seperti bahasa Jerman.",
    "Dutch sits between English and German: the vocabulary often looks familiar to English speakers, while the sentence structure behaves like German.",
    "El neerlandés está entre el inglés y el alemán: el vocabulario suena familiar al angloparlante, pero la sintaxis funciona como en alemán.",
  ],
  script: [
    "Abjad Latin 26 huruf; ij dianggap satu kesatuan dan ditulis besar bersama (IJsland). Tekanan umumnya di suku kata pertama.",
    "The 26-letter Latin alphabet; ij counts as one unit and is capitalised together (IJsland). Stress usually falls on the first syllable.",
    "Alfabeto latino de 26 letras; ij cuenta como una unidad y se escribe en mayúscula junta (IJsland). El acento suele ir en la primera sílaba.",
  ],
  pron: [
    ["g / ch", "Bunyi serak /x/ dari tenggorokan — ciri paling khas: goed, nacht.", "A rasping /x/ from the throat — the most characteristic sound: goed, nacht.", "Una /x/ áspera de garganta, el sonido más típico: goed, nacht."],
    ["ui", "Vokal khas Belanda, antara 'au' dan 'ei': huis, uit.", "A uniquely Dutch vowel, between 'ow' and 'ay': huis, uit.", "Vocal propia del neerlandés, entre 'au' y 'ei': huis, uit."],
    ["ij / ei", "Keduanya berbunyi sama /ɛi/: mijn, klein.", "Both sound the same, /ɛi/: mijn, klein.", "Ambas suenan igual, /ɛi/: mijn, klein."],
    ["oe", "Dibaca /u/ seperti 'u' Indonesia: boek, moeder.", "Pronounced /u/ as in 'book': boek, moeder.", "Se pronuncia /u/ como en 'uso': boek, moeder."],
    ["v / w", "v mendekati /f/, w mendekati /ʋ/ (antara v dan w Inggris).", "v leans towards /f/; w is /ʋ/, between English v and w.", "v tiende a /f/; w es /ʋ/, entre la v y la w inglesas."],
    ["-en akhir", "Akhiran -en biasanya diucapkan /ə/ saja: lopen → 'lope'.", "The ending -en is usually just /ə/: lopen → 'lope'.", "La terminación -en suele ser solo /ə/: lopen → 'lope'."],
  ],
  grammar: [
    {
      t: ["de atau het", "de or het", "de o het"],
      d: ["Hanya ada dua artikel tentu: de (umum) dan het (netral). Tidak ada aturan pasti — hafalkan bersama kata bendanya.", "There are only two definite articles: de (common) and het (neuter). No reliable rule exists — learn them with the noun.", "Solo hay dos artículos definidos: de y het. No hay regla fiable: apréndelos con el sustantivo."],
      ex: "de tafel · het boek · een boek",
    },
    {
      t: ["Kata kerja di posisi kedua", "Verb second", "El verbo en segunda posición"],
      d: ["Dalam kalimat pernyataan, kata kerja terkonjugasi selalu unsur kedua.", "In a statement the conjugated verb is always the second element.", "En una afirmación el verbo conjugado es el segundo elemento."],
      ex: "Morgen ga ik naar Amsterdam.",
    },
    {
      t: ["Kata kerja ke ujung", "The verb goes to the end", "El verbo va al final"],
      d: ["Dalam anak kalimat (omdat, dat, als) kata kerjanya pindah ke akhir.", "In a subordinate clause (omdat, dat, als) the verb moves to the end.", "En subordinadas (omdat, dat, als) el verbo va al final."],
      ex: "Ik blijf thuis omdat het regent.",
    },
    {
      t: ["Kata sifat + e", "Adjectives take -e", "El adjetivo toma -e"],
      d: ["Kata sifat mendapat -e sebelum kata benda, kecuali pada het-woord tanpa artikel tentu.", "Adjectives add -e before a noun, except with an indefinite het-word.", "El adjetivo añade -e ante sustantivo, salvo con het indefinido."],
      ex: "de grote tafel · een groot huis",
    },
    {
      t: ["Er — kata kecil yang penting", "er — the small essential word", "er, la palabra clave"],
      d: ["er menyatakan 'ada', menggantikan tempat, dan menahan posisi subjek — sulit tetapi wajib.", "er expresses 'there is', replaces places, and holds the subject slot — tricky but essential.", "er expresa 'hay', sustituye lugares y ocupa el lugar del sujeto."],
      ex: "Er is een probleem. · Ik woon er al jaren.",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "huis", pos: "n", cefr: "A1", gen: "het", ipa: "ɦœys", g: ["rumah", "house", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Ons huis heeft een tuin.", "Rumah kami punya taman.", "Our house has a garden.", "Nuestra casa tiene jardín."] },
  { w: "dag", pos: "n", cefr: "A1", gen: "de", ipa: "dɑx", g: ["hari; halo", "day; hello", "día; hola"], d: ["Waktu 24 jam; juga sapaan singkat.", "A period of 24 hours; also a short greeting.", "Periodo de 24 horas; también un saludo."], ex: ["Ik werk elke dag.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["nacht"] },
  { w: "nacht", pos: "n", cefr: "A1", gen: "de", ipa: "nɑxt", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Goedenacht!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["dag"] },
  { w: "man", pos: "n", cefr: "A1", gen: "de", ipa: "mɑn", g: ["laki-laki; suami", "man; husband", "hombre; marido"], d: ["Manusia dewasa laki-laki; juga suami.", "An adult male; also a husband.", "Hombre adulto; también marido."], ex: ["Die man is mijn buurman.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["vrouw"] },
  { w: "vrouw", pos: "n", cefr: "A1", gen: "de", ipa: "vrɑu", g: ["perempuan; istri", "woman; wife", "mujer; esposa"], d: ["Manusia dewasa perempuan; juga istri.", "An adult female; also a wife.", "Mujer adulta; también esposa."], ex: ["Zijn vrouw is arts.", "Istrinya seorang dokter.", "His wife is a doctor.", "Su mujer es médica."], ant: ["man"] },
  { w: "vriend", pos: "n", cefr: "A1", gen: "de", ipa: "vrint", g: ["teman; pacar", "friend; boyfriend", "amigo; novio"], d: ["Orang dekat; dengan kata milik bisa berarti pacar.", "A close person; with a possessive it can mean boyfriend.", "Persona cercana; con posesivo puede ser novio."], ex: ["Ik ga uit met een vriend.", "Saya keluar dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."] },
  { w: "groot", pos: "adj", cefr: "A1", ipa: "ɣroːt", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Zij wonen in een grote stad.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["klein"] },
  { w: "klein", pos: "adj", cefr: "A1", ipa: "klɛin", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Ik heb een klein appartement.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["groot"] },
  { w: "goed", pos: "adj", cefr: "A1", ipa: "ɣut", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["Dat is een goed idee.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["slecht"] },
  { w: "hebben", pos: "v", cefr: "A1", ipa: "ˈɦɛbə", g: ["punya", "to have", "tener"], d: ["Memiliki sesuatu.", "To possess something.", "Poseer algo."], ex: ["Ik heb twee zussen.", "Saya punya dua saudara perempuan.", "I have two sisters.", "Tengo dos hermanas."] },
  { w: "willen", pos: "v", cefr: "A1", ipa: "ˈʋɪlə", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Ik wil Nederlands leren.", "Saya mau belajar bahasa Belanda.", "I want to learn Dutch.", "Quiero aprender neerlandés."] },
  { w: "gaan", pos: "v", cefr: "A1", ipa: "ɣaːn", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Ik ga naar de markt.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "werk", pos: "n", cefr: "A2", gen: "het", ipa: "ʋɛrk", g: ["pekerjaan", "work", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Mijn werk begint om negen uur.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "geld", pos: "n", cefr: "A2", gen: "het", ipa: "ɣɛlt", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Ik heb niet genoeg geld.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "tijd", pos: "n", cefr: "A2", gen: "de", ipa: "tɛit", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["Ik heb vandaag geen tijd.", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "stad", pos: "n", cefr: "A2", gen: "de", ipa: "stɑt", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Utrecht is een mooie stad.", "Utrecht kota yang indah.", "Utrecht is a beautiful city.", "Utrecht es una ciudad bonita."] },
  { w: "helpen", pos: "v", cefr: "A2", ipa: "ˈɦɛlpə", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Kun je me helpen, alsjeblieft?", "Bisakah kamu menolong saya?", "Can you help me, please?", "¿Puedes ayudarme, por favor?"] },
  { w: "nodig hebben", pos: "v", cefr: "A2", ipa: "ˈnoːdəx ˈɦɛbə", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Ik heb rust nodig.", "Saya butuh istirahat.", "I need some rest.", "Necesito descanso."], note: ["nodig berdiri terpisah dari hebben dan biasanya di akhir kalimat.", "nodig stands apart from hebben and usually sits at the end of the clause.", "nodig se separa de hebben y suele ir al final."] },
  { w: "beginnen", pos: "v", cefr: "A2", ipa: "bəˈɣɪnə", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["De film begint om acht uur.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["stoppen"] },
  { w: "makkelijk", pos: "adj", cefr: "A2", ipa: "ˈmɑkələk", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["Het examen was makkelijk.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["moeilijk"] },
  { w: "moeilijk", pos: "adj", cefr: "A2", ipa: "ˈmujlək", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Hier parkeren is moeilijk.", "Parkir di sini sulit.", "Parking here is difficult.", "Aparcar aquí es difícil."], ant: ["makkelijk"] },
  { w: "snel", pos: "adj", cefr: "A2", ipa: "snɛl", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["De trein is sneller.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["langzaam"] },
  { w: "altijd", pos: "adv", cefr: "A2", ipa: "ˈɑltɛit", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Ik ontbijt altijd thuis.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["nooit"] },
  { w: "omdat", pos: "conj", cefr: "A2", ipa: "ɔmˈdɑt", g: ["karena", "because", "porque"], d: ["Menyatakan sebab; kata kerja pindah ke akhir.", "Introduces a reason; the verb moves to the end.", "Introduce la causa; el verbo va al final."], ex: ["Ik blijf thuis omdat het regent.", "Saya di rumah karena hujan.", "I'm staying home because it's raining.", "Me quedo en casa porque llueve."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "ervaring", pos: "n", cefr: "B1", gen: "de", ipa: "ɛrˈvaːrɪŋ", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Zij heeft veel ervaring.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "beslissing", pos: "n", cefr: "B1", gen: "de", ipa: "bəˈslɪsɪŋ", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Dat was een moeilijke beslissing.", "Itu keputusan yang sulit.", "That was a hard decision.", "Fue una decisión difícil."] },
  { w: "kans", pos: "n", cefr: "B1", gen: "de", ipa: "kɑns", g: ["kesempatan; peluang", "chance, opportunity", "oportunidad"], d: ["Saat yang tepat; juga kemungkinan terjadinya sesuatu.", "A good moment; also the likelihood of something.", "Momento propicio; también probabilidad."], ex: ["Dit is een mooie kans.", "Ini kesempatan bagus.", "This is a great chance.", "Es una buena oportunidad."] },
  { w: "advies", pos: "n", cefr: "B1", gen: "het", ipa: "ɑtˈvis", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Mag ik je een advies geven?", "Boleh saya beri nasihat?", "May I give you some advice?", "¿Puedo darte un consejo?"] },
  { w: "verbeteren", pos: "v", cefr: "B1", ipa: "vərˈbeːtərə", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Ik wil mijn uitspraak verbeteren.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "lukken", pos: "v", cefr: "B1", ipa: "ˈlʏkə", g: ["berhasil", "to succeed, to work out", "salir bien"], d: ["Berjalan sesuai harapan.", "To turn out as hoped.", "Salir como se esperaba."], ex: ["Het is me gelukt!", "Saya berhasil!", "I managed it!", "¡Lo conseguí!"], note: ["Dipakai tanpa pelaku manusia: het lukt mij, bukan ik luk.", "Used impersonally: het lukt mij, never ik luk.", "Se usa impersonalmente: het lukt mij, no ik luk."] },
  { w: "lijken", pos: "v", cefr: "B1", ipa: "ˈlɛikə", g: ["tampak; mirip", "to seem; to resemble", "parecer"], d: ["Memberi kesan tertentu; juga menyerupai.", "To give an impression; also to resemble.", "Dar una impresión; también asemejarse."], ex: ["Hij lijkt moe.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "hoewel", pos: "conj", cefr: "B1", ipa: "huˈʋɛl", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras; kata kerja ke akhir.", "Marks a contrast; the verb goes to the end.", "Marca contraste; el verbo va al final."], ex: ["Hoewel het regent, gaan we naar buiten.", "Meskipun hujan, kami keluar.", "Although it's raining, we're going out.", "Aunque llueve, salimos."] },
  { w: "echter", pos: "adv", cefr: "B1", ipa: "ˈɛxtər", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Het is duur; het is echter de moeite waard.", "Mahal; namun begitu sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "misschien", pos: "adv", cefr: "B1", ipa: "mɪˈsxin", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Misschien komt hij morgen.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "wennen", pos: "v", cefr: "B1", ipa: "ˈʋɛnə", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Ik moet nog wennen aan het weer.", "Saya masih harus membiasakan diri dengan cuacanya.", "I still have to get used to the weather.", "Aún tengo que acostumbrarme al clima."] },
  { w: "missen", pos: "v", cefr: "B1", ipa: "ˈmɪsə", g: ["merindukan; ketinggalan", "to miss (someone; a train)", "echar de menos; perder"], d: ["Merasa kehilangan; juga terlambat naik kendaraan.", "To feel someone's absence; also to be too late for a train.", "Sentir la ausencia; también perder un tren."], ex: ["Ik mis mijn familie.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "ontwikkeling", pos: "n", cefr: "B2", gen: "de", ipa: "ɔntˈʋɪkəlɪŋ", g: ["perkembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["De ontwikkeling verloopt goed.", "Perkembangannya berjalan baik.", "The development is going well.", "El desarrollo va bien."] },
  { w: "milieu", pos: "n", cefr: "B2", gen: "het", ipa: "miˈljø", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["We moeten het milieu beschermen.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "uitdaging", pos: "n", cefr: "B2", gen: "de", ipa: "ˈœydaːɣɪŋ", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Dat is een echte uitdaging.", "Ini benar-benar tantangan.", "That's a real challenge.", "Es todo un desafío."] },
  { w: "afspraak", pos: "n", cefr: "B2", gen: "de", ipa: "ˈɑfspraːk", g: ["kesepakatan; janji temu", "agreement; appointment", "acuerdo; cita"], d: ["Kesepakatan bersama; juga jadwal bertemu.", "A mutual agreement; also a scheduled meeting.", "Acuerdo mutuo; también una cita."], ex: ["We hebben een afspraak gemaakt.", "Kami membuat kesepakatan.", "We made an agreement.", "Hicimos un acuerdo."] },
  { w: "bereiken", pos: "v", cefr: "B2", ipa: "bəˈrɛikə", g: ["mencapai", "to reach, to achieve", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["We hebben het doel bereikt.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "benadrukken", pos: "v", cefr: "B2", ipa: "bəˈnaːdrʏkə", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Hij benadrukte de veiligheid.", "Dia menekankan keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "betrouwbaar", pos: "adj", cefr: "B2", ipa: "bəˈtrʌubaːr", g: ["dapat diandalkan", "reliable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Het is een betrouwbare bron.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "onmisbaar", pos: "adj", cefr: "B2", ipa: "ɔnˈmɪsbaːr", g: ["mutlak perlu", "indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Een paspoort is onmisbaar.", "Paspor mutlak diperlukan.", "A passport is indispensable.", "El pasaporte es imprescindible."] },
  { w: "ondanks", pos: "prep", cefr: "B2", ipa: "ɔnˈdɑŋks", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Ondanks de kou zijn we gegaan.", "Meski dingin, kami tetap pergi.", "Despite the cold we went.", "A pesar del frío fuimos."] },
  { w: "daarom", pos: "conj", cefr: "B2", ipa: "ˈdaːrɔm", g: ["karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Het regende; daarom bleven we thuis.", "Hujan; karena itu kami di rumah.", "It rained; therefore we stayed home.", "Llovía; por eso nos quedamos en casa."] },
  { w: "kwestie", pos: "n", cefr: "B2", gen: "de", ipa: "ˈkʋɛsti", g: ["persoalan", "matter, issue", "cuestión"], d: ["Hal yang sedang dibicarakan atau ditangani.", "The matter under discussion.", "Tema del que se trata."], ex: ["Dat is een gevoelige kwestie.", "Itu perkara yang sensitif.", "That's a delicate matter.", "Es una cuestión delicada."] },
  { w: "uitvoeren", pos: "v", cefr: "B2", ipa: "ˈœytvurə", g: ["melaksanakan", "to carry out, to implement", "ejecutar"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["We voeren het plan volgende week uit.", "Kami laksanakan rencananya minggu depan.", "We'll carry out the plan next week.", "Ejecutaremos el plan la próxima semana."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "gebied", pos: "n", cefr: "C1", gen: "het", ipa: "ɣəˈbit", g: ["bidang; wilayah", "field; area", "ámbito; territorio"], d: ["Wilayah kegiatan atau pengetahuan; juga daerah.", "An area of activity or knowledge; also a region.", "Área de actividad o conocimiento; también región."], ex: ["Op juridisch gebied ligt het anders.", "Dalam bidang hukum hal itu berbeda.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "aanpak", pos: "n", cefr: "C1", gen: "de", ipa: "ˈaːnpɑk", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["We hebben een andere aanpak nodig.", "Kita butuh pendekatan lain.", "We need a different approach.", "Necesitamos otro enfoque."] },
  { w: "nuance", pos: "n", cefr: "C1", gen: "de", ipa: "nyˈaːsə", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["Er zit een belangrijke nuance in.", "Ada nuansa penting di dalamnya.", "There's an important nuance in it.", "Hay un matiz importante."] },
  { w: "aanpakken", pos: "v", cefr: "C1", ipa: "ˈaːnpɑkə", g: ["menangani", "to tackle, to address", "abordar"], d: ["Mulai menghadapi masalah secara langsung.", "To start dealing with a problem head-on.", "Empezar a afrontar un problema."], ex: ["We moeten dit probleem aanpakken.", "Kita harus menangani masalah ini.", "We must tackle this problem.", "Debemos abordar este problema."] },
  { w: "bevorderen", pos: "v", cefr: "C1", ipa: "bəˈvɔrdərə", g: ["mendorong", "to promote, to foster", "fomentar"], d: ["Membantu sesuatu tumbuh atau berkembang.", "To help something grow.", "Ayudar a que algo crezca."], ex: ["De wet bevordert recycling.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "weerspiegelen", pos: "v", cefr: "C1", ipa: "ˈʋeːrspiɣələ", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["De cijfers weerspiegelen een verbetering.", "Angkanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "grondig", pos: "adj", cefr: "C1", ipa: "ˈɣrɔndəx", g: ["menyeluruh, teliti", "thorough", "minucioso"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest detail.", "Hecho hasta el último detalle."], ex: ["Een grondige analyse is nodig.", "Analisis menyeluruh diperlukan.", "A thorough analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "niettemin", pos: "conj", cefr: "C1", ipa: "nitəˈmɪn", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Niettemin blijft het voorstel staan.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue en pie."] },
  { w: "teneinde", pos: "prep", cefr: "C1", ipa: "tənˈɛində", g: ["demi, agar", "in order to", "a fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["Teneinde tijd te besparen, vereenvoudigen we.", "Demi menghemat waktu, kami sederhanakan.", "In order to save time, we simplify.", "A fin de ahorrar tiempo, simplificamos."] },
  { w: "verstevigen", pos: "v", cefr: "C1", ipa: "vərˈsteːvəɣə", g: ["memperkukuh", "to strengthen, to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Het bedrijf versterkte zijn positie.", "Perusahaan memperkukuh posisinya.", "The company strengthened its position.", "La empresa consolidó su posición."] },
  { w: "reikwijdte", pos: "n", cefr: "C1", gen: "de", ipa: "ˈrɛikʋɛitə", g: ["jangkauan", "scope, reach", "alcance"], d: ["Seberapa jauh dampak sesuatu terasa.", "How far something's effect reaches.", "Hasta dónde llega el efecto."], ex: ["De reikwijdte is enorm.", "Jangkauannya luar biasa.", "The scope is enormous.", "El alcance es enorme."] },
  { w: "belichten", pos: "v", cefr: "C1", ipa: "bəˈlɪxtə", g: ["menyoroti", "to highlight, to shed light on", "poner de relieve"], d: ["Menerangi sisi tertentu agar diperhatikan.", "To shine light on one aspect so it is noticed.", "Iluminar un aspecto para que se note."], ex: ["Het rapport belicht de risico's.", "Laporan itu menyoroti risikonya.", "The report sheds light on the risks.", "El informe pone de relieve los riesgos."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "deur", pos: "n", cefr: "A1", gen: "de", ipa: "døːr", g: ["pintu", "door", "puerta"] },
  { w: "raam", pos: "n", cefr: "A1", gen: "het", ipa: "raːm", g: ["jendela", "window", "ventana"] },
  { w: "kamer", pos: "n", cefr: "A1", gen: "de", ipa: "ˈkaː.mər", g: ["kamar, ruangan", "room", "habitación"] },
  { w: "tafel", pos: "n", cefr: "A1", gen: "de", ipa: "ˈtaː.fəl", g: ["meja", "table", "mesa"] },
  { w: "stoel", pos: "n", cefr: "A1", gen: "de", ipa: "stuːl", g: ["kursi", "chair", "silla"] },
  { w: "bed", pos: "n", cefr: "A1", gen: "het", ipa: "bɛt", g: ["tempat tidur", "bed", "cama"] },
  { w: "keuken", pos: "n", cefr: "A1", gen: "de", ipa: "ˈkøː.kə", g: ["dapur", "kitchen", "cocina"] },
  { w: "badkamer", pos: "n", cefr: "A1", gen: "de", ipa: "ˈbɑtˌkaː.mər", g: ["kamar mandi", "bathroom", "cuarto de baño"] },
  { w: "lamp", pos: "n", cefr: "A1", gen: "de", ipa: "lɑmp", g: ["lampu", "lamp", "lámpara"] },
  { w: "sleutel", pos: "n", cefr: "A1", gen: "de", ipa: "ˈsløː.təl", g: ["kunci", "key", "llave"] },
  { w: "muur", pos: "n", cefr: "A1", gen: "de", ipa: "myːr", g: ["dinding, tembok", "wall", "pared"] },
  { w: "dak", pos: "n", cefr: "A1", gen: "het", ipa: "dɑk", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "brood", pos: "n", cefr: "A1", gen: "het", ipa: "broːt", g: ["roti", "bread", "pan"] },
  { w: "rijst", pos: "n", cefr: "A1", gen: "de", ipa: "rɛist", g: ["nasi, beras", "rice", "arroz"] },
  { w: "vlees", pos: "n", cefr: "A1", gen: "het", ipa: "vleːs", g: ["daging", "meat", "carne"] },
  { w: "vis", pos: "n", cefr: "A1", gen: "de", ipa: "vɪs", g: ["ikan", "fish", "pescado"] },
  { w: "ei", pos: "n", cefr: "A1", gen: "het", ipa: "ɛi", g: ["telur", "egg", "huevo"] },
  { w: "melk", pos: "n", cefr: "A1", gen: "de", ipa: "mɛlk", g: ["susu", "milk", "leche"] },
  { w: "thee", pos: "n", cefr: "A1", gen: "de", ipa: "teː", g: ["teh", "tea", "té"] },
  { w: "koffie", pos: "n", cefr: "A1", gen: "de", ipa: "ˈkɔ.fi", g: ["kopi", "coffee", "café"] },
  { w: "suiker", pos: "n", cefr: "A1", gen: "de", ipa: "ˈsœy.kər", g: ["gula", "sugar", "azúcar"] },
  { w: "zout", pos: "n", cefr: "A1", gen: "het", ipa: "zɑut", g: ["garam", "salt", "sal"] },
  { w: "fruit", pos: "n", cefr: "A1", gen: "het", ipa: "frœyt", g: ["buah", "fruit", "fruta"] },
  { w: "groente", pos: "n", cefr: "A1", gen: "de", ipa: "ˈɣrun.tə", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "hemd", pos: "n", cefr: "A2", gen: "het", ipa: "hɛmt", g: ["kemeja", "shirt", "camisa"] },
  { w: "broek", pos: "n", cefr: "A2", gen: "de", ipa: "bruk", g: ["celana", "trousers", "pantalón"] },
  { w: "schoen", pos: "n", cefr: "A2", gen: "de", ipa: "sxun", g: ["sepatu", "shoe", "zapato"] },
  { w: "hoed", pos: "n", cefr: "A2", gen: "de", ipa: "ɦut", g: ["topi", "hat", "sombrero"] },
  { w: "hand", pos: "n", cefr: "A2", gen: "de", ipa: "hɑnt", g: ["tangan", "hand", "mano"] },
  { w: "oog", pos: "n", cefr: "A2", gen: "het", ipa: "oːx", g: ["mata", "eye", "ojo"] },
  { w: "hoofd", pos: "n", cefr: "A2", gen: "het", ipa: "hoːft", g: ["kepala", "head", "cabeza"] },
  { w: "hart", pos: "n", cefr: "A2", gen: "het", ipa: "hɑrt", g: ["jantung, hati", "heart", "corazón"] },
  { w: "haar", pos: "n", cefr: "A2", gen: "het", ipa: "haːr", g: ["rambut", "hair", "pelo"] },
  { w: "tand", pos: "n", cefr: "A2", gen: "de", ipa: "tɑnt", g: ["gigi", "tooth", "diente"] },
  { w: "oor", pos: "n", cefr: "A2", gen: "het", ipa: "oːr", g: ["telinga", "ear", "oreja"] },
  { w: "gezicht", pos: "n", cefr: "A2", gen: "het", ipa: "ɣəˈzɪxt", g: ["wajah; penglihatan", "face; sight", "cara; vista"] },
  /* -- alam & hewan -- */
  { w: "boom", pos: "n", cefr: "A2", gen: "de", ipa: "boːm", g: ["pohon", "tree", "árbol"] },
  { w: "bloem", pos: "n", cefr: "A2", gen: "de", ipa: "blum", g: ["bunga", "flower", "flor"] },
  { w: "berg", pos: "n", cefr: "A2", gen: "de", ipa: "bɛrx", g: ["gunung", "mountain", "montaña"] },
  { w: "rivier", pos: "n", cefr: "A2", gen: "de", ipa: "riˈviːr", g: ["sungai", "river", "río"] },
  { w: "zee", pos: "n", cefr: "A2", gen: "de", ipa: "zeː", g: ["laut", "sea", "mar"] },
  { w: "hemel", pos: "n", cefr: "A2", gen: "de", ipa: "ˈɦeː.məl", g: ["langit; surga", "sky; heaven", "cielo"] },
  { w: "ster", pos: "n", cefr: "A2", gen: "de", ipa: "stɛr", g: ["bintang", "star", "estrella"] },
  { w: "hond", pos: "n", cefr: "A2", gen: "de", ipa: "ɦɔnt", g: ["anjing", "dog", "perro"] },
  { w: "kat", pos: "n", cefr: "A2", gen: "de", ipa: "kɑt", g: ["kucing", "cat", "gato"] },
  { w: "vogel", pos: "n", cefr: "A2", gen: "de", ipa: "ˈvoː.ɣəl", g: ["burung", "bird", "pájaro"] },
  { w: "paard", pos: "n", cefr: "A2", gen: "het", ipa: "paːrt", g: ["kuda", "horse", "caballo"] },
  { w: "regen", pos: "n", cefr: "A2", gen: "de", ipa: "ˈreː.ɣə", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "straat", pos: "n", cefr: "B1", gen: "de", ipa: "straːt", g: ["jalan", "street", "calle"] },
  { w: "brug", pos: "n", cefr: "B1", gen: "de", ipa: "brʏx", g: ["jembatan", "bridge", "puente"] },
  { w: "markt", pos: "n", cefr: "B1", gen: "de", ipa: "mɑrkt", g: ["pasar", "market", "mercado"] },
  { w: "school", pos: "n", cefr: "B1", gen: "de", ipa: "sxoːl", g: ["sekolah", "school", "escuela"] },
  { w: "ziekenhuis", pos: "n", cefr: "B1", gen: "het", ipa: "ˈziː.kən.ɦœys", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "kantoor", pos: "n", cefr: "B1", gen: "het", ipa: "kɑnˈtoːr", g: ["kantor", "office", "oficina"] },
  { w: "bus", pos: "n", cefr: "B1", gen: "de", ipa: "bʏs", g: ["bus", "bus", "autobús"] },
  { w: "trein", pos: "n", cefr: "B1", gen: "de", ipa: "trɛin", g: ["kereta api", "train", "tren"] },
  { w: "auto", pos: "n", cefr: "B1", gen: "de", ipa: "ˈɔu.to", g: ["mobil", "car", "coche"] },
  { w: "fiets", pos: "n", cefr: "B1", gen: "de", ipa: "fits", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "luchthaven", pos: "n", cefr: "B1", gen: "de", ipa: "ˈlʏxtˌɦaː.və", g: ["bandara", "airport", "aeropuerto"] },
  { w: "kaartje", pos: "n", cefr: "B1", gen: "het", ipa: "ˈkaːr.tjə", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "bedrijf", pos: "n", cefr: "B2", gen: "het", ipa: "bəˈdrɛif", g: ["perusahaan", "company", "empresa"] },
  { w: "vergadering", pos: "n", cefr: "B2", gen: "de", ipa: "vərˈɣaː.də.rɪŋ", g: ["rapat", "meeting", "reunión"] },
  { w: "contract", pos: "n", cefr: "B2", gen: "het", ipa: "kɔnˈtrɑkt", g: ["kontrak", "contract", "contrato"] },
  { w: "salaris", pos: "n", cefr: "B2", gen: "het", ipa: "saːˈlaː.rɪs", g: ["gaji", "salary", "sueldo"] },
  { w: "prijs", pos: "n", cefr: "B2", gen: "de", ipa: "prɛis", g: ["harga; hadiah", "price; prize", "precio; premio"] },
  { w: "belasting", pos: "n", cefr: "B2", gen: "de", ipa: "bəˈlɑs.tɪŋ", g: ["pajak", "tax", "impuesto"] },
  { w: "bank", pos: "n", cefr: "B2", gen: "de", ipa: "bɑŋk", g: ["bank; bangku", "bank; bench", "banco"] },
  { w: "computer", pos: "n", cefr: "B2", gen: "de", ipa: "kɔmˈpjuː.tər", g: ["komputer", "computer", "ordenador"] },
  { w: "telefoon", pos: "n", cefr: "B2", gen: "de", ipa: "teː.ləˈfoːn", g: ["telepon", "telephone", "teléfono"] },
  { w: "e-mail", pos: "n", cefr: "B2", gen: "de", ipa: "ˈiː.meːl", g: ["surel, email", "email", "correo electrónico"] },
  { w: "bestand", pos: "n", cefr: "B2", gen: "het", ipa: "bəˈstɑnt", g: ["berkas", "file", "archivo"] },
  { w: "wachtwoord", pos: "n", cefr: "B2", gen: "het", ipa: "ˈwɑxtˌwoːrt", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "paradigma", pos: "n", cefr: "C2", gen: "het", ipa: "paːraːˈdɪɣmaː", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Dat was een paradigmawisseling.", "Itu pergeseran paradigma.", "That was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "ontwijken", pos: "v", cefr: "C2", ipa: "ɔntˈʋɛikə", g: ["mengelak", "to evade, to dodge", "eludir"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue rather than face it.", "Evitar un asunto sin afrontarlo."], ex: ["Hij ontweek de vraag.", "Dia mengelak dari pertanyaan itu.", "He dodged the question.", "Eludió la pregunta."] },
  { w: "toelichten", pos: "v", cefr: "C2", ipa: "ˈtulɪxtə", g: ["menguraikan", "to elucidate, to explain further", "explicar en detalle"], d: ["Menjelaskan lebih lanjut agar terang.", "To explain further so it becomes clear.", "Explicar más para aclarar."], ex: ["Kunt u dat nader toelichten?", "Bisakah Anda menguraikannya lebih lanjut?", "Could you elucidate that further?", "¿Podría explicarlo con más detalle?"] },
  { w: "onuitsprekelijk", pos: "adj", cefr: "C2", ipa: "ɔnˈœytspreːkələk", g: ["tak terlukiskan", "ineffable, unspeakable", "inefable"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Een onuitsprekelijke vreugde.", "Sukacita yang tak terlukiskan.", "An ineffable joy.", "Una alegría inefable."] },
  { w: "dwingend", pos: "adj", cefr: "C2", ipa: "ˈdʋɪŋənt", g: ["memaksa, mengikat", "compelling, mandatory", "imperativo"], d: ["Tak menyisakan pilihan lain.", "Leaving no other option.", "Que no deja otra opción."], ex: ["Dat is geen dwingende reden.", "Itu bukan alasan yang memaksa.", "That is not a compelling reason.", "No es una razón imperativa."] },
  { w: "sprankje", pos: "n", cefr: "C2", gen: "het", ipa: "ˈsprɑŋkjə", g: ["secercah", "glimmer, spark", "chispa, destello"], d: ["Tanda sangat kecil dari sesuatu.", "A very faint sign of something.", "Señal muy leve de algo."], ex: ["Er is nog een sprankje hoop.", "Masih ada secercah harapan.", "There's still a glimmer of hope.", "Aún queda un destello de esperanza."] },
  { w: "vooringenomenheid", pos: "n", cefr: "C2", gen: "de", ipa: "voːrɪnɣəˈnoːmənɦɛit", g: ["prasangka, bias", "bias, prejudice", "sesgo"], d: ["Kecenderungan menilai secara tidak berimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["Het onderzoek toont vooringenomenheid.", "Kajian itu menunjukkan bias.", "The study shows a bias.", "El estudio muestra un sesgo."] },
  { w: "afbreuk doen", pos: "phr", cefr: "C2", ipa: "ˈɑfbrøk dun", g: ["merongrong, mengurangi", "to detract from, to undermine", "menoscabar"], d: ["Mengurangi nilai atau kekuatan sesuatu.", "To reduce the value or force of something.", "Reducir el valor o la fuerza de algo."], ex: ["Dat doet afbreuk aan zijn geloofwaardigheid.", "Hal itu merongrong kredibilitasnya.", "That undermines his credibility.", "Eso menoscaba su credibilidad."] },
  { w: "mijlpaal", pos: "n", cefr: "C2", gen: "de", ipa: "ˈmɛilpaːl", g: ["tonggak", "milestone", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Het akkoord was een mijlpaal.", "Kesepakatan itu menjadi tonggak.", "The agreement was a milestone.", "El acuerdo fue un hito."] },
  { w: "onvermijdelijk", pos: "adj", cefr: "C2", ipa: "ɔnvərˈmɛidələk", g: ["tak terhindarkan", "inevitable", "ineludible"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Een prijsstijging is onvermijdelijk.", "Kenaikan harga tak terhindarkan.", "A price rise is inevitable.", "La subida de precios es inevitable."] },
  { w: "hersenschim", pos: "n", cefr: "C2", gen: "de", ipa: "ˈɦɛrsənsxɪm", g: ["khayalan kosong", "figment, pipe dream", "quimera"], d: ["Gagasan indah yang tak mungkin nyata.", "A lovely idea that cannot be real.", "Idea hermosa e irrealizable."], ex: ["Dat plan is een hersenschim.", "Rencana itu khayalan belaka.", "That plan is a pipe dream.", "Ese plan es una quimera."] },
  { w: "in het licht van", pos: "phr", cefr: "C2", ipa: "ɪn ət lɪxt vɑn", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["In het licht van de resultaten is het een succes.", "Berdasarkan hasilnya, ini sukses.", "In the light of the results it's a success.", "A la luz de los resultados, es un éxito."] },
];
