/* =========================================================================
   lexicon/pl.js — Słownik: Polski. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Polandia terkenal karena gugus konsonannya (szcz, prz) dan tujuh kasus. Kabar baiknya: ejaannya sangat teratur — sekali aturan bunyinya dikuasai, semua kata bisa dibaca.",
    "Polish is famous for consonant clusters (szcz, prz) and seven cases. The good news: spelling is highly regular — learn the sound rules once and every word is readable.",
    "El polaco destaca por sus grupos consonánticos (szcz, prz) y sus siete casos. La buena noticia: la ortografía es muy regular.",
  ],
  script: [
    "32 huruf, termasuk ą ć ę ł ń ó ś ź ż. Tekanan hampir selalu jatuh pada suku kata kedua dari belakang — sangat mudah ditebak.",
    "32 letters, including ą ć ę ł ń ó ś ź ż. Stress falls almost always on the second-to-last syllable — remarkably predictable.",
    "32 letras, incluidas ą ć ę ł ń ó ś ź ż. El acento cae casi siempre en la penúltima sílaba.",
  ],
  pron: [
    ["sz / cz / ż", "Bunyi keras: sz = 'sy', cz = 'c', ż = 'zy' — szczotka.", "The hard series: sz = 'sh', cz = 'ch', ż = 'zh' — szczotka.", "La serie dura: sz = 'sh', cz = 'ch', ż = 'zh' — szczotka."],
    ["ś / ć / ź", "Bunyi lembut, lidah lebih ke depan: śnieg, ćwiczyć.", "The soft series, tongue further forward: śnieg, ćwiczyć.", "La serie suave, con la lengua más adelante: śnieg, ćwiczyć."],
    ["ł", "Dibaca seperti 'w' Inggris: mały → 'mawy'.", "Sounds like English 'w': mały → 'mawy'.", "Suena como la 'w' inglesa: mały → 'mawy'."],
    ["ą / ę", "Vokal sengau: mądry, ręka; di akhir kata ę melemah.", "Nasal vowels: mądry, ręka; a final ę weakens.", "Vocales nasales: mądry, ręka; la ę final se debilita."],
    ["rz", "Sama dengan ż: rzeka terdengar 'żeka'.", "Identical to ż: rzeka sounds like 'żeka'.", "Igual que ż: rzeka suena 'żeka'."],
    ["w", "Selalu /v/: woda = 'voda'.", "Always /v/: woda = 'voda'.", "Siempre /v/: woda = 'voda'."],
  ],
  grammar: [
    {
      t: ["Tujuh kasus", "Seven cases", "Siete casos"],
      d: ["Akhiran kata benda berubah menurut perannya; itulah sebabnya urutan kata bisa bebas.", "Noun endings change with the role a word plays, which is why word order is free.", "Las terminaciones cambian según la función, por eso el orden es libre."],
      ex: "kot (kucing) → kota, kotu, kotem, kocie…",
    },
    {
      t: ["Tanpa artikel", "No articles at all", "Sin artículos"],
      d: ["Tidak ada 'a' atau 'the'; kepastian disampaikan lewat konteks dan urutan kata.", "There is no 'a' or 'the'; definiteness comes from context and word order.", "No hay 'a' ni 'the'; la determinación viene del contexto."],
      ex: "Kot śpi. = The cat / A cat is sleeping.",
    },
    {
      t: ["Aspek: selesai atau belum", "Aspect: finished or not", "Aspecto: acabado o no"],
      d: ["Hampir setiap kata kerja punya sepasang bentuk: tak selesai (robić) dan selesai (zrobić).", "Almost every verb comes in a pair: imperfective (robić) and perfective (zrobić).", "Casi todo verbo tiene pareja: imperfectivo (robić) y perfectivo (zrobić)."],
      ex: "Czytałem książkę. · Przeczytałem książkę.",
    },
    {
      t: ["Gender pada kata kerja lampau", "Gender in the past tense", "Género en el pasado"],
      d: ["Bentuk lampau menyesuaikan jenis kelamin pelakunya.", "Past-tense forms agree with the speaker's gender.", "El pasado concuerda con el género del sujeto."],
      ex: "Byłem (laki-laki) · Byłam (perempuan)",
    },
    {
      t: ["Subjek boleh dihilangkan", "The subject can vanish", "El sujeto puede omitirse"],
      d: ["Akhiran kata kerja sudah menandai pelakunya, jadi ja/ty jarang dipakai.", "Verb endings already mark the person, so ja/ty are usually dropped.", "Las terminaciones ya marcan la persona: ja/ty se omiten."],
      ex: "(Ja) mówię po polsku.",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "dom", pos: "n", cefr: "A1", gen: "m", ipa: "dɔm", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Mój dom jest blisko parku.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "dzień", pos: "n", cefr: "A1", gen: "m", ipa: "d͡ʑɛɲ", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Pracuję codziennie.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["noc"] },
  { w: "noc", pos: "n", cefr: "A1", gen: "f", ipa: "nɔt͡s", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Dobranoc!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["dzień"] },
  { w: "mężczyzna", pos: "n", cefr: "A1", gen: "m", ipa: "mɛ̃ʂˈt͡ʂɨzna", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["Ten mężczyzna to mój sąsiad.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["kobieta"] },
  { w: "kobieta", pos: "n", cefr: "A1", gen: "f", ipa: "kɔˈbjɛta", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["Kobieta w kapeluszu to moja ciocia.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["mężczyzna"] },
  { w: "przyjaciel", pos: "n", cefr: "A1", gen: "m", ipa: "pʂɨˈjat͡ɕɛl", g: ["sahabat", "close friend", "amigo íntimo"], d: ["Teman yang sangat dekat dan dipercaya.", "A friend you are genuinely close to.", "Amigo verdaderamente cercano."], ex: ["To mój najlepszy przyjaciel.", "Dia sahabat terbaik saya.", "He's my best friend.", "Es mi mejor amigo."], note: ["przyjaciel = sahabat karib; kolega = teman biasa.", "przyjaciel is a close friend; kolega is a casual acquaintance.", "przyjaciel es amigo íntimo; kolega, un conocido."] },
  { w: "duży", pos: "adj", cefr: "A1", ipa: "ˈduʐɨ", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Mieszkają w dużym mieście.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["mały"] },
  { w: "mały", pos: "adj", cefr: "A1", ipa: "ˈmawɨ", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Mam małe mieszkanie.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["duży"] },
  { w: "dobry", pos: "adj", cefr: "A1", ipa: "ˈdɔbrɨ", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["To dobry pomysł.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["zły"] },
  { w: "mieć", pos: "v", cefr: "A1", ipa: "mjɛt͡ɕ", g: ["punya", "to have", "tener"], d: ["Memiliki sesuatu.", "To possess something.", "Poseer algo."], ex: ["Mam dwie siostry.", "Saya punya dua saudara perempuan.", "I have two sisters.", "Tengo dos hermanas."] },
  { w: "chcieć", pos: "v", cefr: "A1", ipa: "xt͡ɕɛt͡ɕ", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Chcę uczyć się polskiego.", "Saya mau belajar bahasa Polandia.", "I want to learn Polish.", "Quiero aprender polaco."] },
  { w: "iść", pos: "v", cefr: "A1", ipa: "iɕt͡ɕ", g: ["berjalan, pergi", "to go (on foot)", "ir (a pie)"], d: ["Berpindah dengan berjalan kaki.", "To move on foot.", "Desplazarse a pie."], ex: ["Idę na targ.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."], note: ["iść untuk berjalan kaki; jechać untuk berkendara.", "iść is on foot; jechać is by vehicle.", "iść es a pie; jechać, en vehículo."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "praca", pos: "n", cefr: "A2", gen: "f", ipa: "ˈprat͡sa", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Moja praca zaczyna się o dziewiątej.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "pieniądze", pos: "n", cefr: "A2", ipa: "pjɛˈɲɔnd͡zɛ", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Nie mam dość pieniędzy.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."], note: ["Selalu jamak, seperti 'pengar' Swedia.", "Always plural, like Swedish 'pengar'.", "Siempre en plural."] },
  { w: "czas", pos: "n", cefr: "A2", gen: "m", ipa: "t͡ʂas", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["Nie mam dziś czasu.", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "miasto", pos: "n", cefr: "A2", gen: "nt", ipa: "ˈmjastɔ", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Kraków to piękne miasto.", "Kraków kota yang indah.", "Kraków is a beautiful city.", "Cracovia es una ciudad preciosa."] },
  { w: "pomagać", pos: "v", cefr: "A2", ipa: "pɔˈmaɡat͡ɕ", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Czy możesz mi pomóc?", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "potrzebować", pos: "v", cefr: "A2", ipa: "pɔt͡ʂɛˈbɔvat͡ɕ", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Potrzebuję odpoczynku.", "Saya butuh istirahat.", "I need rest.", "Necesito descanso."] },
  { w: "zaczynać", pos: "v", cefr: "A2", ipa: "zaˈt͡ʂɨnat͡ɕ", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Film zaczyna się o ósmej.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["kończyć"] },
  { w: "łatwy", pos: "adj", cefr: "A2", ipa: "ˈwatfɨ", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["Egzamin był łatwy.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["trudny"] },
  { w: "trudny", pos: "adj", cefr: "A2", ipa: "ˈtrudnɨ", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Trudno tu zaparkować.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["łatwy"] },
  { w: "szybki", pos: "adj", cefr: "A2", ipa: "ˈʂɨpki", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Pociąg jest szybszy.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["wolny"] },
  { w: "zawsze", pos: "adv", cefr: "A2", ipa: "ˈzafʂɛ", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Zawsze jem śniadanie w domu.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["nigdy"] },
  { w: "ponieważ", pos: "conj", cefr: "A2", ipa: "pɔˈɲɛvaʂ", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Zostaję w domu, ponieważ pada deszcz.", "Saya di rumah karena hujan.", "I'm staying home because it's raining.", "Me quedo en casa porque llueve."], syn: ["bo"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "doświadczenie", pos: "n", cefr: "B1", gen: "nt", ipa: "dɔɕfjatˈt͡ʂɛɲɛ", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Ma duże doświadczenie.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "decyzja", pos: "n", cefr: "B1", gen: "f", ipa: "dɛˈt͡sɨzja", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["To była trudna decyzja.", "Itu keputusan yang sulit.", "That was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya podjąć decyzję.", "The collocation is podjąć decyzję (to make a decision).", "La colocación es podjąć decyzję."] },
  { w: "okazja", pos: "n", cefr: "B1", gen: "f", ipa: "ɔˈkazja", g: ["kesempatan", "opportunity, occasion", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["To dobra okazja.", "Ini kesempatan bagus.", "It's a good opportunity.", "Es una buena oportunidad."] },
  { w: "rada", pos: "n", cefr: "B1", gen: "f", ipa: "ˈrada", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Dasz mi radę?", "Boleh minta saran?", "Can you give me some advice?", "¿Me das un consejo?"] },
  { w: "poprawić", pos: "v", cefr: "B1", ipa: "pɔˈpravit͡ɕ", g: ["memperbaiki", "to improve, to correct", "mejorar, corregir"], d: ["Menjadikan sesuatu lebih baik atau benar.", "To make something better or correct.", "Hacer algo mejor o correcto."], ex: ["Chcę poprawić wymowę.", "Saya ingin memperbaiki pelafalan.", "I want to improve my pronunciation.", "Quiero mejorar la pronunciación."] },
  { w: "udać się", pos: "v", cefr: "B1", ipa: "ˈudat͡ɕ ɕɛ", g: ["berhasil", "to succeed, to work out", "salir bien"], d: ["Berjalan sesuai harapan.", "To turn out as hoped.", "Salir como se esperaba."], ex: ["Udało mi się skończyć na czas.", "Saya berhasil selesai tepat waktu.", "I managed to finish on time.", "Logré terminar a tiempo."] },
  { w: "wydawać się", pos: "v", cefr: "B1", ipa: "vɨˈdavat͡ɕ ɕɛ", g: ["tampak", "to seem", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Wydaje się zmęczony.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "chociaż", pos: "conj", cefr: "B1", ipa: "ˈxɔt͡ɕaʂ", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Chociaż pada, wychodzimy.", "Meskipun hujan, kami keluar.", "Although it's raining, we're going out.", "Aunque llueve, salimos."] },
  { w: "jednak", pos: "conj", cefr: "B1", ipa: "ˈjɛdnak", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Jest drogo; jednak warto.", "Mahal; namun begitu sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "może", pos: "adv", cefr: "B1", ipa: "ˈmɔʐɛ", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Może przyjdzie jutro.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "przyzwyczaić się", pos: "v", cefr: "B1", ipa: "pʂɨzvɨˈt͡ʂait͡ɕ ɕɛ", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Przyzwyczaiłem się do zimy.", "Saya sudah terbiasa dengan musim dingin.", "I got used to the winter.", "Me acostumbré al invierno."] },
  { w: "tęsknić", pos: "v", cefr: "B1", ipa: "ˈtɛ̃sknit͡ɕ", g: ["merindukan", "to miss, to long for", "echar de menos"], d: ["Merasa sedih karena sesuatu tidak ada.", "To feel the absence of someone or something.", "Sentir la ausencia de alguien."], ex: ["Tęsknię za rodziną.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "rozwój", pos: "n", cefr: "B2", gen: "m", ipa: "ˈrɔzvuj", g: ["perkembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Rozwój projektu idzie dobrze.", "Perkembangan proyeknya baik.", "The project's development is going well.", "El desarrollo del proyecto va bien."] },
  { w: "środowisko", pos: "n", cefr: "B2", gen: "nt", ipa: "ɕrɔdɔˈviskɔ", g: ["lingkungan", "environment", "medio ambiente"], d: ["Alam sekitar; juga lingkungan kerja.", "The natural surroundings; also a work setting.", "Entorno natural; también ambiente laboral."], ex: ["Musimy chronić środowisko.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "wyzwanie", pos: "n", cefr: "B2", gen: "nt", ipa: "vɨzˈvaɲɛ", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["To prawdziwe wyzwanie.", "Ini benar-benar tantangan.", "That's a real challenge.", "Es todo un desafío."] },
  { w: "umowa", pos: "n", cefr: "B2", gen: "f", ipa: "uˈmɔva", g: ["perjanjian, kontrak", "agreement, contract", "contrato"], d: ["Kesepakatan resmi antara dua pihak.", "A formal agreement between two sides.", "Acuerdo formal entre dos partes."], ex: ["Podpisaliśmy umowę.", "Kami menandatangani perjanjian.", "We signed an agreement.", "Firmamos un contrato."] },
  { w: "osiągnąć", pos: "v", cefr: "B2", ipa: "ɔˈɕɔŋɡnɔɲt͡ɕ", g: ["mencapai", "to achieve, to attain", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Osiągnęliśmy cel.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "podkreślić", pos: "v", cefr: "B2", ipa: "pɔtˈkrɛɕlit͡ɕ", g: ["menegaskan", "to emphasise, to underline", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Warto podkreślić ten punkt.", "Poin itu perlu ditegaskan.", "That point is worth emphasising.", "Cabe subrayar ese punto."] },
  { w: "niezawodny", pos: "adj", cefr: "B2", ipa: "ɲɛzaˈvɔdnɨ", g: ["dapat diandalkan", "reliable, unfailing", "fiable"], d: ["Tidak pernah mengecewakan.", "Never letting you down.", "Que nunca falla."], ex: ["To niezawodne źródło.", "Itu sumber yang bisa diandalkan.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "niezbędny", pos: "adj", cefr: "B2", ipa: "ɲɛzˈbɛndnɨ", g: ["mutlak perlu", "indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Paszport jest niezbędny.", "Paspor mutlak diperlukan.", "A passport is indispensable.", "El pasaporte es imprescindible."] },
  { w: "pomimo", pos: "prep", cefr: "B2", ipa: "pɔˈmimɔ", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Pomimo zimna wyszliśmy.", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."] },
  { w: "dlatego", pos: "conj", cefr: "B2", ipa: "dlaˈtɛɡɔ", g: ["karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Padało; dlatego zostaliśmy w domu.", "Hujan; karena itu kami di rumah.", "It rained; therefore we stayed home.", "Llovía; por eso nos quedamos en casa."] },
  { w: "kwestia", pos: "n", cefr: "B2", gen: "f", ipa: "ˈkfɛstja", g: ["persoalan", "matter, issue", "cuestión"], d: ["Hal yang sedang dibicarakan atau ditangani.", "The matter under discussion.", "Tema del que se trata."], ex: ["To delikatna kwestia.", "Itu perkara yang sensitif.", "It's a delicate matter.", "Es una cuestión delicada."] },
  { w: "wdrożyć", pos: "v", cefr: "B2", ipa: "ˈvdrɔʐɨt͡ɕ", g: ["menerapkan", "to implement, to roll out", "implantar"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["Wdrożymy nowy system.", "Kami akan menerapkan sistem baru.", "We'll implement the new system.", "Implantaremos el nuevo sistema."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "dziedzina", pos: "n", cefr: "C1", gen: "f", ipa: "d͡ʑɛˈd͡ʑina", g: ["bidang", "field, domain", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["W dziedzinie prawa jest inaczej.", "Dalam bidang hukum hal itu berbeda.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "podejście", pos: "n", cefr: "C1", gen: "nt", ipa: "pɔˈdɛjɕt͡ɕɛ", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Potrzebujemy innego podejścia.", "Kita butuh pendekatan lain.", "We need a different approach.", "Necesitamos otro enfoque."] },
  { w: "niuans", pos: "n", cefr: "C1", gen: "m", ipa: "ˈɲuans", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["Jest tu ważny niuans.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "zająć się", pos: "v", cefr: "C1", ipa: "ˈzajɔɲt͡ɕ ɕɛ", g: ["menangani", "to take care of, to tackle", "ocuparse de"], d: ["Mengambil alih dan menyelesaikan sesuatu.", "To take something on and deal with it.", "Hacerse cargo de algo."], ex: ["Musimy zająć się tym problemem.", "Kita harus menangani masalah ini.", "We must tackle this problem.", "Debemos ocuparnos de este problema."] },
  { w: "wspierać", pos: "v", cefr: "C1", ipa: "ˈfspjɛrat͡ɕ", g: ["mendukung", "to support, to foster", "apoyar"], d: ["Membantu sesuatu bertahan atau tumbuh.", "To help something stand or grow.", "Ayudar a que algo se sostenga o crezca."], ex: ["Program wspiera młodych artystów.", "Program itu mendukung seniman muda.", "The programme supports young artists.", "El programa apoya a jóvenes artistas."] },
  { w: "odzwierciedlać", pos: "v", cefr: "C1", ipa: "ɔdzvjɛrˈt͡ɕɛdlat͡ɕ", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Dane odzwierciedlają poprawę.", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "skrupulatny", pos: "adj", cefr: "C1", ipa: "skrupuˈlatnɨ", g: ["teliti, cermat", "meticulous, scrupulous", "escrupuloso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["Przeprowadził skrupulatną analizę.", "Dia melakukan analisis yang teliti.", "He carried out a meticulous analysis.", "Hizo un análisis escrupuloso."] },
  { w: "niemniej jednak", pos: "conj", cefr: "C1", ipa: "ˈɲɛmɲɛj ˈjɛdnak", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Niemniej jednak propozycja jest aktualna.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "w celu", pos: "prep", cefr: "C1", ipa: "f ˈt͡sɛlu", g: ["demi, agar", "in order to", "con el fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["W celu oszczędzenia czasu upraszczamy.", "Demi menghemat waktu, kami sederhanakan.", "In order to save time, we simplify.", "Con el fin de ahorrar tiempo, simplificamos."] },
  { w: "umocnić", pos: "v", cefr: "C1", ipa: "uˈmɔt͡sɲit͡ɕ", g: ["memperkukuh", "to strengthen, to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Firma umocniła swoją pozycję.", "Perusahaan memperkukuh posisinya.", "The firm consolidated its position.", "La empresa consolidó su posición."] },
  { w: "zasięg", pos: "n", cefr: "C1", gen: "m", ipa: "ˈzaɕɛŋk", g: ["jangkauan", "range, reach", "alcance"], d: ["Seberapa jauh pengaruh sesuatu terasa.", "How far something's effect reaches.", "Hasta dónde llega el efecto."], ex: ["Decyzja o szerokim zasięgu.", "Keputusan berjangkauan luas.", "A decision of wide reach.", "Una decisión de gran alcance."] },
  { w: "uwydatnić", pos: "v", cefr: "C1", ipa: "uvɨˈdatɲit͡ɕ", g: ["menonjolkan", "to bring out, to highlight", "resaltar"], d: ["Membuat sesuatu tampak lebih jelas.", "To make something stand out more clearly.", "Hacer que algo resalte."], ex: ["Raport uwydatnia zagrożenia.", "Laporan itu menonjolkan ancamannya.", "The report brings out the risks.", "El informe resalta los riesgos."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "paradygmat", pos: "n", cefr: "C2", gen: "m", ipa: "paraˈdɨɡmat", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["To była zmiana paradygmatu.", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "uchylić się", pos: "v", cefr: "C2", ipa: "uˈxɨlit͡ɕ ɕɛ", g: ["mengelak", "to evade, to dodge", "eludir"], d: ["Menghindari kewajiban atau pertanyaan.", "To avoid a duty or a question.", "Evitar un deber o una pregunta."], ex: ["Uchylił się od odpowiedzi.", "Dia mengelak dari jawaban.", "He dodged the answer.", "Eludió la respuesta."] },
  { w: "naświetlić", pos: "v", cefr: "C2", ipa: "naˈɕfjɛtlit͡ɕ", g: ["menerangi, menjelaskan", "to shed light on, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Trzeba naświetlić kontekst.", "Konteksnya perlu diterangkan.", "The context must be elucidated.", "Hay que esclarecer el contexto."] },
  { w: "niewysłowiony", pos: "adj", cefr: "C2", ipa: "ɲɛvɨswɔˈvjɔnɨ", g: ["tak terlukiskan", "ineffable, unutterable", "inefable"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Niewysłowiona radość.", "Sukacita yang tak terlukiskan.", "An ineffable joy.", "Una alegría inefable."] },
  { w: "bezwzględny", pos: "adj", cefr: "C2", ipa: "bɛzˈvzɡlɛndnɨ", g: ["mutlak; tanpa kompromi", "absolute; ruthless", "absoluto; implacable"], d: ["Tidak menerima pengecualian; bisa juga berarti kejam.", "Admitting no exception; can also mean ruthless.", "Que no admite excepción; también implacable."], ex: ["To bezwzględny wymóg.", "Itu syarat mutlak.", "That's an absolute requirement.", "Es un requisito absoluto."] },
  { w: "przebłysk", pos: "n", cefr: "C2", gen: "m", ipa: "ˈpʂɛbwɨsk", g: ["kilasan, secercah", "flash, glimmer", "destello"], d: ["Tanda atau cahaya yang sangat sekilas.", "A very brief sign or flash of light.", "Señal o luz muy breve."], ex: ["Przebłysk nadziei wciąż jest.", "Secercah harapan masih ada.", "A glimmer of hope remains.", "Queda un destello de esperanza."] },
  { w: "stronniczość", pos: "n", cefr: "C2", gen: "f", ipa: "strɔˈɲit͡ʂɔɕt͡ɕ", g: ["keberpihakan, bias", "bias, partiality", "parcialidad"], d: ["Kecenderungan berpihak sehingga tidak adil.", "A leaning that makes judgement unfair.", "Inclinación que hace injusto el juicio."], ex: ["Badanie wykazuje stronniczość.", "Kajian itu menunjukkan keberpihakan.", "The study shows bias.", "El estudio muestra parcialidad."] },
  { w: "umniejszać", pos: "v", cefr: "C2", ipa: "umˈɲɛjʂat͡ɕ", g: ["merendahkan, mengurangi", "to belittle, to diminish", "menoscabar"], d: ["Membuat nilai sesuatu tampak lebih kecil.", "To make something seem less valuable.", "Hacer que algo parezca menor."], ex: ["Nie chcę umniejszać jego pracy.", "Saya tak ingin merendahkan kerjanya.", "I don't want to belittle his work.", "No quiero menoscabar su trabajo."] },
  { w: "kamień milowy", pos: "n", cefr: "C2", gen: "m", ipa: "ˈkamjɛɲ miˈlɔvɨ", g: ["tonggak", "milestone", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Umowa to kamień milowy.", "Perjanjian itu tonggak sejarah.", "The agreement is a milestone.", "El acuerdo es un hito."] },
  { w: "nieunikniony", pos: "adj", cefr: "C2", ipa: "ɲɛuɲikˈɲɔnɨ", g: ["tak terhindarkan", "inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Podwyżka cen jest nieunikniona.", "Kenaikan harga tak terhindarkan.", "A price rise is inevitable.", "La subida de precios es inevitable."] },
  { w: "mrzonka", pos: "n", cefr: "C2", gen: "f", ipa: "ˈmʐɔnka", g: ["angan kosong", "pipe dream", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Ta obietnica to mrzonka.", "Janji itu angan kosong.", "That promise is a pipe dream.", "Esa promesa es una quimera."] },
  { w: "w świetle", pos: "prep", cefr: "C2", ipa: "f ˈɕfjɛtlɛ", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["W świetle wyników to sukces.", "Berdasarkan hasilnya, ini sukses.", "In the light of the results it's a success.", "A la luz de los resultados, es un éxito."] },
];
