/* =========================================================================
   lexicon/pt.js — Dicionário: Português (variante brasileira nos exemplos).
   Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Portugis dituturkan di empat benua. Ciri khasnya vokal sengau (ã, õ) yang tidak dimiliki bahasa Latin lain, dan perbedaan jelas antara logat Brasil dan Portugal.",
    "Portuguese is spoken on four continents. Its signature is the nasal vowels (ã, õ) no other Romance language has, plus a clear split between Brazilian and European accents.",
    "El portugués se habla en cuatro continentes. Su sello son las vocales nasales (ã, õ) y la clara diferencia entre el acento brasileño y el europeo.",
  ],
  script: [
    "Abjad Latin dengan tilde (ã õ), cedilla (ç), dan aksen (á â à). Tekanan biasanya di suku kedua dari belakang; aksen menandai pengecualian.",
    "Latin alphabet with the tilde (ã õ), cedilla (ç) and accents (á â à). Stress normally falls on the second-to-last syllable; accents mark the exceptions.",
    "Alfabeto latino con tilde (ã õ), cedilla (ç) y acentos (á â à). El acento suele ir en la penúltima sílaba; las tildes marcan excepciones.",
  ],
  pron: [
    ["ão", "Vokal sengau ganda; ujung kata paling khas: pão, não, mão.", "A double nasal vowel, the most characteristic word ending: pão, não, mão.", "Vocal nasal doble, la terminación más típica: pão, não, mão."],
    ["nh / lh", "nh = /ɲ/ (banho), lh = /ʎ/ (filho).", "nh = /ɲ/ (banho), lh = /ʎ/ (filho).", "nh = /ɲ/ (banho), lh = /ʎ/ (filho)."],
    ["ç", "Selalu /s/ di depan a o u: começar, açúcar.", "Always /s/ before a o u: começar, açúcar.", "Siempre /s/ ante a o u: começar, açúcar."],
    ["r / rr", "r di awal kata dan rr dibunyikan serak /h/ di Brasil: rio, carro.", "Initial r and rr are a throaty /h/ in Brazil: rio, carro.", "La r inicial y rr suenan guturales /h/ en Brasil: rio, carro."],
    ["de / te", "Di Brasil, di dan ti berbunyi /dʒi/ dan /tʃi/: dia → 'djia', gente → 'gentchi'.", "In Brazil di and ti become /dʒi/ and /tʃi/: dia → 'djia', gente → 'gentchi'.", "En Brasil di y ti suenan /dʒi/ y /tʃi/: dia, gente."],
    ["-m akhir", "m di akhir kata menyengaukan vokal, tidak dibunyikan sebagai m: bem, com.", "A final m nasalises the vowel instead of sounding as m: bem, com.", "La m final nasaliza la vocal, no suena como m: bem, com."],
  ],
  grammar: [
    {
      t: ["Gender & artikel", "Gender & articles", "Género y artículos"],
      d: ["Kata benda maskulin (o) atau feminin (a); artikel menyatu dengan kata depan: de + o = do.", "Nouns are masculine (o) or feminine (a); articles fuse with prepositions: de + o = do.", "Los sustantivos son masculinos (o) o femeninos (a); los artículos se funden: de + o = do."],
      ex: "o livro · a casa · do carro · na cidade",
    },
    {
      t: ["Ser vs. estar", "Ser vs. estar", "Ser y estar"],
      d: ["ser untuk identitas dan sifat tetap, estar untuk keadaan sementara dan lokasi.", "ser for identity and lasting traits, estar for temporary states and location.", "ser para identidad y rasgos duraderos; estar para estados y ubicación."],
      ex: "Ele é médico. · Ele está cansado.",
    },
    {
      t: ["Gerúndio Brasil vs. Portugal", "Gerund: Brazil vs. Portugal", "Gerundio: Brasil y Portugal"],
      d: ["Brasil memakai estar + -ndo (estou falando); Portugal memakai estar a + infinitif (estou a falar).", "Brazil uses estar + -ndo (estou falando); Portugal uses estar a + infinitive (estou a falar).", "Brasil usa estar + -ndo; Portugal, estar a + infinitivo."],
      ex: "Estou estudando. · (PT) Estou a estudar.",
    },
    {
      t: ["Infinitif berpelaku", "The personal infinitive", "El infinitivo personal"],
      d: ["Keunikan Portugis: infinitif bisa dikonjugasikan agar pelakunya jelas.", "A Portuguese speciality: the infinitive can take endings so its subject is explicit.", "Rareza del portugués: el infinitivo puede conjugarse para marcar el sujeto."],
      ex: "É melhor tu ires. · Antes de nós sairmos…",
    },
    {
      t: ["Subjuntivo", "The subjunctive", "El subjuntivo"],
      d: ["Dipakai setelah harapan, keraguan, dan pada klausa masa depan dengan quando/se.", "Used after wishes and doubt, and in future clauses with quando/se.", "Se usa tras deseos y dudas, y en cláusulas de futuro con quando/se."],
      ex: "Quando eu chegar, ligo. · Espero que venha.",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "casa", pos: "n", cefr: "A1", gen: "f", ipa: "ˈka.zɐ", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Minha casa fica perto do parque.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "dia", pos: "n", cefr: "A1", gen: "m", ipa: "ˈdʒi.ɐ", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Trabalho todos os dias.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["noite"] },
  { w: "noite", pos: "n", cefr: "A1", gen: "f", ipa: "ˈnoj.tʃi", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Boa noite!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["dia"] },
  { w: "homem", pos: "n", cefr: "A1", gen: "m", ipa: "ˈɔ.mẽj", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["Aquele homem é meu vizinho.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["mulher"] },
  { w: "mulher", pos: "n", cefr: "A1", gen: "f", ipa: "muˈʎɛʁ", g: ["perempuan; istri", "woman; wife", "mujer; esposa"], d: ["Manusia dewasa perempuan; juga istri.", "An adult female; also a wife.", "Mujer adulta; también esposa."], ex: ["A mulher de chapéu é minha tia.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["homem"] },
  { w: "amigo", pos: "n", cefr: "A1", gen: "m", ipa: "aˈmi.ɡu", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Vou ao cinema com um amigo.", "Saya ke bioskop dengan teman.", "I'm going to the cinema with a friend.", "Voy al cine con un amigo."] },
  { w: "grande", pos: "adj", cefr: "A1", ipa: "ˈɡɾɐ̃.dʒi", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Moramos numa cidade grande.", "Kami tinggal di kota besar.", "We live in a big city.", "Vivimos en una ciudad grande."], ant: ["pequeno"] },
  { w: "pequeno", pos: "adj", cefr: "A1", ipa: "peˈke.nu", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Tenho um apartamento pequeno.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["grande"] },
  { w: "bom", pos: "adj", cefr: "A1", ipa: "bõ", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["É um bom restaurante.", "Itu restoran yang bagus.", "It's a good restaurant.", "Es un buen restaurante."], ant: ["ruim"] },
  { w: "ter", pos: "v", cefr: "A1", ipa: "teʁ", g: ["punya", "to have", "tener"], d: ["Memiliki sesuatu; juga menyatakan usia.", "To possess; also used for age.", "Poseer; también expresa edad."], ex: ["Tenho duas irmãs.", "Saya punya dua saudara perempuan.", "I have two sisters.", "Tengo dos hermanas."] },
  { w: "querer", pos: "v", cefr: "A1", ipa: "keˈɾeʁ", g: ["mau, mencintai", "to want; to love", "querer"], d: ["Menginginkan sesuatu; menyayangi seseorang.", "To want something; to love someone.", "Desear algo; amar a alguien."], ex: ["Quero aprender português.", "Saya mau belajar bahasa Portugis.", "I want to learn Portuguese.", "Quiero aprender portugués."] },
  { w: "ir", pos: "v", cefr: "A1", ipa: "iʁ", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Vou ao mercado agora.", "Saya pergi ke pasar sekarang.", "I'm going to the market now.", "Voy al mercado ahora."], note: ["ir + infinitif = masa depan dekat: vou estudar.", "ir + infinitive is the near future: vou estudar.", "ir + infinitivo es el futuro próximo: vou estudar."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "trabalho", pos: "n", cefr: "A2", gen: "m", ipa: "tɾaˈba.ʎu", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Meu trabalho começa às nove.", "Pekerjaan saya mulai pukul sembilan.", "My job starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "dinheiro", pos: "n", cefr: "A2", gen: "m", ipa: "dʒiˈɲej.ɾu", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Não tenho dinheiro suficiente.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "tempo", pos: "n", cefr: "A2", gen: "m", ipa: "ˈtẽ.pu", g: ["waktu; cuaca", "time; weather", "tiempo"], d: ["Jam yang berjalan; juga keadaan cuaca.", "Passing hours; also the weather.", "El paso del tiempo; también el clima."], ex: ["Não tenho tempo hoje.", "Hari ini saya tak punya waktu.", "I don't have time today.", "Hoy no tengo tiempo."] },
  { w: "cidade", pos: "n", cefr: "A2", gen: "f", ipa: "siˈda.dʒi", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Lisboa é uma cidade linda.", "Lisbon kota yang indah.", "Lisbon is a beautiful city.", "Lisboa es una ciudad preciosa."] },
  { w: "ajudar", pos: "v", cefr: "A2", ipa: "aʒuˈdaʁ", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Você pode me ajudar, por favor?", "Bisakah kamu menolong saya?", "Can you help me, please?", "¿Puedes ayudarme, por favor?"] },
  { w: "precisar", pos: "v", cefr: "A2", ipa: "pɾeziˈzaʁ", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Preciso descansar um pouco.", "Saya perlu istirahat sebentar.", "I need to rest a little.", "Necesito descansar un poco."], note: ["Diikuti de sebelum kata benda: preciso de ajuda.", "Takes de before a noun: preciso de ajuda.", "Lleva de ante sustantivo: preciso de ajuda."] },
  { w: "começar", pos: "v", cefr: "A2", ipa: "komeˈsaʁ", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["O filme começa às oito.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["terminar"] },
  { w: "fácil", pos: "adj", cefr: "A2", ipa: "ˈfa.siw", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["A prova foi fácil.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["difícil"] },
  { w: "difícil", pos: "adj", cefr: "A2", ipa: "dʒiˈfi.siw", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["É difícil estacionar aqui.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["fácil"] },
  { w: "rápido", pos: "adj", cefr: "A2", ipa: "ˈʁa.pi.du", g: ["cepat", "fast, quick", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["O trem é mais rápido.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["lento"] },
  { w: "sempre", pos: "adv", cefr: "A2", ipa: "ˈsẽ.pɾi", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Sempre tomo café de manhã.", "Saya selalu minum kopi pagi hari.", "I always have coffee in the morning.", "Siempre tomo café por la mañana."], ant: ["nunca"] },
  { w: "porque", pos: "conj", cefr: "A2", ipa: "puʁˈke", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Fico em casa porque está chovendo.", "Saya di rumah karena hujan.", "I'm staying home because it's raining.", "Me quedo en casa porque llueve."], note: ["porque = karena; por que = mengapa; porquê = alasannya.", "porque = because; por que = why; o porquê = the reason.", "porque = causa; por que = pregunta; o porquê = la razón."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "experiência", pos: "n", cefr: "B1", gen: "f", ipa: "es.peɾiˈẽ.sjɐ", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Ela tem muita experiência.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "decisão", pos: "n", cefr: "B1", gen: "f", ipa: "desiˈzɐ̃w", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Foi uma decisão difícil.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya tomar uma decisão.", "The collocation is tomar uma decisão.", "La colocación es tomar uma decisão."] },
  { w: "oportunidade", pos: "n", cefr: "B1", gen: "f", ipa: "o.poʁ.tu.niˈda.dʒi", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["É uma ótima oportunidade.", "Ini kesempatan yang bagus.", "It's a great opportunity.", "Es una gran oportunidad."] },
  { w: "conselho", pos: "n", cefr: "B1", gen: "m", ipa: "kõˈse.ʎu", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Me dá um conselho?", "Boleh minta saran?", "Can you give me some advice?", "¿Me das un consejo?"] },
  { w: "melhorar", pos: "v", cefr: "B1", ipa: "meʎoˈɾaʁ", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan atau menjadi lebih baik.", "To make or get better.", "Hacer o volverse mejor."], ex: ["Quero melhorar minha pronúncia.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."], ant: ["piorar"] },
  { w: "conseguir", pos: "v", cefr: "B1", ipa: "kõseˈɡiʁ", g: ["berhasil, mendapatkan", "to manage to, to get", "conseguir"], d: ["Berhasil memperoleh atau melakukan sesuatu.", "To obtain something or succeed in doing it.", "Lograr obtener o hacer algo."], ex: ["Consegui terminar a tempo.", "Saya berhasil selesai tepat waktu.", "I managed to finish on time.", "Conseguí terminar a tiempo."] },
  { w: "parecer", pos: "v", cefr: "B1", ipa: "paɾeˈseʁ", g: ["tampak", "to seem", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Ele parece cansado.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "embora", pos: "conj", cefr: "B1", ipa: "ẽˈbɔ.ɾɐ", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras; diikuti subjuntivo.", "Marks a contrast; takes the subjunctive.", "Marca contraste; exige subjuntivo."], ex: ["Embora chova, vamos sair.", "Meskipun hujan, kami akan keluar.", "Although it's raining, we'll go out.", "Aunque llueva, saldremos."] },
  { w: "no entanto", pos: "phr", cefr: "B1", ipa: "nu ẽˈtɐ̃.tu", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["É caro; no entanto, vale a pena.", "Mahal; namun begitu, sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "talvez", pos: "adv", cefr: "B1", ipa: "tawˈves", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Talvez ele venha amanhã.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "acostumar-se", pos: "v", cefr: "B1", ipa: "a.kos.tuˈmaʁ.si", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Me acostumei ao clima daqui.", "Saya terbiasa dengan iklim di sini.", "I got used to the climate here.", "Me acostumbré al clima de aquí."] },
  { w: "saudade", pos: "n", cefr: "B1", gen: "f", ipa: "sawˈda.dʒi", g: ["rindu (rasa kehilangan yang manis)", "longing for someone or something absent", "morriña, añoranza"], d: ["Rasa rindu bercampur kenangan indah — kata paling khas Portugis.", "A longing mixed with sweet memory — the most Portuguese of words.", "Añoranza mezclada con dulce recuerdo; la palabra más portuguesa."], ex: ["Estou com saudade da minha família.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."], note: ["Dipakai dengan ter atau estar com: tenho saudade / estou com saudade.", "Used with ter or estar com: tenho saudade / estou com saudade.", "Se usa con ter o estar com: tenho saudade."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "desenvolvimento", pos: "n", cefr: "B2", gen: "m", ipa: "de.zẽ.vow.viˈmẽ.tu", g: ["pengembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["O desenvolvimento do projeto vai bem.", "Pengembangan proyeknya berjalan baik.", "The project's development is going well.", "El desarrollo del proyecto va bien."] },
  { w: "meio ambiente", pos: "n", cefr: "B2", gen: "m", ipa: "ˈmej.u ɐ̃ˈbjẽ.tʃi", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["Precisamos cuidar do meio ambiente.", "Kita harus menjaga lingkungan.", "We must look after the environment.", "Debemos cuidar el medio ambiente."] },
  { w: "desafio", pos: "n", cefr: "B2", gen: "m", ipa: "deza.ˈfi.u", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Aprender chinês é um baita desafio.", "Belajar bahasa Mandarin benar-benar tantangan.", "Learning Chinese is quite a challenge.", "Aprender chino es todo un desafío."] },
  { w: "acordo", pos: "n", cefr: "B2", gen: "m", ipa: "aˈkoʁ.du", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Chegamos a um acordo justo.", "Kami mencapai kesepakatan yang adil.", "We reached a fair agreement.", "Llegamos a un acuerdo justo."] },
  { w: "alcançar", pos: "v", cefr: "B2", ipa: "aw.kɐ̃ˈsaʁ", g: ["mencapai", "to reach, to achieve", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Alcançamos a meta do trimestre.", "Kami mencapai target kuartal ini.", "We reached the quarterly target.", "Alcanzamos la meta del trimestre."] },
  { w: "destacar", pos: "v", cefr: "B2", ipa: "des.taˈkaʁ", g: ["menonjolkan, menyoroti", "to highlight, to stand out", "destacar"], d: ["Menonjolkan hal penting; juga menonjol sendiri.", "To highlight something; also to stand out.", "Resaltar algo; también sobresalir."], ex: ["Vale destacar o esforço da equipe.", "Perlu disoroti kerja keras tim.", "The team's effort is worth highlighting.", "Cabe destacar el esfuerzo del equipo."] },
  { w: "confiável", pos: "adj", cefr: "B2", ipa: "kõfiˈa.vew", g: ["dapat diandalkan", "reliable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["É uma fonte confiável.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "imprescindível", pos: "adj", cefr: "B2", ipa: "ĩ.pɾe.sĩˈdʒi.vew", g: ["mutlak perlu", "essential", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["O passaporte é imprescindível.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "apesar de", pos: "prep", cefr: "B2", ipa: "a.peˈzaʁ dʒi", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Apesar do frio, saímos.", "Meski dingin, kami keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "portanto", pos: "conj", cefr: "B2", ipa: "poʁˈtɐ̃.tu", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat logis.", "Marks a logical consequence.", "Marca la consecuencia lógica."], ex: ["Choveu; portanto, cancelamos.", "Hujan; oleh karena itu kami batalkan.", "It rained; therefore we cancelled.", "Llovió; por lo tanto cancelamos."] },
  { w: "assunto", pos: "n", cefr: "B2", gen: "m", ipa: "aˈsũ.tu", g: ["urusan, topik", "matter, subject", "asunto"], d: ["Hal yang sedang dibicarakan atau ditangani.", "The matter under discussion.", "Tema del que se trata."], ex: ["É um assunto delicado.", "Ini perkara yang sensitif.", "It's a delicate matter.", "Es un asunto delicado."] },
  { w: "implementar", pos: "v", cefr: "B2", ipa: "ĩ.ple.mẽˈtaʁ", g: ["menerapkan", "to implement", "implementar"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["Vamos implementar o novo sistema.", "Kami akan menerapkan sistem baru.", "We'll implement the new system.", "Vamos a implementar el nuevo sistema."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "âmbito", pos: "n", cefr: "C1", gen: "m", ipa: "ˈɐ̃.bi.tu", g: ["ranah, lingkup", "sphere, scope", "ámbito"], d: ["Wilayah tempat sesuatu berlaku.", "The area in which something applies.", "Espacio en que algo se aplica."], ex: ["No âmbito jurídico, é diferente.", "Dalam ranah hukum, hal itu berbeda.", "In the legal sphere it's different.", "En el ámbito jurídico es distinto."] },
  { w: "abordagem", pos: "n", cefr: "C1", gen: "f", ipa: "a.boʁˈda.ʒẽj", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Precisamos de outra abordagem.", "Kita butuh pendekatan lain.", "We need another approach.", "Necesitamos otro enfoque."] },
  { w: "nuance", pos: "n", cefr: "C1", gen: "f", ipa: "nuˈɐ̃.si", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["Há uma nuance importante aqui.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "abordar", pos: "v", cefr: "C1", ipa: "a.boʁˈdaʁ", g: ["menangani, membahas", "to tackle, to address", "abordar"], d: ["Mulai membahas atau menghadapi persoalan.", "To start dealing with an issue.", "Empezar a tratar un asunto."], ex: ["Precisamos abordar o tema com calma.", "Kita harus membahasnya dengan tenang.", "We must address the issue calmly.", "Hay que abordar el tema con calma."] },
  { w: "fomentar", pos: "v", cefr: "C1", ipa: "fo.mẽˈtaʁ", g: ["mendorong", "to foster, to promote", "fomentar"], d: ["Membantu sesuatu tumbuh atau berkembang.", "To help something grow.", "Ayudar a que algo crezca."], ex: ["A lei fomenta a reciclagem.", "Undang-undang itu mendorong daur ulang.", "The law fosters recycling.", "La ley fomenta el reciclaje."] },
  { w: "refletir", pos: "v", cefr: "C1", ipa: "ʁe.fleˈtʃiʁ", g: ["mencerminkan; merenung", "to reflect; to ponder", "reflejar; reflexionar"], d: ["Menunjukkan keadaan lain; juga berpikir dalam-dalam.", "To show another state; also to think deeply.", "Mostrar otra realidad; también meditar."], ex: ["Os dados refletem uma melhora.", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "minucioso", pos: "adj", cefr: "C1", ipa: "mi.nuˈsi.o.zu", g: ["teliti, cermat", "meticulous", "minucioso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["Fez uma análise minuciosa.", "Dia membuat analisis yang teliti.", "She did a meticulous analysis.", "Hizo un análisis minucioso."] },
  { w: "contudo", pos: "conj", cefr: "C1", ipa: "kõˈtu.du", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Contudo, a proposta continua válida.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "a fim de", pos: "prep", cefr: "C1", ipa: "a fĩ dʒi", g: ["demi, agar", "in order to", "a fin de"], d: ["Menyatakan tujuan secara formal.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["A fim de ganhar tempo, simplificamos.", "Demi menghemat waktu, kami sederhanakan.", "In order to save time, we simplified.", "A fin de ahorrar tiempo, simplificamos."] },
  { w: "consolidar", pos: "v", cefr: "C1", ipa: "kõ.so.liˈdaʁ", g: ["memperkukuh", "to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["A empresa consolidou sua posição.", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "alcance", pos: "n", cefr: "C1", gen: "m", ipa: "awˈkɐ̃.si", g: ["jangkauan", "reach, scope", "alcance"], d: ["Seberapa jauh pengaruh sesuatu terasa.", "How far something's effect reaches.", "Hasta dónde llega el efecto de algo."], ex: ["Uma decisão de grande alcance.", "Keputusan berjangkauan luas.", "A decision of great scope.", "Una decisión de gran alcance."] },
  { w: "ressaltar", pos: "v", cefr: "C1", ipa: "ʁe.sawˈtaʁ", g: ["menegaskan", "to emphasise, to point up", "resaltar"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["Vale ressaltar esse ponto.", "Poin itu perlu ditegaskan.", "That point is worth emphasising.", "Cabe resaltar ese punto."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "paradigma", pos: "n", cefr: "C2", gen: "m", ipa: "pa.ɾaˈdʒiɡ.mɐ", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Foi uma mudança de paradigma.", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "esquivar-se", pos: "v", cefr: "C2", ipa: "es.kiˈvaʁ.si", g: ["mengelak", "to dodge, to sidestep", "esquivar"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto sin afrontarlo."], ex: ["Esquivou-se da pergunta.", "Dia mengelak dari pertanyaan itu.", "He sidestepped the question.", "Esquivó la pregunta."] },
  { w: "elucidar", pos: "v", cefr: "C2", ipa: "e.lu.siˈdaʁ", g: ["menjernihkan", "to elucidate", "dilucidar"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Falta elucidar quem decidiu.", "Masih harus dijernihkan siapa yang memutuskan.", "It remains to be elucidated who decided.", "Queda por dilucidar quién decidió."] },
  { w: "inefável", pos: "adj", cefr: "C2", ipa: "i.neˈfa.vew", g: ["tak terlukiskan", "ineffable", "inefable"], d: ["Terlalu besar atau indah untuk dikatakan.", "Too great or beautiful for words.", "Demasiado grande o bello para expresarse."], ex: ["Sentiu uma alegria inefável.", "Dia merasakan sukacita tak terlukiskan.", "She felt an ineffable joy.", "Sintió una alegría inefable."] },
  { w: "peremptório", pos: "adj", cefr: "C2", ipa: "pe.ɾẽpˈtɔ.ɾju", g: ["mendesak, mutlak", "peremptory", "perentorio"], d: ["Harus dipenuhi segera tanpa penundaan.", "Requiring immediate compliance.", "Que no admite demora."], ex: ["O prazo é peremptório.", "Tenggatnya mutlak.", "The deadline is peremptory.", "El plazo es perentorio."] },
  { w: "vislumbre", pos: "n", cefr: "C2", gen: "m", ipa: "vizˈlũ.bɾi", g: ["secercah, kilasan", "glimpse, glimmer", "atisbo"], d: ["Tanda atau penglihatan yang sangat sekilas.", "A very brief sign or sight.", "Señal o visión muy breve."], ex: ["Há um vislumbre de esperança.", "Ada secercah harapan.", "There's a glimmer of hope.", "Hay un atisbo de esperanza."] },
  { w: "viés", pos: "n", cefr: "C2", gen: "m", ipa: "viˈɛs", g: ["bias", "bias, slant", "sesgo"], d: ["Kecondongan menilai secara tidak seimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["O estudo tem um viés claro.", "Kajian itu punya bias yang jelas.", "The study has a clear bias.", "El estudio tiene un sesgo claro."] },
  { w: "minar", pos: "v", cefr: "C2", ipa: "miˈnaʁ", g: ["merongrong", "to undermine", "socavar"], d: ["Melemahkan sesuatu sedikit demi sedikit.", "To weaken something bit by bit.", "Debilitar algo poco a poco."], ex: ["Isso mina a credibilidade dele.", "Hal itu merongrong kredibilitasnya.", "That undermines his credibility.", "Eso socava su credibilidad."] },
  { w: "marco", pos: "n", cefr: "C2", gen: "m", ipa: "ˈmaʁ.ku", g: ["tonggak", "milestone, landmark", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["O acordo foi um marco histórico.", "Kesepakatan itu tonggak sejarah.", "The agreement was a historic milestone.", "El acuerdo fue un hito histórico."] },
  { w: "incontornável", pos: "adj", cefr: "C2", ipa: "ĩ.kõ.toʁˈna.vew", g: ["tak terhindarkan", "unavoidable", "ineludible"], d: ["Tidak mungkin dihindari atau dilewati.", "Impossible to avoid or bypass.", "Imposible de evitar."], ex: ["É um problema incontornável.", "Itu masalah yang tak terhindarkan.", "It's an unavoidable problem.", "Es un problema ineludible."] },
  { w: "quimera", pos: "n", cefr: "C2", gen: "f", ipa: "kiˈmɛ.ɾɐ", g: ["angan kosong", "chimera, pipe dream", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Essa promessa é uma quimera.", "Janji itu angan kosong.", "That promise is a pipe dream.", "Esa promesa es una quimera."] },
  { w: "à luz de", pos: "phr", cefr: "C2", ipa: "a luz dʒi", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["À luz dos resultados, foi um sucesso.", "Berdasarkan hasilnya, ini sukses.", "In the light of the results, it was a success.", "A la luz de los resultados, fue un éxito."] },
];
