/* =========================================================================
   lexicon/ru.js — Словарь: Русский. Front matter + 72 headwords, A1→C2.
   Setiap entri diberi romanisasi praktis pada kolom `r`.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Rusia ditulis dengan aksara Kiril — 33 huruf yang bisa dikuasai dalam beberapa jam. Tantangan sesungguhnya bukan hurufnya, melainkan enam kasus dan pasangan aspek kata kerjanya.",
    "Russian is written in Cyrillic — 33 letters you can master in a few hours. The real challenge is not the alphabet but the six cases and the aspect pairs of its verbs.",
    "El ruso se escribe en cirílico: 33 letras que se dominan en pocas horas. El reto real no es el alfabeto, sino los seis casos y los pares aspectuales.",
  ],
  script: [
    "Tekanan tidak ditulis tetapi menentukan bunyi vokal: о tanpa tekanan berbunyi /a/. Karena itu setiap entri di sini diberi romanisasi.",
    "Stress is not written yet it reshapes the vowels: an unstressed о sounds like /a/. That is why every entry here carries a romanisation.",
    "El acento no se escribe pero cambia las vocales: una о átona suena /a/. Por eso cada entrada lleva romanización.",
  ],
  pron: [
    ["ы", "Vokal khas Rusia: seperti 'i' tetapi lidah ditarik ke belakang — мы, ты.", "A distinctly Russian vowel: like 'i' but with the tongue pulled back — мы, ты.", "Vocal típicamente rusa: como 'i' con la lengua atrás — мы, ты."],
    ["akanye", "о tanpa tekanan berbunyi /a/: молоко → 'malako'.", "An unstressed о is pronounced /a/: молоко → 'malako'.", "La о átona suena /a/: молоко → 'malako'."],
    ["ь", "Tanda lunak melembutkan konsonan sebelumnya: мать ≠ мат.", "The soft sign palatalises the consonant before it: мать ≠ мат.", "El signo blando palataliza la consonante previa: мать ≠ мат."],
    ["ж / ш / щ", "ж = 'zy', ш = 'sy' keras, щ = 'sysy' lembut panjang.", "ж = 'zh', ш = hard 'sh', щ = a long soft 'shch'.", "ж = 'zh', ш = 'sh' dura, щ = 'shch' larga y suave."],
    ["konsonan akhir", "б, в, г, д, ж, з di akhir kata mengeras: год → 'got'.", "Final б в г д ж з devoice: год → 'got'.", "б в г д ж з finales se ensordecen: год → 'got'."],
    ["р", "Getar ujung lidah, bukan tenggorokan: работа.", "A tongue-tip trill, not a throat r: работа.", "Vibrante alveolar, no gutural: работа."],
  ],
  grammar: [
    {
      t: ["Enam kasus", "Six cases", "Seis casos"],
      d: ["Akhiran kata benda menandai perannya, sehingga urutan kata bisa dibolak-balik tanpa mengubah arti.", "Noun endings mark the role, so word order can be rearranged without changing meaning.", "Las terminaciones marcan la función, así que el orden es libre."],
      ex: "книга → книгу, книге, книгой…",
    },
    {
      t: ["Tanpa 'adalah' di masa kini", "No 'to be' in the present", "Sin verbo 'ser' en presente"],
      d: ["Kalimat masa kini tidak memakai kata kerja быть: «Он врач» = 'Dia (adalah) dokter'.", "The present tense drops быть entirely: «Он врач» = 'He is a doctor'.", "El presente omite быть: «Он врач» = 'Él es médico'."],
      ex: "Я студент. · Это дом.",
    },
    {
      t: ["Aspek kata kerja", "Verb aspect", "El aspecto verbal"],
      d: ["Setiap kata kerja punya pasangan: belum selesai (делать) dan selesai (сделать).", "Every verb comes in a pair: imperfective (делать) and perfective (сделать).", "Cada verbo tiene pareja: imperfectivo (делать) y perfectivo (сделать)."],
      ex: "Я читал книгу. · Я прочитал книгу.",
    },
    {
      t: ["Kata kerja gerak", "Verbs of motion", "Verbos de movimiento"],
      d: ["Berjalan (идти/ходить) dan berkendara (ехать/ездить) memakai kata kerja berbeda — dan tiap pasangan punya bentuk satu arah & berulang.", "Going on foot (идти/ходить) and by vehicle (ехать/ездить) use different verbs — each pair split into one-way and repeated.", "Ir a pie (идти/ходить) y en vehículo (ехать/ездить) usan verbos distintos."],
      ex: "Я иду в парк. · Я езжу на работу.",
    },
    {
      t: ["Gender pada masa lampau", "Gender in the past tense", "Género en el pasado"],
      d: ["Bentuk lampau menyesuaikan jenis kelamin pelaku: он читал / она читала.", "Past-tense forms agree with the subject's gender: он читал / она читала.", "El pasado concuerda con el género: он читал / она читала."],
      ex: "Я был · Я была",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "быть", r: "byt'", pos: "v", cefr: "A1", ipa: "bɨtʲ", g: ["ada, menjadi", "to be", "ser, estar"], d: ["Menyatakan keberadaan; tidak dipakai di masa kini.", "Expresses existence; it disappears in the present tense.", "Expresa existencia; desaparece en presente."], ex: ["Он был дома.", "Dia ada di rumah.", "He was at home.", "Estaba en casa."] },
  { w: "большой", r: "bol'shoy", pos: "adj", cefr: "A1", ipa: "bɐlʲˈʂoj", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Они живут в большом городе.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["маленький"] },
  { w: "город", r: "gorod", pos: "n", cefr: "A1", gen: "m", ipa: "ˈɡorət", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Это красивый город.", "Ini kota yang indah.", "This is a beautiful city.", "Es una ciudad bonita."] },
  { w: "день", r: "den'", pos: "n", cefr: "A1", gen: "m", ipa: "dʲenʲ", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Я работаю каждый день.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["ночь"] },
  { w: "дом", r: "dom", pos: "n", cefr: "A1", gen: "m", ipa: "dom", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Мой дом рядом с парком.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "друг", r: "drug", pos: "n", cefr: "A1", gen: "m", ipa: "druk", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Это мой лучший друг.", "Ini sahabat terbaik saya.", "This is my best friend.", "Es mi mejor amigo."], note: ["Jamaknya tak beraturan: друг → друзья.", "Irregular plural: друг → друзья.", "Plural irregular: друг → друзья."] },
  { w: "женщина", r: "zhenshchina", pos: "n", cefr: "A1", gen: "f", ipa: "ˈʐɛnʲɕːɪnə", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["Эта женщина — врач.", "Perempuan itu seorang dokter.", "That woman is a doctor.", "Esa mujer es médica."], ant: ["мужчина"] },
  { w: "идти", r: "idti", pos: "v", cefr: "A1", ipa: "ɪdˈtʲi", g: ["berjalan, pergi", "to go on foot", "ir a pie"], d: ["Berpindah dengan berjalan kaki ke satu arah.", "To move on foot in one direction.", "Desplazarse a pie en una dirección."], ex: ["Я иду на рынок.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "маленький", r: "malen'kiy", pos: "adj", cefr: "A1", ipa: "ˈmalʲɪnʲkʲɪj", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["У меня маленькая квартира.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["большой"] },
  { w: "мужчина", r: "muzhchina", pos: "n", cefr: "A1", gen: "m", ipa: "mʊˈɕːinə", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["Этот мужчина — мой сосед.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["женщина"] },
  { w: "ночь", r: "noch'", pos: "n", cefr: "A1", gen: "f", ipa: "notɕ", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Спокойной ночи!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["день"] },
  { w: "хотеть", r: "khotet'", pos: "v", cefr: "A1", ipa: "xɐˈtʲetʲ", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Я хочу учить русский.", "Saya mau belajar bahasa Rusia.", "I want to learn Russian.", "Quiero aprender ruso."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "быстрый", r: "bystryy", pos: "adj", cefr: "A2", ipa: "ˈbɨstrɨj", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Поезд быстрее.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["медленный"] },
  { w: "всегда", r: "vsegda", pos: "adv", cefr: "A2", ipa: "fsʲɪɡˈda", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Я всегда завтракаю дома.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["никогда"] },
  { w: "деньги", r: "den'gi", pos: "n", cefr: "A2", ipa: "ˈdʲenʲɡʲɪ", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["У меня не хватает денег.", "Uang saya tidak cukup.", "I don't have enough money.", "No me alcanza el dinero."], note: ["Selalu jamak; tidak ada bentuk tunggal.", "Always plural; there is no singular.", "Siempre plural; no tiene singular."] },
  { w: "лёгкий", r: "lyogkiy", pos: "adj", cefr: "A2", ipa: "ˈlʲɵxʲkʲɪj", g: ["mudah; ringan", "easy; light", "fácil; ligero"], d: ["Tidak menuntut usaha; juga tidak berat.", "Not requiring effort; also not heavy.", "Que no exige esfuerzo; también ligero."], ex: ["Экзамен был лёгкий.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["трудный"] },
  { w: "начинать", r: "nachinat'", pos: "v", cefr: "A2", ipa: "nətɕɪˈnatʲ", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Фильм начинается в восемь.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "нужный", r: "nuzhnyy", pos: "adj", cefr: "A2", ipa: "ˈnuʐnɨj", g: ["diperlukan", "needed, necessary", "necesario"], d: ["Yang dibutuhkan; bentuk pendek нужно = 'perlu'.", "Required; the short form нужно means 'one needs'.", "Necesario; la forma corta нужно significa 'hace falta'."], ex: ["Мне нужно отдохнуть.", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "помогать", r: "pomogat'", pos: "v", cefr: "A2", ipa: "pəmɐˈɡatʲ", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Ты можешь мне помочь?", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"], note: ["Memakai kasus datif: помогать другу.", "It takes the dative: помогать другу.", "Rige dativo: помогать другу."] },
  { w: "потому что", r: "potomu chto", pos: "conj", cefr: "A2", ipa: "pətɐˈmu ʂtə", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Я дома, потому что идёт дождь.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },
  { w: "работа", r: "rabota", pos: "n", cefr: "A2", gen: "f", ipa: "rɐˈbotə", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Моя работа начинается в девять.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "трудный", r: "trudnyy", pos: "adj", cefr: "A2", ipa: "ˈtrudnɨj", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Здесь трудно припарковаться.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["лёгкий"] },
  { w: "время", r: "vremya", pos: "n", cefr: "A2", gen: "nt", ipa: "ˈvrʲemʲə", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["У меня нет времени.", "Saya tidak punya waktu.", "I don't have time.", "No tengo tiempo."] },
  { w: "часто", r: "chasto", pos: "adv", cefr: "A2", ipa: "ˈtɕastə", g: ["sering", "often", "a menudo"], d: ["Berulang kali dalam rentang waktu tertentu.", "Many times within a period.", "Muchas veces en un periodo."], ex: ["Мы часто созваниваемся.", "Kami sering menelepon.", "We often call each other.", "Nos llamamos a menudo."], ant: ["редко"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "возможность", r: "vozmozhnost'", pos: "n", cefr: "B1", gen: "f", ipa: "vɐzˈmoʐnəsʲtʲ", g: ["kesempatan; kemungkinan", "opportunity; possibility", "oportunidad; posibilidad"], d: ["Saat atau keadaan yang memungkinkan sesuatu.", "A chance or condition that makes something possible.", "Ocasión o condición que hace algo posible."], ex: ["Это отличная возможность.", "Ini kesempatan bagus.", "This is a great opportunity.", "Es una gran oportunidad."] },
  { w: "казаться", r: "kazat'sya", pos: "v", cefr: "B1", ipa: "kɐˈzat͡sːə", g: ["tampak", "to seem", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Он кажется усталым.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "может быть", r: "mozhet byt'", pos: "adv", cefr: "B1", ipa: "ˈmoʐɨd bɨtʲ", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Может быть, он придёт завтра.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "однако", r: "odnako", pos: "conj", cefr: "B1", ipa: "ɐdˈnakə", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Дорого; однако оно того стоит.", "Mahal; namun begitu sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "опыт", r: "opyt", pos: "n", cefr: "B1", gen: "m", ipa: "ˈopɨt", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["У неё большой опыт.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "привыкнуть", r: "privyknut'", pos: "v", cefr: "B1", ipa: "prʲɪˈvɨknʊtʲ", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Я привык к холоду.", "Saya sudah terbiasa dengan dinginnya.", "I got used to the cold.", "Me acostumbré al frío."] },
  { w: "решение", r: "resheniye", pos: "n", cefr: "B1", gen: "nt", ipa: "rʲɪˈʂɛnʲɪjə", g: ["keputusan; solusi", "decision; solution", "decisión; solución"], d: ["Pilihan yang ditetapkan; juga jalan keluar.", "A settled choice; also a way out of a problem.", "Elección tomada; también solución."], ex: ["Это было трудное решение.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya принять решение.", "The collocation is принять решение (to make a decision).", "La colocación es принять решение."] },
  { w: "скучать", r: "skuchat'", pos: "v", cefr: "B1", ipa: "skʊˈtɕatʲ", g: ["merindukan; bosan", "to miss; to be bored", "echar de menos; aburrirse"], d: ["Merasa kehilangan seseorang; juga merasa jenuh.", "To feel someone's absence; also to be bored.", "Sentir la ausencia; también aburrirse."], ex: ["Я скучаю по семье.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },
  { w: "совет", r: "sovet", pos: "n", cefr: "B1", gen: "m", ipa: "sɐˈvʲet", g: ["nasihat; dewan", "advice; council", "consejo"], d: ["Saran; juga badan permusyawaratan.", "A recommendation; also a council.", "Recomendación; también consejo (órgano)."], ex: ["Дай мне совет.", "Beri saya nasihat.", "Give me some advice.", "Dame un consejo."] },
  { w: "улучшить", r: "uluchshit'", pos: "v", cefr: "B1", ipa: "ʊˈlutʂʂɨtʲ", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Я хочу улучшить произношение.", "Saya ingin memperbaiki pelafalan.", "I want to improve my pronunciation.", "Quiero mejorar la pronunciación."] },
  { w: "хотя", r: "khotya", pos: "conj", cefr: "B1", ipa: "xɐˈtʲa", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Хотя идёт дождь, мы выйдем.", "Meskipun hujan, kami akan keluar.", "Although it's raining, we'll go out.", "Aunque llueve, saldremos."] },
  { w: "цель", r: "tsel'", pos: "n", cefr: "B1", gen: "f", ipa: "t͡sɛlʲ", g: ["tujuan, sasaran", "goal, aim", "meta"], d: ["Hasil yang ingin dicapai.", "The result you are aiming at.", "Resultado que se persigue."], ex: ["Наша цель — закончить в срок.", "Tujuan kami selesai tepat waktu.", "Our goal is to finish on time.", "Nuestra meta es terminar a tiempo."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "внедрить", r: "vnedrit'", pos: "v", cefr: "B2", ipa: "vnʲɪˈdrʲitʲ", g: ["menerapkan", "to implement, to roll out", "implantar"], d: ["Memasukkan sistem baru ke dalam praktik.", "To put a new system into practice.", "Poner en práctica un sistema nuevo."], ex: ["Мы внедрим новую систему.", "Kami akan menerapkan sistem baru.", "We'll implement the new system.", "Implantaremos el nuevo sistema."] },
  { w: "вопрос", r: "vopros", pos: "n", cefr: "B2", gen: "m", ipa: "vɐˈpros", g: ["pertanyaan; persoalan", "question; issue", "pregunta; cuestión"], d: ["Kalimat tanya; juga perkara yang dibahas.", "A question; also a matter under discussion.", "Pregunta; también asunto."], ex: ["Это деликатный вопрос.", "Itu persoalan yang sensitif.", "It's a delicate issue.", "Es una cuestión delicada."] },
  { w: "вызов", r: "vyzov", pos: "n", cefr: "B2", gen: "m", ipa: "ˈvɨzəf", g: ["tantangan; panggilan", "challenge; a call", "desafío; llamada"], d: ["Hal sulit yang menuntut usaha; juga panggilan.", "Something demanding; also a summons or call.", "Algo exigente; también una llamada."], ex: ["Это серьёзный вызов.", "Ini tantangan yang serius.", "That's a serious challenge.", "Es un desafío serio."] },
  { w: "достичь", r: "dostich'", pos: "v", cefr: "B2", ipa: "dɐˈsʲtʲitɕ", g: ["mencapai", "to achieve, to attain", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Мы достигли цели.", "Kami mencapai targetnya.", "We reached the goal.", "Alcanzamos el objetivo."] },
  { w: "надёжный", r: "nadyozhnyy", pos: "adj", cefr: "B2", ipa: "nɐˈdʲɵʐnɨj", g: ["dapat diandalkan", "reliable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Это надёжный источник.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "необходимый", r: "neobkhodimyy", pos: "adj", cefr: "B2", ipa: "nʲɪɐpxɐˈdʲimɨj", g: ["mutlak perlu", "essential, indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Паспорт необходим.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "несмотря на", r: "nesmotrya na", pos: "prep", cefr: "B2", ipa: "nʲɪsmɐˈtrʲa nə", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Несмотря на холод, мы вышли.", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."] },
  { w: "окружающая среда", r: "okruzhayushchaya sreda", pos: "n", cefr: "B2", gen: "f", ipa: "ɐkrʊˈʐajʊɕːɪjə srʲɪˈda", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["Надо беречь окружающую среду.", "Kita harus menjaga lingkungan.", "We must protect the environment.", "Debemos cuidar el medio ambiente."] },
  { w: "подчеркнуть", r: "podcherknut'", pos: "v", cefr: "B2", ipa: "pətɕɪrkˈnutʲ", g: ["menegaskan", "to emphasise, to underline", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Хочу подчеркнуть этот момент.", "Saya ingin menegaskan poin ini.", "I want to underline this point.", "Quiero subrayar este punto."] },
  { w: "поэтому", r: "poetomu", pos: "conj", cefr: "B2", ipa: "pɐˈɛtəmʊ", g: ["karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Шёл дождь, поэтому мы остались дома.", "Hujan, karena itu kami di rumah.", "It rained, therefore we stayed home.", "Llovía, por eso nos quedamos en casa."] },
  { w: "развитие", r: "razvitiye", pos: "n", cefr: "B2", gen: "nt", ipa: "rɐzˈvʲitʲɪjə", g: ["perkembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Развитие проекта идёт хорошо.", "Perkembangan proyeknya baik.", "The project's development is going well.", "El desarrollo del proyecto va bien."] },
  { w: "соглашение", r: "soglasheniye", pos: "n", cefr: "B2", gen: "nt", ipa: "səɡlɐˈʂɛnʲɪjə", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Мы подписали соглашение.", "Kami menandatangani kesepakatan.", "We signed an agreement.", "Firmamos un acuerdo."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "выделить", r: "vydelit'", pos: "v", cefr: "C1", ipa: "ˈvɨdʲɪlʲɪtʲ", g: ["menyoroti; mengalokasikan", "to single out; to allocate", "destacar; asignar"], d: ["Menonjolkan sesuatu; juga menyisihkan sumber daya.", "To make something stand out; also to set resources aside.", "Hacer resaltar algo; también asignar recursos."], ex: ["Хочу выделить три момента.", "Saya ingin menyoroti tiga hal.", "I'd like to single out three points.", "Quiero destacar tres puntos."] },
  { w: "затронуть", r: "zatronut'", pos: "v", cefr: "C1", ipa: "zɐˈtronʊtʲ", g: ["menyinggung, membahas", "to touch on, to affect", "abordar, afectar"], d: ["Membahas sebentar; juga berdampak pada sesuatu.", "To touch on a topic; also to affect something.", "Tocar un tema; también afectar algo."], ex: ["Он затронул важную тему.", "Dia menyinggung topik penting.", "He touched on an important topic.", "Abordó un tema importante."] },
  { w: "нюанс", r: "nyuans", pos: "n", cefr: "C1", gen: "m", ipa: "nʲʊˈans", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["Здесь есть важный нюанс.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "область", r: "oblast'", pos: "n", cefr: "C1", gen: "f", ipa: "ˈobləsʲtʲ", g: ["bidang; wilayah", "field; region", "ámbito; región"], d: ["Wilayah kegiatan atau pengetahuan; juga daerah administratif.", "An area of activity or knowledge; also an administrative region.", "Área de actividad o conocimiento; también región."], ex: ["В области права всё иначе.", "Dalam bidang hukum semuanya berbeda.", "In the legal field it's all different.", "En el ámbito jurídico todo es distinto."] },
  { w: "охват", r: "okhvat", pos: "n", cefr: "C1", gen: "m", ipa: "ɐxˈvat", g: ["jangkauan, cakupan", "reach, coverage", "alcance"], d: ["Seberapa luas sesuatu menjangkau.", "How widely something reaches.", "Hasta dónde llega algo."], ex: ["Охват программы очень широкий.", "Cakupan programnya sangat luas.", "The programme's reach is very wide.", "El alcance del programa es amplio."] },
  { w: "отражать", r: "otrazhat'", pos: "v", cefr: "C1", ipa: "ɐtrɐˈʐatʲ", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Данные отражают улучшение.", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "подход", r: "podkhod", pos: "n", cefr: "C1", gen: "m", ipa: "pɐtˈxot", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Нужен другой подход.", "Kita butuh pendekatan lain.", "A different approach is needed.", "Hace falta otro enfoque."] },
  { w: "содействовать", r: "sodeystvovat'", pos: "v", cefr: "C1", ipa: "sɐˈdʲejstvəvətʲ", g: ["mendorong, membantu", "to promote, to further", "fomentar"], d: ["Membantu sesuatu berjalan atau tumbuh.", "To help something along or grow.", "Ayudar a que algo avance."], ex: ["Закон содействует переработке.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "тем не менее", r: "tem ne meneye", pos: "conj", cefr: "C1", ipa: "tʲem nʲɪ ˈmʲenʲɪjə", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Тем не менее предложение в силе.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "тщательный", r: "tshchatel'nyy", pos: "adj", cefr: "C1", ipa: "ˈtɕːatʲɪlʲnɨj", g: ["teliti, saksama", "thorough, meticulous", "minucioso"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest detail.", "Hecho hasta el último detalle."], ex: ["Нужен тщательный анализ.", "Analisis yang saksama diperlukan.", "A thorough analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "укрепить", r: "ukrepit'", pos: "v", cefr: "C1", ipa: "ʊkrʲɪˈpʲitʲ", g: ["memperkukuh", "to strengthen, to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Компания укрепила свои позиции.", "Perusahaan memperkukuh posisinya.", "The company strengthened its position.", "La empresa consolidó su posición."] },
  { w: "с целью", r: "s tsel'yu", pos: "prep", cefr: "C1", ipa: "s ˈt͡sɛlʲjʊ", g: ["demi, agar", "in order to", "con el fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["С целью экономии времени мы упростили процесс.", "Demi menghemat waktu, prosesnya kami sederhanakan.", "In order to save time we simplified the process.", "Con el fin de ahorrar tiempo simplificamos el proceso."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "дверь", r: "dver'", pos: "n", cefr: "A1", gen: "f", g: ["pintu", "door", "puerta"] },
  { w: "окно", r: "okno", pos: "n", cefr: "A1", gen: "nt", g: ["jendela", "window", "ventana"] },
  { w: "комната", r: "komnata", pos: "n", cefr: "A1", gen: "f", g: ["kamar, ruangan", "room", "habitación"] },
  { w: "стол", r: "stol", pos: "n", cefr: "A1", gen: "m", g: ["meja", "table", "mesa"] },
  { w: "стул", r: "stul", pos: "n", cefr: "A1", gen: "m", g: ["kursi", "chair", "silla"] },
  { w: "кровать", r: "krovat'", pos: "n", cefr: "A1", gen: "f", g: ["tempat tidur", "bed", "cama"] },
  { w: "кухня", r: "kukhnya", pos: "n", cefr: "A1", gen: "f", g: ["dapur", "kitchen", "cocina"] },
  { w: "ванная", r: "vannaya", pos: "n", cefr: "A1", gen: "f", g: ["kamar mandi", "bathroom", "cuarto de baño"] },
  { w: "лампа", r: "lampa", pos: "n", cefr: "A1", gen: "f", g: ["lampu", "lamp", "lámpara"] },
  { w: "ключ", r: "klyuch", pos: "n", cefr: "A1", gen: "m", g: ["kunci", "key", "llave"] },
  { w: "стена", r: "stena", pos: "n", cefr: "A1", gen: "f", g: ["dinding", "wall", "pared"] },
  { w: "крыша", r: "krysha", pos: "n", cefr: "A1", gen: "f", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "хлеб", r: "khleb", pos: "n", cefr: "A1", gen: "m", g: ["roti", "bread", "pan"] },
  { w: "рис", r: "ris", pos: "n", cefr: "A1", gen: "m", g: ["nasi, beras", "rice", "arroz"] },
  { w: "мясо", r: "myaso", pos: "n", cefr: "A1", gen: "nt", g: ["daging", "meat", "carne"] },
  { w: "рыба", r: "ryba", pos: "n", cefr: "A1", gen: "f", g: ["ikan", "fish", "pescado"] },
  { w: "яйцо", r: "yaytso", pos: "n", cefr: "A1", gen: "nt", g: ["telur", "egg", "huevo"] },
  { w: "молоко", r: "moloko", pos: "n", cefr: "A1", gen: "nt", g: ["susu", "milk", "leche"] },
  { w: "чай", r: "chay", pos: "n", cefr: "A1", gen: "m", g: ["teh", "tea", "té"] },
  { w: "кофе", r: "kofe", pos: "n", cefr: "A1", gen: "m", g: ["kopi", "coffee", "café"], note: ["Kata pinjaman yang tidak berubah bentuk; secara baku maskulin.", "An indeclinable loanword; formally masculine.", "Préstamo indeclinable; formalmente masculino."] },
  { w: "сахар", r: "sakhar", pos: "n", cefr: "A1", gen: "m", g: ["gula", "sugar", "azúcar"] },
  { w: "соль", r: "sol'", pos: "n", cefr: "A1", gen: "f", g: ["garam", "salt", "sal"] },
  { w: "фрукт", r: "frukt", pos: "n", cefr: "A1", gen: "m", g: ["buah", "fruit", "fruta"] },
  { w: "овощ", r: "ovoshch", pos: "n", cefr: "A1", gen: "m", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "рубашка", r: "rubashka", pos: "n", cefr: "A2", gen: "f", g: ["kemeja", "shirt", "camisa"] },
  { w: "брюки", r: "bryuki", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalones"], note: ["Selalu jamak.", "Always plural.", "Siempre plural."] },
  { w: "обувь", r: "obuv'", pos: "n", cefr: "A2", gen: "f", g: ["alas kaki, sepatu", "footwear, shoes", "calzado"] },
  { w: "шляпа", r: "shlyapa", pos: "n", cefr: "A2", gen: "f", g: ["topi", "hat", "sombrero"] },
  { w: "рука", r: "ruka", pos: "n", cefr: "A2", gen: "f", g: ["tangan, lengan", "hand, arm", "mano, brazo"] },
  { w: "глаз", r: "glaz", pos: "n", cefr: "A2", gen: "m", g: ["mata", "eye", "ojo"] },
  { w: "голова", r: "golova", pos: "n", cefr: "A2", gen: "f", g: ["kepala", "head", "cabeza"] },
  { w: "сердце", r: "serdtse", pos: "n", cefr: "A2", gen: "nt", g: ["jantung, hati", "heart", "corazón"] },
  { w: "волосы", r: "volosy", pos: "n", cefr: "A2", g: ["rambut", "hair", "cabello"] },
  { w: "зуб", r: "zub", pos: "n", cefr: "A2", gen: "m", g: ["gigi", "tooth", "diente"] },
  { w: "ухо", r: "ukho", pos: "n", cefr: "A2", gen: "nt", g: ["telinga", "ear", "oreja"] },
  { w: "лицо", r: "litso", pos: "n", cefr: "A2", gen: "nt", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "дерево", r: "derevo", pos: "n", cefr: "A2", gen: "nt", g: ["pohon; kayu", "tree; wood", "árbol; madera"] },
  { w: "цветок", r: "tsvetok", pos: "n", cefr: "A2", gen: "m", g: ["bunga", "flower", "flor"] },
  { w: "гора", r: "gora", pos: "n", cefr: "A2", gen: "f", g: ["gunung", "mountain", "montaña"] },
  { w: "река", r: "reka", pos: "n", cefr: "A2", gen: "f", g: ["sungai", "river", "río"] },
  { w: "море", r: "more", pos: "n", cefr: "A2", gen: "nt", g: ["laut", "sea", "mar"] },
  { w: "небо", r: "nebo", pos: "n", cefr: "A2", gen: "nt", g: ["langit", "sky", "cielo"] },
  { w: "звезда", r: "zvezda", pos: "n", cefr: "A2", gen: "f", g: ["bintang", "star", "estrella"] },
  { w: "собака", r: "sobaka", pos: "n", cefr: "A2", gen: "f", g: ["anjing", "dog", "perro"] },
  { w: "кошка", r: "koshka", pos: "n", cefr: "A2", gen: "f", g: ["kucing", "cat", "gato"] },
  { w: "птица", r: "ptitsa", pos: "n", cefr: "A2", gen: "f", g: ["burung", "bird", "pájaro"] },
  { w: "лошадь", r: "loshad'", pos: "n", cefr: "A2", gen: "f", g: ["kuda", "horse", "caballo"] },
  { w: "дождь", r: "dozhd'", pos: "n", cefr: "A2", gen: "m", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "улица", r: "ulitsa", pos: "n", cefr: "B1", gen: "f", g: ["jalan", "street", "calle"] },
  { w: "мост", r: "most", pos: "n", cefr: "B1", gen: "m", g: ["jembatan", "bridge", "puente"] },
  { w: "рынок", r: "rynok", pos: "n", cefr: "B1", gen: "m", g: ["pasar", "market", "mercado"] },
  { w: "школа", r: "shkola", pos: "n", cefr: "B1", gen: "f", g: ["sekolah", "school", "escuela"] },
  { w: "больница", r: "bol'nitsa", pos: "n", cefr: "B1", gen: "f", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "офис", r: "ofis", pos: "n", cefr: "B1", gen: "m", g: ["kantor", "office", "oficina"] },
  { w: "автобус", r: "avtobus", pos: "n", cefr: "B1", gen: "m", g: ["bus", "bus", "autobús"] },
  { w: "поезд", r: "poyezd", pos: "n", cefr: "B1", gen: "m", g: ["kereta api", "train", "tren"] },
  { w: "машина", r: "mashina", pos: "n", cefr: "B1", gen: "f", g: ["mobil; mesin", "car; machine", "coche; máquina"] },
  { w: "велосипед", r: "velosiped", pos: "n", cefr: "B1", gen: "m", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "аэропорт", r: "aeroport", pos: "n", cefr: "B1", gen: "m", g: ["bandara", "airport", "aeropuerto"] },
  { w: "билет", r: "bilet", pos: "n", cefr: "B1", gen: "m", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "компания", r: "kompaniya", pos: "n", cefr: "B2", gen: "f", g: ["perusahaan", "company", "empresa"] },
  { w: "встреча", r: "vstrecha", pos: "n", cefr: "B2", gen: "f", g: ["pertemuan, rapat", "meeting", "reunión"] },
  { w: "договор", r: "dogovor", pos: "n", cefr: "B2", gen: "m", g: ["kontrak, perjanjian", "contract", "contrato"] },
  { w: "зарплата", r: "zarplata", pos: "n", cefr: "B2", gen: "f", g: ["gaji", "salary", "sueldo"] },
  { w: "цена", r: "tsena", pos: "n", cefr: "B2", gen: "f", g: ["harga", "price", "precio"] },
  { w: "налог", r: "nalog", pos: "n", cefr: "B2", gen: "m", g: ["pajak", "tax", "impuesto"] },
  { w: "банк", r: "bank", pos: "n", cefr: "B2", gen: "m", g: ["bank", "bank", "banco"] },
  { w: "компьютер", r: "komp'yuter", pos: "n", cefr: "B2", gen: "m", g: ["komputer", "computer", "ordenador"] },
  { w: "телефон", r: "telefon", pos: "n", cefr: "B2", gen: "m", g: ["telepon", "telephone", "teléfono"] },
  { w: "почта", r: "pochta", pos: "n", cefr: "B2", gen: "f", g: ["pos; surel", "post; mail", "correo"] },
  { w: "файл", r: "fayl", pos: "n", cefr: "B2", gen: "m", g: ["berkas", "file", "archivo"] },
  { w: "пароль", r: "parol'", pos: "n", cefr: "B2", gen: "m", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "безотлагательный", r: "bezotlagatel'nyy", pos: "adj", cefr: "C2", ipa: "bʲɪzətlɐˈɡatʲɪlʲnɨj", g: ["mendesak, tak bisa ditunda", "urgent, brooking no delay", "inaplazable"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay at all.", "Que exige acción sin demora."], ex: ["Это безотлагательный вопрос.", "Ini persoalan mendesak.", "This is an urgent matter.", "Es un asunto inaplazable."] },
  { w: "веха", r: "vekha", pos: "n", cefr: "C2", gen: "f", ipa: "ˈvʲexə", g: ["tonggak", "milestone, landmark", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Договор стал важной вехой.", "Perjanjian itu menjadi tonggak penting.", "The treaty became an important milestone.", "El tratado fue un hito importante."] },
  { w: "в свете", r: "v svete", pos: "prep", cefr: "C2", ipa: "f ˈsvʲetʲɪ", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["В свете новых данных это успех.", "Berdasarkan data baru, ini sukses.", "In the light of the new data it's a success.", "A la luz de los nuevos datos, es un éxito."] },
  { w: "неизбежный", r: "neizbezhnyy", pos: "adj", cefr: "C2", ipa: "nʲɪɪzˈbʲeʐnɨj", g: ["tak terhindarkan", "inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Рост цен неизбежен.", "Kenaikan harga tak terhindarkan.", "A price rise is inevitable.", "La subida de precios es inevitable."] },
  { w: "невыразимый", r: "nevyrazimyy", pos: "adj", cefr: "C2", ipa: "nʲɪvɨrɐˈzʲimɨj", g: ["tak terlukiskan", "ineffable, inexpressible", "inefable"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Невыразимая радость.", "Sukacita yang tak terlukiskan.", "An ineffable joy.", "Una alegría inefable."] },
  { w: "парадигма", r: "paradigma", pos: "n", cefr: "C2", gen: "f", ipa: "pərɐˈdʲiɡmə", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Это была смена парадигмы.", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "предвзятость", r: "predvzyatost'", pos: "n", cefr: "C2", gen: "f", ipa: "prʲɪdˈvzʲatəsʲtʲ", g: ["prasangka, bias", "bias, prejudice", "sesgo"], d: ["Kecenderungan menilai secara tidak berimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["В исследовании есть предвзятость.", "Kajian itu mengandung bias.", "The study contains a bias.", "El estudio tiene un sesgo."] },
  { w: "проблеск", r: "problesk", pos: "n", cefr: "C2", gen: "m", ipa: "ˈprobʲlʲɪsk", g: ["secercah", "glimmer, gleam", "destello"], d: ["Cahaya lemah; kiasan untuk tanda kecil harapan.", "A faint light; figuratively a small sign of hope.", "Luz tenue; indicio de esperanza."], ex: ["Есть проблеск надежды.", "Ada secercah harapan.", "There's a glimmer of hope.", "Hay un destello de esperanza."] },
  { w: "прояснить", r: "proyasnit'", pos: "v", cefr: "C2", ipa: "prəjɪˈsʲnʲitʲ", g: ["menjernihkan", "to clarify, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Нужно прояснить детали.", "Rinciannya perlu dijernihkan.", "The details need clarifying.", "Hay que esclarecer los detalles."] },
  { w: "уклоняться", r: "uklonyat'sya", pos: "v", cefr: "C2", ipa: "ʊklɐˈnʲat͡sːə", g: ["mengelak", "to evade, to dodge", "eludir"], d: ["Menghindari kewajiban atau pertanyaan.", "To avoid a duty or a question.", "Evitar un deber o una pregunta."], ex: ["Он уклонился от ответа.", "Dia mengelak dari jawaban.", "He dodged the answer.", "Eludió la respuesta."] },
  { w: "умалять", r: "umalyat'", pos: "v", cefr: "C2", ipa: "ʊmɐˈlʲatʲ", g: ["merendahkan, mengurangi", "to belittle, to diminish", "menoscabar"], d: ["Membuat nilai sesuatu tampak lebih kecil.", "To make something seem less valuable.", "Hacer que algo parezca menor."], ex: ["Не хочу умалять его заслуги.", "Saya tak ingin merendahkan jasanya.", "I don't want to belittle his merits.", "No quiero menoscabar sus méritos."] },
  { w: "химера", r: "khimera", pos: "n", cefr: "C2", gen: "f", ipa: "xʲɪˈmʲerə", g: ["angan kosong", "chimera, pipe dream", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Это обещание — химера.", "Janji itu angan kosong.", "That promise is a chimera.", "Esa promesa es una quimera."] },
];
