/* =========================================================================
   lexicon/sv.js — Ordbok: Svenska. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Swedia punya melodi: setiap kata membawa nada, dan dua kata dengan huruf sama bisa berbeda arti hanya karena naik-turunnya suara. Tata bahasanya sendiri termasuk paling sederhana di Eropa.",
    "Swedish is a musical language: every word carries a tone, and two identical spellings can mean different things purely by pitch. The grammar itself is among Europe's simplest.",
    "El sueco es una lengua melódica: cada palabra lleva un tono y dos grafías idénticas pueden diferir solo por la entonación. Su gramática es de las más simples de Europa.",
  ],
  script: [
    "29 huruf: abjad Latin ditambah å, ä, ö yang berdiri di urutan paling akhir — penting saat mencari kata di kamus.",
    "29 letters: the Latin alphabet plus å, ä, ö, which come last in alphabetical order — important when looking words up.",
    "29 letras: el alfabeto latino más å, ä, ö, que van al final del orden alfabético.",
  ],
  pron: [
    ["sj / sk", "Bunyi khas /ɧ/ yang tak ada di bahasa lain: sju, skön.", "The uniquely Swedish /ɧ/ sound: sju, skön.", "El sonido /ɧ/, exclusivo del sueco: sju, skön."],
    ["k + e/i/y", "Berubah jadi /ɕ/: kyrka, kär — bukan /k/.", "Turns into /ɕ/: kyrka, kär — not /k/.", "Se convierte en /ɕ/: kyrka, kär, no /k/."],
    ["å ä ö", "å ≈ 'o' bulat, ä ≈ 'e' terbuka, ö ≈ 'e' dengan bibir bulat.", "å ≈ rounded 'o', ä ≈ open 'e', ö ≈ 'e' with rounded lips.", "å ≈ 'o' redondeada, ä ≈ 'e' abierta, ö ≈ 'e' con labios redondeados."],
    ["dua nada", "Nada 1 vs nada 2 membedakan arti: anden (bebek itu) ≠ anden (roh itu).", "Tone 1 vs tone 2 distinguishes words: anden (the duck) ≠ anden (the spirit).", "El tono 1 y el 2 distinguen palabras: anden (el pato) ≠ anden (el espíritu)."],
    ["rs", "r + s melebur jadi /ʂ/: kors, först.", "r + s merge into /ʂ/: kors, först.", "r + s se funden en /ʂ/: kors, först."],
    ["huruf bisu", "g, d, h sering bisu di awal: djur, hjärta, gjorde.", "g, d, h are often silent at the start: djur, hjärta, gjorde.", "g, d, h suelen ser mudas al inicio: djur, hjärta, gjorde."],
  ],
  grammar: [
    {
      t: ["en atau ett", "en or ett", "en o ett"],
      d: ["Dua gender saja. Artikel tentu menempel di belakang kata: en bok → boken, ett hus → huset.", "Only two genders. The definite article attaches to the end: en bok → boken, ett hus → huset.", "Solo dos géneros. El artículo definido se pega al final: en bok → boken."],
      ex: "en bil → bilen · ett bord → bordet",
    },
    {
      t: ["Kata kerja tanpa persona", "Verbs ignore the person", "El verbo ignora la persona"],
      d: ["Satu bentuk untuk semua pelaku: jag är, du är, vi är — tak ada konjugasi.", "One form for every subject: jag är, du är, vi är — no conjugation at all.", "Una sola forma para todos: jag är, du är, vi är."],
      ex: "jag talar · du talar · de talar",
    },
    {
      t: ["Kata kerja di posisi kedua", "Verb second", "El verbo en segunda posición"],
      d: ["Seperti bahasa Jerman, kata kerja adalah unsur kedua dalam kalimat pernyataan.", "As in German, the verb is the second element of a statement.", "Como en alemán, el verbo es el segundo elemento."],
      ex: "I morgon åker jag till Malmö.",
    },
    {
      t: ["Kata sandang ganda", "The double definite", "La doble determinación"],
      d: ["Bila ada kata sifat, artikelnya muncul dua kali: den stora bilen.", "With an adjective the article appears twice: den stora bilen.", "Con adjetivo el artículo aparece dos veces: den stora bilen."],
      ex: "huset → det gula huset",
    },
    {
      t: ["Kalimat pasif ber-s", "The -s passive", "La pasiva en -s"],
      d: ["Cukup tambahkan -s untuk membentuk pasif: dörren öppnas.", "Just add -s to form the passive: dörren öppnas.", "Basta añadir -s para la pasiva: dörren öppnas."],
      ex: "Boken läses av många.",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "hus", pos: "n", cefr: "A1", gen: "ett", ipa: "hʉːs", g: ["rumah", "house", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Vårt hus har en trädgård.", "Rumah kami punya taman.", "Our house has a garden.", "Nuestra casa tiene jardín."] },
  { w: "dag", pos: "n", cefr: "A1", gen: "en", ipa: "dɑːɡ", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Jag arbetar varje dag.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["natt"] },
  { w: "natt", pos: "n", cefr: "A1", gen: "en", ipa: "natː", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["God natt!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["dag"] },
  { w: "man", pos: "n", cefr: "A1", gen: "en", ipa: "manː", g: ["laki-laki; suami", "man; husband", "hombre; marido"], d: ["Manusia dewasa laki-laki; juga suami.", "An adult male; also a husband.", "Hombre adulto; también marido."], ex: ["Mannen där är min granne.", "Laki-laki di sana tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["kvinna"] },
  { w: "kvinna", pos: "n", cefr: "A1", gen: "en", ipa: "ˈkvɪnːa", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["Kvinnan med hatten är min moster.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["man"] },
  { w: "vän", pos: "n", cefr: "A1", gen: "en", ipa: "vɛnː", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Jag träffar en vän ikväll.", "Saya bertemu teman malam ini.", "I'm meeting a friend tonight.", "Veré a un amigo esta noche."] },
  { w: "stor", pos: "adj", cefr: "A1", ipa: "stuːr", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["De bor i en stor stad.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["liten"] },
  { w: "liten", pos: "adj", cefr: "A1", ipa: "ˈliːtɛn", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Jag har en liten lägenhet.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["stor"], note: ["Bentuknya tak beraturan: liten / litet / lilla / små.", "Highly irregular: liten / litet / lilla / små.", "Muy irregular: liten / litet / lilla / små."] },
  { w: "bra", pos: "adj", cefr: "A1", ipa: "brɑː", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["Det är en bra idé.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["dålig"] },
  { w: "ha", pos: "v", cefr: "A1", ipa: "hɑː", g: ["punya", "to have", "tener"], d: ["Memiliki sesuatu.", "To possess something.", "Poseer algo."], ex: ["Jag har två systrar.", "Saya punya dua saudara perempuan.", "I have two sisters.", "Tengo dos hermanas."] },
  { w: "vilja", pos: "v", cefr: "A1", ipa: "ˈvɪlja", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Jag vill lära mig svenska.", "Saya mau belajar bahasa Swedia.", "I want to learn Swedish.", "Quiero aprender sueco."] },
  { w: "gå", pos: "v", cefr: "A1", ipa: "ɡoː", g: ["berjalan, pergi", "to walk, to go", "andar, ir"], d: ["Berpindah dengan berjalan kaki.", "To move on foot.", "Desplazarse a pie."], ex: ["Jag går till torget.", "Saya berjalan ke alun-alun.", "I'm walking to the square.", "Voy andando a la plaza."], note: ["gå berarti berjalan kaki; untuk berkendara pakai åka.", "gå means to walk; use åka when you travel by vehicle.", "gå es ir a pie; para vehículos se usa åka."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "arbete", pos: "n", cefr: "A2", gen: "ett", ipa: "ˈarbeːtɛ", g: ["pekerjaan", "work", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Mitt arbete börjar klockan nio.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "pengar", pos: "n", cefr: "A2", ipa: "ˈpɛŋar", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Jag har inte tillräckligt med pengar.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."], note: ["Selalu jamak: pengar, tidak ada bentuk tunggalnya.", "Always plural: pengar has no singular.", "Siempre plural: pengar no tiene singular."] },
  { w: "tid", pos: "n", cefr: "A2", gen: "en", ipa: "tiːd", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["Jag har ingen tid i dag.", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "stad", pos: "n", cefr: "A2", gen: "en", ipa: "stɑːd", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Göteborg är en fin stad.", "Göteborg kota yang indah.", "Gothenburg is a lovely city.", "Gotemburgo es una ciudad bonita."] },
  { w: "hjälpa", pos: "v", cefr: "A2", ipa: "ˈjɛlpa", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Kan du hjälpa mig, tack?", "Bisakah kamu menolong saya?", "Can you help me, please?", "¿Puedes ayudarme, por favor?"] },
  { w: "behöva", pos: "v", cefr: "A2", ipa: "bɛˈhøːva", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Jag behöver vila.", "Saya butuh istirahat.", "I need rest.", "Necesito descansar."] },
  { w: "börja", pos: "v", cefr: "A2", ipa: "ˈbœrja", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Filmen börjar klockan åtta.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["sluta"] },
  { w: "lätt", pos: "adj", cefr: "A2", ipa: "lɛtː", g: ["mudah; ringan", "easy; light", "fácil; ligero"], d: ["Tidak menuntut usaha; juga tidak berat.", "Not requiring effort; also not heavy.", "Que no exige esfuerzo; también ligero."], ex: ["Provet var lätt.", "Ujiannya mudah.", "The test was easy.", "El examen fue fácil."], ant: ["svår"] },
  { w: "svår", pos: "adj", cefr: "A2", ipa: "svoːr", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Det är svårt att parkera här.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["lätt"] },
  { w: "snabb", pos: "adj", cefr: "A2", ipa: "snabː", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Tåget är snabbare.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["långsam"] },
  { w: "alltid", pos: "adv", cefr: "A2", ipa: "ˈalːtiːd", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Jag äter alltid frukost hemma.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["aldrig"] },
  { w: "eftersom", pos: "conj", cefr: "A2", ipa: "ˈɛftɛrsɔm", g: ["karena", "because, since", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Jag stannar hemma eftersom det regnar.", "Saya di rumah karena hujan.", "I'm staying home because it's raining.", "Me quedo en casa porque llueve."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "erfarenhet", pos: "n", cefr: "B1", gen: "en", ipa: "ɛrˈfɑːrɛnheːt", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Hon har lång erfarenhet.", "Dia sangat berpengalaman.", "She has long experience.", "Tiene mucha experiencia."] },
  { w: "beslut", pos: "n", cefr: "B1", gen: "ett", ipa: "bɛˈslʉːt", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Det var ett svårt beslut.", "Itu keputusan yang sulit.", "That was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya fatta ett beslut.", "The collocation is fatta ett beslut (to make a decision).", "La colocación es fatta ett beslut."] },
  { w: "tillfälle", pos: "n", cefr: "B1", gen: "ett", ipa: "ˈtɪlfɛlːɛ", g: ["kesempatan", "opportunity, occasion", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["Det är ett bra tillfälle.", "Ini kesempatan bagus.", "It's a good opportunity.", "Es una buena oportunidad."] },
  { w: "råd", pos: "n", cefr: "B1", gen: "ett", ipa: "roːd", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Får jag ge dig ett råd?", "Boleh saya beri nasihat?", "May I give you some advice?", "¿Puedo darte un consejo?"] },
  { w: "förbättra", pos: "v", cefr: "B1", ipa: "fœrˈbɛtːra", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Jag vill förbättra mitt uttal.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "lyckas", pos: "v", cefr: "B1", ipa: "ˈlʏkːas", g: ["berhasil", "to succeed", "lograr"], d: ["Berhasil melakukan yang diusahakan.", "To succeed in doing something.", "Lograr hacer algo."], ex: ["Jag lyckades bli klar i tid.", "Saya berhasil selesai tepat waktu.", "I managed to finish on time.", "Logré terminar a tiempo."], ant: ["misslyckas"] },
  { w: "verka", pos: "v", cefr: "B1", ipa: "ˈvæ̌rka", g: ["tampak", "to seem", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Han verkar trött.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "fastän", pos: "conj", cefr: "B1", ipa: "ˈfastɛn", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Fastän det regnar går vi ut.", "Meskipun hujan, kami keluar.", "Although it's raining, we're going out.", "Aunque llueve, salimos."] },
  { w: "dock", pos: "adv", cefr: "B1", ipa: "dɔkː", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Det är dyrt; det är dock värt det.", "Mahal; namun begitu sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "kanske", pos: "adv", cefr: "B1", ipa: "ˈkanːʃɛ", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Kanske kommer han i morgon.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "vänja sig", pos: "v", cefr: "B1", ipa: "ˈvɛnja sɛj", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Jag har vant mig vid kylan.", "Saya sudah terbiasa dengan dinginnya.", "I've got used to the cold.", "Me he acostumbrado al frío."] },
  { w: "sakna", pos: "v", cefr: "B1", ipa: "ˈsɑːkna", g: ["merindukan; tidak punya", "to miss; to lack", "echar de menos; carecer"], d: ["Merasa kehilangan; juga tidak memiliki.", "To feel an absence; also to lack.", "Sentir una ausencia; también carecer."], ex: ["Jag saknar min familj.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "utveckling", pos: "n", cefr: "B2", gen: "en", ipa: "ˈʉːtvɛklɪŋ", g: ["perkembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Utvecklingen går framåt.", "Perkembangannya maju.", "The development is progressing.", "El desarrollo avanza."] },
  { w: "miljö", pos: "n", cefr: "B2", gen: "en", ipa: "mɪlˈjøː", g: ["lingkungan", "environment", "medio ambiente"], d: ["Alam sekitar; juga suasana tempat kerja.", "The natural surroundings; also a work setting.", "Entorno natural; también ambiente laboral."], ex: ["Vi måste skydda miljön.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "utmaning", pos: "n", cefr: "B2", gen: "en", ipa: "ˈʉːtmɑːnɪŋ", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Det är en riktig utmaning.", "Ini benar-benar tantangan.", "That's a real challenge.", "Es todo un desafío."] },
  { w: "avtal", pos: "n", cefr: "B2", gen: "ett", ipa: "ˈɑːvtɑːl", g: ["perjanjian", "agreement, contract", "acuerdo"], d: ["Kesepakatan resmi antara dua pihak.", "A formal agreement between two sides.", "Acuerdo formal entre dos partes."], ex: ["Vi har skrivit ett avtal.", "Kami menandatangani perjanjian.", "We signed an agreement.", "Firmamos un acuerdo."] },
  { w: "uppnå", pos: "v", cefr: "B2", ipa: "ˈʉpːnoː", g: ["mencapai", "to achieve, to attain", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Vi uppnådde målet.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "betona", pos: "v", cefr: "B2", ipa: "bɛˈtuːna", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Hon betonade säkerheten.", "Dia menekankan keselamatan.", "She emphasised safety.", "Subrayó la seguridad."] },
  { w: "pålitlig", pos: "adj", cefr: "B2", ipa: "ˈpoːliːtlɪɡ", g: ["dapat diandalkan", "reliable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Det är en pålitlig källa.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "oumbärlig", pos: "adj", cefr: "B2", ipa: "ˈuːʉmbæːrlɪɡ", g: ["mutlak perlu", "indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Passet är oumbärligt.", "Paspor mutlak diperlukan.", "The passport is indispensable.", "El pasaporte es imprescindible."] },
  { w: "trots", pos: "prep", cefr: "B2", ipa: "trɔtːs", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Trots kylan gick vi ut.", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."] },
  { w: "därför", pos: "conj", cefr: "B2", ipa: "ˈdæːrfœr", g: ["karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Det regnade; därför stannade vi hemma.", "Hujan; karena itu kami di rumah.", "It rained; therefore we stayed home.", "Llovía; por eso nos quedamos en casa."] },
  { w: "fråga", pos: "n", cefr: "B2", gen: "en", ipa: "ˈfroːɡa", g: ["pertanyaan; persoalan", "question; issue", "pregunta; cuestión"], d: ["Kalimat tanya; juga perkara yang dibahas.", "A question; also a matter under discussion.", "Una pregunta; también un asunto."], ex: ["Det är en känslig fråga.", "Itu persoalan yang sensitif.", "It's a sensitive issue.", "Es una cuestión delicada."] },
  { w: "genomföra", pos: "v", cefr: "B2", ipa: "ˈjeːnɔmfœːra", g: ["melaksanakan", "to carry out, to implement", "llevar a cabo"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["Vi genomför planen i höst.", "Kami laksanakan rencananya musim gugur ini.", "We'll carry out the plan this autumn.", "Llevaremos a cabo el plan en otoño."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "område", pos: "n", cefr: "C1", gen: "ett", ipa: "ˈɔmroːdɛ", g: ["bidang; wilayah", "field; area", "ámbito; zona"], d: ["Wilayah kegiatan atau pengetahuan; juga daerah.", "An area of activity or knowledge; also a region.", "Área de actividad o conocimiento; también zona."], ex: ["Inom juridiska området gäller annat.", "Dalam bidang hukum berlaku hal lain.", "Different rules apply in the legal field.", "En el ámbito jurídico rige otra cosa."] },
  { w: "ansats", pos: "n", cefr: "C1", gen: "en", ipa: "ˈansatːs", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Vi behöver en ny ansats.", "Kita butuh pendekatan baru.", "We need a new approach.", "Necesitamos un nuevo enfoque."] },
  { w: "nyans", pos: "n", cefr: "C1", gen: "en", ipa: "nyˈaŋs", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau warna.", "A subtle difference in meaning or colour.", "Diferencia sutil de sentido o color."], ex: ["Det finns en viktig nyans här.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "ta itu med", pos: "phr", cefr: "C1", ipa: "tɑː ˈiːtʉː meːd", g: ["menangani", "to tackle, to get to grips with", "abordar"], d: ["Mulai menghadapi masalah secara langsung.", "To start dealing with a problem head-on.", "Empezar a afrontar un problema."], ex: ["Vi måste ta itu med problemet.", "Kita harus menangani masalah itu.", "We must tackle the problem.", "Debemos abordar el problema."] },
  { w: "främja", pos: "v", cefr: "C1", ipa: "ˈfrɛmja", g: ["mendorong", "to promote, to foster", "fomentar"], d: ["Membantu sesuatu tumbuh atau berkembang.", "To help something grow.", "Ayudar a que algo crezca."], ex: ["Lagen främjar återvinning.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "återspegla", pos: "v", cefr: "C1", ipa: "ˈoːtɛrspeːɡla", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Siffrorna återspeglar en förbättring.", "Angkanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "grundlig", pos: "adj", cefr: "C1", ipa: "ˈɡrʉndlɪɡ", g: ["menyeluruh, teliti", "thorough", "minucioso"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest detail.", "Hecho hasta el último detalle."], ex: ["En grundlig granskning krävs.", "Pemeriksaan menyeluruh diperlukan.", "A thorough review is required.", "Se requiere una revisión minuciosa."] },
  { w: "likväl", pos: "conj", cefr: "C1", ipa: "liːkˈvɛːl", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Likväl står förslaget kvar.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue en pie."] },
  { w: "i syfte att", pos: "phr", cefr: "C1", ipa: "iː ˈsʏftɛ at", g: ["demi, agar", "in order to", "con el fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["I syfte att spara tid förenklar vi.", "Demi menghemat waktu, kami sederhanakan.", "In order to save time, we simplify.", "Con el fin de ahorrar tiempo, simplificamos."] },
  { w: "befästa", pos: "v", cefr: "C1", ipa: "bɛˈfɛsta", g: ["memperkukuh", "to consolidate, to entrench", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Företaget befäste sin ställning.", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "räckvidd", pos: "n", cefr: "C1", gen: "en", ipa: "ˈrɛkviːd", g: ["jangkauan", "reach, scope", "alcance"], d: ["Seberapa jauh pengaruh sesuatu terasa.", "How far something's effect reaches.", "Hasta dónde llega el efecto."], ex: ["Beslutets räckvidd är stor.", "Jangkauan keputusan itu luas.", "The decision's scope is wide.", "El alcance de la decisión es amplio."] },
  { w: "framhäva", pos: "v", cefr: "C1", ipa: "ˈframhɛːva", g: ["menyoroti", "to highlight, to bring out", "resaltar"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["Rapporten framhäver riskerna.", "Laporan itu menyoroti risikonya.", "The report highlights the risks.", "El informe resalta los riesgos."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "paradigm", pos: "n", cefr: "C2", gen: "ett", ipa: "paraˈdiɡm", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Det var ett paradigmskifte.", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "kringgå", pos: "v", cefr: "C2", ipa: "ˈkrɪŋɡoː", g: ["mengelak, menyiasati", "to circumvent, to sidestep", "eludir"], d: ["Menghindari aturan atau persoalan tanpa melanggarnya terang-terangan.", "To get around a rule or an issue without meeting it head-on.", "Sortear una norma o un asunto sin afrontarlo."], ex: ["Han kringgick frågan.", "Dia mengelak dari pertanyaan itu.", "He sidestepped the question.", "Eludió la pregunta."] },
  { w: "klargöra", pos: "v", cefr: "C2", ipa: "ˈklɑːrjøːra", g: ["menjernihkan", "to clarify, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Det återstår att klargöra vem som beslutade.", "Masih harus dijernihkan siapa yang memutuskan.", "It remains to be clarified who decided.", "Queda por esclarecer quién decidió."] },
  { w: "obeskrivlig", pos: "adj", cefr: "C2", ipa: "ˈuːbɛskriːvlɪɡ", g: ["tak terlukiskan", "indescribable, ineffable", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["En obeskrivlig glädje.", "Sukacita yang tak terlukiskan.", "An indescribable joy.", "Una alegría indescriptible."] },
  { w: "tvingande", pos: "adj", cefr: "C2", ipa: "ˈtvɪŋandɛ", g: ["memaksa, mengikat", "compelling, imperative", "imperativo"], d: ["Tak menyisakan pilihan lain.", "Leaving no other option.", "Que no deja otra opción."], ex: ["Det är inget tvingande skäl.", "Itu bukan alasan yang memaksa.", "That is no compelling reason.", "No es una razón imperativa."] },
  { w: "glimt", pos: "n", cefr: "C2", gen: "en", ipa: "ɡlɪmt", g: ["kilasan, secercah", "glimpse, glimmer", "destello"], d: ["Penampakan atau tanda yang sangat sekilas.", "A very brief sight or sign.", "Visión o señal muy breve."], ex: ["En glimt av hopp finns kvar.", "Masih ada secercah harapan.", "A glimmer of hope remains.", "Queda un destello de esperanza."] },
  { w: "snedvridning", pos: "n", cefr: "C2", gen: "en", ipa: "ˈsneːdvriːdnɪŋ", g: ["bias, distorsi", "bias, distortion", "sesgo"], d: ["Penyimpangan yang membuat gambaran tidak jujur.", "A distortion that makes the picture untrue.", "Distorsión que falsea la imagen."], ex: ["Studien har en tydlig snedvridning.", "Kajian itu punya bias yang jelas.", "The study has a clear bias.", "El estudio tiene un sesgo claro."] },
  { w: "undergräva", pos: "v", cefr: "C2", ipa: "ˈʉndɛrɡrɛːva", g: ["merongrong", "to undermine", "socavar"], d: ["Melemahkan sesuatu sedikit demi sedikit.", "To weaken something bit by bit.", "Debilitar algo poco a poco."], ex: ["Det undergräver hans trovärdighet.", "Hal itu merongrong kredibilitasnya.", "That undermines his credibility.", "Eso socava su credibilidad."] },
  { w: "milstolpe", pos: "n", cefr: "C2", gen: "en", ipa: "ˈmiːlstɔlpɛ", g: ["tonggak", "milestone", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Avtalet var en milstolpe.", "Perjanjian itu menjadi tonggak.", "The agreement was a milestone.", "El acuerdo fue un hito."] },
  { w: "ofrånkomlig", pos: "adj", cefr: "C2", ipa: "ˈuːfroːnkɔmlɪɡ", g: ["tak terhindarkan", "inescapable", "ineludible"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["En prishöjning är ofrånkomlig.", "Kenaikan harga tak terhindarkan.", "A price rise is inescapable.", "La subida de precios es ineludible."] },
  { w: "hjärnspöke", pos: "n", cefr: "C2", gen: "ett", ipa: "ˈjæːrnspøːkɛ", g: ["khayalan kosong", "figment, phantom idea", "quimera"], d: ["Gagasan yang hanya ada dalam bayangan.", "An idea that exists only in the mind.", "Idea que solo existe en la imaginación."], ex: ["Planen är ett hjärnspöke.", "Rencana itu khayalan belaka.", "The plan is a figment.", "El plan es una quimera."] },
  { w: "i ljuset av", pos: "phr", cefr: "C2", ipa: "iː ˈjʉːsɛt ɑːv", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["I ljuset av resultaten är det en framgång.", "Berdasarkan hasilnya, ini sukses.", "In the light of the results it's a success.", "A la luz de los resultados, es un éxito."] },
];
