/* =========================================================================
   lexicon/sw.js — Kamusi: Kiswahili. Front matter + 72 headwords, A1→C2.
   Kata kerja dicantumkan dengan awalan infinitif ku-, seperti dalam kamus.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Swahili adalah bahasa penghubung Afrika Timur — dituturkan lebih dari 100 juta orang di Tanzania, Kenya, Uganda, dan Kongo. Kosakatanya Bantu dengan lapisan tebal serapan Arab.",
    "Swahili is East Africa's link language — spoken by over 100 million people across Tanzania, Kenya, Uganda and Congo. Its vocabulary is Bantu with a thick layer of Arabic loans.",
    "El suajili es la lengua franca de África Oriental: más de 100 millones de hablantes. Su léxico es bantú con una capa árabe.",
  ],
  script: [
    "Abjad Latin tanpa q dan x. Ejaannya benar-benar fonetis, dan tekanan hampir selalu jatuh pada suku kata kedua dari belakang — jadi membaca Swahili mudah sejak hari pertama.",
    "The Latin alphabet minus q and x. Spelling is perfectly phonetic and stress falls almost always on the second-to-last syllable — Swahili is readable from day one.",
    "Alfabeto latino sin q ni x. Ortografía totalmente fonética y acento en la penúltima sílaba.",
  ],
  pron: [
    ["ng'", "Bunyi /ŋ/ tersendiri, berbeda dari ng biasa: ng'ombe (sapi).", "A standalone /ŋ/, different from plain ng: ng'ombe (cow).", "Una /ŋ/ independiente, distinta de ng: ng'ombe (vaca)."],
    ["mb / nd / nj", "Konsonan sengau rangkap di awal kata: mbwa, ndege, njia.", "Prenasalised consonants can begin a word: mbwa, ndege, njia.", "Consonantes prenasalizadas iniciales: mbwa, ndege, njia."],
    ["dh / gh", "Serapan Arab: dhambi /ð/, ghali /ɣ/.", "From Arabic: dhambi /ð/, ghali /ɣ/.", "Del árabe: dhambi /ð/, ghali /ɣ/."],
    ["vokal", "Hanya lima dan selalu jernih: a e i o u — tidak pernah luruh seperti bahasa Inggris.", "Only five, always pure: a e i o u — never reduced as in English.", "Solo cinco y siempre puras: a e i o u."],
    ["m- suku kata", "m bisa menjadi suku kata sendiri: mtu dibaca 'm-tu'.", "m can be a syllable on its own: mtu is 'm-tu'.", "La m puede ser sílaba: mtu suena 'm-tu'."],
    ["tekanan", "Selalu di suku kata kedua dari belakang: kiSWAhili, asAnte.", "Always on the second-to-last syllable: kiSWAhili, asAnte.", "Siempre en la penúltima sílaba: kiSWAhili, asAnte."],
  ],
  grammar: [
    {
      t: ["Kelas kata benda", "Noun classes", "Clases nominales"],
      d: ["Ada belasan kelas; setiap kelas mengatur awalan kata sifat dan kata kerja yang mengikutinya.", "There are over a dozen; each class governs the prefixes on the adjectives and verbs that follow.", "Hay más de una docena; cada clase rige los prefijos de adjetivos y verbos."],
      ex: "mtu mmoja mzuri · watu wawili wazuri · kitu kimoja kizuri",
    },
    {
      t: ["Kata kerja sebagai kalimat", "A verb is a sentence", "El verbo es una frase"],
      d: ["Pelaku, waktu, dan objek semuanya menempel pada satu kata kerja.", "Subject, tense and object all attach to a single verb.", "Sujeto, tiempo y objeto se pegan al verbo."],
      ex: "ni-na-ku-penda = saya-sedang-kamu-suka",
    },
    {
      t: ["Penanda waktu", "Tense markers", "Marcas de tiempo"],
      d: ["-na- (sedang), -li- (lampau), -ta- (akan), -me- (sudah) disisipkan di tengah kata kerja.", "-na- (present), -li- (past), -ta- (future), -me- (perfect) sit inside the verb.", "-na- (presente), -li- (pasado), -ta- (futuro), -me- (perfecto)."],
      ex: "ninasoma · nilisoma · nitasoma · nimesoma",
    },
    {
      t: ["Infinitif ku-", "The ku- infinitive", "El infinitivo ku-"],
      d: ["Bentuk kamus kata kerja selalu berawalan ku-: kusoma (membaca).", "The dictionary form of a verb always begins with ku-: kusoma (to read).", "La forma de diccionario lleva ku-: kusoma (leer)."],
      ex: "kusoma · kuandika · kwenda",
    },
    {
      t: ["Kata sifat mengikuti benda", "Adjectives follow and agree", "El adjetivo sigue y concuerda"],
      d: ["Kata sifat berdiri sesudah kata benda dan mengambil awalan kelasnya.", "Adjectives come after the noun and take its class prefix.", "El adjetivo va detrás y toma el prefijo de clase."],
      ex: "nyumba kubwa · kitabu kikubwa",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "kubwa", pos: "adj", cefr: "A1", ipa: "ˈkuɓwa", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Wanaishi katika mji mkubwa.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["ndogo"] },
  { w: "kuwa", pos: "v", cefr: "A1", ipa: "ˈkuwa", g: ["menjadi, ada", "to be, to become", "ser, estar"], d: ["Menyatakan keadaan atau perubahan keadaan.", "Expresses a state or becoming.", "Expresa estado o transformación."], ex: ["Anataka kuwa daktari.", "Dia ingin menjadi dokter.", "She wants to be a doctor.", "Quiere ser médica."], note: ["'Punya' dinyatakan dengan kuwa na: nina = saya punya.", "'To have' is kuwa na: nina = I have.", "'Tener' se dice kuwa na: nina = tengo."] },
  { w: "kwenda", pos: "v", cefr: "A1", ipa: "ˈkwenda", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Ninakwenda sokoni.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."], ant: ["kuja"] },
  { w: "kuja", pos: "v", cefr: "A1", ipa: "ˈkuja", g: ["datang", "to come", "venir"], d: ["Bergerak mendekat ke tempat pembicara.", "To move towards the speaker.", "Moverse hacia el hablante."], ex: ["Rafiki yangu alikuja nyumbani.", "Teman saya datang ke rumah.", "My friend came to my house.", "Mi amigo vino a casa."], ant: ["kwenda"] },
  { w: "kutaka", pos: "v", cefr: "A1", ipa: "kuˈtaka", g: ["mau, ingin", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Nataka kujifunza Kiswahili.", "Saya mau belajar bahasa Swahili.", "I want to learn Swahili.", "Quiero aprender suajili."] },
  { w: "maji", pos: "n", cefr: "A1", ipa: "ˈmadʒi", g: ["air", "water", "agua"], d: ["Cairan bening yang diminum.", "The clear liquid we drink.", "Líquido transparente que se bebe."], ex: ["Naomba maji, tafadhali.", "Tolong airnya.", "Water, please.", "Agua, por favor."], note: ["Selalu jamak dalam Swahili — tidak ada bentuk tunggalnya.", "Always plural in Swahili — there is no singular.", "Siempre plural: no tiene singular."] },
  { w: "mtu", pos: "n", cefr: "A1", ipa: "ˈmtu", g: ["orang", "person", "persona"], d: ["Satu manusia.", "A single human being.", "Un ser humano."], ex: ["Yeye ni mtu mzuri.", "Dia orang yang baik.", "He is a good person.", "Es una buena persona."], note: ["Jamaknya watu — pergantian m-/wa- adalah kelas kata benda pertama.", "Plural watu — the m-/wa- switch is the first noun class.", "Plural watu: la alternancia m-/wa- es la primera clase."] },
  { w: "mwanamke", pos: "n", cefr: "A1", ipa: "mwaˈnamke", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["Mwanamke yule ni shangazi yangu.", "Perempuan itu bibi saya.", "That woman is my aunt.", "Esa mujer es mi tía."], ant: ["mwanamume"] },
  { w: "mwanamume", pos: "n", cefr: "A1", ipa: "mwaˈnamume", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["Mwanamume yule ni jirani yangu.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["mwanamke"] },
  { w: "ndogo", pos: "adj", cefr: "A1", ipa: "ˈndoɡo", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Nina nyumba ndogo.", "Saya punya rumah kecil.", "I have a small house.", "Tengo una casa pequeña."], ant: ["kubwa"] },
  { w: "nyumba", pos: "n", cefr: "A1", ipa: "ˈɲumba", g: ["rumah", "house", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Nyumba yangu iko karibu na bustani.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "rafiki", pos: "n", cefr: "A1", ipa: "raˈfiki", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Ninatoka na rafiki yangu.", "Saya keluar dengan teman saya.", "I'm going out with my friend.", "Salgo con mi amigo."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "daima", pos: "adv", cefr: "A2", ipa: "daˈima", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Daima ninakula kifungua kinywa nyumbani.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], syn: ["sikuzote"] },
  { w: "haraka", pos: "adj", cefr: "A2", ipa: "haˈraka", g: ["cepat", "fast, quick", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Treni ni ya haraka zaidi.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["polepole"] },
  { w: "kazi", pos: "n", cefr: "A2", ipa: "ˈkazi", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Kazi yangu inaanza saa tatu.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."], note: ["Jam Swahili berbeda enam jam dari jam Barat: saa tatu = pukul sembilan pagi.", "Swahili clock time runs six hours off: saa tatu = nine o'clock.", "La hora suajili va seis horas desfasada: saa tatu = las nueve."] },
  { w: "kuanza", pos: "v", cefr: "A2", ipa: "kuˈanza", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Filamu inaanza saa mbili usiku.", "Filmnya mulai pukul delapan malam.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["kumaliza"] },
  { w: "kuhitaji", pos: "v", cefr: "A2", ipa: "kuhiˈtadʒi", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Ninahitaji kupumzika.", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "kusaidia", pos: "v", cefr: "A2", ipa: "kusaiˈdia", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Unaweza kunisaidia, tafadhali?", "Bisakah kamu menolong saya?", "Can you help me, please?", "¿Puedes ayudarme, por favor?"] },
  { w: "kwa sababu", pos: "conj", cefr: "A2", ipa: "kwa saˈɓaɓu", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Niko nyumbani kwa sababu mvua inanyesha.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },
  { w: "mji", pos: "n", cefr: "A2", ipa: "ˈmdʒi", g: ["kota", "town, city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Arusha ni mji mzuri.", "Arusha kota yang bagus.", "Arusha is a lovely town.", "Arusha es una ciudad bonita."] },
  { w: "ngumu", pos: "adj", cefr: "A2", ipa: "ˈŋɡumu", g: ["sulit; keras", "difficult; hard", "difícil; duro"], d: ["Menuntut usaha; juga keras teksturnya.", "Requiring effort; also hard to the touch.", "Que exige esfuerzo; también duro."], ex: ["Ni vigumu kuegesha hapa.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["rahisi"] },
  { w: "nzuri", pos: "adj", cefr: "A2", ipa: "ˈnzuri", g: ["baik, bagus, cantik", "good, nice, beautiful", "bueno, bonito"], d: ["Bermutu baik atau menyenangkan dilihat.", "Of good quality or pleasant to see.", "De buena calidad o agradable."], ex: ["Hilo ni wazo zuri.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["mbaya"] },
  { w: "pesa", pos: "n", cefr: "A2", ipa: "ˈpesa", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Sina pesa za kutosha.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "rahisi", pos: "adj", cefr: "A2", ipa: "raˈhisi", g: ["mudah; murah", "easy; cheap", "fácil; barato"], d: ["Tidak menuntut usaha; juga tidak mahal.", "Not requiring effort; also inexpensive.", "Que no exige esfuerzo; también barato."], ex: ["Mtihani ulikuwa rahisi.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["ngumu"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "fursa", pos: "n", cefr: "B1", ipa: "ˈfursa", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["Hii ni fursa nzuri.", "Ini kesempatan yang bagus.", "This is a good opportunity.", "Es una buena oportunidad."] },
  { w: "ingawa", pos: "conj", cefr: "B1", ipa: "iˈŋɡawa", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Ingawa mvua inanyesha, tutatoka.", "Meskipun hujan, kami akan keluar.", "Although it's raining, we'll go out.", "Aunque llueve, saldremos."] },
  { w: "kuboresha", pos: "v", cefr: "B1", ipa: "kuɓoˈreʃa", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Nataka kuboresha matamshi yangu.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "kufanikiwa", pos: "v", cefr: "B1", ipa: "kufaniˈkiwa", g: ["berhasil", "to succeed", "tener éxito"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["Mradi ulifanikiwa.", "Proyek itu berhasil.", "The project succeeded.", "El proyecto tuvo éxito."] },
  { w: "kukumbuka", pos: "v", cefr: "B1", ipa: "kukumˈbuka", g: ["mengingat; merindukan", "to remember; to miss", "recordar; añorar"], d: ["Menyimpan dalam ingatan; juga merindukan orang.", "To keep in mind; also to miss someone.", "Recordar; también añorar a alguien."], ex: ["Ninawakumbuka familia yangu.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },
  { w: "kuonekana", pos: "v", cefr: "B1", ipa: "kuoneˈkana", g: ["tampak, terlihat", "to seem, to appear", "parecer"], d: ["Memberi kesan tertentu; juga bisa dilihat.", "To give an impression; also to be visible.", "Dar una impresión; también ser visible."], ex: ["Anaonekana amechoka.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "kuzoea", pos: "v", cefr: "B1", ipa: "kuzoˈea", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Nimezoea hali ya hewa hapa.", "Saya sudah terbiasa dengan cuaca di sini.", "I've got used to the weather here.", "Ya me acostumbré al clima."] },
  { w: "labda", pos: "adv", cefr: "B1", ipa: "ˈlabda", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Labda atakuja kesho.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "lakini", pos: "conj", cefr: "B1", ipa: "laˈkini", g: ["tetapi", "but", "pero"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Ni ghali, lakini inafaa.", "Mahal, tetapi sepadan.", "It's expensive, but it's worth it.", "Es caro, pero vale la pena."] },
  { w: "uamuzi", pos: "n", cefr: "B1", ipa: "uaˈmuzi", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Ulikuwa uamuzi mgumu.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."] },
  { w: "ushauri", pos: "n", cefr: "B1", ipa: "uʃaˈuri", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Naomba ushauri wako.", "Saya minta nasihatmu.", "I'd like your advice.", "Quisiera tu consejo."] },
  { w: "uzoefu", pos: "n", cefr: "B1", ipa: "uzoˈefu", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Ana uzoefu mkubwa.", "Dia sangat berpengalaman.", "She has great experience.", "Tiene mucha experiencia."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "changamoto", pos: "n", cefr: "B2", ipa: "tʃaŋɡaˈmoto", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Hii ni changamoto kubwa.", "Ini tantangan besar.", "This is a big challenge.", "Es un gran desafío."] },
  { w: "kuaminika", pos: "v", cefr: "B2", ipa: "kuamiˈnika", g: ["dapat dipercaya", "to be reliable, trustworthy", "ser fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Ni chanzo kinachoaminika.", "Ini sumber yang bisa dipercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "kufikia", pos: "v", cefr: "B2", ipa: "kufiˈkia", g: ["mencapai", "to reach, to attain", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Tumefikia lengo letu.", "Kami sudah mencapai target kami.", "We have reached our goal.", "Alcanzamos nuestro objetivo."] },
  { w: "kusisitiza", pos: "v", cefr: "B2", ipa: "kusisiˈtiza", g: ["menekankan", "to emphasise, to insist", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Alisisitiza usalama.", "Dia menekankan keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "kutekeleza", pos: "v", cefr: "B2", ipa: "kutekeˈleza", g: ["melaksanakan", "to implement, to carry out", "ejecutar"], d: ["Mengubah rencana menjadi tindakan nyata.", "To turn a plan into action.", "Convertir un plan en acción."], ex: ["Tutatekeleza mpango huo mwezi ujao.", "Kami akan melaksanakan rencana itu bulan depan.", "We'll carry out that plan next month.", "Ejecutaremos ese plan el mes próximo."] },
  { w: "kwa hiyo", pos: "conj", cefr: "B2", ipa: "kwa ˈhijo", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Mvua ilinyesha; kwa hiyo tuliahirisha.", "Hujan turun; oleh karena itu kami tunda.", "It rained; therefore we postponed.", "Llovió; por lo tanto lo aplazamos."] },
  { w: "licha ya", pos: "prep", cefr: "B2", ipa: "ˈlitʃa ja", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Licha ya baridi, tulitoka nje.", "Meski dingin, kami keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "maendeleo", pos: "n", cefr: "B2", ipa: "maendeˈleo", g: ["kemajuan, pembangunan", "development, progress", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Maendeleo ya mradi yanaenda vizuri.", "Perkembangan proyeknya berjalan baik.", "The project's progress is going well.", "El desarrollo del proyecto va bien."] },
  { w: "makubaliano", pos: "n", cefr: "B2", ipa: "makuɓaliˈano", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Tulifikia makubaliano ya haki.", "Kami mencapai kesepakatan yang adil.", "We reached a fair agreement.", "Llegamos a un acuerdo justo."] },
  { w: "mazingira", pos: "n", cefr: "B2", ipa: "maziŋˈɡira", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["Lazima tutunze mazingira.", "Kita harus menjaga lingkungan.", "We must protect the environment.", "Debemos cuidar el medio ambiente."] },
  { w: "muhimu", pos: "adj", cefr: "B2", ipa: "muˈhimu", g: ["penting", "important, essential", "importante"], d: ["Punya bobot besar bagi hasil akhir.", "Carrying great weight for the outcome.", "Que pesa mucho en el resultado."], ex: ["Pasipoti ni muhimu sana.", "Paspor sangat penting.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "suala", pos: "n", cefr: "B2", ipa: "suˈala", g: ["persoalan, isu", "issue, matter", "asunto"], d: ["Hal yang sedang dibicarakan atau ditangani.", "The matter under discussion.", "Tema del que se trata."], ex: ["Hili ni suala nyeti.", "Ini persoalan yang sensitif.", "This is a sensitive issue.", "Es un asunto delicado."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "hata hivyo", pos: "conj", cefr: "C1", ipa: "ˈhata ˈhivjo", g: ["walaupun demikian", "nonetheless, however", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Hata hivyo, pendekezo bado linafaa.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "ili", pos: "conj", cefr: "C1", ipa: "ˈili", g: ["agar, supaya", "so that, in order to", "para que"], d: ["Menyatakan tujuan dari suatu tindakan.", "States the purpose of an action.", "Expresa la finalidad de una acción."], ex: ["Tulirahisisha mchakato ili kuokoa muda.", "Kami sederhanakan prosesnya agar hemat waktu.", "We simplified the process in order to save time.", "Simplificamos el proceso para ahorrar tiempo."] },
  { w: "kuakisi", pos: "v", cefr: "C1", ipa: "kuaˈkisi", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Takwimu zinaakisi maboresho.", "Datanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "kuangazia", pos: "v", cefr: "C1", ipa: "kuaŋɡaˈzia", g: ["menyoroti", "to shed light on, to highlight", "poner de relieve"], d: ["Membuat sesuatu terlihat dan diperhatikan.", "To make something visible and noticed.", "Hacer visible algo."], ex: ["Ripoti inaangazia hatari kuu.", "Laporan itu menyoroti risiko utama.", "The report highlights the main risks.", "El informe destaca los riesgos."] },
  { w: "kuimarisha", pos: "v", cefr: "C1", ipa: "kuimaˈriʃa", g: ["memperkukuh", "to strengthen, to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Kampuni iliimarisha nafasi yake.", "Perusahaan memperkukuh posisinya.", "The company strengthened its position.", "La empresa consolidó su posición."] },
  { w: "kukuza", pos: "v", cefr: "C1", ipa: "kuˈkuza", g: ["menumbuhkan, mendorong", "to grow, to promote", "fomentar"], d: ["Membantu sesuatu tumbuh atau berkembang.", "To help something grow.", "Ayudar a que algo crezca."], ex: ["Sheria inakuza urejelezaji.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "kushughulikia", pos: "v", cefr: "C1", ipa: "kuʃuɣuliˈkia", g: ["menangani", "to handle, to deal with", "ocuparse de"], d: ["Mengurus persoalan sampai selesai.", "To deal with a matter until it is settled.", "Ocuparse de un asunto hasta resolverlo."], ex: ["Tunapaswa kushughulikia suala hili.", "Kita harus menangani persoalan ini.", "We must deal with this issue.", "Debemos ocuparnos de este asunto."] },
  { w: "makini", pos: "adj", cefr: "C1", ipa: "maˈkini", g: ["cermat, saksama", "careful, meticulous", "cuidadoso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["Uchambuzi makini unahitajika.", "Analisis yang saksama diperlukan.", "A careful analysis is needed.", "Hace falta un análisis cuidadoso."] },
  { w: "mtazamo", pos: "n", cefr: "C1", ipa: "mtaˈzamo", g: ["sudut pandang, pendekatan", "viewpoint, approach", "punto de vista"], d: ["Cara seseorang memandang persoalan.", "The angle from which someone sees an issue.", "Ángulo desde el que se ve un asunto."], ex: ["Tunahitaji mtazamo mpya.", "Kita butuh sudut pandang baru.", "We need a new approach.", "Necesitamos un nuevo enfoque."] },
  { w: "nyanja", pos: "n", cefr: "C1", ipa: "ˈɲandʒa", g: ["bidang, ranah", "field, sphere", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["Katika nyanja ya sheria hali ni tofauti.", "Dalam ranah hukum keadaannya berbeda.", "In the legal sphere things differ.", "En el ámbito jurídico es distinto."] },
  { w: "tofauti fiche", pos: "n", cefr: "C1", ipa: "toˈfauti ˈfitʃe", g: ["nuansa, beda halus", "nuance, subtle difference", "matiz"], d: ["Perbedaan halus yang mudah terlewat.", "A fine difference that is easily missed.", "Diferencia fina que se pasa por alto."], ex: ["Kuna tofauti fiche muhimu hapa.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "wigo", pos: "n", cefr: "C1", ipa: "ˈwiɡo", g: ["cakupan, lingkup", "scope, range", "alcance"], d: ["Seberapa luas sesuatu berlaku.", "How far something extends.", "Hasta dónde llega algo."], ex: ["Wigo wa mradi ni mpana.", "Cakupan proyeknya luas.", "The project's scope is broad.", "El alcance del proyecto es amplio."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "mlango", pos: "n", cefr: "A1", g: ["pintu", "door", "puerta"] },
  { w: "dirisha", pos: "n", cefr: "A1", g: ["jendela", "window", "ventana"] },
  { w: "chumba", pos: "n", cefr: "A1", g: ["kamar, ruangan", "room", "habitación"] },
  { w: "meza", pos: "n", cefr: "A1", g: ["meja", "table", "mesa"] },
  { w: "kiti", pos: "n", cefr: "A1", g: ["kursi", "chair", "silla"] },
  { w: "kitanda", pos: "n", cefr: "A1", g: ["tempat tidur", "bed", "cama"] },
  { w: "jiko", pos: "n", cefr: "A1", g: ["dapur; tungku", "kitchen; stove", "cocina"] },
  { w: "choo", pos: "n", cefr: "A1", g: ["toilet, kamar kecil", "toilet", "aseo"] },
  { w: "taa", pos: "n", cefr: "A1", g: ["lampu", "lamp, light", "lámpara"] },
  { w: "ufunguo", pos: "n", cefr: "A1", g: ["kunci", "key", "llave"] },
  { w: "ukuta", pos: "n", cefr: "A1", g: ["dinding, tembok", "wall", "pared"] },
  { w: "paa", pos: "n", cefr: "A1", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "mkate", pos: "n", cefr: "A1", g: ["roti", "bread", "pan"] },
  { w: "wali", pos: "n", cefr: "A1", g: ["nasi", "cooked rice", "arroz cocido"] },
  { w: "nyama", pos: "n", cefr: "A1", g: ["daging", "meat", "carne"] },
  { w: "samaki", pos: "n", cefr: "A1", g: ["ikan", "fish", "pescado"] },
  { w: "yai", pos: "n", cefr: "A1", g: ["telur", "egg", "huevo"] },
  { w: "maziwa", pos: "n", cefr: "A1", g: ["susu", "milk", "leche"] },
  { w: "chai", pos: "n", cefr: "A1", g: ["teh", "tea", "té"] },
  { w: "kahawa", pos: "n", cefr: "A1", g: ["kopi", "coffee", "café"] },
  { w: "sukari", pos: "n", cefr: "A1", g: ["gula", "sugar", "azúcar"] },
  { w: "chumvi", pos: "n", cefr: "A1", g: ["garam", "salt", "sal"] },
  { w: "tunda", pos: "n", cefr: "A1", g: ["buah", "fruit", "fruta"] },
  { w: "mboga", pos: "n", cefr: "A1", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "shati", pos: "n", cefr: "A2", g: ["kemeja", "shirt", "camisa"] },
  { w: "suruali", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalón"] },
  { w: "kiatu", pos: "n", cefr: "A2", g: ["sepatu", "shoe", "zapato"] },
  { w: "kofia", pos: "n", cefr: "A2", g: ["topi, peci", "hat, cap", "sombrero"] },
  { w: "mkono", pos: "n", cefr: "A2", g: ["tangan, lengan", "hand, arm", "mano, brazo"] },
  { w: "jicho", pos: "n", cefr: "A2", g: ["mata", "eye", "ojo"], note: ["Jamaknya macho — pergantian ji-/ma- adalah kelas kata benda ke-5.", "Plural macho — the ji-/ma- switch is noun class 5.", "Plural macho: la alternancia ji-/ma- es la clase 5."] },
  { w: "kichwa", pos: "n", cefr: "A2", g: ["kepala", "head", "cabeza"] },
  { w: "moyo", pos: "n", cefr: "A2", g: ["jantung, hati", "heart", "corazón"] },
  { w: "nywele", pos: "n", cefr: "A2", g: ["rambut", "hair", "cabello"] },
  { w: "jino", pos: "n", cefr: "A2", g: ["gigi", "tooth", "diente"] },
  { w: "sikio", pos: "n", cefr: "A2", g: ["telinga", "ear", "oreja"] },
  { w: "uso", pos: "n", cefr: "A2", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "mti", pos: "n", cefr: "A2", g: ["pohon", "tree", "árbol"] },
  { w: "ua", pos: "n", cefr: "A2", g: ["bunga; pagar", "flower; fence", "flor; cerca"] },
  { w: "mlima", pos: "n", cefr: "A2", g: ["gunung", "mountain", "montaña"] },
  { w: "mto", pos: "n", cefr: "A2", g: ["sungai; bantal", "river; pillow", "río; almohada"] },
  { w: "bahari", pos: "n", cefr: "A2", g: ["laut", "sea", "mar"] },
  { w: "anga", pos: "n", cefr: "A2", g: ["langit, angkasa", "sky", "cielo"] },
  { w: "nyota", pos: "n", cefr: "A2", g: ["bintang", "star", "estrella"] },
  { w: "mbwa", pos: "n", cefr: "A2", g: ["anjing", "dog", "perro"] },
  { w: "paka", pos: "n", cefr: "A2", g: ["kucing", "cat", "gato"] },
  { w: "ndege", pos: "n", cefr: "A2", g: ["burung; pesawat", "bird; aeroplane", "pájaro; avión"], note: ["Satu kata untuk burung dan pesawat terbang.", "One word covers both bird and aeroplane.", "Una palabra para pájaro y avión."] },
  { w: "farasi", pos: "n", cefr: "A2", g: ["kuda", "horse", "caballo"] },
  { w: "mvua", pos: "n", cefr: "A2", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "barabara", pos: "n", cefr: "B1", g: ["jalan raya", "road, street", "carretera"] },
  { w: "daraja", pos: "n", cefr: "B1", g: ["jembatan; jenjang", "bridge; grade", "puente"] },
  { w: "soko", pos: "n", cefr: "B1", g: ["pasar", "market", "mercado"] },
  { w: "shule", pos: "n", cefr: "B1", g: ["sekolah", "school", "escuela"] },
  { w: "hospitali", pos: "n", cefr: "B1", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "ofisi", pos: "n", cefr: "B1", g: ["kantor", "office", "oficina"] },
  { w: "basi", pos: "n", cefr: "B1", g: ["bus", "bus", "autobús"] },
  { w: "treni", pos: "n", cefr: "B1", g: ["kereta api", "train", "tren"] },
  { w: "gari", pos: "n", cefr: "B1", g: ["mobil, kendaraan", "car, vehicle", "coche"] },
  { w: "baiskeli", pos: "n", cefr: "B1", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "uwanja wa ndege", pos: "n", cefr: "B1", g: ["bandara", "airport", "aeropuerto"] },
  { w: "tiketi", pos: "n", cefr: "B1", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "kampuni", pos: "n", cefr: "B2", g: ["perusahaan", "company", "empresa"] },
  { w: "mkutano", pos: "n", cefr: "B2", g: ["rapat, pertemuan", "meeting", "reunión"] },
  { w: "mkataba", pos: "n", cefr: "B2", g: ["kontrak, perjanjian", "contract", "contrato"] },
  { w: "mshahara", pos: "n", cefr: "B2", g: ["gaji", "salary", "sueldo"] },
  { w: "bei", pos: "n", cefr: "B2", g: ["harga", "price", "precio"] },
  { w: "kodi", pos: "n", cefr: "B2", g: ["pajak; sewa", "tax; rent", "impuesto; alquiler"] },
  { w: "benki", pos: "n", cefr: "B2", g: ["bank", "bank", "banco"] },
  { w: "kompyuta", pos: "n", cefr: "B2", g: ["komputer", "computer", "ordenador"] },
  { w: "simu", pos: "n", cefr: "B2", g: ["telepon", "telephone", "teléfono"] },
  { w: "barua pepe", pos: "n", cefr: "B2", g: ["surel, email", "email", "correo electrónico"], note: ["Bentukan asli: barua (surat) + pepe (elektronik).", "A native coinage: barua (letter) + pepe (electronic).", "Creación propia: barua (carta) + pepe (electrónico)."] },
  { w: "faili", pos: "n", cefr: "B2", g: ["berkas", "file", "archivo"] },
  { w: "nenosiri", pos: "n", cefr: "B2", g: ["kata sandi", "password", "contraseña"], note: ["Bentukan asli: neno (kata) + siri (rahasia).", "A native coinage: neno (word) + siri (secret).", "Creación propia: neno (palabra) + siri (secreto)."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "dharura", pos: "n", cefr: "C2", ipa: "ðaˈrura", g: ["keadaan darurat, kegentingan", "emergency, urgency", "emergencia"], d: ["Keadaan yang menuntut tindakan segera.", "A situation demanding immediate action.", "Situación que exige acción inmediata."], ex: ["Hili ni suala la dharura.", "Ini persoalan yang mendesak.", "This is an urgent matter.", "Es un asunto urgente."] },
  { w: "dhana", pos: "n", cefr: "C2", ipa: "ˈðana", g: ["konsep, paradigma", "concept, paradigm", "concepto"], d: ["Kerangka berpikir yang menjadi acuan.", "A framework of thinking that guides others.", "Marco de pensamiento de referencia."], ex: ["Ilikuwa mabadiliko ya dhana.", "Itu perubahan paradigma.", "It was a shift of paradigm.", "Fue un cambio de paradigma."] },
  { w: "hatua muhimu", pos: "n", cefr: "C2", ipa: "haˈtua muˈhimu", g: ["tonggak penting", "milestone", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Makubaliano hayo ni hatua muhimu.", "Kesepakatan itu tonggak penting.", "That agreement is a milestone.", "Ese acuerdo es un hito."] },
  { w: "isiyoepukika", pos: "adj", cefr: "C2", ipa: "isijoepuˈkika", g: ["tak terhindarkan", "unavoidable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Ongezeko la bei haliepukiki.", "Kenaikan harga tak terhindarkan.", "The price rise is unavoidable.", "La subida es inevitable."] },
  { w: "kudharau", pos: "v", cefr: "C2", ipa: "kuðaˈrau", g: ["meremehkan", "to belittle, to look down on", "menospreciar"], d: ["Menganggap sesuatu lebih rendah nilainya.", "To treat something as worth less than it is.", "Tratar algo como de menor valor."], ex: ["Usidharau juhudi zake.", "Jangan remehkan usahanya.", "Don't belittle her effort.", "No menosprecies su esfuerzo."] },
  { w: "kufafanua", pos: "v", cefr: "C2", ipa: "kufafaˈnua", g: ["menjelaskan, menjernihkan", "to clarify, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Ni lazima kufafanua maelezo haya.", "Rincian ini perlu dijernihkan.", "These details must be clarified.", "Hay que esclarecer estos detalles."] },
  { w: "kukwepa", pos: "v", cefr: "C2", ipa: "kuˈkwepa", g: ["mengelak", "to dodge, to evade", "eludir"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto sin afrontarlo."], ex: ["Alikwepa swali hilo.", "Dia mengelak dari pertanyaan itu.", "He dodged that question.", "Eludió esa pregunta."] },
  { w: "kwa kuzingatia", pos: "phr", cefr: "C2", ipa: "kwa kuziŋɡaˈtia", g: ["dengan mempertimbangkan", "in the light of, considering", "teniendo en cuenta"], d: ["Menilai sesuatu dengan memperhatikan fakta tertentu.", "Judging something while taking given facts into account.", "Juzgar algo teniendo en cuenta ciertos datos."], ex: ["Kwa kuzingatia matokeo, ni mafanikio.", "Dengan mempertimbangkan hasilnya, ini keberhasilan.", "In the light of the results, it's a success.", "Teniendo en cuenta los resultados, es un éxito."] },
  { w: "mwanga wa matumaini", pos: "n", cefr: "C2", ipa: "ˈmwaŋɡa wa matuˈmaini", g: ["secercah harapan", "a ray of hope", "un rayo de esperanza"], d: ["Tanda kecil bahwa keadaan bisa membaik.", "A small sign that things may improve.", "Pequeña señal de que algo puede mejorar."], ex: ["Bado kuna mwanga wa matumaini.", "Masih ada secercah harapan.", "There's still a ray of hope.", "Aún queda un rayo de esperanza."] },
  { w: "ndoto za mchana", pos: "n", cefr: "C2", ipa: "ˈndoto za mˈtʃana", g: ["angan-angan siang bolong", "daydream, pipe dream", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Ahadi hiyo ni ndoto za mchana.", "Janji itu angan-angan belaka.", "That promise is a pipe dream.", "Esa promesa es una quimera."] },
  { w: "upendeleo", pos: "n", cefr: "C2", ipa: "upendeˈleo", g: ["keberpihakan, bias", "bias, favouritism", "sesgo"], d: ["Kecenderungan berpihak sehingga tidak adil.", "A leaning that makes judgement unfair.", "Inclinación que hace injusto el juicio."], ex: ["Utafiti huo una upendeleo.", "Riset itu mengandung keberpihakan.", "That study carries a bias.", "Ese estudio tiene un sesgo."] },
  { w: "yasiyoelezeka", pos: "adj", cefr: "C2", ipa: "jasijoeleˈzeka", g: ["tak terlukiskan", "indescribable", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Alihisi furaha isiyoelezeka.", "Dia merasakan sukacita tak terlukiskan.", "She felt an indescribable joy.", "Sintió una alegría indescriptible."] },
];
