/* =========================================================================
   lexicon/th.js — พจนานุกรม: ภาษาไทย (Thai). Front matter + 72 headwords.
   Romanisation follows RTGS; entries are filed under their initial consonant,
   the way a Thai dictionary does (leading vowel signs are skipped).
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Thai memakai aksaranya sendiri sejak abad ke-13. Tidak ada spasi antarkata, ada lima nada, dan kelas huruf menentukan nada — tiga hal yang harus dipelajari bersamaan.",
    "Thai has used its own script since the 13th century. There are no spaces between words, five tones, and consonant classes that decide those tones — three things learned together.",
    "El tailandés usa su propia escritura desde el siglo XIII. No separa palabras, tiene cinco tonos y clases consonánticas que los determinan.",
  ],
  script: [
    "44 huruf konsonan dan 32 tanda vokal. Empat vokal (เ แ โ ไ) ditulis di depan konsonan meski dibunyikan sesudahnya — karena itu kamus mengurutkannya menurut konsonan.",
    "44 consonants and 32 vowel signs. Four vowels (เ แ โ ไ) are written before their consonant though pronounced after it — so dictionaries file them under the consonant.",
    "44 consonantes y 32 signos vocálicos. Cuatro vocales (เ แ โ ไ) se escriben antes de la consonante aunque suenan después.",
  ],
  pron: [
    ["5 nada", "Datar, rendah, turun, tinggi, naik — mengubah arti sepenuhnya: mai (ไม้/ไหม/ไม่).", "Mid, low, falling, high, rising — they change meaning entirely: mai (ไม้/ไหม/ไม่).", "Medio, bajo, descendente, alto y ascendente; cambian el significado."],
    ["kelas konsonan", "Tiga kelas (tinggi, tengah, rendah) menentukan nada suku kata.", "Three classes (high, mid, low) determine a syllable's tone.", "Tres clases (alta, media, baja) determinan el tono."],
    ["ng ง", "Bisa berdiri di awal kata: งาน (ngan).", "It can begin a word: งาน (ngan).", "Puede iniciar palabra: งาน (ngan)."],
    ["konsonan akhir", "Hanya delapan bunyi penutup; semuanya tidak dilepaskan.", "Only eight final sounds exist, and none is released.", "Solo hay ocho finales, y ninguna se suelta."],
    ["r / l", "ร sering diucapkan seperti ล dalam percakapan santai.", "ร is often pronounced like ล in casual speech.", "ร suele sonar como ล en el habla informal."],
    ["tanpa spasi", "Spasi menandai akhir kalimat, bukan akhir kata.", "Spaces mark the end of a clause, not of a word.", "El espacio marca el fin de la oración, no de la palabra."],
  ],
  grammar: [
    {
      t: ["Kata tak berubah", "Words never inflect", "Las palabras no se flexionan"],
      d: ["Tidak ada konjugasi maupun jamak; waktu ditandai kata bantu: แล้ว (sudah), จะ (akan), กำลัง (sedang).", "No conjugation, no plurals; time comes from particles: แล้ว (already), จะ (will), กำลัง (in progress).", "Sin conjugación ni plural; el tiempo lo marcan partículas."],
      ex: "กินแล้ว · จะกิน · กำลังกิน",
    },
    {
      t: ["Kata penggolong", "Classifiers", "Clasificadores"],
      d: ["Menghitung benda memerlukan penggolong: คน (orang), ตัว (hewan/benda), เล่ม (buku).", "Counting needs a classifier: คน (people), ตัว (animals/objects), เล่ม (books).", "Contar requiere clasificador: คน, ตัว, เล่ม."],
      ex: "หนังสือสองเล่ม (dua buku)",
    },
    {
      t: ["Kata sifat mengikuti benda", "Adjectives follow the noun", "El adjetivo sigue al sustantivo"],
      d: ["Penjelas selalu datang sesudah kata bendanya, tanpa kata kerja 'adalah'.", "Modifiers come after the noun, and no verb 'to be' is needed.", "El modificador va detrás y no hace falta el verbo 'ser'."],
      ex: "บ้านใหญ่ (rumah besar)",
    },
    {
      t: ["Kata akhir yang menyopankan", "Politeness particles", "Partículas de cortesía"],
      d: ["ครับ (laki-laki) dan ค่ะ (perempuan) ditambahkan di akhir kalimat.", "ครับ (male speaker) and ค่ะ (female speaker) close a polite sentence.", "ครับ (hombre) y ค่ะ (mujer) cierran una frase cortés."],
      ex: "ขอบคุณครับ · ขอบคุณค่ะ",
    },
    {
      t: ["Pertanyaan dengan ไหม", "Questions with ไหม", "Preguntas con ไหม"],
      d: ["Kalimat tanya ya/tidak dibentuk dengan menambah ไหม di akhir.", "A yes-no question just adds ไหม at the end.", "La pregunta cerrada añade ไหม al final."],
      ex: "อร่อยไหม (Enak?)",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "กิน", r: "kin", pos: "v", cefr: "A1", g: ["makan", "to eat", "comer"], d: ["Memasukkan makanan ke mulut.", "To take food into the mouth.", "Tomar alimento."], ex: ["ฉันกินข้าวแล้ว", "Saya sudah makan.", "I have already eaten.", "Ya he comido."] },
  { w: "คน", r: "khon", pos: "n", cefr: "A1", g: ["orang", "person", "persona"], d: ["Satu manusia; juga penggolong untuk orang.", "A human being; also the classifier for people.", "Un ser humano; también su clasificador."], ex: ["เขาเป็นคนดี", "Dia orang baik.", "He is a good person.", "Es una buena persona."] },
  { w: "คืน", r: "khuen", pos: "n", cefr: "A1", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["ราตรีสวัสดิ์", "Selamat malam.", "Good night.", "Buenas noches."], ant: ["วัน"] },
  { w: "ดี", r: "di", pos: "adj", cefr: "A1", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["เป็นความคิดที่ดี", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["ไม่ดี"] },
  { w: "บ้าน", r: "ban", pos: "n", cefr: "A1", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["บ้านของฉันอยู่ใกล้สวน", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "ผู้ชาย", r: "phu chai", pos: "n", cefr: "A1", g: ["laki-laki", "man", "hombre"], d: ["Manusia berjenis kelamin laki-laki.", "A male human being.", "Ser humano de sexo masculino."], ex: ["ผู้ชายคนนั้นเป็นเพื่อนบ้าน", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["ผู้หญิง"] },
  { w: "ผู้หญิง", r: "phu ying", pos: "n", cefr: "A1", g: ["perempuan", "woman", "mujer"], d: ["Manusia berjenis kelamin perempuan.", "A female human being.", "Ser humano de sexo femenino."], ex: ["ผู้หญิงคนนั้นเป็นน้าของฉัน", "Perempuan itu bibi saya.", "That woman is my aunt.", "Esa mujer es mi tía."], ant: ["ผู้ชาย"] },
  { w: "เพื่อน", r: "phuean", pos: "n", cefr: "A1", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["ฉันไปเที่ยวกับเพื่อน", "Saya pergi jalan-jalan dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."] },
  { w: "ไป", r: "pai", pos: "v", cefr: "A1", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["ฉันไปตลาด", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."], ant: ["มา"] },
  { w: "วัน", r: "wan", pos: "n", cefr: "A1", g: ["hari", "day", "día"], d: ["Waktu 24 jam.", "A period of 24 hours.", "Periodo de 24 horas."], ex: ["ฉันทำงานทุกวัน", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["คืน"] },
  { w: "ใหญ่", r: "yai", pos: "adj", cefr: "A1", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["พวกเขาอยู่ในเมืองใหญ่", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["เล็ก"] },
  { w: "เล็ก", r: "lek", pos: "adj", cefr: "A1", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["ฉันมีห้องเล็ก ๆ", "Saya punya kamar kecil.", "I have a small room.", "Tengo una habitación pequeña."], ant: ["ใหญ่"] },

  /* ------------------------------------------------------------------ A2 */
  { w: "ช่วย", r: "chuai", pos: "v", cefr: "A2", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["ช่วยฉันหน่อยได้ไหม", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "ต้องการ", r: "tongkan", pos: "v", cefr: "A2", g: ["membutuhkan", "to need, to want", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["ฉันต้องการพักผ่อน", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "เมือง", r: "mueang", pos: "n", cefr: "A2", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["เชียงใหม่เป็นเมืองที่สวย", "Chiang Mai kota yang indah.", "Chiang Mai is a beautiful city.", "Chiang Mai es una ciudad bonita."] },
  { w: "เร็ว", r: "reo", pos: "adj", cefr: "A2", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["รถไฟเร็วกว่า", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["ช้า"] },
  { w: "เริ่ม", r: "roem", pos: "v", cefr: "A2", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["หนังเริ่มสองทุ่ม", "Filmnya mulai pukul delapan malam.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "งาน", r: "ngan", pos: "n", cefr: "A2", g: ["pekerjaan; acara", "work; an event", "trabajo; evento"], d: ["Kegiatan mencari nafkah; juga pesta atau acara.", "The work you earn a living by; also a party or event.", "El trabajo; también una fiesta o evento."], ex: ["งานของฉันเริ่มเก้าโมง", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "เงิน", r: "ngoen", pos: "n", cefr: "A2", g: ["uang; perak", "money; silver", "dinero; plata"], d: ["Alat tukar untuk membeli; juga logam perak.", "What you buy things with; also the metal silver.", "Medio para comprar; también la plata."], ex: ["ฉันมีเงินไม่พอ", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "เวลา", r: "wela", pos: "n", cefr: "A2", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["วันนี้ฉันไม่มีเวลา", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "ง่าย", r: "ngai", pos: "adj", cefr: "A2", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["ข้อสอบง่ายมาก", "Ujiannya sangat mudah.", "The exam was very easy.", "El examen fue muy fácil."], ant: ["ยาก"] },
  { w: "ยาก", r: "yak", pos: "adj", cefr: "A2", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["จอดรถที่นี่ยาก", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["ง่าย"] },
  { w: "เสมอ", r: "samoe", pos: "adv", cefr: "A2", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["ฉันกินข้าวเช้าที่บ้านเสมอ", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },
  { w: "เพราะ", r: "phro", pos: "conj", cefr: "A2", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["ฉันอยู่บ้านเพราะฝนตก", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "ประสบการณ์", r: "prasopkan", pos: "n", cefr: "B1", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["เธอมีประสบการณ์มาก", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "ตัดสินใจ", r: "tatsinchai", pos: "v", cefr: "B1", g: ["memutuskan", "to decide", "decidir"], d: ["Menetapkan pilihan setelah berpikir.", "To settle on a choice after thinking.", "Tomar una decisión tras pensar."], ex: ["ฉันยังตัดสินใจไม่ได้", "Saya belum bisa memutuskan.", "I can't decide yet.", "Todavía no puedo decidir."] },
  { w: "โอกาส", r: "okat", pos: "n", cefr: "B1", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["นี่เป็นโอกาสที่ดี", "Ini kesempatan yang baik.", "This is a good opportunity.", "Es una buena oportunidad."] },
  { w: "คำแนะนำ", r: "kham naenam", pos: "n", cefr: "B1", g: ["saran, nasihat", "advice, recommendation", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["ขอคำแนะนำหน่อยได้ไหม", "Boleh minta saran?", "May I ask for some advice?", "¿Me das un consejo?"] },
  { w: "ปรับปรุง", r: "prapprung", pos: "v", cefr: "B1", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["ฉันอยากปรับปรุงการออกเสียง", "Saya ingin memperbaiki pelafalan.", "I want to improve my pronunciation.", "Quiero mejorar la pronunciación."] },
  { w: "สำเร็จ", r: "samret", pos: "v", cefr: "B1", g: ["berhasil, selesai", "to succeed, to be completed", "lograrse"], d: ["Tercapai atau selesai dengan baik.", "To be achieved or completed.", "Lograrse o completarse."], ex: ["โครงการสำเร็จแล้ว", "Proyeknya sudah berhasil.", "The project has succeeded.", "El proyecto ha tenido éxito."] },
  { w: "ดูเหมือน", r: "du muean", pos: "v", cefr: "B1", g: ["tampaknya", "to seem, to look like", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["เขาดูเหมือนเหนื่อย", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "ถึงแม้ว่า", r: "thueng mae wa", pos: "conj", cefr: "B1", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["ถึงแม้ว่าฝนตก เราก็จะไป", "Meskipun hujan, kami tetap pergi.", "Although it's raining, we'll still go.", "Aunque llueve, iremos igual."] },
  { w: "แต่", r: "tae", pos: "conj", cefr: "B1", g: ["tetapi", "but", "pero"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["แพงแต่คุ้มค่า", "Mahal tetapi sepadan.", "Expensive but worth it.", "Caro pero vale la pena."] },
  { w: "บางที", r: "bang thi", pos: "adv", cefr: "B1", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["บางทีพรุ่งนี้เขาจะมา", "Mungkin besok dia datang.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "คุ้นเคย", r: "khunkhoei", pos: "v", cefr: "B1", g: ["terbiasa, akrab", "to be familiar with", "estar familiarizado"], d: ["Sudah terbiasa sehingga tidak asing lagi.", "So familiar that it no longer feels new.", "Tan familiar que ya no extraña."], ex: ["ฉันคุ้นเคยกับอากาศที่นี่แล้ว", "Saya sudah terbiasa dengan cuaca di sini.", "I'm used to the weather here now.", "Ya me acostumbré al clima de aquí."] },
  { w: "คิดถึง", r: "khitthueng", pos: "v", cefr: "B1", g: ["merindukan", "to miss (someone)", "echar de menos"], d: ["Memikirkan seseorang karena rindu.", "To think of someone you miss.", "Pensar en alguien a quien se añora."], ex: ["ฉันคิดถึงครอบครัว", "Saya rindu keluarga.", "I miss my family.", "Echo de menos a mi familia."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "พัฒนา", r: "phatthana", pos: "v", cefr: "B2", g: ["mengembangkan", "to develop", "desarrollar"], d: ["Menjadikan sesuatu lebih maju.", "To make something more advanced.", "Hacer avanzar algo."], ex: ["เราต้องพัฒนาระบบนี้", "Kita harus mengembangkan sistem ini.", "We must develop this system.", "Debemos desarrollar este sistema."] },
  { w: "สิ่งแวดล้อม", r: "sing waetlom", pos: "n", cefr: "B2", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["เราต้องรักษาสิ่งแวดล้อม", "Kita harus menjaga lingkungan.", "We must protect the environment.", "Debemos cuidar el medio ambiente."] },
  { w: "ความท้าทาย", r: "khwam thathai", pos: "n", cefr: "B2", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["นี่เป็นความท้าทายใหญ่", "Ini tantangan besar.", "This is a big challenge.", "Es un gran desafío."] },
  { w: "ข้อตกลง", r: "kho toklong", pos: "n", cefr: "B2", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["ทั้งสองฝ่ายลงนามข้อตกลง", "Kedua pihak menandatangani kesepakatan.", "Both sides signed the agreement.", "Ambas partes firmaron el acuerdo."] },
  { w: "บรรลุ", r: "banlu", pos: "v", cefr: "B2", g: ["mencapai", "to attain, to achieve", "alcanzar"], d: ["Sampai pada tujuan setelah berusaha.", "To reach a goal after effort.", "Alcanzar una meta tras esfuerzo."], ex: ["เราบรรลุเป้าหมายแล้ว", "Kami sudah mencapai targetnya.", "We have reached the target.", "Alcanzamos el objetivo."] },
  { w: "เน้น", r: "nen", pos: "v", cefr: "B2", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["เขาเน้นเรื่องความปลอดภัย", "Dia menekankan soal keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "น่าเชื่อถือ", r: "na chuea thue", pos: "adj", cefr: "B2", g: ["dapat dipercaya", "reliable, credible", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["นี่เป็นแหล่งข้อมูลที่น่าเชื่อถือ", "Ini sumber yang bisa dipercaya.", "This is a reliable source.", "Es una fuente fiable."] },
  { w: "จำเป็น", r: "champen", pos: "adj", cefr: "B2", g: ["perlu, wajib", "necessary", "necesario"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["หนังสือเดินทางจำเป็นมาก", "Paspor sangat diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "แม้จะ", r: "mae cha", pos: "conj", cefr: "B2", g: ["meskipun", "even though", "aun cuando"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["แม้จะหนาว เราก็ออกไปข้างนอก", "Meski dingin, kami tetap keluar.", "Even though it was cold, we went out.", "Aun con frío, salimos."] },
  { w: "ดังนั้น", r: "dangnan", pos: "conj", cefr: "B2", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat logis.", "Marks a logical consequence.", "Marca la consecuencia lógica."], ex: ["ฝนตก ดังนั้นเราจึงยกเลิก", "Hujan, oleh karena itu kami batalkan.", "It rained, therefore we cancelled.", "Llovió, por lo tanto cancelamos."] },
  { w: "ประเด็น", r: "praden", pos: "n", cefr: "B2", g: ["poin, persoalan", "point, issue", "cuestión"], d: ["Hal utama yang sedang dibahas.", "The main matter under discussion.", "El punto que se discute."], ex: ["นี่เป็นประเด็นที่อ่อนไหว", "Ini persoalan yang sensitif.", "It's a sensitive issue.", "Es una cuestión delicada."] },
  { w: "ดำเนินการ", r: "damnoenkan", pos: "v", cefr: "B2", g: ["melaksanakan", "to carry out, to proceed", "llevar a cabo"], d: ["Menjalankan rencana menjadi tindakan.", "To put a plan into action.", "Convertir un plan en acción."], ex: ["เราจะดำเนินการตามแผน", "Kami akan melaksanakan rencananya.", "We'll carry out the plan.", "Llevaremos a cabo el plan."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "สาขา", r: "sakha", pos: "n", cefr: "C1", g: ["bidang; cabang", "field; branch", "ámbito; sucursal"], d: ["Cabang ilmu atau usaha; juga kantor cabang.", "A branch of knowledge or business; also a branch office.", "Rama del saber o del negocio; también sucursal."], ex: ["ในสาขากฎหมายจะต่างออกไป", "Dalam bidang hukum hal itu berbeda.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "แนวทาง", r: "naeothang", pos: "n", cefr: "C1", g: ["pendekatan, arah", "approach, guideline", "enfoque"], d: ["Cara atau garis besar untuk menangani sesuatu.", "The way or outline for handling something.", "Manera o pauta para abordar algo."], ex: ["เราต้องการแนวทางใหม่", "Kita butuh pendekatan baru.", "We need a new approach.", "Necesitamos un nuevo enfoque."] },
  { w: "ความละเอียดอ่อน", r: "khwam la-iat on", pos: "n", cefr: "C1", g: ["kepekaan, nuansa", "subtlety, sensitivity", "sutileza"], d: ["Hal halus yang mudah terlewat.", "A fine point that is easily missed.", "Detalle fino que se pasa por alto."], ex: ["เรื่องนี้มีความละเอียดอ่อน", "Hal ini punya nuansa yang halus.", "This matter has a subtlety to it.", "Este asunto tiene su sutileza."] },
  { w: "จัดการ", r: "chatkan", pos: "v", cefr: "C1", g: ["mengurus, menangani", "to manage, to handle", "gestionar"], d: ["Mengatur dan menyelesaikan sesuatu.", "To organise and deal with something.", "Organizar y resolver algo."], ex: ["เขาจัดการปัญหาได้ดี", "Dia menangani masalah dengan baik.", "He handled the problem well.", "Gestionó bien el problema."] },
  { w: "ส่งเสริม", r: "songsoem", pos: "v", cefr: "C1", g: ["mendorong, memajukan", "to promote, to foster", "fomentar"], d: ["Membantu sesuatu tumbuh atau berkembang.", "To help something grow.", "Ayudar a que algo crezca."], ex: ["กฎหมายส่งเสริมการรีไซเคิล", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "สะท้อน", r: "sathon", pos: "v", cefr: "C1", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["ตัวเลขสะท้อนการพัฒนา", "Angkanya mencerminkan kemajuan.", "The figures reflect the progress.", "Las cifras reflejan la mejora."] },
  { w: "ละเอียด", r: "la-iat", pos: "adj", cefr: "C1", g: ["teliti, rinci", "detailed, meticulous", "minucioso"], d: ["Memperhatikan setiap bagian kecil.", "Attending to every small part.", "Que atiende a cada detalle."], ex: ["ต้องมีการวิเคราะห์อย่างละเอียด", "Diperlukan analisis yang teliti.", "A thorough analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "อย่างไรก็ตาม", r: "yangrai ko tam", pos: "conj", cefr: "C1", g: ["walaupun demikian", "nonetheless, however", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["อย่างไรก็ตาม ข้อเสนอยังมีผล", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "เพื่อ", r: "phuea", pos: "conj", cefr: "C1", g: ["agar, demi", "in order to, for", "para"], d: ["Menyatakan tujuan dari suatu tindakan.", "States the purpose of an action.", "Expresa la finalidad de una acción."], ex: ["เราลดขั้นตอนเพื่อประหยัดเวลา", "Kami memangkas prosedur demi menghemat waktu.", "We cut steps in order to save time.", "Recortamos pasos para ahorrar tiempo."] },
  { w: "เสริมสร้าง", r: "soemsang", pos: "v", cefr: "C1", g: ["memperkukuh, membangun", "to strengthen, to build up", "consolidar"], d: ["Membuat sesuatu makin kuat dan mantap.", "To make something stronger and firmer.", "Hacer algo más fuerte y firme."], ex: ["บริษัทเสริมสร้างความน่าเชื่อถือ", "Perusahaan memperkukuh kredibilitasnya.", "The company built up its credibility.", "La empresa consolidó su credibilidad."] },
  { w: "ขอบเขต", r: "khopkhet", pos: "n", cefr: "C1", g: ["cakupan, batas", "scope, boundary", "alcance, ámbito"], d: ["Seberapa jauh sesuatu berlaku.", "How far something extends.", "Hasta dónde llega algo."], ex: ["ขอบเขตของโครงการกว้างมาก", "Cakupan proyeknya sangat luas.", "The project's scope is very wide.", "El alcance del proyecto es amplio."] },
  { w: "ชี้ให้เห็น", r: "chi hai hen", pos: "v", cefr: "C1", g: ["menunjukkan, menegaskan", "to point out", "señalar"], d: ["Menarik perhatian pada suatu fakta.", "To draw attention to a fact.", "Llamar la atención sobre un hecho."], ex: ["รายงานชี้ให้เห็นความเสี่ยง", "Laporan itu menunjukkan risikonya.", "The report points out the risks.", "El informe señala los riesgos."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "กระบวนทัศน์", r: "krabuanthat", pos: "n", cefr: "C2", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["นี่คือการเปลี่ยนกระบวนทัศน์", "Ini pergeseran paradigma.", "This is a paradigm shift.", "Es un cambio de paradigma."] },
  { w: "หลีกเลี่ยง", r: "liklieng", pos: "v", cefr: "C2", g: ["menghindari, mengelak", "to avoid, to evade", "eludir"], d: ["Menjauhi persoalan alih-alih menghadapinya.", "To keep away from an issue instead of facing it.", "Evitar un asunto en vez de afrontarlo."], ex: ["เขาหลีกเลี่ยงคำถาม", "Dia mengelak dari pertanyaan itu.", "He evaded the question.", "Eludió la pregunta."] },
  { w: "กระจ่าง", r: "krachang", pos: "adj", cefr: "C2", g: ["terang, jernih", "clear, elucidated", "claro"], d: ["Sudah jelas sehingga tak menyisakan keraguan.", "So clear that no doubt remains.", "Tan claro que no deja dudas."], ex: ["เรื่องนี้ยังไม่กระจ่าง", "Perkara ini belum jernih.", "This matter is not yet clear.", "Este asunto aún no está claro."] },
  { w: "สุดจะบรรยาย", r: "sut cha banyai", pos: "phr", cefr: "C2", g: ["tak terlukiskan", "beyond description", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["เธอดีใจสุดจะบรรยาย", "Dia gembira tak terlukiskan.", "Her joy was beyond description.", "Su alegría era indescriptible."] },
  { w: "เร่งด่วน", r: "reng duan", pos: "adj", cefr: "C2", g: ["mendesak", "urgent, pressing", "urgente"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["นี่เป็นเรื่องเร่งด่วน", "Ini perkara mendesak.", "This is an urgent matter.", "Es un asunto urgente."] },
  { w: "ประกาย", r: "prakai", pos: "n", cefr: "C2", g: ["kilau, percikan", "spark, glimmer", "destello"], d: ["Cahaya kecil; kiasan untuk tanda harapan.", "A small light; figuratively a sign of hope.", "Luz pequeña; indicio de esperanza."], ex: ["ยังมีประกายแห่งความหวัง", "Masih ada secercah harapan.", "There's still a glimmer of hope.", "Aún hay un destello de esperanza."] },
  { w: "อคติ", r: "akhati", pos: "n", cefr: "C2", g: ["prasangka, bias", "bias, prejudice", "sesgo"], d: ["Kecenderungan menilai secara tidak berimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["งานวิจัยนี้มีอคติ", "Riset ini mengandung bias.", "This research carries a bias.", "Esta investigación tiene un sesgo."] },
  { w: "ลดทอน", r: "lotthon", pos: "v", cefr: "C2", g: ["mengurangi, merongrong", "to diminish, to undercut", "menoscabar"], d: ["Membuat nilai sesuatu berkurang.", "To reduce the value of something.", "Reducir el valor de algo."], ex: ["สิ่งนี้ลดทอนความน่าเชื่อถือ", "Hal itu merongrong kredibilitasnya.", "That undercuts his credibility.", "Eso menoscaba su credibilidad."] },
  { w: "หมุดหมาย", r: "mutmai", pos: "n", cefr: "C2", g: ["tonggak, penanda", "milestone, marker", "hito"], d: ["Titik penting yang menandai kemajuan.", "A point that marks progress.", "Punto que marca un avance."], ex: ["ข้อตกลงนี้เป็นหมุดหมายสำคัญ", "Kesepakatan ini tonggak penting.", "This agreement is an important milestone.", "Este acuerdo es un hito importante."] },
  { w: "ไม่อาจเลี่ยงได้", r: "mai at liang dai", pos: "phr", cefr: "C2", g: ["tak terhindarkan", "unavoidable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["การขึ้นราคาไม่อาจเลี่ยงได้", "Kenaikan harga tak terhindarkan.", "The price rise is unavoidable.", "La subida es inevitable."] },
  { w: "ความเพ้อฝัน", r: "khwam phoefan", pos: "n", cefr: "C2", g: ["angan kosong", "pipe dream, fantasy", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["คำสัญญานั้นเป็นความเพ้อฝัน", "Janji itu angan kosong.", "That promise is a pipe dream.", "Esa promesa es una quimera."] },
  { w: "ในแง่ของ", r: "nai ngae khong", pos: "phr", cefr: "C2", g: ["dari segi", "in terms of", "en términos de"], d: ["Membatasi penilaian pada satu sudut pandang.", "Limits a judgement to one standpoint.", "Limita el juicio a un punto de vista."], ex: ["ในแง่ของต้นทุน นี่ดีที่สุด", "Dari segi biaya, ini yang terbaik.", "In terms of cost, this is the best.", "En términos de coste, es lo mejor."] },
];
