/* =========================================================================
   lexicon/tl.js — Diksiyonaryo: Tagalog/Filipino. Front matter + 72 headwords.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Tagalog (dasar bahasa Filipino) menyimpan jejak sejarah kepulauan: akar Austronesia, ribuan kata serapan Spanyol, dan campuran bahasa Inggris yang hidup dalam percakapan sehari-hari.",
    "Tagalog (the basis of Filipino) carries the archipelago's history: an Austronesian core, thousands of Spanish loanwords, and everyday code-switching with English.",
    "El tagalo (base del filipino) refleja la historia del archipiélago: raíz austronesia, miles de préstamos españoles y mezcla cotidiana con el inglés.",
  ],
  script: [
    "Abjad Latin 28 huruf (termasuk ñ dan ng). Aksara kuno Baybayin kini dipakai untuk keperluan budaya. Tekanan kata bisa membedakan arti dan sering tidak ditulis.",
    "A 28-letter Latin alphabet (including ñ and ng). The old Baybayin script survives in cultural use. Stress can change meaning and is usually not written.",
    "Alfabeto latino de 28 letras (incluidas ñ y ng). La antigua escritura baybayin pervive en usos culturales.",
  ],
  pron: [
    ["ng", "Satu huruf tersendiri, dibaca /ŋ/ — bisa berada di awal kata: ngayon.", "A single letter pronounced /ŋ/ — it can begin a word: ngayon.", "Una sola letra, /ŋ/, que puede iniciar palabra: ngayon."],
    ["hentakan glotal", "Banyak kata berakhir dengan hentakan: bata' (anak) ≠ bata (jubah).", "Many words end in a glottal stop: bata' (child) ≠ bata (robe).", "Muchas palabras acaban en oclusión glotal: bata' ≠ bata."],
    ["e / i dan o / u", "Sering bertukar karena aslinya satu bunyi: lalake ~ lalaki.", "These often swap because they were once one sound each: lalake ~ lalaki.", "Suelen intercambiarse: lalake ~ lalaki."],
    ["r / d", "d berubah jadi r di antara vokal: dagat → karagatan.", "d turns into r between vowels: dagat → karagatan.", "La d pasa a r entre vocales: dagat → karagatan."],
    ["tekanan", "Membedakan arti: búkas (besok) vs bukás (terbuka).", "Stress distinguishes words: búkas (tomorrow) vs bukás (open).", "El acento distingue: búkas (mañana) y bukás (abierto)."],
    ["serapan Spanyol", "Dibaca mengikuti bunyi Tagalog: silya, kutsara, kabayo.", "Spanish loans follow Tagalog sounds: silya, kutsara, kabayo.", "Los préstamos españoles siguen los sonidos tagalos: silya, kutsara."],
  ],
  grammar: [
    {
      t: ["Kata kerja di depan", "The verb comes first", "El verbo va primero"],
      d: ["Urutan dasarnya Kata kerja–Pelaku–Objek, kebalikan dari bahasa Indonesia.", "The basic order is Verb–Actor–Object, the reverse of English.", "El orden básico es verbo–actor–objeto."],
      ex: "Kumain ako ng kanin. (Makan · saya · nasi)",
    },
    {
      t: ["Penanda ang, ng, sa", "The markers ang, ng, sa", "Los marcadores ang, ng, sa"],
      d: ["ang menandai fokus kalimat, ng menandai pelaku/objek lain, sa menandai tempat & arah.", "ang marks the focus, ng marks the other participant, sa marks place and direction.", "ang marca el foco, ng el otro participante, sa el lugar."],
      ex: "Binili ng bata ang libro sa tindahan.",
    },
    {
      t: ["Fokus kata kerja", "Verb focus", "El enfoque verbal"],
      d: ["Imbuhan menentukan siapa yang jadi sorotan: um-/mag- (pelaku), -in (objek), -an (tempat).", "Affixes decide who is in focus: um-/mag- (actor), -in (object), -an (location).", "Los afijos deciden el foco: um-/mag- (actor), -in (objeto), -an (lugar)."],
      ex: "bumili (membeli) · binili (dibeli) · binilhan (tempat membeli)",
    },
    {
      t: ["Waktu lewat pengulangan", "Tense by reduplication", "Tiempo por reduplicación"],
      d: ["Suku kata pertama diulang untuk masa kini/berlangsung: kumakain (sedang makan).", "The first syllable repeats for the ongoing form: kumakain (is eating).", "La primera sílaba se repite para el presente: kumakain."],
      ex: "kakain · kumakain · kumain",
    },
    {
      t: ["Kata kecil po", "The particle po", "La partícula po"],
      d: ["po/opo menyisipkan rasa hormat pada kalimat mana pun — tanda kesopanan Filipina.", "po/opo slips respect into any sentence — the Filipino politeness marker.", "po/opo añade respeto a cualquier frase."],
      ex: "Salamat po. · Opo, tama po kayo.",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "araw", pos: "n", cefr: "A1", ipa: "ˈaɾaw", g: ["hari; matahari", "day; sun", "día; sol"], d: ["Waktu 24 jam; juga matahari itu sendiri.", "A period of 24 hours; also the sun itself.", "Periodo de 24 horas; también el sol."], ex: ["Nagtatrabaho ako araw-araw.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["gabi"] },
  { w: "babae", pos: "n", cefr: "A1", ipa: "baˈbaʔe", g: ["perempuan", "woman", "mujer"], d: ["Manusia berjenis kelamin perempuan.", "A female human being.", "Ser humano de sexo femenino."], ex: ["Ang babaeng may sombrero ay tita ko.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["lalaki"] },
  { w: "bahay", pos: "n", cefr: "A1", ipa: "ˈbahaj", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Malapit ang bahay ko sa parke.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "gabi", pos: "n", cefr: "A1", ipa: "ɡaˈbi", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Magandang gabi!", "Selamat malam!", "Good evening!", "¡Buenas noches!"], ant: ["araw"] },
  { w: "gusto", pos: "v", cefr: "A1", ipa: "ˈɡusto", g: ["suka, mau", "to like, to want", "gustar, querer"], d: ["Menyukai atau menginginkan sesuatu.", "To like or want something.", "Gustar o querer algo."], ex: ["Gusto kong matuto ng Tagalog.", "Saya mau belajar bahasa Tagalog.", "I want to learn Tagalog.", "Quiero aprender tagalo."] },
  { w: "kaibigan", pos: "n", cefr: "A1", ipa: "kaʔiˈbiɡan", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Lalabas ako kasama ang kaibigan ko.", "Saya keluar bersama teman saya.", "I'm going out with my friend.", "Salgo con mi amigo."] },
  { w: "lalaki", pos: "n", cefr: "A1", ipa: "laˈlaki", g: ["laki-laki", "man, male", "hombre"], d: ["Manusia berjenis kelamin laki-laki.", "A male human being.", "Ser humano de sexo masculino."], ex: ["Kapitbahay ko ang lalaking iyon.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["babae"] },
  { w: "mabuti", pos: "adj", cefr: "A1", ipa: "maˈbuti", g: ["baik", "good, fine", "bueno"], d: ["Bermutu baik atau berperilaku baik.", "Of good quality or well-behaved.", "De buena calidad o de buen obrar."], ex: ["Magandang ideya iyan.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["masama"] },
  { w: "malaki", pos: "adj", cefr: "A1", ipa: "maˈlaki", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Nakatira sila sa malaking lungsod.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["maliit"] },
  { w: "maliit", pos: "adj", cefr: "A1", ipa: "maliˈʔit", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["May maliit akong apartment.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["malaki"] },
  { w: "mayroon", pos: "v", cefr: "A1", ipa: "majˈɾoʔon", g: ["ada, punya", "there is; to have", "haber; tener"], d: ["Menyatakan keberadaan atau kepemilikan.", "States that something exists or is owned.", "Indica existencia o posesión."], ex: ["Mayroon akong dalawang kapatid.", "Saya punya dua saudara.", "I have two siblings.", "Tengo dos hermanos."], note: ["Bentuk pendeknya 'may': May tanong ako.", "The short form is 'may': May tanong ako (I have a question).", "La forma corta es 'may': May tanong ako."] },
  { w: "pumunta", pos: "v", cefr: "A1", ipa: "puˈmunta", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Pupunta ako sa palengke.", "Saya akan pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "dahil", pos: "conj", cefr: "A2", ipa: "ˈdahil", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Nasa bahay ako dahil umuulan.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },
  { w: "kailangan", pos: "v", cefr: "A2", ipa: "kajˈlaŋan", g: ["butuh, harus", "to need, must", "necesitar, deber"], d: ["Memerlukan sesuatu; juga menyatakan keharusan.", "To require something; also expresses obligation.", "Requerir algo; también obligación."], ex: ["Kailangan kong magpahinga.", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "lungsod", pos: "n", cefr: "A2", ipa: "ˈluŋsod", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Maganda ang lungsod ng Cebu.", "Kota Cebu itu indah.", "The city of Cebu is beautiful.", "La ciudad de Cebú es bonita."] },
  { w: "mabilis", pos: "adj", cefr: "A2", ipa: "maˈbilis", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Mas mabilis ang tren.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["mabagal"] },
  { w: "madali", pos: "adj", cefr: "A2", ipa: "maˈdaliʔ", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["Madali ang pagsusulit.", "Ujiannya mudah.", "The test was easy.", "El examen fue fácil."], ant: ["mahirap"] },
  { w: "magsimula", pos: "v", cefr: "A2", ipa: "maɡsiˈmula", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Magsisimula ang pelikula sa alas-otso.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "mahirap", pos: "adj", cefr: "A2", ipa: "maˈhiɾap", g: ["sulit; miskin", "difficult; poor", "difícil; pobre"], d: ["Menuntut usaha; juga berarti miskin.", "Requiring effort; it also means poor.", "Que exige esfuerzo; también pobre."], ex: ["Mahirap pumarada rito.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["madali"] },
  { w: "oras", pos: "n", cefr: "A2", ipa: "ˈʔoɾas", g: ["waktu; jam", "time; hour", "tiempo; hora"], d: ["Waktu yang berjalan; juga satuan jam.", "Passing time; also the unit 'hour'.", "El tiempo; también la hora."], ex: ["Wala akong oras ngayon.", "Saya tidak punya waktu sekarang.", "I have no time now.", "No tengo tiempo ahora."] },
  { w: "palagi", pos: "adv", cefr: "A2", ipa: "paˈlaɡiʔ", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Palagi akong nag-aalmusal sa bahay.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },
  { w: "pera", pos: "n", cefr: "A2", ipa: "ˈpeɾa", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Kulang ang pera ko.", "Uang saya kurang.", "I don't have enough money.", "No me alcanza el dinero."] },
  { w: "trabaho", pos: "n", cefr: "A2", ipa: "tɾaˈbaho", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Nagsisimula ang trabaho ko ng alas-nuwebe.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "tumulong", pos: "v", cefr: "A2", ipa: "tuˈmuloŋ", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Pwede mo ba akong tulungan?", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "desisyon", pos: "n", cefr: "B1", ipa: "desiˈʃon", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Mahirap na desisyon iyon.", "Itu keputusan yang sulit.", "That was a hard decision.", "Fue una decisión difícil."], syn: ["pasya"] },
  { w: "kahit na", pos: "conj", cefr: "B1", ipa: "ˈkahit na", g: ["meskipun", "although, even if", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Kahit na umuulan, lalabas kami.", "Meskipun hujan, kami akan keluar.", "Even though it's raining, we'll go out.", "Aunque llueve, saldremos."] },
  { w: "karanasan", pos: "n", cefr: "B1", ipa: "kaɾaˈnasan", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Malawak ang karanasan niya.", "Pengalamannya luas.", "She has broad experience.", "Tiene amplia experiencia."] },
  { w: "magtagumpay", pos: "v", cefr: "B1", ipa: "maɡtaɡumˈpaj", g: ["berhasil", "to succeed", "triunfar"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["Nagtagumpay siyang tapusin ang pag-aaral.", "Dia berhasil menyelesaikan studinya.", "She succeeded in finishing her studies.", "Logró terminar sus estudios."] },
  { w: "mangulila", pos: "v", cefr: "B1", ipa: "maŋuˈlila", g: ["merindukan", "to long for, to miss", "añorar"], d: ["Merasa sedih karena seseorang tidak ada.", "To feel the absence of someone.", "Sentir la ausencia de alguien."], ex: ["Nangungulila ako sa pamilya ko.", "Saya rindu keluarga saya.", "I miss my family.", "Añoro a mi familia."], note: ["Dalam percakapan sehari-hari orang lebih sering berkata 'na-miss kita'.", "In everyday speech people usually say 'na-miss kita' instead.", "En el habla diaria se dice 'na-miss kita'."] },
  { w: "masanay", pos: "v", cefr: "B1", ipa: "maˈsanaj", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Nasanay na ako sa init.", "Saya sudah terbiasa dengan panasnya.", "I've got used to the heat.", "Ya me acostumbré al calor."] },
  { w: "mukhang", pos: "v", cefr: "B1", ipa: "muxˈaŋ", g: ["tampaknya", "it seems, looks like", "parece que"], d: ["Menyatakan kesan tanpa kepastian.", "States an impression without certainty.", "Expresa una impresión sin certeza."], ex: ["Mukhang pagod siya.", "Dia tampak lelah.", "He looks tired.", "Parece cansado."] },
  { w: "ngunit", pos: "conj", cefr: "B1", ipa: "ˈŋunit", g: ["tetapi, namun", "but, however", "pero"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Mahal; ngunit sulit naman.", "Mahal; namun sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."], syn: ["pero"] },
  { w: "pagkakataon", pos: "n", cefr: "B1", ipa: "paɡkakaˈtaʔon", g: ["kesempatan", "opportunity, chance", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["Magandang pagkakataon ito.", "Ini kesempatan bagus.", "This is a good opportunity.", "Es una buena oportunidad."] },
  { w: "pagbutihin", pos: "v", cefr: "B1", ipa: "paɡbuˈtihin", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Gusto kong pagbutihin ang pagbigkas ko.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "payo", pos: "n", cefr: "B1", ipa: "ˈpajo", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Pwede ba akong humingi ng payo?", "Boleh saya minta nasihat?", "May I ask for some advice?", "¿Puedo pedirte un consejo?"] },
  { w: "siguro", pos: "adv", cefr: "B1", ipa: "siˈɡuɾo", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Siguro darating siya bukas.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."], note: ["Berbeda dari 'seguro' Spanyol yang berarti pasti; dalam Tagalog justru 'mungkin'.", "Unlike Spanish 'seguro' (certain), Tagalog siguro means 'maybe'.", "A diferencia del español 'seguro', en tagalo significa 'quizá'."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "bigyang-diin", pos: "v", cefr: "B2", ipa: "biɡˈjaŋ diˈʔin", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Binigyang-diin niya ang kaligtasan.", "Dia menekankan keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "hamon", pos: "n", cefr: "B2", ipa: "ˈhamon", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Malaking hamon ito.", "Ini tantangan besar.", "This is a big challenge.", "Es un gran desafío."] },
  { w: "ipatupad", pos: "v", cefr: "B2", ipa: "ʔipaˈtupad", g: ["melaksanakan, memberlakukan", "to implement, to enforce", "implementar"], d: ["Mengubah rencana atau aturan menjadi kenyataan.", "To put a plan or rule into force.", "Poner en vigor un plan o norma."], ex: ["Ipatutupad namin ang bagong patakaran.", "Kami akan memberlakukan kebijakan baru.", "We'll implement the new policy.", "Implementaremos la nueva política."] },
  { w: "isyu", pos: "n", cefr: "B2", ipa: "ˈʔiʃu", g: ["isu, persoalan", "issue", "asunto"], d: ["Hal yang sedang dibicarakan atau diperdebatkan.", "The matter under discussion.", "Tema del que se trata."], ex: ["Sensitibong isyu ito.", "Ini isu yang sensitif.", "It's a sensitive issue.", "Es un asunto delicado."] },
  { w: "kapaligiran", pos: "n", cefr: "B2", ipa: "kapaliˈɡiɾan", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["Dapat nating alagaan ang kapaligiran.", "Kita harus menjaga lingkungan.", "We must care for the environment.", "Debemos cuidar el medio ambiente."] },
  { w: "kasunduan", pos: "n", cefr: "B2", ipa: "kasunˈduʔan", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Nakarating kami sa isang kasunduan.", "Kami mencapai kesepakatan.", "We reached an agreement.", "Llegamos a un acuerdo."] },
  { w: "kaunlaran", pos: "n", cefr: "B2", ipa: "kaʔunˈlaɾan", g: ["kemajuan, pembangunan", "development, progress", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Mabilis ang kaunlaran ng proyekto.", "Kemajuan proyeknya cepat.", "The project's progress is fast.", "El avance del proyecto es rápido."] },
  { w: "maaasahan", pos: "adj", cefr: "B2", ipa: "maʔaʔaˈsahan", g: ["dapat diandalkan", "reliable, dependable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Maaasahang pinagkunan ito.", "Ini sumber yang bisa diandalkan.", "This is a reliable source.", "Es una fuente fiable."] },
  { w: "makamit", pos: "v", cefr: "B2", ipa: "maˈkamit", g: ["mencapai, meraih", "to attain, to achieve", "alcanzar"], d: ["Sampai pada tujuan setelah berusaha.", "To reach a goal after effort.", "Alcanzar una meta tras esfuerzo."], ex: ["Nakamit namin ang layunin.", "Kami meraih tujuannya.", "We attained the goal.", "Alcanzamos el objetivo."] },
  { w: "mahalaga", pos: "adj", cefr: "B2", ipa: "mahaˈlaɡa", g: ["penting; berharga", "important; valuable", "importante; valioso"], d: ["Punya bobot besar atau bernilai tinggi.", "Carrying great weight or value.", "De gran peso o valor."], ex: ["Mahalaga ang pasaporte.", "Paspor itu penting.", "The passport is important.", "El pasaporte es importante."] },
  { w: "sa kabila ng", pos: "prep", cefr: "B2", ipa: "sa kaˈbila naŋ", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Sa kabila ng lamig, lumabas kami.", "Meski dingin, kami keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "samakatuwid", pos: "conj", cefr: "B2", ipa: "samakatuˈwid", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai kesimpulan logis.", "Marks a logical conclusion.", "Marca una conclusión lógica."], ex: ["Umulan; samakatuwid, kinansela namin.", "Hujan; oleh karena itu kami batalkan.", "It rained; therefore we cancelled.", "Llovió; por lo tanto cancelamos."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "gayunpaman", pos: "conj", cefr: "C1", ipa: "ɡajunpaˈman", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Gayunpaman, nananatiling bisa ang panukala.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "itaguyod", pos: "v", cefr: "C1", ipa: "ʔitaˈɡujod", g: ["mendorong, memperjuangkan", "to promote, to champion", "impulsar"], d: ["Mendukung sesuatu agar tumbuh dan berhasil.", "To support something so it grows and succeeds.", "Apoyar algo para que prospere."], ex: ["Itinataguyod ng batas ang pag-recycle.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley impulsa el reciclaje."] },
  { w: "itampok", pos: "v", cefr: "C1", ipa: "ʔitamˈpok", g: ["menonjolkan", "to highlight, to feature", "destacar"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["Itinampok ng ulat ang mga panganib.", "Laporan itu menonjolkan bahayanya.", "The report highlighted the risks.", "El informe destacó los riesgos."] },
  { w: "larangan", pos: "n", cefr: "C1", ipa: "laˈɾaŋan", g: ["bidang", "field, domain", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["Sa larangan ng batas, iba ang tuntunin.", "Dalam bidang hukum, aturannya lain.", "In the legal field the rules differ.", "En el ámbito jurídico las reglas cambian."] },
  { w: "masusi", pos: "adj", cefr: "C1", ipa: "maˈsusi", g: ["teliti, saksama", "thorough, meticulous", "minucioso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["Kailangan ng masusing pagsusuri.", "Diperlukan analisis yang saksama.", "A thorough analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "nuwansa", pos: "n", cefr: "C1", ipa: "nuˈwansa", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["May mahalagang nuwansa rito.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "pamamaraan", pos: "n", cefr: "C1", ipa: "pamamaˈɾaʔan", g: ["metode, pendekatan", "method, approach", "método"], d: ["Cara tertentu untuk mengerjakan sesuatu.", "A particular way of doing something.", "Manera concreta de hacer algo."], ex: ["Kailangan natin ng ibang pamamaraan.", "Kita butuh pendekatan lain.", "We need a different approach.", "Necesitamos otro método."] },
  { w: "patatagin", pos: "v", cefr: "C1", ipa: "pataˈtaɡin", g: ["memperkukuh", "to strengthen, to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Pinatatag ng kompanya ang posisyon nito.", "Perusahaan itu memperkukuh posisinya.", "The company strengthened its position.", "La empresa consolidó su posición."] },
  { w: "saklaw", pos: "n", cefr: "C1", ipa: "sakˈlaw", g: ["cakupan, jangkauan", "scope, coverage", "alcance"], d: ["Seberapa luas sesuatu menjangkau.", "How widely something reaches.", "Hasta dónde llega algo."], ex: ["Malawak ang saklaw ng programa.", "Cakupan programnya luas.", "The programme's scope is wide.", "El alcance del programa es amplio."] },
  { w: "salamin", pos: "n", cefr: "C1", ipa: "saˈlamin", g: ["cermin; cerminan", "mirror; reflection", "espejo; reflejo"], d: ["Benda pemantul; kiasan untuk gambaran keadaan.", "A mirror; figuratively an image of a situation.", "Espejo; en sentido figurado, reflejo."], ex: ["Salamin ng lipunan ang panitikan.", "Sastra adalah cerminan masyarakat.", "Literature is a mirror of society.", "La literatura es espejo de la sociedad."] },
  { w: "tugunan", pos: "v", cefr: "C1", ipa: "tuˈɡunan", g: ["menanggapi, menangani", "to address, to respond to", "atender"], d: ["Menangani persoalan dengan tindakan.", "To deal with an issue by acting on it.", "Atender un asunto con acciones."], ex: ["Dapat tugunan ang isyung ito agad.", "Isu ini harus segera ditangani.", "This issue must be addressed at once.", "Hay que atender este asunto ya."] },
  { w: "upang", pos: "conj", cefr: "C1", ipa: "ˈʔupaŋ", g: ["agar, supaya", "in order to", "a fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["Pinasimple namin ang proseso upang makatipid ng oras.", "Prosesnya kami sederhanakan agar hemat waktu.", "We simplified the process in order to save time.", "Simplificamos el proceso a fin de ahorrar tiempo."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "pinto", pos: "n", cefr: "A1", g: ["pintu", "door", "puerta"] },
  { w: "bintana", pos: "n", cefr: "A1", g: ["jendela", "window", "ventana"] },
  { w: "kwarto", pos: "n", cefr: "A1", g: ["kamar", "room", "habitación"] },
  { w: "mesa", pos: "n", cefr: "A1", g: ["meja", "table", "mesa"] },
  { w: "silya", pos: "n", cefr: "A1", g: ["kursi", "chair", "silla"] },
  { w: "kama", pos: "n", cefr: "A1", g: ["tempat tidur", "bed", "cama"] },
  { w: "kusina", pos: "n", cefr: "A1", g: ["dapur", "kitchen", "cocina"] },
  { w: "banyo", pos: "n", cefr: "A1", g: ["kamar mandi", "bathroom", "baño"] },
  { w: "ilaw", pos: "n", cefr: "A1", g: ["lampu, cahaya", "light, lamp", "luz"] },
  { w: "susi", pos: "n", cefr: "A1", g: ["kunci", "key", "llave"] },
  { w: "pader", pos: "n", cefr: "A1", g: ["dinding", "wall", "pared"] },
  { w: "bubong", pos: "n", cefr: "A1", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "tinapay", pos: "n", cefr: "A1", g: ["roti", "bread", "pan"] },
  { w: "kanin", pos: "n", cefr: "A1", g: ["nasi", "cooked rice", "arroz cocido"] },
  { w: "karne", pos: "n", cefr: "A1", g: ["daging", "meat", "carne"] },
  { w: "isda", pos: "n", cefr: "A1", g: ["ikan", "fish", "pescado"] },
  { w: "itlog", pos: "n", cefr: "A1", g: ["telur", "egg", "huevo"] },
  { w: "gatas", pos: "n", cefr: "A1", g: ["susu", "milk", "leche"] },
  { w: "tsaa", pos: "n", cefr: "A1", g: ["teh", "tea", "té"] },
  { w: "kape", pos: "n", cefr: "A1", g: ["kopi", "coffee", "café"] },
  { w: "asukal", pos: "n", cefr: "A1", g: ["gula", "sugar", "azúcar"] },
  { w: "asin", pos: "n", cefr: "A1", g: ["garam", "salt", "sal"] },
  { w: "prutas", pos: "n", cefr: "A1", g: ["buah", "fruit", "fruta"] },
  { w: "gulay", pos: "n", cefr: "A1", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "kamiseta", pos: "n", cefr: "A2", g: ["kaus, kemeja", "shirt, T-shirt", "camiseta"] },
  { w: "pantalon", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalón"] },
  { w: "sapatos", pos: "n", cefr: "A2", g: ["sepatu", "shoe", "zapato"] },
  { w: "sumbrero", pos: "n", cefr: "A2", g: ["topi", "hat", "sombrero"] },
  { w: "kamay", pos: "n", cefr: "A2", g: ["tangan", "hand", "mano"] },
  { w: "mata", pos: "n", cefr: "A2", g: ["mata", "eye", "ojo"] },
  { w: "ulo", pos: "n", cefr: "A2", g: ["kepala", "head", "cabeza"] },
  { w: "puso", pos: "n", cefr: "A2", g: ["jantung, hati", "heart", "corazón"] },
  { w: "buhok", pos: "n", cefr: "A2", g: ["rambut", "hair", "cabello"] },
  { w: "ngipin", pos: "n", cefr: "A2", g: ["gigi", "tooth", "diente"] },
  { w: "tainga", pos: "n", cefr: "A2", g: ["telinga", "ear", "oreja"] },
  { w: "mukha", pos: "n", cefr: "A2", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "puno", pos: "n", cefr: "A2", g: ["pohon", "tree", "árbol"] },
  { w: "bulaklak", pos: "n", cefr: "A2", g: ["bunga", "flower", "flor"] },
  { w: "bundok", pos: "n", cefr: "A2", g: ["gunung", "mountain", "montaña"] },
  { w: "ilog", pos: "n", cefr: "A2", g: ["sungai", "river", "río"] },
  { w: "dagat", pos: "n", cefr: "A2", g: ["laut", "sea", "mar"] },
  { w: "langit", pos: "n", cefr: "A2", g: ["langit", "sky", "cielo"] },
  { w: "bituin", pos: "n", cefr: "A2", g: ["bintang", "star", "estrella"] },
  { w: "aso", pos: "n", cefr: "A2", g: ["anjing", "dog", "perro"] },
  { w: "pusa", pos: "n", cefr: "A2", g: ["kucing", "cat", "gato"] },
  { w: "ibon", pos: "n", cefr: "A2", g: ["burung", "bird", "pájaro"] },
  { w: "kabayo", pos: "n", cefr: "A2", g: ["kuda", "horse", "caballo"] },
  { w: "ulan", pos: "n", cefr: "A2", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "kalye", pos: "n", cefr: "B1", g: ["jalan", "street", "calle"] },
  { w: "tulay", pos: "n", cefr: "B1", g: ["jembatan", "bridge", "puente"] },
  { w: "palengke", pos: "n", cefr: "B1", g: ["pasar", "market", "mercado"] },
  { w: "paaralan", pos: "n", cefr: "B1", g: ["sekolah", "school", "escuela"] },
  { w: "ospital", pos: "n", cefr: "B1", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "opisina", pos: "n", cefr: "B1", g: ["kantor", "office", "oficina"] },
  { w: "bus", pos: "n", cefr: "B1", g: ["bus", "bus", "autobús"] },
  { w: "tren", pos: "n", cefr: "B1", g: ["kereta api", "train", "tren"] },
  { w: "kotse", pos: "n", cefr: "B1", g: ["mobil", "car", "coche"] },
  { w: "bisikleta", pos: "n", cefr: "B1", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "paliparan", pos: "n", cefr: "B1", g: ["bandara", "airport", "aeropuerto"] },
  { w: "tiket", pos: "n", cefr: "B1", g: ["tiket", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "kumpanya", pos: "n", cefr: "B2", g: ["perusahaan", "company", "empresa"] },
  { w: "pulong", pos: "n", cefr: "B2", g: ["rapat, pertemuan", "meeting", "reunión"] },
  { w: "kontrata", pos: "n", cefr: "B2", g: ["kontrak", "contract", "contrato"] },
  { w: "sweldo", pos: "n", cefr: "B2", g: ["gaji", "salary", "sueldo"] },
  { w: "presyo", pos: "n", cefr: "B2", g: ["harga", "price", "precio"] },
  { w: "buwis", pos: "n", cefr: "B2", g: ["pajak", "tax", "impuesto"] },
  { w: "bangko", pos: "n", cefr: "B2", g: ["bank", "bank", "banco"] },
  { w: "kompyuter", pos: "n", cefr: "B2", g: ["komputer", "computer", "ordenador"] },
  { w: "telepono", pos: "n", cefr: "B2", g: ["telepon", "telephone", "teléfono"] },
  { w: "e-mail", pos: "n", cefr: "B2", g: ["surel, email", "email", "correo electrónico"] },
  { w: "talaksan", pos: "n", cefr: "B2", g: ["berkas", "file", "archivo"], note: ["Dalam percakapan orang lebih sering memakai 'file'.", "In everyday speech people simply say 'file'.", "En el habla diaria se dice 'file'."] },
  { w: "password", pos: "n", cefr: "B2", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "di-maiiwasan", pos: "adj", cefr: "C2", ipa: "di majʔiˈwasan", g: ["tak terhindarkan", "unavoidable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Di-maiiwasan ang pagtaas ng presyo.", "Kenaikan harga tak terhindarkan.", "The price rise is unavoidable.", "La subida es inevitable."] },
  { w: "di-maipaliwanag", pos: "adj", cefr: "C2", ipa: "di majpaliˈwanaɡ", g: ["tak terjelaskan", "inexplicable, beyond words", "inexplicable"], d: ["Terlalu besar atau rumit untuk dijelaskan.", "Too great or complex to explain.", "Demasiado grande o complejo para explicarse."], ex: ["Di-maipaliwanag ang saya niya.", "Kebahagiaannya tak terkatakan.", "Her joy was beyond words.", "Su alegría era inexplicable."] },
  { w: "guni-guni", pos: "n", cefr: "C2", ipa: "ɡuniˈɡuni", g: ["khayalan", "figment, imagining", "figuración"], d: ["Gambaran yang hanya ada dalam pikiran.", "Something that exists only in the mind.", "Algo que solo existe en la mente."], ex: ["Guni-guni lang ang pangambang iyon.", "Kekhawatiran itu hanya khayalan.", "That fear is only a figment.", "Ese miedo es solo una figuración."] },
  { w: "kislap", pos: "n", cefr: "C2", ipa: "kisˈlap", g: ["kilau, secercah", "gleam, glimmer", "destello"], d: ["Cahaya kecil; kiasan untuk tanda harapan.", "A small light; figuratively a sign of hope.", "Luz pequeña; indicio de esperanza."], ex: ["May kislap pa rin ng pag-asa.", "Masih ada secercah harapan.", "There's still a glimmer of hope.", "Aún hay un destello de esperanza."] },
  { w: "kinikilingan", pos: "v", cefr: "C2", ipa: "kinikiˈliŋan", g: ["berpihak, bias", "to be biased towards", "estar sesgado"], d: ["Menilai dengan memihak sehingga tidak adil.", "Judging in a way that favours one side.", "Juzgar favoreciendo a una parte."], ex: ["Kinikilingan ng pag-aaral ang isang panig.", "Kajian itu berpihak pada satu sisi.", "The study is biased towards one side.", "El estudio se inclina hacia un lado."] },
  { w: "linawin", pos: "v", cefr: "C2", ipa: "liˈnawin", g: ["menjernihkan", "to clarify, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Kailangang linawin ang mga detalye.", "Rinciannya perlu dijernihkan.", "The details must be clarified.", "Hay que esclarecer los detalles."] },
  { w: "madalian", pos: "adj", cefr: "C2", ipa: "madaliˈʔan", g: ["mendesak, kilat", "urgent, immediate", "urgente"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["Madaliang usapin ito.", "Ini persoalan mendesak.", "This is an urgent matter.", "Es un asunto urgente."] },
  { w: "maliitin", pos: "v", cefr: "C2", ipa: "maliʔiˈtin", g: ["meremehkan", "to belittle, to look down on", "menospreciar"], d: ["Menganggap sesuatu lebih rendah nilainya.", "To treat something as worth less than it is.", "Tratar algo como de menor valor."], ex: ["Huwag mong maliitin ang sikap niya.", "Jangan remehkan usahanya.", "Don't belittle her effort.", "No menosprecies su esfuerzo."] },
  { w: "palatandaan", pos: "n", cefr: "C2", ipa: "palatanˈdaʔan", g: ["penanda, tonggak", "landmark, sign", "señal, hito"], d: ["Tanda penting yang menjadi rujukan.", "A prominent sign others navigate by.", "Señal destacada que sirve de referencia."], ex: ["Naging palatandaan ng kasaysayan ang kasunduan.", "Perjanjian itu menjadi tonggak sejarah.", "The treaty became a historic landmark.", "El tratado fue un hito histórico."] },
  { w: "paradigma", pos: "n", cefr: "C2", ipa: "paɾaˈdiɡma", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Isang pagbabago ng paradigma iyon.", "Itu sebuah pergeseran paradigma.", "That was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "sa liwanag ng", pos: "phr", cefr: "C2", ipa: "sa liˈwanaɡ naŋ", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["Sa liwanag ng resulta, tagumpay ito.", "Berdasarkan hasilnya, ini keberhasilan.", "In the light of the results, it's a success.", "A la luz de los resultados, es un éxito."] },
  { w: "umiwas", pos: "v", cefr: "C2", ipa: "ʔuˈmiwas", g: ["mengelak, menghindar", "to evade, to steer clear of", "eludir"], d: ["Menjauhi persoalan alih-alih menghadapinya.", "To keep away from an issue instead of facing it.", "Evitar un asunto en vez de afrontarlo."], ex: ["Umiwas siya sa tanong.", "Dia mengelak dari pertanyaan itu.", "He evaded the question.", "Eludió la pregunta."] },
];
