/* =========================================================================
   lexicon/tr.js — Sözlük: Türkçe. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Turki bekerja dengan menempelkan akhiran demi akhiran pada satu akar kata — satu kata Turki bisa setara satu kalimat penuh dalam bahasa lain. Ejaannya benar-benar fonetis.",
    "Turkish works by gluing suffix after suffix onto a single root — one Turkish word can equal a whole sentence elsewhere. Its spelling is perfectly phonetic.",
    "El turco encadena sufijo tras sufijo sobre una raíz: una palabra turca puede equivaler a una frase entera. Su ortografía es totalmente fonética.",
  ],
  script: [
    "29 huruf Latin sejak 1928. Perhatikan dua huruf I: I/ı (tanpa titik) dan İ/i (bertitik) adalah huruf yang berbeda.",
    "29 Latin letters since 1928. Mind the two I's: I/ı (dotless) and İ/i (dotted) are different letters.",
    "29 letras latinas desde 1928. Atención a las dos íes: I/ı (sin punto) e İ/i (con punto) son letras distintas.",
  ],
  pron: [
    ["ı", "Vokal tanpa titik, di tengah mulut: kız, ılık.", "The dotless vowel, made mid-mouth: kız, ılık.", "La vocal sin punto, en el centro de la boca: kız, ılık."],
    ["ğ", "Tidak dibunyikan; ia memanjangkan vokal sebelumnya: dağ → 'daa'.", "Never pronounced; it lengthens the vowel before it: dağ → 'daa'.", "No se pronuncia; alarga la vocal previa: dağ → 'daa'."],
    ["c / ç", "c = 'j' (cam), ç = 'c' (çay).", "c = English 'j' (cam), ç = 'ch' (çay).", "c = 'y' inglesa de 'jam'; ç = 'ch' (çay)."],
    ["ş", "Selalu 'sy': şeker, kuş.", "Always 'sh': şeker, kuş.", "Siempre 'sh': şeker, kuş."],
    ["ö / ü", "Bibir dibulatkan seperti dalam bahasa Jerman: göz, gün.", "Rounded lips, as in German: göz, gün.", "Labios redondeados, como en alemán: göz, gün."],
    ["tekanan", "Umumnya di suku kata terakhir; nama tempat sering di suku pertama: ÍStanbul.", "Usually on the last syllable; place names often stress the first: ÍStanbul.", "Normalmente en la última sílaba; los topónimos, en la primera: ÍStanbul."],
  ],
  grammar: [
    {
      t: ["Harmoni vokal", "Vowel harmony", "Armonía vocálica"],
      d: ["Vokal akhiran menyesuaikan vokal terakhir akar kata — inilah kunci semua tata bahasa Turki.", "Suffix vowels copy the last vowel of the root — the key to all Turkish grammar.", "Las vocales del sufijo siguen la última vocal de la raíz: la clave del turco."],
      ex: "ev-ler · kitap-lar · göz-ler",
    },
    {
      t: ["Kata kerja di akhir", "The verb comes last", "El verbo va al final"],
      d: ["Urutannya Subjek–Objek–Kata kerja, dan semua keterangan mendahului kata kerja.", "The order is Subject–Object–Verb, with every modifier before the verb.", "El orden es sujeto–objeto–verbo."],
      ex: "Ben kitabı okudum. (Saya · buku · membaca)",
    },
    {
      t: ["Akhiran menggantikan kata depan", "Suffixes replace prepositions", "Los sufijos sustituyen preposiciones"],
      d: ["-de (di), -den (dari), -e (ke) menempel langsung di kata bendanya.", "-de (in), -den (from), -e (to) attach straight onto the noun.", "-de (en), -den (de), -e (a) se pegan al sustantivo."],
      ex: "evde · evden · eve",
    },
    {
      t: ["Tanpa gender", "No grammatical gender", "Sin género"],
      d: ["Satu kata ganti o dipakai untuk dia laki-laki, dia perempuan, dan itu.", "A single pronoun o covers he, she and it.", "Un solo pronombre o vale para él, ella y ello."],
      ex: "O geldi. = Dia/ia datang.",
    },
    {
      t: ["Kabar langsung vs. kabar dengar", "Witnessed vs. reported past", "Pasado presenciado y referido"],
      d: ["-di menandai yang kamu saksikan sendiri, -miş menandai yang kamu dengar dari orang lain.", "-di marks what you witnessed; -miş marks what you were told.", "-di marca lo presenciado; -miş, lo que te contaron."],
      ex: "Geldi. (saya lihat) · Gelmiş. (katanya)",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "adam", pos: "n", cefr: "A1", ipa: "aˈdam", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["O adam komşum.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["kadın"] },
  { w: "arkadaş", pos: "n", cefr: "A1", ipa: "aɾkaˈdaʃ", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Bir arkadaşla buluşuyorum.", "Saya bertemu seorang teman.", "I'm meeting a friend.", "Voy a ver a un amigo."] },
  { w: "büyük", pos: "adj", cefr: "A1", ipa: "byˈjyk", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Büyük bir şehirde yaşıyorlar.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["küçük"] },
  { w: "ev", pos: "n", cefr: "A1", ipa: "ev", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Evim parkın yanında.", "Rumah saya di dekat taman.", "My house is next to the park.", "Mi casa está junto al parque."] },
  { w: "gece", pos: "n", cefr: "A1", ipa: "ɟeˈdʒe", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["İyi geceler!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["gündüz"] },
  { w: "gitmek", pos: "v", cefr: "A1", ipa: "ɟitˈmec", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Pazara gidiyorum.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "gün", pos: "n", cefr: "A1", ipa: "ɟyn", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Her gün çalışıyorum.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."] },
  { w: "iyi", pos: "adj", cefr: "A1", ipa: "iˈji", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["Bu iyi bir fikir.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["kötü"] },
  { w: "istemek", pos: "v", cefr: "A1", ipa: "isteˈmec", g: ["mau, ingin", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Türkçe öğrenmek istiyorum.", "Saya mau belajar bahasa Turki.", "I want to learn Turkish.", "Quiero aprender turco."] },
  { w: "kadın", pos: "n", cefr: "A1", ipa: "kaˈdɯn", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["Şapkalı kadın teyzem.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["adam"] },
  { w: "küçük", pos: "adj", cefr: "A1", ipa: "cyˈtʃyc", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Küçük bir dairem var.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["büyük"] },
  { w: "olmak", pos: "v", cefr: "A1", ipa: "olˈmak", g: ["menjadi, ada", "to be, to become", "ser, llegar a ser"], d: ["Menyatakan keberadaan atau perubahan keadaan.", "Expresses existence or becoming.", "Expresa existencia o transformación."], ex: ["Doktor olmak istiyor.", "Dia ingin menjadi dokter.", "She wants to become a doctor.", "Quiere ser médica."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "başlamak", pos: "v", cefr: "A2", ipa: "baʃlaˈmak", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Film sekizde başlıyor.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["bitmek"] },
  { w: "çünkü", pos: "conj", cefr: "A2", ipa: "ˈtʃynky", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Evdeyim çünkü yağmur yağıyor.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },
  { w: "her zaman", pos: "adv", cefr: "A2", ipa: "heɾ zaˈman", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Kahvaltıyı her zaman evde yaparım.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["hiçbir zaman"] },
  { w: "hızlı", pos: "adj", cefr: "A2", ipa: "hɯzˈlɯ", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Tren daha hızlı.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["yavaş"] },
  { w: "ihtiyaç", pos: "n", cefr: "A2", ipa: "ihtiˈjatʃ", g: ["kebutuhan", "need", "necesidad"], d: ["Hal yang diperlukan; ihtiyacım var = saya butuh.", "Something required; ihtiyacım var = I need.", "Lo que hace falta; ihtiyacım var = necesito."], ex: ["Dinlenmeye ihtiyacım var.", "Saya butuh istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "iş", pos: "n", cefr: "A2", ipa: "iʃ", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["İşim dokuzda başlıyor.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "kolay", pos: "adj", cefr: "A2", ipa: "koˈlaj", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["Sınav kolaydı.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["zor"] },
  { w: "para", pos: "n", cefr: "A2", ipa: "paˈɾa", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Yeterli param yok.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "şehir", pos: "n", cefr: "A2", ipa: "ʃeˈhiɾ", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["İzmir güzel bir şehir.", "İzmir kota yang indah.", "İzmir is a beautiful city.", "Esmirna es una ciudad bonita."] },
  { w: "yardım etmek", pos: "v", cefr: "A2", ipa: "jaɾˈdɯm etˈmec", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Bana yardım eder misin?", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "zaman", pos: "n", cefr: "A2", ipa: "zaˈman", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["Bugün hiç zamanım yok.", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "zor", pos: "adj", cefr: "A2", ipa: "zoɾ", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Burada park etmek zor.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["kolay"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "alışmak", pos: "v", cefr: "B1", ipa: "alɯʃˈmak", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Havaya alıştım.", "Saya sudah terbiasa dengan cuacanya.", "I got used to the weather.", "Me acostumbré al clima."] },
  { w: "ancak", pos: "conj", cefr: "B1", ipa: "anˈdʒak", g: ["namun; hanya", "however; only", "sin embargo; solo"], d: ["Menandai pertentangan; juga berarti 'hanya'.", "Marks a contrast; also means 'only'.", "Marca contraste; también significa 'solo'."], ex: ["Pahalı; ancak buna değer.", "Mahal; namun sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "başarmak", pos: "v", cefr: "B1", ipa: "baʃaɾˈmak", g: ["berhasil", "to succeed, to manage", "lograr"], d: ["Berhasil melakukan yang diusahakan.", "To succeed in doing something.", "Lograr hacer algo."], ex: ["Zamanında bitirmeyi başardım.", "Saya berhasil selesai tepat waktu.", "I managed to finish on time.", "Logré terminar a tiempo."] },
  { w: "belki", pos: "adv", cefr: "B1", ipa: "belˈci", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Belki yarın gelir.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "deneyim", pos: "n", cefr: "B1", ipa: "deneˈjim", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Çok deneyimi var.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."], syn: ["tecrübe"] },
  { w: "fırsat", pos: "n", cefr: "B1", ipa: "fɯɾˈsat", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["Bu harika bir fırsat.", "Ini kesempatan bagus.", "This is a great opportunity.", "Es una gran oportunidad."] },
  { w: "geliştirmek", pos: "v", cefr: "B1", ipa: "ɟeliʃtiɾˈmec", g: ["mengembangkan, memperbaiki", "to develop, to improve", "desarrollar, mejorar"], d: ["Menjadikan sesuatu lebih baik atau lebih maju.", "To make something better or more advanced.", "Hacer algo mejor o más avanzado."], ex: ["Telaffuzumu geliştirmek istiyorum.", "Saya ingin memperbaiki pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "görünmek", pos: "v", cefr: "B1", ipa: "ɟyɾynˈmec", g: ["tampak", "to seem, to appear", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Yorgun görünüyor.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "karar", pos: "n", cefr: "B1", ipa: "kaˈɾaɾ", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Zor bir karardı.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."], note: ["Kolokasinya karar vermek.", "The collocation is karar vermek (to make a decision).", "La colocación es karar vermek."] },
  { w: "özlemek", pos: "v", cefr: "B1", ipa: "øzleˈmec", g: ["merindukan", "to miss (someone)", "echar de menos"], d: ["Merasa sedih karena sesuatu tidak ada.", "To feel the absence of someone.", "Sentir la ausencia de alguien."], ex: ["Ailemi özlüyorum.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },
  { w: "tavsiye", pos: "n", cefr: "B1", ipa: "tavsiˈje", g: ["nasihat, saran", "advice, recommendation", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Bir tavsiye verir misin?", "Boleh minta saran?", "Can you give me some advice?", "¿Me das un consejo?"] },
  { w: "sorun", pos: "n", cefr: "B1", ipa: "soˈɾun", g: ["masalah", "problem", "problema"], d: ["Hal yang menyulitkan dan perlu diselesaikan.", "Something difficult that needs solving.", "Algo difícil que hay que resolver."], ex: ["Küçük bir sorun var.", "Ada masalah kecil.", "There's a small problem.", "Hay un pequeño problema."], syn: ["problem"] },

  /* ------------------------------------------------------------------ B2 */
  { w: "anlaşma", pos: "n", cefr: "B2", ipa: "anlaʃˈma", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Adil bir anlaşmaya vardık.", "Kami mencapai kesepakatan yang adil.", "We reached a fair agreement.", "Llegamos a un acuerdo justo."] },
  { w: "bu yüzden", pos: "conj", cefr: "B2", ipa: "bu ˈjyzden", g: ["karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Yağmur yağdı; bu yüzden iptal ettik.", "Hujan; karena itu kami batalkan.", "It rained; therefore we cancelled.", "Llovió; por eso cancelamos."] },
  { w: "çevre", pos: "n", cefr: "B2", ipa: "tʃevˈɾe", g: ["lingkungan; sekitar", "environment; surroundings", "medio ambiente; entorno"], d: ["Alam sekitar; juga lingkaran pergaulan.", "The natural surroundings; also one's circle.", "Entorno natural; también círculo social."], ex: ["Çevreyi korumalıyız.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "gelişme", pos: "n", cefr: "B2", ipa: "ɟeliʃˈme", g: ["perkembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Projedeki gelişme iyi.", "Perkembangan proyeknya baik.", "The project's development is good.", "El desarrollo del proyecto es bueno."] },
  { w: "güvenilir", pos: "adj", cefr: "B2", ipa: "ɟyveniˈliɾ", g: ["dapat diandalkan", "reliable, trustworthy", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Güvenilir bir kaynak.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "konu", pos: "n", cefr: "B2", ipa: "koˈnu", g: ["topik, perkara", "topic, matter", "tema, asunto"], d: ["Hal yang sedang dibicarakan.", "The matter under discussion.", "Tema del que se trata."], ex: ["Bu hassas bir konu.", "Ini perkara yang sensitif.", "It's a delicate matter.", "Es un asunto delicado."] },
  { w: "rağmen", pos: "prep", cefr: "B2", ipa: "ɾaːˈmen", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Soğuğa rağmen dışarı çıktık.", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."], note: ["Diletakkan sesudah kata bendanya, berbeda dengan kata depan Eropa.", "It follows its noun, unlike European prepositions.", "Va detrás del sustantivo, no delante."] },
  { w: "ulaşmak", pos: "v", cefr: "B2", ipa: "ulaʃˈmak", g: ["mencapai; menghubungi", "to reach; to get hold of", "alcanzar; contactar"], d: ["Sampai pada tujuan; juga berhasil menghubungi.", "To arrive at a goal; also to get hold of someone.", "Llegar a una meta; también localizar a alguien."], ex: ["Hedefe ulaştık.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "uygulamak", pos: "v", cefr: "B2", ipa: "ujɡulaˈmak", g: ["menerapkan", "to apply, to implement", "aplicar"], d: ["Mengubah rencana atau aturan menjadi tindakan.", "To put a plan or rule into practice.", "Poner en práctica un plan o norma."], ex: ["Yeni sistemi uygulayacağız.", "Kami akan menerapkan sistem baru.", "We'll implement the new system.", "Aplicaremos el nuevo sistema."] },
  { w: "vazgeçilmez", pos: "adj", cefr: "B2", ipa: "vazɟetʃilˈmez", g: ["mutlak perlu", "indispensable", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Pasaport vazgeçilmezdir.", "Paspor mutlak diperlukan.", "A passport is indispensable.", "El pasaporte es imprescindible."] },
  { w: "vurgulamak", pos: "v", cefr: "B2", ipa: "vuɾɡulaˈmak", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Güvenliği vurguladı.", "Dia menekankan keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "zorluk", pos: "n", cefr: "B2", ipa: "zoɾˈluk", g: ["kesulitan, tantangan", "difficulty, challenge", "dificultad"], d: ["Hal yang membuat sesuatu sulit dikerjakan.", "What makes something hard to do.", "Lo que hace difícil algo."], ex: ["Bu gerçek bir zorluk.", "Ini benar-benar tantangan.", "That's a real challenge.", "Es una verdadera dificultad."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "alan", pos: "n", cefr: "C1", ipa: "aˈlan", g: ["bidang; area", "field; area", "ámbito; área"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["Hukuk alanında durum farklı.", "Dalam bidang hukum keadaannya berbeda.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "amacıyla", pos: "prep", cefr: "C1", ipa: "amadʒɯjˈla", g: ["demi, agar", "for the purpose of", "con el fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["Zaman kazanmak amacıyla süreci sadeleştirdik.", "Demi menghemat waktu, prosesnya kami sederhanakan.", "In order to save time we simplified the process.", "Con el fin de ahorrar tiempo simplificamos el proceso."] },
  { w: "ele almak", pos: "phr", cefr: "C1", ipa: "eˈle alˈmak", g: ["menangani, membahas", "to take up, to address", "abordar"], d: ["Mulai membahas atau menangani persoalan.", "To take an issue up and deal with it.", "Tomar un asunto y tratarlo."], ex: ["Konuyu sakin bir şekilde ele alalım.", "Mari bahas persoalannya dengan tenang.", "Let's address the issue calmly.", "Abordemos el tema con calma."] },
  { w: "kapsam", pos: "n", cefr: "C1", ipa: "kapˈsam", g: ["cakupan", "scope, coverage", "alcance"], d: ["Seberapa luas sesuatu menjangkau.", "How widely something reaches.", "Hasta dónde llega algo."], ex: ["Kararın kapsamı geniş.", "Cakupan keputusannya luas.", "The decision's scope is wide.", "El alcance de la decisión es amplio."] },
  { w: "nüans", pos: "n", cefr: "C1", ipa: "nyˈans", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["Burada önemli bir nüans var.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "öne çıkarmak", pos: "phr", cefr: "C1", ipa: "øˈne tʃɯkaɾˈmak", g: ["menonjolkan", "to bring to the fore, to highlight", "poner de relieve"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["Rapor riskleri öne çıkarıyor.", "Laporan itu menonjolkan risikonya.", "The report highlights the risks.", "El informe pone de relieve los riesgos."] },
  { w: "pekiştirmek", pos: "v", cefr: "C1", ipa: "pecuʃtiɾˈmec", g: ["memperkukuh", "to reinforce, to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Şirket konumunu pekiştirdi.", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "teşvik etmek", pos: "v", cefr: "C1", ipa: "teʃˈvic etˈmec", g: ["mendorong", "to encourage, to promote", "fomentar"], d: ["Membantu sesuatu tumbuh atau berkembang.", "To help something grow.", "Ayudar a que algo crezca."], ex: ["Yasa geri dönüşümü teşvik ediyor.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "titiz", pos: "adj", cefr: "C1", ipa: "tiˈtiz", g: ["teliti, cermat", "meticulous, fastidious", "meticuloso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["Titiz bir analiz yaptı.", "Dia membuat analisis yang teliti.", "She did a meticulous analysis.", "Hizo un análisis meticuloso."] },
  { w: "yaklaşım", pos: "n", cefr: "C1", ipa: "jaklaˈʃɯm", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Farklı bir yaklaşım gerekiyor.", "Kita butuh pendekatan berbeda.", "A different approach is needed.", "Hace falta otro enfoque."] },
  { w: "yansıtmak", pos: "v", cefr: "C1", ipa: "jansɯtˈmak", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Veriler bir iyileşmeyi yansıtıyor.", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "yine de", pos: "conj", cefr: "C1", ipa: "jiˈne de", g: ["walaupun demikian", "nonetheless, even so", "aun así"], d: ["Menyatakan bahwa hasilnya tetap sama.", "Says the result holds anyway.", "Indica que el resultado se mantiene."], ex: ["Yine de öneri geçerli.", "Walaupun demikian, usulan itu tetap berlaku.", "Even so, the proposal stands.", "Aun así, la propuesta sigue vigente."] },

  /* ------------------------------------------------------------------ C2 */
  { w: "aydınlatmak", pos: "v", cefr: "C2", ipa: "ajdɯnlatˈmak", g: ["menerangi, menjernihkan", "to illuminate, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Detayların aydınlatılması gerekiyor.", "Rinciannya perlu dijernihkan.", "The details need elucidating.", "Hay que esclarecer los detalles."] },
  { w: "dönüm noktası", pos: "n", cefr: "C2", ipa: "døˈnym noktaˈsɯ", g: ["titik balik, tonggak", "turning point, milestone", "punto de inflexión"], d: ["Peristiwa yang mengubah arah sesuatu.", "An event that changes the direction of things.", "Suceso que cambia el rumbo."], ex: ["Anlaşma bir dönüm noktasıydı.", "Kesepakatan itu titik balik.", "The agreement was a turning point.", "El acuerdo fue un punto de inflexión."] },
  { w: "hüsnükuruntu", pos: "n", cefr: "C2", ipa: "hysnycuɾunˈtu", g: ["angan-angan", "wishful thinking", "ilusión"], d: ["Keyakinan yang lahir dari harapan, bukan bukti.", "A belief born of hope rather than evidence.", "Creencia nacida del deseo, no de pruebas."], ex: ["Bu sadece bir hüsnükuruntu.", "Itu hanya angan-angan.", "That's just wishful thinking.", "Eso es solo una ilusión."] },
  { w: "ivedi", pos: "adj", cefr: "C2", ipa: "iveˈdi", g: ["mendesak", "urgent, pressing", "urgente"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["Bu ivedi bir konudur.", "Ini persoalan mendesak.", "This is an urgent matter.", "Es un asunto urgente."] },
  { w: "kaçınılmaz", pos: "adj", cefr: "C2", ipa: "katʃɯnɯlˈmaz", g: ["tak terhindarkan", "inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Zam kaçınılmaz.", "Kenaikan harga tak terhindarkan.", "A price rise is inevitable.", "La subida es inevitable."] },
  { w: "kaçınmak", pos: "v", cefr: "C2", ipa: "katʃɯnˈmak", g: ["menghindari", "to avoid, to refrain from", "evitar"], d: ["Sengaja menjauhi sesuatu.", "To deliberately keep away from something.", "Apartarse de algo a propósito."], ex: ["Sorudan kaçındı.", "Dia menghindari pertanyaan itu.", "He avoided the question.", "Eludió la pregunta."] },
  { w: "küçümsemek", pos: "v", cefr: "C2", ipa: "cytʃymseˈmec", g: ["meremehkan", "to belittle, to underrate", "menospreciar"], d: ["Menganggap sesuatu lebih kecil nilainya.", "To treat something as less valuable than it is.", "Considerar algo de menos valor."], ex: ["Emeğini küçümsemek istemem.", "Saya tak ingin meremehkan jerih payahnya.", "I don't mean to belittle his effort.", "No quiero menospreciar su esfuerzo."] },
  { w: "önyargı", pos: "n", cefr: "C2", ipa: "øɲjaɾˈɡɯ", g: ["prasangka, bias", "prejudice, bias", "prejuicio"], d: ["Penilaian yang dibuat sebelum mengetahui fakta.", "A judgement made before knowing the facts.", "Juicio previo al conocimiento de los hechos."], ex: ["Çalışmada belirgin bir önyargı var.", "Kajian itu punya bias yang jelas.", "The study has a clear bias.", "El estudio tiene un sesgo claro."] },
  { w: "paradigma", pos: "n", cefr: "C2", ipa: "paɾadiɡˈma", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Bu bir paradigma değişimiydi.", "Itu pergeseran paradigma.", "That was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "pırıltı", pos: "n", cefr: "C2", ipa: "pɯɾɯlˈtɯ", g: ["kilauan, secercah", "glimmer, sparkle", "destello"], d: ["Cahaya kecil; kiasan untuk tanda harapan.", "A small light; figuratively a sign of hope.", "Luz pequeña; indicio de esperanza."], ex: ["Hâlâ bir umut pırıltısı var.", "Masih ada secercah harapan.", "There's still a glimmer of hope.", "Aún hay un destello de esperanza."] },
  { w: "tarifsiz", pos: "adj", cefr: "C2", ipa: "taɾifˈsiz", g: ["tak terlukiskan", "indescribable", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Tarifsiz bir mutluluk duydu.", "Dia merasakan kebahagiaan tak terlukiskan.", "She felt an indescribable happiness.", "Sintió una felicidad indescriptible."] },
  { w: "ışığında", pos: "phr", cefr: "C2", ipa: "ɯʃɯːˈɯnda", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["Sonuçların ışığında bu bir başarıdır.", "Berdasarkan hasilnya, ini sebuah keberhasilan.", "In the light of the results, it's a success.", "A la luz de los resultados, es un éxito."] },
];
