/* =========================================================================
   lexicon/uk.js — Словник: Українська. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Ukraina memakai Kiril versinya sendiri: ada і, ї, є, dan ґ yang tidak dimiliki bahasa Rusia. Vokalnya lebih jernih — huruf о tetap dibaca /o/ walau tanpa tekanan.",
    "Ukrainian uses its own Cyrillic: it has і, ї, є and ґ, which Russian lacks. Its vowels stay clearer — an unstressed о is still /o/.",
    "El ucraniano usa su propio cirílico: tiene і, ї, є y ґ, que el ruso no tiene. Sus vocales son más claras: la о átona sigue siendo /o/.",
  ],
  script: [
    "33 huruf. Perhatikan pasangan yang menipu: и dibaca /ɪ/, sedangkan і dibaca /i/; г dibaca /ɦ/ yang lembut, bukan /g/.",
    "33 letters. Watch the deceptive pairs: и is /ɪ/ while і is /i/; г is a soft /ɦ/, not a hard /g/.",
    "33 letras. Ojo con los pares engañosos: и es /ɪ/ e і es /i/; г es una /ɦ/ suave, no /g/.",
  ],
  pron: [
    ["г vs ґ", "г lembut /ɦ/ (гарний); ґ keras /ɡ/ dan langka (ґудзик).", "г is a soft /ɦ/ (гарний); ґ is a hard /ɡ/ and rare (ґудзик).", "г es /ɦ/ suave (гарний); ґ es /ɡ/ dura y rara (ґудзик)."],
    ["и vs і", "и /ɪ/ lebih pendek dan tengah; і /i/ jelas dan tinggi.", "и /ɪ/ is shorter and central; і /i/ is clear and high.", "и /ɪ/ es más central; і /i/ es clara y alta."],
    ["ї", "Selalu dibaca 'yi': Київ → 'Kyyiv'.", "Always 'yi': Київ → 'Kyyiv'.", "Siempre 'yi': Київ → 'Kyyiv'."],
    ["є", "Dibaca 'ye': Європа, синє.", "Pronounced 'ye': Європа, синє.", "Se pronuncia 'ye': Європа, синє."],
    ["о tanpa tekanan", "Tetap /o/, tidak berubah jadi /a/ seperti dalam bahasa Rusia.", "Stays /o/; it does not shift to /a/ as in Russian.", "Se mantiene /o/; no cambia a /a/ como en ruso."],
    ["в di akhir", "Melemah jadi /w/: любов → 'lyubow'.", "Weakens to /w/: любов → 'lyubow'.", "Se debilita en /w/: любов → 'lyubow'."],
  ],
  grammar: [
    {
      t: ["Tujuh kasus", "Seven cases", "Siete casos"],
      d: ["Selain enam kasus seperti Rusia, ada kasus vokatif untuk memanggil orang.", "Beyond the six Russian-style cases there is a vocative, used to address people.", "Además de los seis casos, existe el vocativo para dirigirse a alguien."],
      ex: "Оксана → Оксано! · друг → друже!",
    },
    {
      t: ["Tanpa 'adalah'", "No 'to be' in the present", "Sin 'ser' en presente"],
      d: ["Kalimat masa kini tidak memakai kata kerja бути.", "The present tense drops бути entirely.", "El presente omite бути."],
      ex: "Він лікар. · Це дім.",
    },
    {
      t: ["Aspek kata kerja", "Verb aspect", "El aspecto verbal"],
      d: ["Setiap kata kerja berpasangan: belum selesai (робити) dan selesai (зробити).", "Every verb comes in a pair: imperfective (робити) and perfective (зробити).", "Cada verbo tiene pareja: imperfectivo (робити) y perfectivo (зробити)."],
      ex: "Я читав книжку. · Я прочитав книжку.",
    },
    {
      t: ["Masa depan dua bentuk", "Two futures", "Dos futuros"],
      d: ["Bisa memakai буду + infinitif, atau akhiran -му yang melekat pada kata kerjanya.", "Either буду + infinitive, or the ending -му fused onto the verb.", "Con буду + infinitivo o con la terminación -му pegada al verbo."],
      ex: "буду читати = читатиму",
    },
    {
      t: ["Gender pada masa lampau", "Gender in the past tense", "Género en el pasado"],
      d: ["Bentuk lampau menyesuaikan jenis kelamin pelakunya.", "Past-tense forms agree with the subject's gender.", "El pasado concuerda con el género del sujeto."],
      ex: "Я був · Я була",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "бути", r: "buty", pos: "v", cefr: "A1", ipa: "ˈbutɪ", g: ["ada, menjadi", "to be", "ser, estar"], d: ["Menyatakan keberadaan; hilang di masa kini.", "Expresses existence; it disappears in the present.", "Expresa existencia; desaparece en presente."], ex: ["Він був удома.", "Dia ada di rumah.", "He was at home.", "Estaba en casa."] },
  { w: "великий", r: "velykyi", pos: "adj", cefr: "A1", ipa: "wɛˈlɪkɪj", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Вони живуть у великому місті.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["малий"] },
  { w: "день", r: "den'", pos: "n", cefr: "A1", gen: "m", ipa: "dɛnʲ", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Я працюю щодня.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["ніч"] },
  { w: "дім", r: "dim", pos: "n", cefr: "A1", gen: "m", ipa: "dim", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Мій дім поруч із парком.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "добрий", r: "dobryi", pos: "adj", cefr: "A1", ipa: "ˈdɔbrɪj", g: ["baik", "good, kind", "bueno"], d: ["Bermutu baik; juga berhati baik.", "Of good quality; also kind-hearted.", "De buena calidad; también bondadoso."], ex: ["Це добра ідея.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["поганий"] },
  { w: "друг", r: "druh", pos: "n", cefr: "A1", gen: "m", ipa: "druɦ", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["Це мій найкращий друг.", "Ini sahabat terbaik saya.", "This is my best friend.", "Es mi mejor amigo."] },
  { w: "жінка", r: "zhinka", pos: "n", cefr: "A1", gen: "f", ipa: "ˈʒinkɐ", g: ["perempuan; istri", "woman; wife", "mujer; esposa"], d: ["Manusia dewasa perempuan; juga istri.", "An adult female; also a wife.", "Mujer adulta; también esposa."], ex: ["Ця жінка — лікарка.", "Perempuan itu seorang dokter.", "That woman is a doctor.", "Esa mujer es médica."], ant: ["чоловік"] },
  { w: "іти", r: "ity", pos: "v", cefr: "A1", ipa: "iˈtɪ", g: ["berjalan, pergi", "to go on foot", "ir a pie"], d: ["Berpindah dengan berjalan kaki.", "To move on foot.", "Desplazarse a pie."], ex: ["Я йду на ринок.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "малий", r: "malyi", pos: "adj", cefr: "A1", ipa: "mɐˈlɪj", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["У мене мала квартира.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["великий"], syn: ["маленький"] },
  { w: "ніч", r: "nich", pos: "n", cefr: "A1", gen: "f", ipa: "nitʃ", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["На добраніч!", "Selamat malam!", "Good night!", "¡Buenas noches!"], ant: ["день"] },
  { w: "хотіти", r: "khotity", pos: "v", cefr: "A1", ipa: "xɔˈtitɪ", g: ["mau", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Я хочу вивчати українську.", "Saya mau belajar bahasa Ukraina.", "I want to learn Ukrainian.", "Quiero aprender ucraniano."] },
  { w: "чоловік", r: "cholovik", pos: "n", cefr: "A1", gen: "m", ipa: "tʃɔlɔˈwik", g: ["laki-laki; suami", "man; husband", "hombre; marido"], d: ["Manusia dewasa laki-laki; juga suami.", "An adult male; also a husband.", "Hombre adulto; también marido."], ex: ["Цей чоловік — мій сусід.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["жінка"] },

  /* ------------------------------------------------------------------ A2 */
  { w: "важкий", r: "vazhkyi", pos: "adj", cefr: "A2", ipa: "wɐʒˈkɪj", g: ["sulit; berat", "difficult; heavy", "difícil; pesado"], d: ["Menuntut usaha; juga berbobot besar.", "Requiring effort; also weighing a lot.", "Que exige esfuerzo; también pesado."], ex: ["Тут важко припаркуватися.", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["легкий"] },
  { w: "гроші", r: "hroshi", pos: "n", cefr: "A2", ipa: "ˈɦrɔʃi", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Мені бракує грошей.", "Uang saya kurang.", "I'm short of money.", "Me falta dinero."], note: ["Selalu jamak.", "Always plural.", "Siempre en plural."] },
  { w: "допомагати", r: "dopomahaty", pos: "v", cefr: "A2", ipa: "dɔpɔmɐˈɦatɪ", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Ти можеш мені допомогти?", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "завжди", r: "zavzhdy", pos: "adv", cefr: "A2", ipa: "ˈzawʒdɪ", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Я завжди снідаю вдома.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."], ant: ["ніколи"] },
  { w: "легкий", r: "lehkyi", pos: "adj", cefr: "A2", ipa: "ˈlɛɦkɪj", g: ["mudah; ringan", "easy; light", "fácil; ligero"], d: ["Tidak menuntut usaha; juga tidak berat.", "Not requiring effort; also not heavy.", "Que no exige esfuerzo; también ligero."], ex: ["Іспит був легкий.", "Ujiannya mudah.", "The exam was easy.", "El examen fue fácil."], ant: ["важкий"] },
  { w: "місто", r: "misto", pos: "n", cefr: "A2", gen: "nt", ipa: "ˈmistɔ", g: ["kota", "city, town", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Львів — гарне місто.", "Lviv kota yang indah.", "Lviv is a beautiful city.", "Leópolis es una ciudad bonita."] },
  { w: "потрібний", r: "potribnyi", pos: "adj", cefr: "A2", ipa: "pɔˈtribnɪj", g: ["diperlukan", "needed, necessary", "necesario"], d: ["Yang dibutuhkan; bentuk pendek потрібно = 'perlu'.", "Required; the short form потрібно means 'one needs'.", "Necesario; la forma corta потрібно significa 'hace falta'."], ex: ["Мені потрібно відпочити.", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "починати", r: "pochynaty", pos: "v", cefr: "A2", ipa: "pɔtʃɪˈnatɪ", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Фільм починається о восьмій.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."] },
  { w: "робота", r: "robota", pos: "n", cefr: "A2", gen: "f", ipa: "rɔˈbɔtɐ", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Моя робота починається о дев'ятій.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "тому що", r: "tomu shcho", pos: "conj", cefr: "A2", ipa: "tɔˈmu ʃtʃɔ", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Я вдома, тому що йде дощ.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },
  { w: "час", r: "chas", pos: "n", cefr: "A2", gen: "m", ipa: "tʃɑs", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["У мене немає часу.", "Saya tidak punya waktu.", "I don't have time.", "No tengo tiempo."] },
  { w: "швидкий", r: "shvydkyi", pos: "adj", cefr: "A2", ipa: "ʃwɪdˈkɪj", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Потяг швидший.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["повільний"] },

  /* ------------------------------------------------------------------ B1 */
  { w: "галузь", r: "haluz'", pos: "n", cefr: "B1", gen: "f", ipa: "ɦɐˈluzʲ", g: ["bidang, sektor", "field, branch", "ámbito, sector"], d: ["Wilayah kegiatan atau industri tertentu.", "An area of activity or industry.", "Área de actividad o industria."], ex: ["Він працює в галузі освіти.", "Dia bekerja di bidang pendidikan.", "He works in the education field.", "Trabaja en el ámbito educativo."] },
  { w: "досвід", r: "dosvid", pos: "n", cefr: "B1", gen: "m", ipa: "ˈdɔswid", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["У неї великий досвід.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "здаватися", r: "zdavatysia", pos: "v", cefr: "B1", ipa: "zdɐˈwatɪsʲɐ", g: ["tampak; menyerah", "to seem; to give up", "parecer; rendirse"], d: ["Memberi kesan tertentu; juga berhenti berjuang.", "To give an impression; also to surrender.", "Dar una impresión; también rendirse."], ex: ["Він здається втомленим.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "звикнути", r: "zvyknuty", pos: "v", cefr: "B1", ipa: "ˈzwɪknutɪ", g: ["terbiasa", "to get used to", "acostumbrarse"], d: ["Menjadi terbiasa dengan keadaan baru.", "To grow used to something new.", "Habituarse a algo nuevo."], ex: ["Я звик до холоду.", "Saya sudah terbiasa dengan dinginnya.", "I got used to the cold.", "Me acostumbré al frío."] },
  { w: "можливість", r: "mozhlyvist'", pos: "n", cefr: "B1", gen: "f", ipa: "mɔʒˈlɪwistʲ", g: ["kesempatan; kemungkinan", "opportunity; possibility", "oportunidad; posibilidad"], d: ["Saat atau keadaan yang memungkinkan sesuatu.", "A chance or condition making something possible.", "Ocasión o condición que hace algo posible."], ex: ["Це чудова можливість.", "Ini kesempatan bagus.", "This is a great opportunity.", "Es una gran oportunidad."] },
  { w: "можливо", r: "mozhlyvo", pos: "adv", cefr: "B1", ipa: "mɔʒˈlɪwɔ", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Можливо, він прийде завтра.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "однак", r: "odnak", pos: "conj", cefr: "B1", ipa: "ɔdˈnak", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Дорого; однак воно того варте.", "Mahal; namun begitu sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },
  { w: "покращити", r: "pokrashchyty", pos: "v", cefr: "B1", ipa: "pɔˈkrɑʃtʃɪtɪ", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Я хочу покращити вимову.", "Saya ingin memperbaiki pelafalan.", "I want to improve my pronunciation.", "Quiero mejorar la pronunciación."] },
  { w: "порада", r: "porada", pos: "n", cefr: "B1", gen: "f", ipa: "pɔˈrɑdɐ", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Дай мені пораду.", "Beri saya nasihat.", "Give me some advice.", "Dame un consejo."] },
  { w: "рішення", r: "rishennia", pos: "n", cefr: "B1", gen: "nt", ipa: "riˈʃɛnʲːɐ", g: ["keputusan; solusi", "decision; solution", "decisión; solución"], d: ["Pilihan yang ditetapkan; juga jalan keluar.", "A settled choice; also a way out of a problem.", "Elección tomada; también solución."], ex: ["Це було складне рішення.", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."] },
  { w: "сумувати", r: "sumuvaty", pos: "v", cefr: "B1", ipa: "sumuˈwatɪ", g: ["merindukan; bersedih", "to miss; to be sad", "echar de menos; estar triste"], d: ["Merasa kehilangan seseorang; juga bersedih.", "To feel someone's absence; also to be sad.", "Sentir la ausencia; también estar triste."], ex: ["Я сумую за родиною.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."] },
  { w: "хоча", r: "khocha", pos: "conj", cefr: "B1", ipa: "xɔˈtʃɑ", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Хоча йде дощ, ми вийдемо.", "Meskipun hujan, kami akan keluar.", "Although it's raining, we'll go out.", "Aunque llueve, saldremos."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "виклик", r: "vyklyk", pos: "n", cefr: "B2", gen: "m", ipa: "ˈwɪklɪk", g: ["tantangan; panggilan", "challenge; a call", "desafío; llamada"], d: ["Hal sulit yang menuntut usaha; juga panggilan.", "Something demanding; also a call.", "Algo exigente; también una llamada."], ex: ["Це серйозний виклик.", "Ini tantangan serius.", "That's a serious challenge.", "Es un desafío serio."] },
  { w: "впровадити", r: "vprovadyty", pos: "v", cefr: "B2", ipa: "wprɔˈwadɪtɪ", g: ["menerapkan", "to implement", "implantar"], d: ["Memasukkan sistem baru ke dalam praktik.", "To put a new system into practice.", "Poner en práctica un sistema nuevo."], ex: ["Ми впровадимо нову систему.", "Kami akan menerapkan sistem baru.", "We'll implement the new system.", "Implantaremos el nuevo sistema."] },
  { w: "довкілля", r: "dovkillia", pos: "n", cefr: "B2", gen: "nt", ipa: "dɔwˈkilʲːɐ", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar tempat makhluk hidup berada.", "The natural surroundings we live in.", "Entorno natural en que vivimos."], ex: ["Треба берегти довкілля.", "Kita harus menjaga lingkungan.", "We must protect the environment.", "Debemos cuidar el medio ambiente."] },
  { w: "досягти", r: "dosiahty", pos: "v", cefr: "B2", ipa: "dɔsʲɐɦˈtɪ", g: ["mencapai", "to achieve, to attain", "alcanzar"], d: ["Sampai pada tujuan atau angka tertentu.", "To reach a goal or a figure.", "Llegar a una meta o cifra."], ex: ["Ми досягли мети.", "Kami mencapai tujuannya.", "We reached the goal.", "Alcanzamos el objetivo."] },
  { w: "надійний", r: "nadiinyi", pos: "adj", cefr: "B2", ipa: "nɐˈdijnɪj", g: ["dapat diandalkan", "reliable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Це надійне джерело.", "Itu sumber tepercaya.", "It's a reliable source.", "Es una fuente fiable."] },
  { w: "необхідний", r: "neobkhidnyi", pos: "adj", cefr: "B2", ipa: "nɛɔbˈxidnɪj", g: ["mutlak perlu", "essential", "imprescindible"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Паспорт необхідний.", "Paspor mutlak diperlukan.", "A passport is essential.", "El pasaporte es imprescindible."] },
  { w: "питання", r: "pytannia", pos: "n", cefr: "B2", gen: "nt", ipa: "pɪˈtɑnʲːɐ", g: ["pertanyaan; persoalan", "question; issue", "pregunta; cuestión"], d: ["Kalimat tanya; juga perkara yang dibahas.", "A question; also a matter under discussion.", "Pregunta; también asunto."], ex: ["Це делікатне питання.", "Itu persoalan yang sensitif.", "It's a delicate issue.", "Es una cuestión delicada."] },
  { w: "підкреслити", r: "pidkreslyty", pos: "v", cefr: "B2", ipa: "pidˈkrɛslɪtɪ", g: ["menegaskan", "to emphasise, to underline", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Хочу підкреслити цей момент.", "Saya ingin menegaskan poin ini.", "I want to underline this point.", "Quiero subrayar este punto."] },
  { w: "попри", r: "popry", pos: "prep", cefr: "B2", ipa: "ˈpɔprɪ", g: ["meskipun ada", "despite", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Попри холод, ми вийшли.", "Meski dingin, kami keluar.", "Despite the cold we went out.", "A pesar del frío salimos."] },
  { w: "розвиток", r: "rozvytok", pos: "n", cefr: "B2", gen: "m", ipa: "ˈrɔzwɪtɔk", g: ["perkembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["Розвиток проєкту йде добре.", "Perkembangan proyeknya baik.", "The project's development is going well.", "El desarrollo del proyecto va bien."] },
  { w: "тому", r: "tomu", pos: "conj", cefr: "B2", ipa: "tɔˈmu", g: ["karena itu", "therefore", "por eso"], d: ["Menandai akibat dari pernyataan sebelumnya.", "Marks the consequence of what precedes.", "Marca la consecuencia de lo anterior."], ex: ["Йшов дощ, тому ми лишилися вдома.", "Hujan, karena itu kami di rumah.", "It rained, therefore we stayed home.", "Llovía, por eso nos quedamos en casa."] },
  { w: "угода", r: "uhoda", pos: "n", cefr: "B2", gen: "f", ipa: "uˈɦɔdɐ", g: ["kesepakatan", "agreement, deal", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Ми підписали угоду.", "Kami menandatangani kesepakatan.", "We signed an agreement.", "Firmamos un acuerdo."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "відображати", r: "vidobrazhaty", pos: "v", cefr: "C1", ipa: "widɔbrɐˈʒatɪ", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Дані відображають покращення.", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "з метою", r: "z metoiu", pos: "prep", cefr: "C1", ipa: "z mɛˈtɔju", g: ["demi, agar", "in order to", "con el fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["З метою економії часу ми спростили процес.", "Demi menghemat waktu, prosesnya kami sederhanakan.", "In order to save time we simplified the process.", "Con el fin de ahorrar tiempo simplificamos el proceso."] },
  { w: "зміцнити", r: "zmitsnyty", pos: "v", cefr: "C1", ipa: "zmit͡sˈnɪtɪ", g: ["memperkukuh", "to strengthen, to consolidate", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Компанія зміцнила свої позиції.", "Perusahaan memperkukuh posisinya.", "The company strengthened its position.", "La empresa consolidó su posición."] },
  { w: "наголосити", r: "naholosyty", pos: "v", cefr: "C1", ipa: "nɐɦɔlɔˈsɪtɪ", g: ["menekankan", "to stress, to highlight", "recalcar"], d: ["Menonjolkan bagian yang penting.", "To make an important part stand out.", "Hacer resaltar lo importante."], ex: ["Доповідач наголосив на ризиках.", "Pembicara menekankan risikonya.", "The speaker stressed the risks.", "El ponente recalcó los riesgos."] },
  { w: "нюанс", r: "niuans", pos: "n", cefr: "C1", gen: "m", ipa: "nʲuˈans", g: ["nuansa", "nuance", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["Тут є важливий нюанс.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "охоплення", r: "okhoplennia", pos: "n", cefr: "C1", gen: "nt", ipa: "ɔˈxɔplɛnʲːɐ", g: ["cakupan, jangkauan", "coverage, reach", "alcance"], d: ["Seberapa luas sesuatu menjangkau.", "How widely something reaches.", "Hasta dónde llega algo."], ex: ["Охоплення програми дуже широке.", "Cakupan programnya sangat luas.", "The programme's reach is very wide.", "El alcance del programa es amplio."] },
  { w: "підхід", r: "pidkhid", pos: "n", cefr: "C1", gen: "m", ipa: "pidˈxid", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Потрібен інший підхід.", "Kita butuh pendekatan lain.", "A different approach is needed.", "Hace falta otro enfoque."] },
  { w: "порушити", r: "porushyty", pos: "v", cefr: "C1", ipa: "pɔˈruʃɪtɪ", g: ["mengangkat (isu); melanggar", "to raise (an issue); to violate", "plantear; infringir"], d: ["Mengangkat persoalan; juga melanggar aturan.", "To raise a matter; also to break a rule.", "Plantear un asunto; también infringir."], ex: ["Він порушив важливе питання.", "Dia mengangkat persoalan penting.", "He raised an important issue.", "Planteó una cuestión importante."] },
  { w: "проте", r: "prote", pos: "conj", cefr: "C1", ipa: "prɔˈtɛ", g: ["walaupun demikian", "nonetheless, yet", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Проте пропозиція залишається чинною.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },
  { w: "ретельний", r: "retel'nyi", pos: "adj", cefr: "C1", ipa: "rɛˈtɛlʲnɪj", g: ["teliti, saksama", "thorough, meticulous", "minucioso"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest detail.", "Hecho hasta el último detalle."], ex: ["Потрібен ретельний аналіз.", "Analisis saksama diperlukan.", "A thorough analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "сприяти", r: "spryiaty", pos: "v", cefr: "C1", ipa: "sprɪˈjatɪ", g: ["mendorong, membantu", "to promote, to further", "fomentar"], d: ["Membantu sesuatu berjalan atau tumbuh.", "To help something along or grow.", "Ayudar a que algo avance."], ex: ["Закон сприяє переробці.", "Undang-undang itu mendorong daur ulang.", "The law promotes recycling.", "La ley fomenta el reciclaje."] },
  { w: "чинник", r: "chynnyk", pos: "n", cefr: "C1", gen: "m", ipa: "ˈtʃɪnːɪk", g: ["faktor", "factor", "factor"], d: ["Hal yang ikut menentukan hasil.", "Something that helps determine an outcome.", "Elemento que influye en el resultado."], ex: ["Ціна — вирішальний чинник.", "Harga adalah faktor penentu.", "Price is the decisive factor.", "El precio es el factor decisivo."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "двері", r: "dveri", pos: "n", cefr: "A1", g: ["pintu", "door", "puerta"], note: ["Selalu jamak, seperti drzwi dalam bahasa Polandia.", "Always plural, like Polish drzwi.", "Siempre plural, como el polaco drzwi."] },
  { w: "вікно", r: "vikno", pos: "n", cefr: "A1", gen: "nt", g: ["jendela", "window", "ventana"] },
  { w: "кімната", r: "kimnata", pos: "n", cefr: "A1", gen: "f", g: ["kamar, ruangan", "room", "habitación"] },
  { w: "стіл", r: "stil", pos: "n", cefr: "A1", gen: "m", g: ["meja", "table", "mesa"] },
  { w: "стілець", r: "stilets'", pos: "n", cefr: "A1", gen: "m", g: ["kursi", "chair", "silla"] },
  { w: "ліжко", r: "lizhko", pos: "n", cefr: "A1", gen: "nt", g: ["tempat tidur", "bed", "cama"] },
  { w: "кухня", r: "kukhnya", pos: "n", cefr: "A1", gen: "f", g: ["dapur", "kitchen", "cocina"] },
  { w: "ванна", r: "vanna", pos: "n", cefr: "A1", gen: "f", g: ["kamar mandi, bak mandi", "bathroom, bathtub", "baño, bañera"] },
  { w: "лампа", r: "lampa", pos: "n", cefr: "A1", gen: "f", g: ["lampu", "lamp", "lámpara"] },
  { w: "ключ", r: "klyuch", pos: "n", cefr: "A1", gen: "m", g: ["kunci", "key", "llave"] },
  { w: "стіна", r: "stina", pos: "n", cefr: "A1", gen: "f", g: ["dinding", "wall", "pared"] },
  { w: "дах", r: "dakh", pos: "n", cefr: "A1", gen: "m", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "хліб", r: "khlib", pos: "n", cefr: "A1", gen: "m", g: ["roti", "bread", "pan"] },
  { w: "рис", r: "rys", pos: "n", cefr: "A1", gen: "m", g: ["nasi, beras", "rice", "arroz"] },
  { w: "м'ясо", r: "m'yaso", pos: "n", cefr: "A1", gen: "nt", g: ["daging", "meat", "carne"] },
  { w: "риба", r: "ryba", pos: "n", cefr: "A1", gen: "f", g: ["ikan", "fish", "pescado"] },
  { w: "яйце", r: "yaytse", pos: "n", cefr: "A1", gen: "nt", g: ["telur", "egg", "huevo"] },
  { w: "молоко", r: "moloko", pos: "n", cefr: "A1", gen: "nt", g: ["susu", "milk", "leche"] },
  { w: "чай", r: "chay", pos: "n", cefr: "A1", gen: "m", g: ["teh", "tea", "té"] },
  { w: "кава", r: "kava", pos: "n", cefr: "A1", gen: "f", g: ["kopi", "coffee", "café"] },
  { w: "цукор", r: "tsukor", pos: "n", cefr: "A1", gen: "m", g: ["gula", "sugar", "azúcar"] },
  { w: "сіль", r: "sil'", pos: "n", cefr: "A1", gen: "f", g: ["garam", "salt", "sal"] },
  { w: "фрукт", r: "frukt", pos: "n", cefr: "A1", gen: "m", g: ["buah", "fruit", "fruta"] },
  { w: "овоч", r: "ovoch", pos: "n", cefr: "A1", gen: "m", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "сорочка", r: "sorochka", pos: "n", cefr: "A2", gen: "f", g: ["kemeja", "shirt", "camisa"] },
  { w: "штани", r: "shtany", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalones"] },
  { w: "взуття", r: "vzuttya", pos: "n", cefr: "A2", gen: "nt", g: ["alas kaki, sepatu", "footwear, shoes", "calzado"] },
  { w: "капелюх", r: "kapelyukh", pos: "n", cefr: "A2", gen: "m", g: ["topi", "hat", "sombrero"] },
  { w: "рука", r: "ruka", pos: "n", cefr: "A2", gen: "f", g: ["tangan, lengan", "hand, arm", "mano, brazo"] },
  { w: "око", r: "oko", pos: "n", cefr: "A2", gen: "nt", g: ["mata", "eye", "ojo"] },
  { w: "голова", r: "holova", pos: "n", cefr: "A2", gen: "f", g: ["kepala", "head", "cabeza"] },
  { w: "серце", r: "sertse", pos: "n", cefr: "A2", gen: "nt", g: ["jantung, hati", "heart", "corazón"] },
  { w: "волосся", r: "volossya", pos: "n", cefr: "A2", gen: "nt", g: ["rambut", "hair", "cabello"] },
  { w: "зуб", r: "zub", pos: "n", cefr: "A2", gen: "m", g: ["gigi", "tooth", "diente"] },
  { w: "вухо", r: "vukho", pos: "n", cefr: "A2", gen: "nt", g: ["telinga", "ear", "oreja"] },
  { w: "обличчя", r: "oblychchya", pos: "n", cefr: "A2", gen: "nt", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "дерево", r: "derevo", pos: "n", cefr: "A2", gen: "nt", g: ["pohon; kayu", "tree; wood", "árbol; madera"] },
  { w: "квітка", r: "kvitka", pos: "n", cefr: "A2", gen: "f", g: ["bunga", "flower", "flor"] },
  { w: "гора", r: "hora", pos: "n", cefr: "A2", gen: "f", g: ["gunung", "mountain", "montaña"] },
  { w: "річка", r: "richka", pos: "n", cefr: "A2", gen: "f", g: ["sungai", "river", "río"] },
  { w: "море", r: "more", pos: "n", cefr: "A2", gen: "nt", g: ["laut", "sea", "mar"] },
  { w: "небо", r: "nebo", pos: "n", cefr: "A2", gen: "nt", g: ["langit", "sky", "cielo"] },
  { w: "зірка", r: "zirka", pos: "n", cefr: "A2", gen: "f", g: ["bintang", "star", "estrella"] },
  { w: "собака", r: "sobaka", pos: "n", cefr: "A2", gen: "m", g: ["anjing", "dog", "perro"] },
  { w: "кіт", r: "kit", pos: "n", cefr: "A2", gen: "m", g: ["kucing", "cat", "gato"] },
  { w: "птах", r: "ptakh", pos: "n", cefr: "A2", gen: "m", g: ["burung", "bird", "pájaro"] },
  { w: "кінь", r: "kin'", pos: "n", cefr: "A2", gen: "m", g: ["kuda", "horse", "caballo"] },
  { w: "дощ", r: "doshch", pos: "n", cefr: "A2", gen: "m", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "вулиця", r: "vulytsya", pos: "n", cefr: "B1", gen: "f", g: ["jalan", "street", "calle"] },
  { w: "міст", r: "mist", pos: "n", cefr: "B1", gen: "m", g: ["jembatan", "bridge", "puente"] },
  { w: "ринок", r: "rynok", pos: "n", cefr: "B1", gen: "m", g: ["pasar", "market", "mercado"] },
  { w: "школа", r: "shkola", pos: "n", cefr: "B1", gen: "f", g: ["sekolah", "school", "escuela"] },
  { w: "лікарня", r: "likarnya", pos: "n", cefr: "B1", gen: "f", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "офіс", r: "ofis", pos: "n", cefr: "B1", gen: "m", g: ["kantor", "office", "oficina"] },
  { w: "автобус", r: "avtobus", pos: "n", cefr: "B1", gen: "m", g: ["bus", "bus", "autobús"] },
  { w: "потяг", r: "potyah", pos: "n", cefr: "B1", gen: "m", g: ["kereta api", "train", "tren"] },
  { w: "автомобіль", r: "avtomobil'", pos: "n", cefr: "B1", gen: "m", g: ["mobil", "car", "coche"] },
  { w: "велосипед", r: "velosyped", pos: "n", cefr: "B1", gen: "m", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "аеропорт", r: "aeroport", pos: "n", cefr: "B1", gen: "m", g: ["bandara", "airport", "aeropuerto"] },
  { w: "квиток", r: "kvytok", pos: "n", cefr: "B1", gen: "m", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "компанія", r: "kompaniya", pos: "n", cefr: "B2", gen: "f", g: ["perusahaan", "company", "empresa"] },
  { w: "зустріч", r: "zustrich", pos: "n", cefr: "B2", gen: "f", g: ["pertemuan, rapat", "meeting", "reunión"] },
  { w: "договір", r: "dohovir", pos: "n", cefr: "B2", gen: "m", g: ["kontrak, perjanjian", "contract", "contrato"] },
  { w: "зарплата", r: "zarplata", pos: "n", cefr: "B2", gen: "f", g: ["gaji", "salary", "sueldo"] },
  { w: "ціна", r: "tsina", pos: "n", cefr: "B2", gen: "f", g: ["harga", "price", "precio"] },
  { w: "податок", r: "podatok", pos: "n", cefr: "B2", gen: "m", g: ["pajak", "tax", "impuesto"] },
  { w: "банк", r: "bank", pos: "n", cefr: "B2", gen: "m", g: ["bank", "bank", "banco"] },
  { w: "комп'ютер", r: "komp'yuter", pos: "n", cefr: "B2", gen: "m", g: ["komputer", "computer", "ordenador"] },
  { w: "телефон", r: "telefon", pos: "n", cefr: "B2", gen: "m", g: ["telepon", "telephone", "teléfono"] },
  { w: "пошта", r: "poshta", pos: "n", cefr: "B2", gen: "f", g: ["pos; surel", "post; mail", "correo"] },
  { w: "файл", r: "fayl", pos: "n", cefr: "B2", gen: "m", g: ["berkas", "file", "archivo"] },
  { w: "пароль", r: "parol'", pos: "n", cefr: "B2", gen: "m", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "віха", r: "vikha", pos: "n", cefr: "C2", gen: "f", ipa: "ˈwixɐ", g: ["tonggak", "milestone, landmark", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Угода стала важливою віхою.", "Kesepakatan itu menjadi tonggak penting.", "The agreement became an important milestone.", "El acuerdo fue un hito importante."] },
  { w: "застереження", r: "zasterezhennia", pos: "n", cefr: "C2", gen: "nt", ipa: "zɐstɛˈrɛʒɛnʲːɐ", g: ["peringatan pembatas", "caveat, warning", "salvedad"], d: ["Catatan yang membatasi berlakunya pernyataan.", "A warning that limits how far a statement holds.", "Advertencia que limita el alcance de algo."], ex: ["Погоджуюсь, але з одним застереженням.", "Saya setuju, dengan satu catatan.", "I agree, with one caveat.", "Estoy de acuerdo, con una salvedad."] },
  { w: "невимовний", r: "nevymovnyi", pos: "adj", cefr: "C2", ipa: "nɛwɪˈmɔwnɪj", g: ["tak terlukiskan", "ineffable, inexpressible", "inefable"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Невимовна радість.", "Sukacita yang tak terlukiskan.", "An ineffable joy.", "Una alegría inefable."] },
  { w: "невідкладний", r: "nevidkladnyi", pos: "adj", cefr: "C2", ipa: "nɛwidˈklɑdnɪj", g: ["mendesak, tak bisa ditunda", "urgent, brooking no delay", "inaplazable"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["Це невідкладне питання.", "Ini persoalan mendesak.", "This is an urgent matter.", "Es un asunto inaplazable."] },
  { w: "неминучий", r: "nemynuchyi", pos: "adj", cefr: "C2", ipa: "nɛmɪˈnutʃɪj", g: ["tak terhindarkan", "inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Зростання цін неминуче.", "Kenaikan harga tak terhindarkan.", "A price rise is inevitable.", "La subida de precios es inevitable."] },
  { w: "парадигма", r: "paradyhma", pos: "n", cefr: "C2", gen: "f", ipa: "pɐrɐˈdɪɦmɐ", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Це була зміна парадигми.", "Itu pergeseran paradigma.", "It was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "применшувати", r: "prymenshuvaty", pos: "v", cefr: "C2", ipa: "prɪˈmɛnʃuwɐtɪ", g: ["merendahkan, mengecilkan", "to belittle, to downplay", "menoscabar"], d: ["Membuat nilai sesuatu tampak lebih kecil.", "To make something seem less valuable.", "Hacer que algo parezca menor."], ex: ["Не хочу применшувати його заслуги.", "Saya tak ingin mengecilkan jasanya.", "I don't want to downplay his merits.", "No quiero menoscabar sus méritos."] },
  { w: "проблиск", r: "problysk", pos: "n", cefr: "C2", gen: "m", ipa: "ˈprɔblɪsk", g: ["secercah", "glimmer, gleam", "destello"], d: ["Cahaya lemah; kiasan untuk tanda kecil harapan.", "A faint light; figuratively a small sign of hope.", "Luz tenue; indicio de esperanza."], ex: ["Є проблиск надії.", "Ada secercah harapan.", "There's a glimmer of hope.", "Hay un destello de esperanza."] },
  { w: "у світлі", r: "u svitli", pos: "prep", cefr: "C2", ipa: "u ˈswitli", g: ["berdasarkan, mengingat", "in the light of", "a la luz de"], d: ["Menilai kembali sesuatu berdasarkan fakta baru.", "Re-judging something given new facts.", "Reevaluar algo con nuevos datos."], ex: ["У світлі нових даних це успіх.", "Berdasarkan data baru, ini sukses.", "In the light of the new data it's a success.", "A la luz de los nuevos datos, es un éxito."] },
  { w: "упередженість", r: "uperedzhenist'", pos: "n", cefr: "C2", gen: "f", ipa: "upɛˈrɛdʒɛnistʲ", g: ["prasangka, bias", "bias, prejudice", "sesgo"], d: ["Kecenderungan menilai secara tidak berimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["У дослідженні є упередженість.", "Kajian itu mengandung bias.", "The study contains a bias.", "El estudio tiene un sesgo."] },
  { w: "ухилятися", r: "ukhyliatysia", pos: "v", cefr: "C2", ipa: "uxɪˈlʲatɪsʲɐ", g: ["mengelak", "to evade, to dodge", "eludir"], d: ["Menghindari kewajiban atau pertanyaan.", "To avoid a duty or a question.", "Evitar un deber o una pregunta."], ex: ["Він ухилився від відповіді.", "Dia mengelak dari jawaban.", "He dodged the answer.", "Eludió la respuesta."] },
  { w: "з'ясувати", r: "ziasuvaty", pos: "v", cefr: "C2", ipa: "zjɐsuˈwatɪ", g: ["menjernihkan, memastikan", "to clarify, to find out", "esclarecer"], d: ["Mencari tahu sampai persoalannya terang.", "To find out until the matter is clear.", "Averiguar hasta aclarar el asunto."], ex: ["Треба з'ясувати деталі.", "Rinciannya perlu dipastikan.", "The details need clarifying.", "Hay que esclarecer los detalles."] },
];
