/* =========================================================================
   lexicon/vi.js — Từ điển: Tiếng Việt. Front matter + 72 headwords, A1→C2.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Vietnam ditulis dengan abjad Latin (quốc ngữ) sejak abad ke-17, lengkap dengan tanda nada. Kata-katanya tidak pernah berubah bentuk — yang menentukan arti adalah nada dan urutan kata.",
    "Vietnamese has used the Latin alphabet (quốc ngữ) since the 17th century, complete with tone marks. Words never change shape; tone and word order carry the meaning.",
    "El vietnamita usa el alfabeto latino (quốc ngữ) desde el siglo XVII, con marcas tonales. Las palabras no cambian de forma: el tono y el orden dan el sentido.",
  ],
  script: [
    "29 huruf ditambah lima tanda nada. Nada bukan hiasan: ma, má, mà, mả, mã, mạ adalah enam kata yang berbeda.",
    "29 letters plus five tone marks. Tone is not decoration: ma, má, mà, mả, mã, mạ are six different words.",
    "29 letras más cinco marcas tonales. El tono no es adorno: ma, má, mà, mả, mã, mạ son seis palabras distintas.",
  ],
  pron: [
    ["6 nada", "ngang (datar), sắc (naik), huyền (turun), hỏi (turun-naik), ngã (patah), nặng (berat).", "ngang (level), sắc (rising), huyền (falling), hỏi (dipping), ngã (broken), nặng (heavy).", "ngang (llano), sắc (ascendente), huyền (descendente), hỏi, ngã y nặng."],
    ["đ vs d", "đ dibaca /d/; d tanpa palang dibaca /z/ di utara dan /j/ di selatan.", "đ is /d/; plain d is /z/ in the north and /j/ in the south.", "đ es /d/; la d sin trazo es /z/ en el norte y /j/ en el sur."],
    ["ng- di awal", "Bisa berdiri di awal kata: người, nghe.", "It can begin a word: người, nghe.", "Puede iniciar palabra: người, nghe."],
    ["ơ / ư", "Vokal khas tanpa padanan Latin lain: cơm, thư.", "Distinctive vowels with no Latin equivalent: cơm, thư.", "Vocales propias sin equivalente latino: cơm, thư."],
    ["konsonan akhir", "Tidak dilepas: bát, sách — bibir/lidah berhenti tanpa hembusan.", "Final consonants are unreleased: bát, sách.", "Las consonantes finales no se sueltan: bát, sách."],
    ["tr / ch", "Dibedakan di selatan (tr retrofleks), sering menyatu di utara.", "Distinguished in the south (retroflex tr), often merged in the north.", "Se distinguen en el sur; en el norte suelen fundirse."],
  ],
  grammar: [
    {
      t: ["Kata tak pernah berubah", "Words never inflect", "Las palabras no se flexionan"],
      d: ["Tidak ada konjugasi, jamak, atau kasus. Waktu dinyatakan dengan đã, đang, sẽ.", "No conjugation, no plurals, no cases. Time is carried by đã, đang, sẽ.", "Sin conjugación, plural ni casos. El tiempo lo marcan đã, đang, sẽ."],
      ex: "tôi ăn · tôi đã ăn · tôi sẽ ăn",
    },
    {
      t: ["Kata sifat mengikuti benda", "Adjectives follow the noun", "El adjetivo sigue al sustantivo"],
      d: ["Berbeda dengan bahasa Inggris, penjelas selalu datang sesudah kata bendanya.", "Unlike English, modifiers always come after the noun.", "A diferencia del inglés, el modificador va detrás."],
      ex: "nhà lớn (rumah besar) · áo đỏ (baju merah)",
    },
    {
      t: ["Kata penggolong", "Classifiers", "Clasificadores"],
      d: ["Benda dihitung dengan penggolong: con (bernyawa), cái (benda), quyển (buku).", "Nouns are counted with classifiers: con (animate), cái (thing), quyển (book).", "Los sustantivos se cuentan con clasificadores: con, cái, quyển."],
      ex: "hai con mèo · ba cái bàn",
    },
    {
      t: ["Kata sapaan menggantikan 'saya/kamu'", "Kinship terms replace pronouns", "Los términos de parentesco sustituyen pronombres"],
      d: ["Orang menyebut diri dan lawan bicara menurut usia: anh, chị, em, cô, chú.", "Speakers name themselves and each other by relative age: anh, chị, em, cô, chú.", "Se nombran según la edad relativa: anh, chị, em, cô, chú."],
      ex: "Em cảm ơn anh. (yang lebih muda → yang lebih tua)",
    },
    {
      t: ["Pertanyaan dengan không", "Yes-no questions with không", "Preguntas con không"],
      d: ["Kalimat tanya dibentuk dengan pola có … không.", "A yes-no question uses the frame có … không.", "La pregunta cerrada usa el marco có … không."],
      ex: "Bạn có khỏe không?",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "bạn", pos: "n", cefr: "A1", ipa: "ɓaːn˧˨", g: ["teman; kamu", "friend; you", "amigo; tú"], d: ["Teman; juga kata sapaan netral untuk 'kamu'.", "A friend; also the neutral word for 'you'.", "Amigo; también el 'tú' neutro."], ex: ["Tôi đi chơi với bạn.", "Saya pergi bermain dengan teman.", "I'm going out with a friend.", "Salgo con un amigo."] },
  { w: "có", pos: "v", cefr: "A1", ipa: "kɔ˧˥", g: ["ada, punya", "to have; there is", "tener; haber"], d: ["Menyatakan kepemilikan atau keberadaan.", "States possession or existence.", "Indica posesión o existencia."], ex: ["Tôi có hai chị gái.", "Saya punya dua kakak perempuan.", "I have two older sisters.", "Tengo dos hermanas mayores."] },
  { w: "đêm", pos: "n", cefr: "A1", ipa: "ɗem˧˧", g: ["malam", "night", "noche"], d: ["Waktu gelap antara petang dan pagi.", "The dark hours between evening and morning.", "Horas oscuras entre la tarde y la mañana."], ex: ["Chúc ngủ ngon!", "Selamat tidur!", "Good night!", "¡Buenas noches!"], ant: ["ngày"] },
  { w: "đi", pos: "v", cefr: "A1", ipa: "ɗi˧˧", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["Tôi đi chợ.", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."] },
  { w: "đàn ông", pos: "n", cefr: "A1", ipa: "ɗaːn˧˨ ʔoŋ˧˧", g: ["laki-laki", "man", "hombre"], d: ["Manusia dewasa laki-laki.", "An adult male human being.", "Ser humano adulto masculino."], ex: ["Người đàn ông đó là hàng xóm của tôi.", "Laki-laki itu tetangga saya.", "That man is my neighbour.", "Ese hombre es mi vecino."], ant: ["phụ nữ"] },
  { w: "lớn", pos: "adj", cefr: "A1", ipa: "lɤn˧˥", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["Họ sống ở thành phố lớn.", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["nhỏ"] },
  { w: "muốn", pos: "v", cefr: "A1", ipa: "muən˧˥", g: ["mau, ingin", "to want", "querer"], d: ["Menginginkan sesuatu.", "To want something.", "Desear algo."], ex: ["Tôi muốn học tiếng Việt.", "Saya mau belajar bahasa Vietnam.", "I want to learn Vietnamese.", "Quiero aprender vietnamita."] },
  { w: "ngày", pos: "n", cefr: "A1", ipa: "ŋaj˧˨", g: ["hari", "day", "día"], d: ["Waktu 24 jam; juga masa terang.", "A period of 24 hours; also daylight.", "Periodo de 24 horas; también la luz del día."], ex: ["Tôi làm việc mỗi ngày.", "Saya bekerja setiap hari.", "I work every day.", "Trabajo todos los días."], ant: ["đêm"] },
  { w: "nhà", pos: "n", cefr: "A1", ipa: "ɲaː˧˨", g: ["rumah", "house, home", "casa"], d: ["Bangunan tempat orang tinggal.", "A building where people live.", "Edificio donde vive la gente."], ex: ["Nhà tôi gần công viên.", "Rumah saya dekat taman.", "My house is near the park.", "Mi casa está cerca del parque."] },
  { w: "nhỏ", pos: "adj", cefr: "A1", ipa: "ɲɔ˧˩", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["Tôi có một căn hộ nhỏ.", "Saya punya apartemen kecil.", "I have a small flat.", "Tengo un piso pequeño."], ant: ["lớn"] },
  { w: "phụ nữ", pos: "n", cefr: "A1", ipa: "fu˧˨ nɨ˧˨", g: ["perempuan", "woman", "mujer"], d: ["Manusia dewasa perempuan.", "An adult female human being.", "Ser humano adulto femenino."], ex: ["Người phụ nữ đội mũ là cô tôi.", "Perempuan bertopi itu bibi saya.", "The woman in the hat is my aunt.", "La mujer del sombrero es mi tía."], ant: ["đàn ông"] },
  { w: "tốt", pos: "adj", cefr: "A1", ipa: "tot˧˥", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["Đó là một ý tưởng tốt.", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["xấu"] },

  /* ------------------------------------------------------------------ A2 */
  { w: "bắt đầu", pos: "v", cefr: "A2", ipa: "ɓat˧˥ ɗɜw˧˨", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["Phim bắt đầu lúc tám giờ.", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["kết thúc"] },
  { w: "cần", pos: "v", cefr: "A2", ipa: "kɜn˧˨", g: ["butuh, perlu", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["Tôi cần nghỉ ngơi.", "Saya perlu istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "công việc", pos: "n", cefr: "A2", ipa: "koŋ˧˧ viək˧ˀ˨", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["Công việc của tôi bắt đầu lúc chín giờ.", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "dễ", pos: "adj", cefr: "A2", ipa: "ze˧ˀ˥", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["Bài kiểm tra rất dễ.", "Ujiannya sangat mudah.", "The test was very easy.", "El examen fue muy fácil."], ant: ["khó"] },
  { w: "giúp", pos: "v", cefr: "A2", ipa: "zup˧˥", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["Bạn giúp tôi được không?", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "khó", pos: "adj", cefr: "A2", ipa: "xɔ˧˥", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["Đỗ xe ở đây rất khó.", "Parkir di sini sangat sulit.", "Parking here is very hard.", "Aparcar aquí es muy difícil."], ant: ["dễ"] },
  { w: "luôn luôn", pos: "adv", cefr: "A2", ipa: "luən˧˧ luən˧˧", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["Tôi luôn luôn ăn sáng ở nhà.", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },
  { w: "nhanh", pos: "adj", cefr: "A2", ipa: "ɲaɲ˧˧", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["Tàu hỏa nhanh hơn.", "Keretanya lebih cepat.", "The train is faster.", "El tren es más rápido."], ant: ["chậm"] },
  { w: "thành phố", pos: "n", cefr: "A2", ipa: "tʰaɲ˧˨ fo˧˥", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["Đà Nẵng là thành phố đẹp.", "Đà Nẵng kota yang indah.", "Đà Nẵng is a beautiful city.", "Đà Nẵng es una ciudad bonita."] },
  { w: "thời gian", pos: "n", cefr: "A2", ipa: "tʰɤj˧˨ zaːn˧˧", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["Hôm nay tôi không có thời gian.", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "tiền", pos: "n", cefr: "A2", ipa: "tiən˧˨", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["Tôi không đủ tiền.", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "vì", pos: "conj", cefr: "A2", ipa: "vi˧˨", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["Tôi ở nhà vì trời mưa.", "Saya di rumah karena hujan.", "I'm home because it's raining.", "Estoy en casa porque llueve."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "cải thiện", pos: "v", cefr: "B1", ipa: "kaːj˧˩ tʰiən˧ˀ˨", g: ["memperbaiki", "to improve", "mejorar"], d: ["Menjadikan sesuatu lebih baik.", "To make something better.", "Hacer mejor algo."], ex: ["Tôi muốn cải thiện phát âm.", "Saya ingin memperbaiki pelafalan.", "I want to improve my pronunciation.", "Quiero mejorar la pronunciación."] },
  { w: "có lẽ", pos: "adv", cefr: "B1", ipa: "kɔ˧˥ lɛ˧˩", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["Có lẽ ngày mai anh ấy đến.", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },
  { w: "có vẻ", pos: "v", cefr: "B1", ipa: "kɔ˧˥ vɛ˧˩", g: ["tampaknya", "to seem", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["Anh ấy có vẻ mệt.", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "cơ hội", pos: "n", cefr: "B1", ipa: "kɤ˧˧ hoj˧ˀ˨", g: ["kesempatan", "opportunity", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["Đây là cơ hội tốt.", "Ini kesempatan bagus.", "This is a good opportunity.", "Es una buena oportunidad."] },
  { w: "kinh nghiệm", pos: "n", cefr: "B1", ipa: "kiɲ˧˧ ŋiəm˧ˀ˨", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["Cô ấy có nhiều kinh nghiệm.", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "lời khuyên", pos: "n", cefr: "B1", ipa: "lɤj˧˨ xuiən˧˧", g: ["nasihat", "advice", "consejo"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["Cho tôi một lời khuyên nhé?", "Beri saya nasihat, ya?", "Give me some advice, will you?", "Dame un consejo, ¿vale?"] },
  { w: "mặc dù", pos: "conj", cefr: "B1", ipa: "mak˧ˀ˨ zu˧˨", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras dengan bagian kalimat lain.", "Marks a contrast with the rest of the sentence.", "Marca contraste con el resto."], ex: ["Mặc dù trời mưa, chúng tôi vẫn đi.", "Meskipun hujan, kami tetap pergi.", "Although it's raining, we're still going.", "Aunque llueve, iremos igual."] },
  { w: "nhớ", pos: "v", cefr: "B1", ipa: "ɲɤ˧˥", g: ["ingat; rindu", "to remember; to miss", "recordar; echar de menos"], d: ["Menyimpan dalam ingatan; juga merindukan.", "To keep in mind; also to miss someone.", "Recordar; también echar de menos."], ex: ["Tôi nhớ gia đình tôi.", "Saya rindu keluarga saya.", "I miss my family.", "Echo de menos a mi familia."], note: ["Satu kata untuk 'ingat' dan 'rindu' — konteks yang membedakan.", "One word for both 'remember' and 'miss' — context decides.", "Una palabra para 'recordar' y 'añorar'; el contexto decide."] },
  { w: "quen", pos: "v", cefr: "B1", ipa: "kwɛn˧˧", g: ["terbiasa; kenal", "to be used to; to be acquainted", "acostumbrarse; conocer"], d: ["Sudah terbiasa; juga sudah saling kenal.", "To be accustomed; also to be acquainted.", "Estar habituado; también conocerse."], ex: ["Tôi đã quen với thời tiết ở đây.", "Saya sudah terbiasa dengan cuaca di sini.", "I've got used to the weather here.", "Ya me acostumbré al clima de aquí."] },
  { w: "quyết định", pos: "n", cefr: "B1", ipa: "kwiət˧˥ ɗiɲ˧ˀ˨", g: ["keputusan", "decision", "decisión"], d: ["Pilihan yang sudah ditetapkan.", "A choice that has been settled.", "Elección ya tomada."], ex: ["Đó là một quyết định khó khăn.", "Itu keputusan yang sulit.", "That was a hard decision.", "Fue una decisión difícil."] },
  { w: "thành công", pos: "v", cefr: "B1", ipa: "tʰaɲ˧˨ koŋ˧˧", g: ["berhasil, sukses", "to succeed; success", "tener éxito"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["Cô ấy đã thành công.", "Dia berhasil.", "She succeeded.", "Ella tuvo éxito."] },
  { w: "tuy nhiên", pos: "conj", cefr: "B1", ipa: "twi˧˧ ɲiən˧˧", g: ["namun begitu", "however", "sin embargo"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["Đắt; tuy nhiên rất đáng.", "Mahal; namun begitu sepadan.", "It's expensive; however, it's worth it.", "Es caro; sin embargo, vale la pena."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "bất chấp", pos: "prep", cefr: "B2", ipa: "ɓɜt˧˥ cɜp˧˥", g: ["meskipun ada", "despite, in defiance of", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["Bất chấp giá lạnh, chúng tôi vẫn ra ngoài.", "Meski dingin, kami tetap keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "đáng tin cậy", pos: "adj", cefr: "B2", ipa: "ɗaːŋ˧˥ tin˧˧ kɜj˧ˀ˨", g: ["dapat diandalkan", "reliable, trustworthy", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["Đây là nguồn đáng tin cậy.", "Ini sumber tepercaya.", "This is a reliable source.", "Es una fuente fiable."] },
  { w: "đạt được", pos: "v", cefr: "B2", ipa: "ɗaːt˧ˀ˨ ɗɨək˧ˀ˨", g: ["mencapai", "to achieve, to attain", "alcanzar"], d: ["Sampai pada tujuan setelah berusaha.", "To reach a goal after effort.", "Alcanzar una meta tras esfuerzo."], ex: ["Chúng tôi đã đạt được mục tiêu.", "Kami mencapai targetnya.", "We reached the target.", "Alcanzamos el objetivo."] },
  { w: "do đó", pos: "conj", cefr: "B2", ipa: "zɔ˧˧ ɗɔ˧˥", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai akibat logis.", "Marks a logical consequence.", "Marca la consecuencia lógica."], ex: ["Trời mưa; do đó chúng tôi hủy.", "Hujan; oleh karena itu kami batalkan.", "It rained; therefore we cancelled.", "Llovió; por lo tanto cancelamos."] },
  { w: "môi trường", pos: "n", cefr: "B2", ipa: "moj˧˧ tʂɨəŋ˧˨", g: ["lingkungan hidup", "the environment", "medio ambiente"], d: ["Alam sekitar; juga suasana tempat kerja.", "The natural surroundings; also a work setting.", "Entorno natural; también ambiente laboral."], ex: ["Chúng ta phải bảo vệ môi trường.", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "nhấn mạnh", pos: "v", cefr: "B2", ipa: "ɲɜn˧˥ maɲ˧ˀ˨", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["Ông ấy nhấn mạnh vấn đề an toàn.", "Dia menekankan soal keselamatan.", "He emphasised safety.", "Subrayó la seguridad."] },
  { w: "phát triển", pos: "v", cefr: "B2", ipa: "faːt˧˥ ʈiən˧˩", g: ["berkembang, mengembangkan", "to develop", "desarrollar"], d: ["Tumbuh atau menjadikan lebih maju.", "To grow or make more advanced.", "Crecer o hacer avanzar."], ex: ["Dự án đang phát triển tốt.", "Proyeknya berkembang baik.", "The project is developing well.", "El proyecto se desarrolla bien."] },
  { w: "thách thức", pos: "n", cefr: "B2", ipa: "tʰaːc˧˥ tʰɨk˧˥", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["Đây là một thách thức lớn.", "Ini tantangan besar.", "This is a big challenge.", "Es un gran desafío."] },
  { w: "thỏa thuận", pos: "n", cefr: "B2", ipa: "tʰwaː˧˩ tʰwɜn˧ˀ˨", g: ["kesepakatan", "agreement", "acuerdo"], d: ["Keputusan bersama yang disetujui pihak-pihak.", "A decision the sides accept.", "Decisión aceptada por las partes."], ex: ["Hai bên đã ký thỏa thuận.", "Kedua pihak menandatangani kesepakatan.", "The two sides signed an agreement.", "Ambas partes firmaron el acuerdo."] },
  { w: "triển khai", pos: "v", cefr: "B2", ipa: "ʈiən˧˩ xaːj˧˧", g: ["menerapkan, menggelar", "to deploy, to implement", "desplegar"], d: ["Menjalankan rencana secara luas.", "To roll a plan out in practice.", "Poner un plan en marcha."], ex: ["Chúng tôi sẽ triển khai hệ thống mới.", "Kami akan menerapkan sistem baru.", "We'll deploy the new system.", "Desplegaremos el nuevo sistema."] },
  { w: "vấn đề", pos: "n", cefr: "B2", ipa: "vɜn˧˥ ɗe˧˨", g: ["masalah, persoalan", "problem, issue", "problema"], d: ["Hal yang menyulitkan atau sedang dibahas.", "Something difficult, or the matter at hand.", "Algo difícil o el asunto tratado."], ex: ["Đây là vấn đề nhạy cảm.", "Ini persoalan yang sensitif.", "It's a sensitive issue.", "Es un asunto delicado."] },
  { w: "cần thiết", pos: "adj", cefr: "B2", ipa: "kɜn˧˨ tʰiət˧˥", g: ["diperlukan, penting", "necessary, essential", "necesario"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["Hộ chiếu là cần thiết.", "Paspor itu diperlukan.", "A passport is necessary.", "El pasaporte es necesario."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "cách tiếp cận", pos: "n", cefr: "C1", ipa: "kaːc˧˥ tiəp˧˥ kɜn˧ˀ˨", g: ["pendekatan", "approach", "enfoque"], d: ["Cara memandang dan menangani masalah.", "The way a problem is approached.", "Manera de abordar un problema."], ex: ["Chúng ta cần cách tiếp cận khác.", "Kita butuh pendekatan lain.", "We need a different approach.", "Necesitamos otro enfoque."] },
  { w: "củng cố", pos: "v", cefr: "C1", ipa: "kuŋ˧˩ ko˧˥", g: ["memperkukuh", "to consolidate, to reinforce", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["Công ty đã củng cố vị thế.", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "giải quyết", pos: "v", cefr: "C1", ipa: "zaːj˧˩ kwiət˧˥", g: ["menyelesaikan", "to resolve, to settle", "resolver"], d: ["Menemukan jalan keluar dari masalah.", "To find a way out of a problem.", "Encontrar salida a un problema."], ex: ["Chúng tôi đã giải quyết xong vấn đề.", "Kami sudah menyelesaikan masalahnya.", "We've resolved the problem.", "Resolvimos el problema."] },
  { w: "kỹ lưỡng", pos: "adj", cefr: "C1", ipa: "ki˧ˀ˥ lɨəŋ˧ˀ˨", g: ["teliti, saksama", "thorough, meticulous", "minucioso"], d: ["Dikerjakan sampai ke bagian terkecil.", "Done down to the smallest detail.", "Hecho hasta el último detalle."], ex: ["Cần một phân tích kỹ lưỡng.", "Diperlukan analisis yang saksama.", "A thorough analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "làm nổi bật", pos: "v", cefr: "C1", ipa: "laːm˧˨ noj˧˩ ɓɜt˧ˀ˨", g: ["menonjolkan", "to highlight", "destacar"], d: ["Membuat sesuatu tampak lebih menonjol.", "To make something stand out.", "Hacer que algo resalte."], ex: ["Báo cáo làm nổi bật các rủi ro.", "Laporan itu menonjolkan risikonya.", "The report highlights the risks.", "El informe destaca los riesgos."] },
  { w: "lĩnh vực", pos: "n", cefr: "C1", ipa: "liɲ˧ˀ˥ vɨk˧ˀ˨", g: ["bidang", "field, domain", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["Trong lĩnh vực pháp lý thì khác.", "Dalam bidang hukum hal itu berbeda.", "In the legal field it's different.", "En el ámbito jurídico es distinto."] },
  { w: "nhằm", pos: "conj", cefr: "C1", ipa: "ɲam˧˨", g: ["agar, demi", "in order to, aiming at", "a fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["Chúng tôi đơn giản hóa quy trình nhằm tiết kiệm thời gian.", "Kami menyederhanakan proses agar hemat waktu.", "We simplified the process in order to save time.", "Simplificamos el proceso a fin de ahorrar tiempo."] },
  { w: "phạm vi", pos: "n", cefr: "C1", ipa: "faːm˧ˀ˨ vi˧˧", g: ["cakupan, jangkauan", "scope, range", "alcance"], d: ["Seberapa luas sesuatu menjangkau.", "How widely something reaches.", "Hasta dónde llega algo."], ex: ["Phạm vi của quyết định rất rộng.", "Cakupan keputusannya sangat luas.", "The decision's scope is very wide.", "El alcance de la decisión es amplio."] },
  { w: "phản ánh", pos: "v", cefr: "C1", ipa: "faːn˧˩ ʔaɲ˧˥", g: ["mencerminkan", "to reflect, to mirror", "reflejar"], d: ["Menunjukkan keadaan lain secara setia.", "To show another state faithfully.", "Mostrar fielmente otra realidad."], ex: ["Số liệu phản ánh sự cải thiện.", "Datanya mencerminkan perbaikan.", "The figures reflect an improvement.", "Las cifras reflejan una mejora."] },
  { w: "sắc thái", pos: "n", cefr: "C1", ipa: "sak˧˥ tʰaːj˧˥", g: ["nuansa", "nuance, shade", "matiz"], d: ["Perbedaan halus dalam makna atau warna.", "A subtle difference in meaning or colour.", "Diferencia sutil de sentido o color."], ex: ["Có một sắc thái quan trọng ở đây.", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "thúc đẩy", pos: "v", cefr: "C1", ipa: "tʰuk˧˥ ɗɜj˧˩", g: ["mendorong", "to promote, to drive", "impulsar"], d: ["Membantu sesuatu maju lebih cepat.", "To help something move forward faster.", "Ayudar a que algo avance más rápido."], ex: ["Luật này thúc đẩy tái chế.", "Undang-undang ini mendorong daur ulang.", "This law promotes recycling.", "Esta ley impulsa el reciclaje."] },
  { w: "tuy vậy", pos: "conj", cefr: "C1", ipa: "twi˧˧ vɜj˧ˀ˨", g: ["walaupun demikian", "nonetheless", "no obstante"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["Tuy vậy, đề xuất vẫn còn hiệu lực.", "Walaupun demikian, usulan itu tetap berlaku.", "Nonetheless, the proposal stands.", "No obstante, la propuesta sigue vigente."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "cửa", pos: "n", cefr: "A1", g: ["pintu", "door", "puerta"] },
  { w: "cửa sổ", pos: "n", cefr: "A1", g: ["jendela", "window", "ventana"] },
  { w: "phòng", pos: "n", cefr: "A1", g: ["kamar, ruangan", "room", "habitación"] },
  { w: "bàn", pos: "n", cefr: "A1", g: ["meja", "table", "mesa"] },
  { w: "ghế", pos: "n", cefr: "A1", g: ["kursi", "chair", "silla"] },
  { w: "giường", pos: "n", cefr: "A1", g: ["tempat tidur", "bed", "cama"] },
  { w: "bếp", pos: "n", cefr: "A1", g: ["dapur", "kitchen", "cocina"] },
  { w: "nhà tắm", pos: "n", cefr: "A1", g: ["kamar mandi", "bathroom", "cuarto de baño"] },
  { w: "đèn", pos: "n", cefr: "A1", g: ["lampu", "lamp", "lámpara"] },
  { w: "chìa khóa", pos: "n", cefr: "A1", g: ["kunci", "key", "llave"] },
  { w: "tường", pos: "n", cefr: "A1", g: ["dinding", "wall", "pared"] },
  { w: "mái nhà", pos: "n", cefr: "A1", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "bánh mì", pos: "n", cefr: "A1", g: ["roti", "bread", "pan"] },
  { w: "cơm", pos: "n", cefr: "A1", g: ["nasi", "cooked rice", "arroz cocido"] },
  { w: "thịt", pos: "n", cefr: "A1", g: ["daging", "meat", "carne"] },
  { w: "cá", pos: "n", cefr: "A1", g: ["ikan", "fish", "pescado"] },
  { w: "trứng", pos: "n", cefr: "A1", g: ["telur", "egg", "huevo"] },
  { w: "sữa", pos: "n", cefr: "A1", g: ["susu", "milk", "leche"] },
  { w: "trà", pos: "n", cefr: "A1", g: ["teh", "tea", "té"] },
  { w: "cà phê", pos: "n", cefr: "A1", g: ["kopi", "coffee", "café"] },
  { w: "đường", pos: "n", cefr: "A1", g: ["gula; jalan", "sugar; road", "azúcar; camino"], note: ["Satu kata, dua arti yang jauh — konteks yang membedakan.", "One word, two very different senses; context decides.", "Una palabra, dos sentidos muy distintos."] },
  { w: "muối", pos: "n", cefr: "A1", g: ["garam", "salt", "sal"] },
  { w: "trái cây", pos: "n", cefr: "A1", g: ["buah", "fruit", "fruta"] },
  { w: "rau", pos: "n", cefr: "A1", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "áo sơ mi", pos: "n", cefr: "A2", g: ["kemeja", "shirt", "camisa"] },
  { w: "quần", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalón"] },
  { w: "giày", pos: "n", cefr: "A2", g: ["sepatu", "shoe", "zapato"] },
  { w: "mũ", pos: "n", cefr: "A2", g: ["topi", "hat", "sombrero"] },
  { w: "tay", pos: "n", cefr: "A2", g: ["tangan", "hand, arm", "mano"] },
  { w: "mắt", pos: "n", cefr: "A2", g: ["mata", "eye", "ojo"] },
  { w: "đầu", pos: "n", cefr: "A2", g: ["kepala; awal", "head; beginning", "cabeza; principio"] },
  { w: "tim", pos: "n", cefr: "A2", g: ["jantung", "heart", "corazón"] },
  { w: "tóc", pos: "n", cefr: "A2", g: ["rambut", "hair", "cabello"] },
  { w: "răng", pos: "n", cefr: "A2", g: ["gigi", "tooth", "diente"] },
  { w: "tai", pos: "n", cefr: "A2", g: ["telinga", "ear", "oreja"] },
  { w: "mặt", pos: "n", cefr: "A2", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "cây", pos: "n", cefr: "A2", g: ["pohon", "tree", "árbol"] },
  { w: "hoa", pos: "n", cefr: "A2", g: ["bunga", "flower", "flor"] },
  { w: "núi", pos: "n", cefr: "A2", g: ["gunung", "mountain", "montaña"] },
  { w: "sông", pos: "n", cefr: "A2", g: ["sungai", "river", "río"] },
  { w: "biển", pos: "n", cefr: "A2", g: ["laut", "sea", "mar"] },
  { w: "bầu trời", pos: "n", cefr: "A2", g: ["langit", "sky", "cielo"] },
  { w: "ngôi sao", pos: "n", cefr: "A2", g: ["bintang", "star", "estrella"] },
  { w: "chó", pos: "n", cefr: "A2", g: ["anjing", "dog", "perro"] },
  { w: "mèo", pos: "n", cefr: "A2", g: ["kucing", "cat", "gato"] },
  { w: "chim", pos: "n", cefr: "A2", g: ["burung", "bird", "pájaro"] },
  { w: "ngựa", pos: "n", cefr: "A2", g: ["kuda", "horse", "caballo"] },
  { w: "mưa", pos: "n", cefr: "A2", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "phố", pos: "n", cefr: "B1", g: ["jalan (di kota)", "street", "calle"] },
  { w: "cầu", pos: "n", cefr: "B1", g: ["jembatan", "bridge", "puente"] },
  { w: "chợ", pos: "n", cefr: "B1", g: ["pasar", "market", "mercado"] },
  { w: "trường học", pos: "n", cefr: "B1", g: ["sekolah", "school", "escuela"] },
  { w: "bệnh viện", pos: "n", cefr: "B1", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "văn phòng", pos: "n", cefr: "B1", g: ["kantor", "office", "oficina"] },
  { w: "xe buýt", pos: "n", cefr: "B1", g: ["bus", "bus", "autobús"] },
  { w: "tàu hỏa", pos: "n", cefr: "B1", g: ["kereta api", "train", "tren"] },
  { w: "xe hơi", pos: "n", cefr: "B1", g: ["mobil", "car", "coche"], syn: ["ô tô"] },
  { w: "xe đạp", pos: "n", cefr: "B1", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "sân bay", pos: "n", cefr: "B1", g: ["bandara", "airport", "aeropuerto"] },
  { w: "vé", pos: "n", cefr: "B1", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "công ty", pos: "n", cefr: "B2", g: ["perusahaan", "company", "empresa"] },
  { w: "cuộc họp", pos: "n", cefr: "B2", g: ["rapat", "meeting", "reunión"] },
  { w: "hợp đồng", pos: "n", cefr: "B2", g: ["kontrak", "contract", "contrato"] },
  { w: "lương", pos: "n", cefr: "B2", g: ["gaji", "salary", "sueldo"] },
  { w: "giá", pos: "n", cefr: "B2", g: ["harga", "price", "precio"] },
  { w: "thuế", pos: "n", cefr: "B2", g: ["pajak", "tax", "impuesto"] },
  { w: "ngân hàng", pos: "n", cefr: "B2", g: ["bank", "bank", "banco"] },
  { w: "máy tính", pos: "n", cefr: "B2", g: ["komputer", "computer", "ordenador"] },
  { w: "điện thoại", pos: "n", cefr: "B2", g: ["telepon", "telephone", "teléfono"] },
  { w: "thư điện tử", pos: "n", cefr: "B2", g: ["surel, email", "email", "correo electrónico"] },
  { w: "tệp", pos: "n", cefr: "B2", g: ["berkas", "file", "archivo"] },
  { w: "mật khẩu", pos: "n", cefr: "B2", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "ảo tưởng", pos: "n", cefr: "C2", ipa: "ʔaːw˧˩ tɨəŋ˧˩", g: ["ilusi, angan kosong", "illusion, pipe dream", "ilusión"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["Lời hứa đó chỉ là ảo tưởng.", "Janji itu hanyalah angan kosong.", "That promise is just an illusion.", "Esa promesa es solo una ilusión."] },
  { w: "cấp bách", pos: "adj", cefr: "C2", ipa: "kɜp˧˥ ɓaːc˧˥", g: ["mendesak", "urgent, pressing", "urgente"], d: ["Harus dikerjakan segera tanpa penundaan.", "Requiring action with no delay.", "Que exige acción sin demora."], ex: ["Đây là vấn đề cấp bách.", "Ini persoalan mendesak.", "This is an urgent matter.", "Es un asunto urgente."] },
  { w: "cột mốc", pos: "n", cefr: "C2", ipa: "kot˧ˀ˨ mok˧˥", g: ["tonggak", "milestone, landmark", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["Thỏa thuận là một cột mốc lịch sử.", "Kesepakatan itu tonggak sejarah.", "The agreement was a historic milestone.", "El acuerdo fue un hito histórico."] },
  { w: "dưới góc độ", pos: "phr", cefr: "C2", ipa: "zɨəj˧˥ ɣɔk˧˥ ɗo˧ˀ˨", g: ["dari sudut pandang", "from the standpoint of", "desde el punto de vista de"], d: ["Membatasi penilaian pada satu sudut pandang.", "Limits a judgement to one standpoint.", "Limita el juicio a un punto de vista."], ex: ["Dưới góc độ chi phí, đây là lựa chọn tốt nhất.", "Dari sudut biaya, ini pilihan terbaik.", "From the standpoint of cost, it's the best option.", "Desde el punto de vista del coste, es lo mejor."] },
  { w: "hạ thấp", pos: "v", cefr: "C2", ipa: "haː˧ˀ˨ tʰɜp˧˥", g: ["merendahkan", "to belittle, to lower", "menoscabar"], d: ["Membuat nilai sesuatu tampak lebih kecil.", "To make something seem less valuable.", "Hacer que algo parezca menor."], ex: ["Tôi không muốn hạ thấp công sức của anh ấy.", "Saya tak ingin merendahkan jerih payahnya.", "I don't want to belittle his effort.", "No quiero menoscabar su esfuerzo."] },
  { w: "khôn tả", pos: "adj", cefr: "C2", ipa: "xon˧˧ taː˧˩", g: ["tak terlukiskan", "indescribable, ineffable", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["Một niềm vui khôn tả.", "Sukacita yang tak terlukiskan.", "An indescribable joy.", "Una alegría indescriptible."] },
  { w: "không thể tránh khỏi", pos: "phr", cefr: "C2", ipa: "xoŋ˧˧ tʰe˧˩ ʈaːɲ˧˥ xɔj˧˩", g: ["tak terhindarkan", "unavoidable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["Việc tăng giá là không thể tránh khỏi.", "Kenaikan harga tak terhindarkan.", "The price rise is unavoidable.", "La subida es inevitable."] },
  { w: "làm sáng tỏ", pos: "v", cefr: "C2", ipa: "laːm˧˨ saːŋ˧˥ tɔ˧˩", g: ["menjernihkan", "to shed light on, to elucidate", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["Cần làm sáng tỏ các chi tiết.", "Rinciannya perlu dijernihkan.", "The details need clarifying.", "Hay que esclarecer los detalles."] },
  { w: "mô thức", pos: "n", cefr: "C2", ipa: "mo˧˧ tʰɨk˧˥", g: ["paradigma, pola pikir", "paradigm, model", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["Đó là một sự thay đổi mô thức.", "Itu pergeseran paradigma.", "That was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "né tránh", pos: "v", cefr: "C2", ipa: "nɛ˧˥ ʈaːɲ˧˥", g: ["mengelak", "to dodge, to evade", "eludir"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto sin afrontarlo."], ex: ["Ông ấy né tránh câu hỏi.", "Dia mengelak dari pertanyaan itu.", "He dodged the question.", "Eludió la pregunta."] },
  { w: "thiên kiến", pos: "n", cefr: "C2", ipa: "tʰiən˧˧ kiən˧˥", g: ["prasangka, bias", "bias, prejudice", "sesgo"], d: ["Kecenderungan menilai secara tidak berimbang.", "A tendency that tilts judgement.", "Tendencia que inclina el juicio."], ex: ["Nghiên cứu này có thiên kiến rõ rệt.", "Kajian ini punya bias yang jelas.", "This study has a clear bias.", "Este estudio tiene un sesgo claro."] },
  { w: "tia hy vọng", pos: "n", cefr: "C2", ipa: "tiə˧˧ hi˧˧ vɔŋ˧ˀ˨", g: ["secercah harapan", "a ray of hope", "un rayo de esperanza"], d: ["Tanda kecil bahwa keadaan bisa membaik.", "A small sign that things may improve.", "Pequeña señal de que algo puede mejorar."], ex: ["Vẫn còn một tia hy vọng.", "Masih ada secercah harapan.", "There's still a ray of hope.", "Aún queda un rayo de esperanza."] },
];
