/* =========================================================================
   lexicon/zh.js — 词典: 中文 (Mandarin, simplified). Front matter + 72 headwords.
   Entri diurutkan menurut pinyin — persis seperti indeks 汉语拼音 di kamus cetak.
   ========================================================================= */
export const guide = {
  intro: [
    "Bahasa Mandarin tidak mengenal konjugasi, jamak, maupun gender. Yang harus dikuasai justru dua hal lain: empat nada yang membedakan arti, dan aksara Han yang menyimpan makna, bukan bunyi.",
    "Mandarin has no conjugation, no plurals, no gender. What must be mastered instead is elsewhere: four tones that change meaning, and Han characters that store meaning rather than sound.",
    "El chino no tiene conjugación, plural ni género. Lo difícil está en otra parte: cuatro tonos que cambian el sentido y los caracteres han.",
  ],
  script: [
    "Setiap karakter adalah satu suku kata bermakna. Pinyin (romanisasi resmi sejak 1958) adalah tangga masuk: baca pinyin dulu, karakternya menyusul.",
    "Each character is one meaningful syllable. Pinyin (the official romanisation since 1958) is the way in: read the pinyin first, the characters follow.",
    "Cada carácter es una sílaba con significado. El pinyin (romanización oficial desde 1958) es la puerta de entrada.",
  ],
  pron: [
    ["4 nada", "mā (ibu), má (rami), mǎ (kuda), mà (memarahi) — satu suku kata, empat kata.", "mā (mother), má (hemp), mǎ (horse), mà (to scold) — one syllable, four words.", "mā (madre), má (cáñamo), mǎ (caballo), mà (regañar)."],
    ["nada ketiga", "Dua nada ketiga berturut-turut: yang pertama berubah jadi nada kedua (nǐ hǎo → ní hǎo).", "Two third tones in a row: the first becomes a second tone (nǐ hǎo → ní hǎo).", "Dos terceros tonos seguidos: el primero pasa a segundo (nǐ hǎo → ní hǎo)."],
    ["zh ch sh r", "Lidah ditekuk ke belakang (retrofleks): zhōngguó, chī, shū.", "Retroflex: the tongue curls back — zhōngguó, chī, shū.", "Retroflejas: la lengua se curva — zhōngguó, chī, shū."],
    ["j q x", "Lidah rata dan maju, bibir melebar: jiā, qù, xiè.", "Flat, forward tongue with spread lips: jiā, qù, xiè.", "Lengua plana y adelantada: jiā, qù, xiè."],
    ["ü", "Bibir dibulatkan seperti 'u' Jerman: nǚ, lǜ; ditulis u sesudah j q x y.", "Rounded lips as in German ü: nǚ, lǜ; written u after j q x y.", "Labios redondeados como la ü alemana: nǚ, lǜ."],
    ["nada netral", "Suku kata kedua sering kehilangan nada: 朋友 péngyou, 谢谢 xièxie.", "A second syllable often loses its tone: 朋友 péngyou, 谢谢 xièxie.", "La segunda sílaba suele perder el tono: 朋友 péngyou."],
  ],
  grammar: [
    {
      t: ["Kata tak berubah bentuk", "Words never change shape", "Las palabras no cambian"],
      d: ["Tidak ada konjugasi maupun jamak; waktu ditandai kata bantu seperti 了, 过, 会.", "No conjugation, no plurals; time is marked by particles such as 了, 过, 会.", "Sin conjugación ni plural; el tiempo lo marcan 了, 过, 会."],
      ex: "我吃 · 我吃了 · 我会吃",
    },
    {
      t: ["Kata penggolong", "Measure words", "Clasificadores"],
      d: ["Setiap benda yang dihitung memerlukan penggolongnya sendiri: 一本书, 一杯茶, 三个人.", "Every counted noun needs its own measure word: 一本书, 一杯茶, 三个人.", "Cada sustantivo contado lleva su clasificador: 一本书, 一杯茶."],
      ex: "两只猫 · 五张纸",
    },
    {
      t: ["Urutan waktu-tempat-tindakan", "Time, place, then action", "Tiempo, lugar y luego acción"],
      d: ["Keterangan waktu dan tempat mendahului kata kerja, bukan mengikutinya.", "Time and place expressions come before the verb, never after.", "El tiempo y el lugar van antes del verbo."],
      ex: "我明天在家看书。",
    },
    {
      t: ["Partikel 的", "The particle 的", "La partícula 的"],
      d: ["Menandai kepemilikan dan menempelkan keterangan pada kata benda.", "It marks possession and glues modifiers onto nouns.", "Marca posesión y une modificadores al sustantivo."],
      ex: "我的书 · 很好吃的菜",
    },
    {
      t: ["Pertanyaan dengan 吗 atau A-not-A", "Questions with 吗 or A-not-A", "Preguntas con 吗 o A-no-A"],
      d: ["Tambahkan 吗 di akhir, atau ulangi kata kerjanya dalam bentuk positif-negatif.", "Add 吗 at the end, or repeat the verb in a positive-negative pair.", "Añade 吗 al final o repite el verbo en par positivo-negativo."],
      ex: "你好吗？ · 你去不去？",
    },
  ],
};

export default [
  /* ------------------------------------------------------------------ A1 */
  { w: "吃", r: "chī", pos: "v", cefr: "A1", g: ["makan", "to eat", "comer"], d: ["Memasukkan makanan ke mulut.", "To take food into the mouth.", "Tomar alimento."], ex: ["我已经吃过了。", "Saya sudah makan.", "I've already eaten.", "Ya he comido."] },
  { w: "大", r: "dà", pos: "adj", cefr: "A1", g: ["besar", "big, large", "grande"], d: ["Berukuran lebih dari biasanya.", "Larger than average.", "De tamaño mayor de lo normal."], ex: ["他们住在大城市。", "Mereka tinggal di kota besar.", "They live in a big city.", "Viven en una ciudad grande."], ant: ["小"] },
  { w: "好", r: "hǎo", pos: "adj", cefr: "A1", g: ["baik, bagus", "good", "bueno"], d: ["Bermutu baik atau menyenangkan.", "Of good quality or pleasant.", "De buena calidad o agradable."], ex: ["这是个好主意。", "Itu ide yang bagus.", "That's a good idea.", "Es una buena idea."], ant: ["坏"] },
  { w: "家", r: "jiā", pos: "n", cefr: "A1", g: ["rumah; keluarga", "home; family", "casa; familia"], d: ["Tempat tinggal; juga berarti keluarga.", "The place you live; also your family.", "El hogar; también la familia."], ex: ["我家离公园很近。", "Rumah saya dekat taman.", "My home is near the park.", "Mi casa está cerca del parque."] },
  { w: "看", r: "kàn", pos: "v", cefr: "A1", g: ["melihat, membaca", "to look, to watch, to read", "mirar, leer"], d: ["Mengarahkan mata pada sesuatu.", "To direct your eyes at something.", "Dirigir la vista a algo."], ex: ["昨天我看了一部电影。", "Kemarin saya menonton film.", "I watched a film yesterday.", "Ayer vi una película."] },
  { w: "来", r: "lái", pos: "v", cefr: "A1", g: ["datang", "to come", "venir"], d: ["Bergerak mendekat ke tempat pembicara.", "To move towards the speaker.", "Moverse hacia el hablante."], ex: ["朋友来我家了。", "Teman saya datang ke rumah.", "A friend came to my place.", "Un amigo vino a casa."], ant: ["去"] },
  { w: "朋友", r: "péngyou", pos: "n", cefr: "A1", g: ["teman", "friend", "amigo"], d: ["Orang yang dekat dan kita percayai.", "Someone you like and trust.", "Persona cercana y de confianza."], ex: ["我和朋友一起出去。", "Saya keluar bersama teman.", "I'm going out with a friend.", "Salgo con un amigo."] },
  { w: "去", r: "qù", pos: "v", cefr: "A1", g: ["pergi", "to go", "ir"], d: ["Berpindah menuju suatu tempat.", "To move towards a place.", "Desplazarse a un lugar."], ex: ["我去市场。", "Saya pergi ke pasar.", "I'm going to the market.", "Voy al mercado."], ant: ["来"] },
  { w: "人", r: "rén", pos: "n", cefr: "A1", g: ["orang", "person", "persona"], d: ["Satu manusia.", "A single human being.", "Un ser humano."], ex: ["他是个好人。", "Dia orang yang baik.", "He's a good person.", "Es una buena persona."] },
  { w: "水", r: "shuǐ", pos: "n", cefr: "A1", g: ["air", "water", "agua"], d: ["Cairan bening yang diminum.", "The clear liquid we drink.", "Líquido transparente que se bebe."], ex: ["请给我一杯水。", "Tolong beri saya segelas air.", "A glass of water, please.", "Un vaso de agua, por favor."] },
  { w: "小", r: "xiǎo", pos: "adj", cefr: "A1", g: ["kecil", "small", "pequeño"], d: ["Berukuran kurang dari biasanya.", "Smaller than average.", "De tamaño menor de lo normal."], ex: ["我住在一个小房间。", "Saya tinggal di kamar kecil.", "I live in a small room.", "Vivo en una habitación pequeña."], ant: ["大"] },
  { w: "有", r: "yǒu", pos: "v", cefr: "A1", g: ["punya, ada", "to have; there is", "tener; haber"], d: ["Menyatakan kepemilikan atau keberadaan.", "States possession or existence.", "Indica posesión o existencia."], ex: ["我有两个姐姐。", "Saya punya dua kakak perempuan.", "I have two older sisters.", "Tengo dos hermanas mayores."], note: ["Bentuk negatifnya 没有, bukan 不有.", "The negative is 没有, never 不有.", "La negación es 没有, nunca 不有."] },

  /* ------------------------------------------------------------------ A2 */
  { w: "帮助", r: "bāngzhù", pos: "v", cefr: "A2", g: ["menolong", "to help", "ayudar"], d: ["Membuat pekerjaan orang lain lebih ringan.", "To make someone else's task easier.", "Facilitar la tarea de otro."], ex: ["你能帮助我吗？", "Bisakah kamu menolong saya?", "Can you help me?", "¿Puedes ayudarme?"] },
  { w: "城市", r: "chéngshì", pos: "n", cefr: "A2", g: ["kota", "city", "ciudad"], d: ["Permukiman besar dengan banyak penduduk.", "A large settlement with many inhabitants.", "Población grande con muchos habitantes."], ex: ["杭州是个美丽的城市。", "Hangzhou kota yang indah.", "Hangzhou is a beautiful city.", "Hangzhou es una ciudad preciosa."] },
  { w: "工作", r: "gōngzuò", pos: "n", cefr: "A2", g: ["pekerjaan", "work, job", "trabajo"], d: ["Kegiatan untuk mencari nafkah.", "The activity you earn a living by.", "Actividad para ganarse la vida."], ex: ["我的工作九点开始。", "Pekerjaan saya mulai pukul sembilan.", "My work starts at nine.", "Mi trabajo empieza a las nueve."] },
  { w: "开始", r: "kāishǐ", pos: "v", cefr: "A2", g: ["memulai", "to begin", "empezar"], d: ["Melakukan bagian pertama sesuatu.", "To do the first part of something.", "Dar principio a algo."], ex: ["电影八点开始。", "Filmnya mulai pukul delapan.", "The film starts at eight.", "La película empieza a las ocho."], ant: ["结束"] },
  { w: "快", r: "kuài", pos: "adj", cefr: "A2", g: ["cepat", "fast", "rápido"], d: ["Bergerak atau terjadi dalam waktu singkat.", "Moving or happening in little time.", "Que ocurre en poco tiempo."], ex: ["坐火车比较快。", "Naik kereta lebih cepat.", "Going by train is faster.", "Ir en tren es más rápido."], ant: ["慢"] },
  { w: "难", r: "nán", pos: "adj", cefr: "A2", g: ["sulit", "difficult", "difícil"], d: ["Menuntut usaha atau keahlian.", "Requiring effort or skill.", "Que exige esfuerzo o destreza."], ex: ["在这里停车很难。", "Sulit parkir di sini.", "It's hard to park here.", "Es difícil aparcar aquí."], ant: ["容易"] },
  { w: "钱", r: "qián", pos: "n", cefr: "A2", g: ["uang", "money", "dinero"], d: ["Alat tukar untuk membeli sesuatu.", "What you use to buy things.", "Medio para comprar cosas."], ex: ["我的钱不够。", "Uang saya tidak cukup.", "I don't have enough money.", "No tengo suficiente dinero."] },
  { w: "容易", r: "róngyì", pos: "adj", cefr: "A2", g: ["mudah", "easy", "fácil"], d: ["Tidak menuntut banyak usaha.", "Not requiring much effort.", "Que no exige esfuerzo."], ex: ["这次考试很容易。", "Ujian kali ini mudah.", "This exam was easy.", "Este examen fue fácil."], ant: ["难"] },
  { w: "时间", r: "shíjiān", pos: "n", cefr: "A2", g: ["waktu", "time", "tiempo"], d: ["Jam dan hari yang berjalan.", "The passing of hours and days.", "El paso de horas y días."], ex: ["今天我没有时间。", "Hari ini saya tak punya waktu.", "I have no time today.", "Hoy no tengo tiempo."] },
  { w: "需要", r: "xūyào", pos: "v", cefr: "A2", g: ["membutuhkan", "to need", "necesitar"], d: ["Memerlukan sesuatu yang penting.", "To require something.", "Requerir algo."], ex: ["我需要休息。", "Saya butuh istirahat.", "I need to rest.", "Necesito descansar."] },
  { w: "因为", r: "yīnwèi", pos: "conj", cefr: "A2", g: ["karena", "because", "porque"], d: ["Menyatakan sebab.", "Introduces a reason.", "Introduce la causa."], ex: ["因为下雨，我在家。", "Karena hujan, saya di rumah.", "Because it's raining, I'm at home.", "Como llueve, estoy en casa."], note: ["Sering berpasangan: 因为…所以… ('karena… maka…').", "Often paired: 因为…所以… ('because… therefore…').", "Suele ir en par: 因为…所以…"] },
  { w: "总是", r: "zǒngshì", pos: "adv", cefr: "A2", g: ["selalu", "always", "siempre"], d: ["Pada setiap kesempatan.", "On every occasion.", "En toda ocasión."], ex: ["我总是在家吃早饭。", "Saya selalu sarapan di rumah.", "I always have breakfast at home.", "Siempre desayuno en casa."] },

  /* ------------------------------------------------------------------ B1 */
  { w: "但是", r: "dànshì", pos: "conj", cefr: "B1", g: ["tetapi", "but", "pero"], d: ["Penghubung yang menandai pertentangan.", "A connector marking a contrast.", "Conector de contraste."], ex: ["很贵，但是值得。", "Mahal, tetapi sepadan.", "It's expensive, but worth it.", "Es caro, pero vale la pena."] },
  { w: "成功", r: "chénggōng", pos: "v", cefr: "B1", g: ["berhasil, sukses", "to succeed; success", "tener éxito"], d: ["Mencapai apa yang diusahakan.", "To achieve what you set out to do.", "Lograr lo que se intentaba."], ex: ["这个计划成功了。", "Rencana itu berhasil.", "The plan succeeded.", "El plan tuvo éxito."], ant: ["失败"] },
  { w: "好像", r: "hǎoxiàng", pos: "v", cefr: "B1", g: ["tampaknya, seperti", "to seem, as if", "parecer"], d: ["Memberi kesan tertentu tanpa kepastian.", "To give an impression without certainty.", "Dar cierta impresión sin certeza."], ex: ["他好像很累。", "Dia tampak lelah.", "He seems tired.", "Parece cansado."] },
  { w: "机会", r: "jīhuì", pos: "n", cefr: "B1", g: ["kesempatan", "opportunity, chance", "oportunidad"], d: ["Saat yang tepat untuk melakukan sesuatu.", "A good moment to act.", "Momento propicio para actuar."], ex: ["这是个好机会。", "Ini kesempatan bagus.", "This is a good opportunity.", "Es una buena oportunidad."] },
  { w: "建议", r: "jiànyì", pos: "n", cefr: "B1", g: ["saran, usulan", "advice, suggestion", "consejo, sugerencia"], d: ["Pendapat tentang apa yang sebaiknya dilakukan.", "An opinion on what someone should do.", "Opinión sobre lo que conviene hacer."], ex: ["你能给我一个建议吗？", "Bisakah kamu memberi saya saran?", "Could you give me some advice?", "¿Me das un consejo?"] },
  { w: "经验", r: "jīngyàn", pos: "n", cefr: "B1", g: ["pengalaman", "experience", "experiencia"], d: ["Pengetahuan dari hal yang pernah dijalani.", "Knowledge gained from doing.", "Conocimiento adquirido con la práctica."], ex: ["她很有经验。", "Dia sangat berpengalaman.", "She has a lot of experience.", "Tiene mucha experiencia."] },
  { w: "决定", r: "juédìng", pos: "v", cefr: "B1", g: ["memutuskan; keputusan", "to decide; decision", "decidir; decisión"], d: ["Menetapkan pilihan setelah berpikir.", "To settle on a choice after thinking.", "Tomar una decisión tras pensar."], ex: ["这是个艰难的决定。", "Itu keputusan yang sulit.", "It was a hard decision.", "Fue una decisión difícil."] },
  { w: "虽然", r: "suīrán", pos: "conj", cefr: "B1", g: ["meskipun", "although", "aunque"], d: ["Menandai kontras; sering berpasangan dengan 但是.", "Marks a contrast; often paired with 但是.", "Marca contraste; suele ir con 但是."], ex: ["虽然下雨，我们还是去。", "Meskipun hujan, kami tetap pergi.", "Although it's raining, we're still going.", "Aunque llueve, iremos igual."] },
  { w: "提高", r: "tígāo", pos: "v", cefr: "B1", g: ["meningkatkan", "to raise, to improve", "mejorar"], d: ["Membuat mutu atau angkanya naik.", "To raise a level or a figure.", "Elevar un nivel o una cifra."], ex: ["我想提高我的发音。", "Saya ingin meningkatkan pelafalan saya.", "I want to improve my pronunciation.", "Quiero mejorar mi pronunciación."] },
  { w: "习惯", r: "xíguàn", pos: "n", cefr: "B1", g: ["kebiasaan; terbiasa", "habit; to be used to", "costumbre; acostumbrarse"], d: ["Perbuatan berulang; juga berarti terbiasa.", "A repeated behaviour; also to be accustomed.", "Conducta repetida; también estar habituado."], ex: ["我已经习惯这里的天气了。", "Saya sudah terbiasa dengan cuaca di sini.", "I've got used to the weather here.", "Ya me acostumbré al clima de aquí."] },
  { w: "想念", r: "xiǎngniàn", pos: "v", cefr: "B1", g: ["merindukan", "to miss (someone)", "echar de menos"], d: ["Merasa sedih karena seseorang tidak ada.", "To feel the absence of someone.", "Sentir la ausencia de alguien."], ex: ["我很想念我的家人。", "Saya sangat merindukan keluarga saya.", "I miss my family very much.", "Echo mucho de menos a mi familia."] },
  { w: "也许", r: "yěxǔ", pos: "adv", cefr: "B1", g: ["mungkin", "maybe, perhaps", "quizá"], d: ["Menyatakan kemungkinan, bukan kepastian.", "Expresses possibility, not certainty.", "Expresa posibilidad, no certeza."], ex: ["他也许明天来。", "Mungkin dia datang besok.", "Maybe he'll come tomorrow.", "Quizá venga mañana."] },

  /* ------------------------------------------------------------------ B2 */
  { w: "必要", r: "bìyào", pos: "adj", cefr: "B2", g: ["perlu, wajib", "necessary", "necesario"], d: ["Tidak bisa ditinggalkan sama sekali.", "Impossible to do without.", "Imposible de omitir."], ex: ["护照是必要的。", "Paspor itu diperlukan.", "A passport is necessary.", "El pasaporte es necesario."] },
  { w: "发展", r: "fāzhǎn", pos: "n", cefr: "B2", g: ["perkembangan", "development", "desarrollo"], d: ["Proses tumbuh atau menjadi lebih maju.", "The process of growing or advancing.", "Proceso de crecer o avanzar."], ex: ["项目发展得很顺利。", "Proyeknya berkembang lancar.", "The project is developing smoothly.", "El proyecto se desarrolla bien."] },
  { w: "环境", r: "huánjìng", pos: "n", cefr: "B2", g: ["lingkungan", "environment", "medio ambiente"], d: ["Alam sekitar; juga suasana tempat kerja.", "The natural surroundings; also a work setting.", "Entorno natural; también ambiente laboral."], ex: ["我们要保护环境。", "Kita harus melindungi lingkungan.", "We must protect the environment.", "Debemos proteger el medio ambiente."] },
  { w: "尽管", r: "jǐnguǎn", pos: "conj", cefr: "B2", g: ["meskipun begitu", "despite, even though", "a pesar de"], d: ["Menyatakan hambatan yang tak menghalangi.", "Introduces an obstacle that changes nothing.", "Introduce un obstáculo que no impide nada."], ex: ["尽管很冷，我们还是出去了。", "Meski dingin, kami tetap keluar.", "Despite the cold, we went out.", "A pesar del frío, salimos."] },
  { w: "可靠", r: "kěkào", pos: "adj", cefr: "B2", g: ["dapat diandalkan", "reliable, dependable", "fiable"], d: ["Bisa dipercaya karena konsisten.", "Trustworthy because consistent.", "De confianza por su constancia."], ex: ["这是可靠的来源。", "Ini sumber yang bisa diandalkan.", "This is a reliable source.", "Es una fuente fiable."] },
  { w: "强调", r: "qiángdiào", pos: "v", cefr: "B2", g: ["menekankan", "to emphasise", "subrayar"], d: ["Menonjolkan hal yang dianggap penting.", "To give weight to something important.", "Destacar algo importante."], ex: ["他强调了安全问题。", "Dia menekankan soal keselamatan.", "He emphasised the safety issue.", "Subrayó la cuestión de la seguridad."] },
  { w: "实施", r: "shíshī", pos: "v", cefr: "B2", g: ["melaksanakan", "to implement, to put into effect", "implantar"], d: ["Mengubah rencana atau aturan menjadi kenyataan.", "To put a plan or rule into force.", "Poner en vigor un plan o norma."], ex: ["新制度下个月实施。", "Sistem baru dilaksanakan bulan depan.", "The new system takes effect next month.", "El nuevo sistema se aplica el mes próximo."] },
  { w: "实现", r: "shíxiàn", pos: "v", cefr: "B2", g: ["mewujudkan, mencapai", "to realise, to achieve", "hacer realidad"], d: ["Menjadikan rencana atau cita-cita nyata.", "To turn a plan or a dream into reality.", "Hacer realidad un plan o sueño."], ex: ["我们实现了目标。", "Kami mewujudkan targetnya.", "We achieved the goal.", "Alcanzamos el objetivo."] },
  { w: "挑战", r: "tiǎozhàn", pos: "n", cefr: "B2", g: ["tantangan", "challenge", "desafío"], d: ["Hal sulit yang menuntut usaha besar.", "Something hard that demands effort.", "Algo difícil que exige esfuerzo."], ex: ["这是一个很大的挑战。", "Ini tantangan yang besar.", "This is a big challenge.", "Es un gran desafío."] },
  { w: "问题", r: "wèntí", pos: "n", cefr: "B2", g: ["masalah; pertanyaan", "problem; question", "problema; pregunta"], d: ["Hal yang menyulitkan; juga kalimat tanya.", "Something difficult; also a question.", "Algo difícil; también una pregunta."], ex: ["这是个敏感问题。", "Ini persoalan yang sensitif.", "It's a sensitive issue.", "Es un asunto delicado."] },
  { w: "协议", r: "xiéyì", pos: "n", cefr: "B2", g: ["kesepakatan, perjanjian", "agreement, accord", "acuerdo"], d: ["Kesepakatan resmi antara dua pihak.", "A formal agreement between two sides.", "Acuerdo formal entre dos partes."], ex: ["双方签署了协议。", "Kedua pihak menandatangani perjanjian.", "The two sides signed the agreement.", "Ambas partes firmaron el acuerdo."] },
  { w: "因此", r: "yīncǐ", pos: "conj", cefr: "B2", g: ["oleh karena itu", "therefore", "por lo tanto"], d: ["Menandai kesimpulan logis.", "Marks a logical conclusion.", "Marca una conclusión lógica."], ex: ["下雨了，因此活动取消。", "Hujan, oleh karena itu acaranya dibatalkan.", "It rained; therefore the event was cancelled.", "Llovió; por lo tanto se canceló."] },

  /* ------------------------------------------------------------------ C1 */
  { w: "促进", r: "cùjìn", pos: "v", cefr: "C1", g: ["mendorong, memacu", "to promote, to further", "fomentar"], d: ["Membantu sesuatu tumbuh atau berjalan lebih cepat.", "To help something grow or move faster.", "Ayudar a que algo crezca o avance."], ex: ["这项法律促进了回收。", "Undang-undang itu mendorong daur ulang.", "The law promoted recycling.", "La ley fomentó el reciclaje."] },
  { w: "处理", r: "chǔlǐ", pos: "v", cefr: "C1", g: ["menangani, mengurus", "to handle, to deal with", "gestionar"], d: ["Mengurus persoalan sampai selesai.", "To deal with a matter until it is settled.", "Ocuparse de un asunto hasta resolverlo."], ex: ["他处理得很好。", "Dia menanganinya dengan baik.", "He handled it well.", "Lo gestionó muy bien."] },
  { w: "反映", r: "fǎnyìng", pos: "v", cefr: "C1", g: ["mencerminkan; melaporkan", "to reflect; to report", "reflejar"], d: ["Menunjukkan keadaan lain; juga menyampaikan keluhan ke atas.", "To show another state; also to report an issue upward.", "Mostrar otra realidad; también informar."], ex: ["数据反映了改善。", "Datanya mencerminkan perbaikan.", "The data reflect an improvement.", "Los datos reflejan una mejora."] },
  { w: "范围", r: "fànwéi", pos: "n", cefr: "C1", g: ["cakupan, lingkup", "scope, range", "alcance"], d: ["Seberapa luas sesuatu berlaku.", "How far something extends.", "Hasta dónde llega algo."], ex: ["这项决定的范围很广。", "Cakupan keputusan ini luas.", "This decision's scope is wide.", "El alcance de esta decisión es amplio."] },
  { w: "巩固", r: "gǒnggù", pos: "v", cefr: "C1", g: ["memperkukuh", "to consolidate, to strengthen", "consolidar"], d: ["Membuat sesuatu mantap dan tahan lama.", "To make something firm and lasting.", "Dar firmeza y solidez."], ex: ["公司巩固了自己的地位。", "Perusahaan memperkukuh posisinya.", "The company consolidated its position.", "La empresa consolidó su posición."] },
  { w: "领域", r: "lǐngyù", pos: "n", cefr: "C1", g: ["bidang, ranah", "field, domain", "ámbito"], d: ["Wilayah kegiatan atau pengetahuan tertentu.", "An area of activity or knowledge.", "Área de actividad o conocimiento."], ex: ["在法律领域情况不同。", "Dalam ranah hukum keadaannya berbeda.", "In the legal field things differ.", "En el ámbito jurídico es distinto."] },
  { w: "然而", r: "rán'ér", pos: "conj", cefr: "C1", g: ["namun demikian", "however, nevertheless", "sin embargo"], d: ["Penghubung formal untuk pertentangan.", "A formal contrast connector.", "Conector formal de contraste."], ex: ["然而，结论并不相同。", "Namun demikian, kesimpulannya tidak sama.", "However, the conclusion was not the same.", "Sin embargo, la conclusión no fue la misma."] },
  { w: "突出", r: "tūchū", pos: "v", cefr: "C1", g: ["menonjolkan; menonjol", "to highlight; to stand out", "destacar"], d: ["Membuat sesuatu tampak menonjol; juga menonjol sendiri.", "To make something stand out; also to be prominent.", "Hacer resaltar algo; también sobresalir."], ex: ["报告突出了主要风险。", "Laporan itu menonjolkan risiko utama.", "The report highlighted the main risks.", "El informe destacó los riesgos."] },
  { w: "途径", r: "tújìng", pos: "n", cefr: "C1", g: ["jalan, pendekatan", "avenue, approach", "vía, enfoque"], d: ["Cara atau jalur untuk mencapai sesuatu.", "The route or approach to achieving something.", "Vía o enfoque para lograr algo."], ex: ["我们需要新的途径。", "Kita butuh pendekatan baru.", "We need a new approach.", "Necesitamos una nueva vía."] },
  { w: "细微差别", r: "xìwēi chābié", pos: "n", cefr: "C1", g: ["nuansa, beda halus", "nuance, subtle difference", "matiz"], d: ["Perbedaan halus dalam makna atau nada.", "A subtle difference in meaning or tone.", "Diferencia sutil de sentido o tono."], ex: ["这里有重要的细微差别。", "Ada nuansa penting di sini.", "There's an important nuance here.", "Hay un matiz importante aquí."] },
  { w: "细致", r: "xìzhì", pos: "adj", cefr: "C1", g: ["teliti, cermat", "meticulous, careful", "minucioso"], d: ["Memperhatikan setiap detail kecil.", "Attending to every small detail.", "Que atiende a cada detalle."], ex: ["需要细致的分析。", "Diperlukan analisis yang teliti.", "A meticulous analysis is needed.", "Hace falta un análisis minucioso."] },
  { w: "以便", r: "yǐbiàn", pos: "conj", cefr: "C1", g: ["agar, supaya", "so that, in order to", "a fin de"], d: ["Menyatakan tujuan dalam gaya resmi.", "States a purpose in formal register.", "Expresa finalidad en registro formal."], ex: ["我们简化了流程，以便节省时间。", "Kami sederhanakan prosesnya agar hemat waktu.", "We simplified the process in order to save time.", "Simplificamos el proceso a fin de ahorrar tiempo."] },

  /* ================================================================
     KOSAKATA INTI BERTEMA — lema pendek bergaya kamus.
     ================================================================ */
  /* -- rumah & perabot -- */
  { w: "门", r: "mén", pos: "n", cefr: "A1", g: ["pintu", "door", "puerta"] },
  { w: "窗户", r: "chuānghu", pos: "n", cefr: "A1", g: ["jendela", "window", "ventana"] },
  { w: "房间", r: "fángjiān", pos: "n", cefr: "A1", g: ["kamar, ruangan", "room", "habitación"] },
  { w: "桌子", r: "zhuōzi", pos: "n", cefr: "A1", g: ["meja", "table", "mesa"] },
  { w: "椅子", r: "yǐzi", pos: "n", cefr: "A1", g: ["kursi", "chair", "silla"] },
  { w: "床", r: "chuáng", pos: "n", cefr: "A1", g: ["tempat tidur", "bed", "cama"] },
  { w: "厨房", r: "chúfáng", pos: "n", cefr: "A1", g: ["dapur", "kitchen", "cocina"] },
  { w: "浴室", r: "yùshì", pos: "n", cefr: "A1", g: ["kamar mandi", "bathroom", "cuarto de baño"] },
  { w: "灯", r: "dēng", pos: "n", cefr: "A1", g: ["lampu", "lamp, light", "lámpara"] },
  { w: "钥匙", r: "yàoshi", pos: "n", cefr: "A1", g: ["kunci", "key", "llave"] },
  { w: "墙", r: "qiáng", pos: "n", cefr: "A1", g: ["dinding, tembok", "wall", "pared"] },
  { w: "屋顶", r: "wūdǐng", pos: "n", cefr: "A1", g: ["atap", "roof", "techo"] },
  /* -- makanan & minuman -- */
  { w: "面包", r: "miànbāo", pos: "n", cefr: "A1", g: ["roti", "bread", "pan"] },
  { w: "米饭", r: "mǐfàn", pos: "n", cefr: "A1", g: ["nasi", "cooked rice", "arroz cocido"] },
  { w: "肉", r: "ròu", pos: "n", cefr: "A1", g: ["daging", "meat", "carne"] },
  { w: "鱼", r: "yú", pos: "n", cefr: "A1", g: ["ikan", "fish", "pescado"] },
  { w: "鸡蛋", r: "jīdàn", pos: "n", cefr: "A1", g: ["telur (ayam)", "egg", "huevo"] },
  { w: "牛奶", r: "niúnǎi", pos: "n", cefr: "A1", g: ["susu sapi", "milk", "leche"] },
  { w: "茶", r: "chá", pos: "n", cefr: "A1", g: ["teh", "tea", "té"] },
  { w: "咖啡", r: "kāfēi", pos: "n", cefr: "A1", g: ["kopi", "coffee", "café"] },
  { w: "糖", r: "táng", pos: "n", cefr: "A1", g: ["gula; permen", "sugar; sweets", "azúcar; caramelo"] },
  { w: "盐", r: "yán", pos: "n", cefr: "A1", g: ["garam", "salt", "sal"] },
  { w: "水果", r: "shuǐguǒ", pos: "n", cefr: "A1", g: ["buah", "fruit", "fruta"] },
  { w: "蔬菜", r: "shūcài", pos: "n", cefr: "A1", g: ["sayur", "vegetable", "verdura"] },
  /* -- pakaian & tubuh -- */
  { w: "衬衫", r: "chènshān", pos: "n", cefr: "A2", g: ["kemeja", "shirt", "camisa"] },
  { w: "裤子", r: "kùzi", pos: "n", cefr: "A2", g: ["celana", "trousers", "pantalón"] },
  { w: "鞋", r: "xié", pos: "n", cefr: "A2", g: ["sepatu", "shoe", "zapato"] },
  { w: "帽子", r: "màozi", pos: "n", cefr: "A2", g: ["topi", "hat", "sombrero"] },
  { w: "手", r: "shǒu", pos: "n", cefr: "A2", g: ["tangan", "hand", "mano"] },
  { w: "眼睛", r: "yǎnjing", pos: "n", cefr: "A2", g: ["mata", "eye", "ojo"] },
  { w: "头", r: "tóu", pos: "n", cefr: "A2", g: ["kepala", "head", "cabeza"] },
  { w: "心", r: "xīn", pos: "n", cefr: "A2", g: ["hati, jantung", "heart", "corazón"] },
  { w: "头发", r: "tóufa", pos: "n", cefr: "A2", g: ["rambut", "hair", "cabello"] },
  { w: "牙齿", r: "yáchǐ", pos: "n", cefr: "A2", g: ["gigi", "tooth", "diente"] },
  { w: "耳朵", r: "ěrduo", pos: "n", cefr: "A2", g: ["telinga", "ear", "oreja"] },
  { w: "脸", r: "liǎn", pos: "n", cefr: "A2", g: ["wajah", "face", "cara"] },
  /* -- alam & hewan -- */
  { w: "树", r: "shù", pos: "n", cefr: "A2", g: ["pohon", "tree", "árbol"] },
  { w: "花", r: "huā", pos: "n", cefr: "A2", g: ["bunga", "flower", "flor"] },
  { w: "山", r: "shān", pos: "n", cefr: "A2", g: ["gunung", "mountain", "montaña"] },
  { w: "河", r: "hé", pos: "n", cefr: "A2", g: ["sungai", "river", "río"] },
  { w: "海", r: "hǎi", pos: "n", cefr: "A2", g: ["laut", "sea", "mar"] },
  { w: "天空", r: "tiānkōng", pos: "n", cefr: "A2", g: ["langit", "sky", "cielo"] },
  { w: "星星", r: "xīngxing", pos: "n", cefr: "A2", g: ["bintang", "star", "estrella"] },
  { w: "狗", r: "gǒu", pos: "n", cefr: "A2", g: ["anjing", "dog", "perro"] },
  { w: "猫", r: "māo", pos: "n", cefr: "A2", g: ["kucing", "cat", "gato"] },
  { w: "鸟", r: "niǎo", pos: "n", cefr: "A2", g: ["burung", "bird", "pájaro"] },
  { w: "马", r: "mǎ", pos: "n", cefr: "A2", g: ["kuda", "horse", "caballo"] },
  { w: "雨", r: "yǔ", pos: "n", cefr: "A2", g: ["hujan", "rain", "lluvia"] },
  /* -- kota & transportasi -- */
  { w: "街", r: "jiē", pos: "n", cefr: "B1", g: ["jalan", "street", "calle"] },
  { w: "桥", r: "qiáo", pos: "n", cefr: "B1", g: ["jembatan", "bridge", "puente"] },
  { w: "市场", r: "shìchǎng", pos: "n", cefr: "B1", g: ["pasar", "market", "mercado"] },
  { w: "学校", r: "xuéxiào", pos: "n", cefr: "B1", g: ["sekolah", "school", "escuela"] },
  { w: "医院", r: "yīyuàn", pos: "n", cefr: "B1", g: ["rumah sakit", "hospital", "hospital"] },
  { w: "办公室", r: "bàngōngshì", pos: "n", cefr: "B1", g: ["kantor", "office", "oficina"] },
  { w: "公共汽车", r: "gōnggòng qìchē", pos: "n", cefr: "B1", g: ["bus kota", "bus", "autobús"] },
  { w: "火车", r: "huǒchē", pos: "n", cefr: "B1", g: ["kereta api", "train", "tren"] },
  { w: "汽车", r: "qìchē", pos: "n", cefr: "B1", g: ["mobil", "car", "coche"] },
  { w: "自行车", r: "zìxíngchē", pos: "n", cefr: "B1", g: ["sepeda", "bicycle", "bicicleta"] },
  { w: "机场", r: "jīchǎng", pos: "n", cefr: "B1", g: ["bandara", "airport", "aeropuerto"] },
  { w: "票", r: "piào", pos: "n", cefr: "B1", g: ["tiket, karcis", "ticket", "billete"] },
  /* -- kerja, uang & teknologi -- */
  { w: "公司", r: "gōngsī", pos: "n", cefr: "B2", g: ["perusahaan", "company", "empresa"] },
  { w: "会议", r: "huìyì", pos: "n", cefr: "B2", g: ["rapat", "meeting", "reunión"] },
  { w: "合同", r: "hétong", pos: "n", cefr: "B2", g: ["kontrak", "contract", "contrato"] },
  { w: "工资", r: "gōngzī", pos: "n", cefr: "B2", g: ["gaji", "salary", "sueldo"] },
  { w: "价格", r: "jiàgé", pos: "n", cefr: "B2", g: ["harga", "price", "precio"] },
  { w: "税", r: "shuì", pos: "n", cefr: "B2", g: ["pajak", "tax", "impuesto"] },
  { w: "银行", r: "yínháng", pos: "n", cefr: "B2", g: ["bank", "bank", "banco"], note: ["Dibaca yínháng, bukan yínxíng — 行 punya dua bacaan.", "Read yínháng, not yínxíng — 行 has two readings.", "Se lee yínháng, no yínxíng: 行 tiene dos lecturas."] },
  { w: "电脑", r: "diànnǎo", pos: "n", cefr: "B2", g: ["komputer", "computer", "ordenador"], note: ["Harfiah 'otak listrik'.", "Literally 'electric brain'.", "Literalmente 'cerebro eléctrico'."] },
  { w: "电话", r: "diànhuà", pos: "n", cefr: "B2", g: ["telepon", "telephone", "teléfono"] },
  { w: "电子邮件", r: "diànzǐ yóujiàn", pos: "n", cefr: "B2", g: ["surel, email", "email", "correo electrónico"] },
  { w: "文件", r: "wénjiàn", pos: "n", cefr: "B2", g: ["berkas, dokumen", "file, document", "archivo"] },
  { w: "密码", r: "mìmǎ", pos: "n", cefr: "B2", g: ["kata sandi", "password", "contraseña"] },

  /* ------------------------------------------------------------------ C2 */
  { w: "贬低", r: "biǎndī", pos: "v", cefr: "C2", g: ["merendahkan", "to belittle, to disparage", "menospreciar"], d: ["Menganggap sesuatu lebih rendah nilainya.", "To treat something as worth less than it is.", "Tratar algo como de menor valor."], ex: ["不要贬低他的努力。", "Jangan merendahkan usahanya.", "Don't belittle his effort.", "No menosprecies su esfuerzo."] },
  { w: "不可避免", r: "bùkě bìmiǎn", pos: "adj", cefr: "C2", g: ["tak terhindarkan", "unavoidable, inevitable", "inevitable"], d: ["Tidak mungkin dihindari.", "Impossible to avoid.", "Imposible de evitar."], ex: ["涨价是不可避免的。", "Kenaikan harga tak terhindarkan.", "The price rise is inevitable.", "La subida es inevitable."] },
  { w: "阐明", r: "chǎnmíng", pos: "v", cefr: "C2", g: ["menjernihkan, menguraikan", "to elucidate, to expound", "esclarecer"], d: ["Menjelaskan hal rumit hingga terang.", "To make something complex clear.", "Aclarar algo complejo."], ex: ["需要阐明这些细节。", "Rinciannya perlu dijernihkan.", "These details must be elucidated.", "Hay que esclarecer estos detalles."] },
  { w: "范式", r: "fànshì", pos: "n", cefr: "C2", g: ["paradigma", "paradigm", "paradigma"], d: ["Kerangka berpikir yang menjadi acuan zaman.", "The framework of thinking of an era.", "Modelo de pensamiento de una época."], ex: ["这是一次范式转变。", "Ini pergeseran paradigma.", "This was a paradigm shift.", "Fue un cambio de paradigma."] },
  { w: "幻想", r: "huànxiǎng", pos: "n", cefr: "C2", g: ["angan kosong, khayalan", "illusion, fantasy", "quimera"], d: ["Harapan indah yang mustahil terwujud.", "A lovely hope that cannot come true.", "Ilusión hermosa e irrealizable."], ex: ["那个承诺只是幻想。", "Janji itu hanyalah angan kosong.", "That promise is a mere fantasy.", "Esa promesa es solo una quimera."] },
  { w: "回避", r: "huíbì", pos: "v", cefr: "C2", g: ["mengelak, menghindari", "to evade, to sidestep", "eludir"], d: ["Menghindari persoalan tanpa menghadapinya.", "To avoid an issue instead of facing it.", "Evitar un asunto sin afrontarlo."], ex: ["他回避了这个问题。", "Dia mengelak dari pertanyaan itu.", "He sidestepped the question.", "Eludió la pregunta."] },
  { w: "鉴于", r: "jiànyú", pos: "prep", cefr: "C2", g: ["mengingat, berdasarkan", "in view of, given", "en vista de"], d: ["Menilai sesuatu dengan memperhatikan fakta tertentu.", "Judging something in view of given facts.", "Juzgar algo en vista de ciertos datos."], ex: ["鉴于结果，这是一次成功。", "Mengingat hasilnya, ini keberhasilan.", "In view of the results, it's a success.", "En vista de los resultados, es un éxito."] },
  { w: "里程碑", r: "lǐchéngbēi", pos: "n", cefr: "C2", g: ["tonggak sejarah", "milestone", "hito"], d: ["Peristiwa penting yang menandai babak baru.", "An event marking a new stage.", "Suceso que marca una etapa."], ex: ["这项协议是一个里程碑。", "Perjanjian itu tonggak sejarah.", "This agreement is a milestone.", "Este acuerdo es un hito."] },
  { w: "难以言喻", r: "nányǐ yányù", pos: "phr", cefr: "C2", g: ["tak terlukiskan", "beyond words", "indescriptible"], d: ["Terlalu besar untuk dinyatakan dengan kata.", "Too great to put into words.", "Demasiado grande para expresarse."], ex: ["那是难以言喻的喜悦。", "Itu sukacita yang tak terlukiskan.", "It was a joy beyond words.", "Fue una alegría indescriptible."] },
  { w: "偏见", r: "piānjiàn", pos: "n", cefr: "C2", g: ["prasangka, bias", "prejudice, bias", "prejuicio"], d: ["Penilaian yang dibuat sebelum mengetahui fakta.", "A judgement made before knowing the facts.", "Juicio previo al conocimiento de los hechos."], ex: ["这项研究存在偏见。", "Riset itu mengandung bias.", "The study contains a bias.", "El estudio tiene un sesgo."] },
  { w: "迫在眉睫", r: "pòzài méijié", pos: "phr", cefr: "C2", g: ["sangat mendesak", "extremely urgent, imminent", "acuciante"], d: ["Sudah di depan mata dan harus segera ditangani.", "Right at the door and needing action now.", "Inminente y que exige acción inmediata."], ex: ["这个问题迫在眉睫。", "Persoalan ini sangat mendesak.", "This issue is extremely urgent.", "Este asunto es acuciante."] },
  { w: "一线希望", r: "yīxiàn xīwàng", pos: "n", cefr: "C2", g: ["secercah harapan", "a ray of hope", "un rayo de esperanza"], d: ["Harapan yang sangat tipis tetapi masih ada.", "A very thin hope that nonetheless remains.", "Esperanza muy tenue que aún persiste."], ex: ["还有一线希望。", "Masih ada secercah harapan.", "There's still a ray of hope.", "Aún queda un rayo de esperanza."] },
];
